### ISSUE TITLE
Some creeps cause movement of Ancient building in Serengaard

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#10]
experimental_minion (Void with Bara head) by his chronosphere waves 7,8,9.
Tuskars  serengaard_ice_shard_thrower on wave 22 and 25 with ice shards.

**Comment by redledcat** [comment]
Ancient, btw now has collision it needs, but radius of collision is equal hero's (24). Ancients in Dota 2 have collision size of 81, so that part needs to be adjusted.

**Comment by redledcat** [comment]
As for Reversed Polarity, Chronosphere and Ice shards, they just need to be modified to not interact with magic immune units as probable solution.

**Comment by redledcat** [comment]
try to change rpc_serengaard_ancient from 81
"BoundsHullName"            "DOTA_HULL_SIZE_HUGE" 
to 144
"BoundsHullName"            "DOTA_HULL_SIZE_BARRACKS" 
it will increase  collision x1.7 times
and decreasing model scale slightly will make better (1.2->0.9) maybe will compensate missing collision value.

**Comment by redledcat** [comment]
Also found this:
"Lua SetHullRadius(float) can change this to any value in between or even above 144"

**Comment by ChalkyBrush** [comment]
SetHullRadius is legit, never knew about it.
Great, the pulled ancient issue is solved too
