### ISSUE TITLE
Seinaru's E1 tooltip says it deals Normal Physical damage, when it does not deal damage at all

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1000]
it actually just gives him x% bonus attack damage for the duration of the E1 strikes.

(the strikes themselves, by the way, are regular autoattacks against the targets, and they proc all effects normally. this includes incrementing Dark Reef Shark Helmet stacks, activating Onimaru and R3, etc.)

**Comment by redledcat** [comment]
first 1000 bugs reported!

**Comment by Nintai** [comment]
Removed the damage type and element from E1 and E2
