### ISSUE TITLE
[Dinath] Q3 adds 1 ability_datadriven each cast

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1002]
![20190128225602_1](https://user-images.githubusercontent.com/32621322/51862621-0e8d2e00-2350-11e9-9ad8-9c80fea9bffb.jpg)
![20190128225618_1](https://user-images.githubusercontent.com/32621322/51862628-0f25c480-2350-11e9-9ea6-824920bf6d25.jpg)

**Comment by redledcat** [comment]
Q ability itself works fine, cleancing properly

**Comment by ChalkyBrush** [comment]
weird, ok, thanks

**Comment by redledcat** [comment]
As well as all other abilities of Dinath, including R

**Comment by Nintai** [comment]
Fixed it
