### ISSUE TITLE
[Elemental Warlord] Another entities problem

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1003]
How to reproduce: spam W into dummy. Axes which do not hit the target won't increase debug counter.

![image](https://user-images.githubusercontent.com/32621322/51917395-8317a980-23f0-11e9-8689-5644bd3b568a.png)

**Comment by redledcat** [comment]
Weapon does not matter, but sapphire axe increases speed of stacking x3

**Comment by redledcat** [comment]
Wall hits work too
![20190129180758_1](https://user-images.githubusercontent.com/32621322/51917546-d25dda00-23f0-11e9-96bf-f73eaf7e6cb0.jpg)

**Comment by redledcat** [comment]
fixed?

**Comment by ChalkyBrush** [comment]
ya bavibi fixed it
