### ISSUE TITLE
[Jex] Charged Sproutlings tooltip has two Tech Level scaling lines which say %, and neither should

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1008]
the two lines are SPROUTLING ARMOR AS A MULTIPLE OF JEX'S PER TECH LEVEL and SPROUTLING ATTACK DAMAGE AS A MULTIPLE OF JEX'S PER TECH LEVEL

**Comment by redledcat** [comment]
https://github.com/ChalkyBrush/Roshpit-Champions-Hero-RPG/pull/343
fixed this here probably
