### ISSUE TITLE
[Jex] Wrath of Lightning tooltip says it doesn't scale from ANY T4 runes

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1009]
is this correct?

**Comment by Nintai** [comment]
https://github.com/ChalkyBrush/roshpit-bug-tracker/issues/978

I think not

**Comment by redledcat** [comment]
if w_4_level > 0 then
		damage = damage + damage*(event.w_4_damage_increase_pct/100)*w_4_level


"DOTA_Tooltip_ability_jex_thunder_thunder_q_**q_4**_damage_increase_pct"		"%<font color=\"#7DFF12\">[W4] Lightning base damage increase</font>:"

"08"
			{
				"var_type"				"FIELD_INTEGER"
				"**w_4**_damage_increase_pct"		"10"
			}

**Comment by redledcat** [comment]
fixed here https://github.com/ChalkyBrush/Roshpit-Champions-Hero-RPG/pull/343
