### ISSUE TITLE
Super Ascendency Mask - projectiles issue

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#102]
When buff expires, ranged attacks loses their projectile's model.
I.e. Cherno in Demonic Supremacy has blue/red projectiles normally
![20171028204739_2](https://user-images.githubusercontent.com/32621322/32137057-2c211264-bc19-11e7-89d5-c1de02ef8b77.jpg)
![20171028204742_2](https://user-images.githubusercontent.com/32621322/32137060-3af83894-bc19-11e7-8249-8442f4c1f03f.jpg)
When Super Ascendency is equipped, all projectiles became fireballs.
![20171028204849_1](https://user-images.githubusercontent.com/32621322/32137072-79461422-bc19-11e7-8492-029ea1a74df9.jpg)
And when buff expires, there is no return to normal ranged projectiles of demonic supremacy, they become invisible.
![20171028204857_1](https://user-images.githubusercontent.com/32621322/32137076-9c19add8-bc19-11e7-92b8-59676fea5b59.jpg)

Same thing happens with Elemental Warlord, as I know, not sure about ranged heroes in generalm but these two arcana which changes melee to ranged attacks make projectiles invisible.

**Comment by redledcat** [comment]
Ranged units lose their projectiles too.
![20171028210105_1](https://user-images.githubusercontent.com/32621322/32137170-d328e626-bc1a-11e7-8a11-6accf33c9e6a.jpg)

**Comment by redledcat** [comment]
Astral Ranger: casting R with Super Ascendency makes your autoattacks fireballs, but casting Q with Q3 leveled up makes fireballs frosted arrows.
You can return normal arrows by leaving the cloud walking out of it.
Also if Q expires during Super Ascendency you get fireballs replaced with normal arrows, but when buff of Super Ascendency expires, autoattacks become invisible.

**Comment by ChalkyBrush** [comment]
fixed for next patch
