### ISSUE TITLE
Everybody still gets ejected south of Val'dun's arena when entering

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1020]
and it's super fucking annoying #514

**Comment by DeckardCainRPC** [comment]
i fucking guarantee you it's because of some shitty old "anti-skip" code that only lets you into his arena if you use his designated teleporter, instead of arriving there with Ekkan's or Jex's portals, or by respawning (respawn flag, paladin e1, respawn glyph)

the offending line of code needs to be excised and burned

**Comment by redledcat** [comment]
and please try to fix it please

**Comment by redledcat** [comment]
if it's some sort of skip protection I don't clearly see how valdun can spawn before all of these scripted events
