### ISSUE TITLE
[Jex] Earth Gate secretly shares a portal lockout timer with entrance to Val'dun

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1021]
STEPS TO REPRODUCE:
1. put an earth gate down in front of val'dun's entrance portal
2. teleport to the earth gate
3. step on val'dun's green teleporter column
4. it does jack shit for 10 seconds. you have to stand around and wait for its secret portal lockout timer to expire before it will carry you into the arena

**Comment by ChalkyBrush** [comment]
i don't see how this is possible

**Comment by redledcat** [comment]
Earth gate works with first jumper pad (first room after first sea maiden)

**Comment by redledcat** [comment]
Does it apply for fex or only for allies which TPed with T2 glyph?
Only this jump pad or other portals too?

**Comment by redledcat** [comment]
I know town portal sharing hidden CD with all other portals, so you have to wait redfall forest->farmlands portal because of thisthis.

**Comment by redledcat** [comment]
Maybe you made this chain of events?
1) TP to the base where earth gate is
2) Entered the gate
3) 7 seconds CD not yet expired
4) Jumper pad does not work

or just set earth gate too close to jump pad trigger zone, so it actually requires your hero to leave this zone and reenter to trigger it properly?

**Comment by DeckardCainRPC** [comment]
> 
> 
> Maybe you made this chain of events?
> 
>     1. TP to the base where earth gate is
> 
>     2. Entered the gate
> 
>     3. 7 seconds CD not yet expired
> 
>     4. Jumper pad does not work
> 
> 
> or just set earth gate too close to jump pad trigger zone, so it actually requires your hero to leave this zone and reenter to trigger it properly?

this sounds almost exactly like what happened, with one difference. yes, Still Alive placed the Earth Gate so that its outer rim slightly overlapped the Val'dun portal... i noticed this, and thought exactly what you did: "leave the zone and re-enter to trigger it properly." but that *did not work* - i would move back and forth, getting on the Val'dun portal and stepping back off again, for about 7 seconds, until finally it would decide to accept me.

**Comment by DeckardCainRPC** [comment]
i don't give a fuck about this anymore. i'll reopen it again if i catch my toe on it, which will remind me it exists and prompt me to bitch about it again
