### ISSUE TITLE
E spells which are not the hero's default (Arcanas, Trapper/Jex spells, those provided by Glyphs) allow for 0sec CD with Bloodstone Boots + Hood of Lords

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1032]
the intended behavior is for Bloodstone Boots to force the spell's CD to 1, taking priority over all other effects.

a Discord user claimed that you (chalkybrush) told him that bloodstone boots + hood of lords is working as intended. i am sure you have forgotten the multitude of reasons why a mandatory minimum CD of 1 second is enforced, so here's just a handful:

1. auriun's E4 + rapidly pressing E + rapidly clicking E = server death
2. the entire duskbringer
3. Trapper's stealth E + Hood of Lords or indeed any other CD reduction effect besides Bloodstone Boots already lets her levitate over any obstacles in the game, she is the most straightforward and effective map breaker
4. voltex's clot of E1 illusions will fry the game more quickly and thoroughly than even auriun's horseshit at maximum overdrive
5. an excessive amount of OD's E2 will kill the server with fireworks
6. BM has three fantastic sides and three awesome angles... here lemma show ya (meme noises and reams of angry purple text in the debug console)

**Comment by redledcat** [comment]
yeah, we kinda missed one thing yeserday, E abilities have hardcoded 0.1s cooldown cap, which cannot be lowered by any means.

**Comment by redledcat** [comment]
So for both Voltex and Jex best solution will be capping number of units **if that actually will cause any problems**.
Till people have fun and it's not destructive, making astonishing glitches or servers crashes, it's all fine?

**Comment by mythly** [comment]
"capping number of units" +1

Voltex and Jex are indeed game breakers.

**Comment by DeckardCainRPC** [comment]
i'll reopen this some day when i need to show everyone i was right and satan really does walk among us
