### ISSUE TITLE
in-game tooltip and movespeed cap broken again after Dota2 update today

### ISSUE THREAD

**Issue by mythly** [ChalkyBrush/roshpit-bug-tracker#1035]
![qq 20190217135321](https://user-images.githubusercontent.com/9605204/52909001-6c5fc680-32bb-11e9-94ea-08113e7ebf3a.jpg)

**Comment by redledcat** [comment]
It's fixed, but movespeed still hardcapped at 970 for zhonik/arkimus and other heroes who are speedy enough
