### ISSUE TITLE
【PRC Winter Map】The second room doesn't work any more for the 27th hard

### ISSUE THREAD

**Issue by gphu19** [ChalkyBrush/roshpit-bug-tracker#1040]
As stated in the title.Pls help.
<img width="2048" alt="2019-02-21 5 28 10" src="https://user-images.githubusercontent.com/47870173/53213583-5ecd7800-35fe-11e9-936e-e20b87e7dbf8.png">;
<img width="2048" alt="2019-02-21 5 28 16" src="https://user-images.githubusercontent.com/47870173/53213605-6f7dee00-35fe-11e9-8850-404199e05968.png">

**Comment by Nintai** [comment]
Ive already made the function to find "after fall" combinations better, but currently it is working so good, that u can finish the game in 1 turn.

I will try to make it more balanced, and then this bug should never happen again ;)
