### ISSUE TITLE
Is Glyph of Surging working?

### ISSUE THREAD

**Issue by nguyennk** [ChalkyBrush/roshpit-bug-tracker#1045]
![image](https://user-images.githubusercontent.com/1538969/53393908-34016c00-39d0-11e9-8547-2c16e3b4541c.png)

I tried this glyph on and it doesn't seem to increase any radius. Can anyone confirm on this?

**Comment by redledcat** [comment]
sure.
it has radius of 500 without glyph and 700 with it.
![20190226132244_1](https://user-images.githubusercontent.com/32621322/53405801-af135400-39c9-11e9-98e8-c1ed7742c32b.jpg)
![20190226132150_1](https://user-images.githubusercontent.com/32621322/53405803-b0448100-39c9-11e9-836b-bfb639ae3c3f.jpg)

**Comment by nguyennk** [comment]
oh k, i guess it just not big enough to make the different then XD
