### ISSUE TITLE
Reset Onibi should save XP gained for each module, instead of wiping all progress

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1049]
completely obliterating Onibi progress is far too draconian

**Comment by redledcat** [comment]
well I think if it's really meant to punish player and rollback his progress, 50% of total exp lost is okay?
Chalky programmed his exp to be saved into 1 variable, and it should be possible to reduce it by half insted nullifying?

**Comment by DeckardCainRPC** [comment]
i don't think there should be a punishment at all, i think re-allocating Jex's tech points should be *at most* as hard as using a Reanimation Stone. a curious person who puts 3 or 4 levels in a bunch of spells just to learn what the hero does, should not be punished with several days of grinding module levels again.

i think the current "punishment" system isn't because chalky intended for there to be a punishment, but instead it may just be an artifact of Jex's semi-rushed release

**Comment by Nintai** [comment]
I think this change was made during the last stream
