### ISSUE TITLE
Gravelfoot removes damage from auto-attacks

### ISSUE THREAD

**Issue by TotallyAFlareon** [ChalkyBrush/roshpit-bug-tracker#1050]
Jex is unable to deal damage(seemingly physical no buffs that would add an on hit effect) This was tested with, and without his Arcana equipped, 
With Arcana (Double fire Q was used to clear mobs to the training dummy)
![image](https://user-images.githubusercontent.com/48076610/53537588-7615d500-3ad8-11e9-86c5-859ede040503.png)

Without Arcana 
![image](https://user-images.githubusercontent.com/48076610/53537636-a65d7380-3ad8-11e9-8059-d3264c2da8a0.png)

Tested in two instances, Damage can still be done to the training dummy
![image](https://user-images.githubusercontent.com/48076610/53537704-de64b680-3ad8-11e9-946f-cb8886bd2df8.png)
All damage was done with Double fire Q.

**Comment by ChalkyBrush** [comment]
![image](https://user-images.githubusercontent.com/5232984/53538704-ca22b880-3adc-11e9-8510-dfd9032a21d9.png)
🤔

**Comment by TotallyAFlareon** [comment]
I'll take off the gloves, save stash and go into tanari to see if I deal physical auto attack damage.

**Comment by TotallyAFlareon** [comment]
Took off gloves when I finished the sea run, stashed them and saved, Went into tanari and 
![image](https://user-images.githubusercontent.com/48076610/53539299-fb03ed00-3ade-11e9-8971-3f6acc85c61a.png)

**Comment by TotallyAFlareon** [comment]
So, gloves came off, No auto attack damage, took gear off, still no auto attack damage 
Is there a command I can type in to maybe get more info for this? 
![image](https://user-images.githubusercontent.com/48076610/53539616-4965bb80-3ae0-11e9-9be5-1aa4952fc93d.png)

**Comment by ChalkyBrush** [comment]
looks like Bavibi figured it out, Gravelfoot treads would dispel your 'auto attack modifier' at some point

**Comment by TotallyAFlareon** [comment]
Gravel foot treads currently dispel something when I first spawn in, could it be then? Never thought it could of been the boots
