### ISSUE TITLE
Emerald Speed Runners isn't setting movespeed to a minimum of 550

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1052]
i'm almost positive this is because Valve killed the movespeed function in 7.20 but i'm putting it here to make some people shut up about it

**Comment by redledcat** [comment]
![20190301121437_1](https://user-images.githubusercontent.com/32621322/53628267-9f8b4980-3c1b-11e9-961e-de491d52612b.jpg)

**Comment by redledcat** [comment]
It's actually a misplaced bracket
local movespeedModifier = math.ceil(caster:GetMoveSpeedModifier(movespeed), false)
should be
local movespeedModifier = math.ceil(caster:GetMoveSpeedModifier(movespeed, false))

**Comment by redledcat** [comment]
pushed fix into jex translation

**Comment by DeckardCainRPC** [comment]
i will mark this Closed when the patch is implemented, thank you

**Comment by DeckardCainRPC** [comment]
i think this was fixed
