### ISSUE TITLE
All extant Living Bombs explode when any Bomb's timer expires

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1054]
STEPS TO REPRODUCE:
1. put a bunch of bombs on different units. to clarify, do not just spam Living Bomb on a single unit.
2. wait, while making Techies giggle noises
3. when the first bomb's timer expires, ALL bombs on the map will explode at that time.

**Comment by redledcat** [comment]
cool

**Comment by Nintai** [comment]
There is no bug. I tested it and it works correctly

You enemies probably died from the first explosion, which is clearly stated in the tooltip:
![image](https://user-images.githubusercontent.com/5485559/53574714-62b64880-3b70-11e9-8625-a44e17a3b7a9.png)

**Comment by Nintai** [comment]
Deckard admitted to being a stupid retard, this is not a bug.
