### ISSUE TITLE
A Dota update has broken Earth's Gate

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1055]
UPDATE: i initially thought that Spell Immunity might be preventing Earth's Gate teleports from occurring, however i tested it without Spell Immunity and it still did not function.

NEITHER of these two Jex builds can teleport using Earth's Gate:
https://www.roshpit.ca/players/72513648/heroes/216990
https://www.roshpit.ca/players/72513648/heroes/1011208

**Comment by redledcat** [comment]
I clearly remember I used them with his bkb on

**Comment by DeckardCainRPC** [comment]
i updated the topic to reflect shocking developments

**Comment by ChalkyBrush** [comment]
it works now after last patch
