### ISSUE TITLE
[Tutorial] Jex has 0 elemental damage runes, so he can't pass through question 4D (Djanghor has this bug too)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1058]
https://steamcommunity.com/workshop/filedetails/discussion/469311655/1843566500515275411/

**Comment by redledcat** [comment]
"tutorial_master_dialogue_4_4e"										"Some abilities have dual elements which allow them to benefit from both types."
	"tutorial_master_dialogue_4_4f"										"Now let's see if you can read your element names."

	"tutorial_quiz_question_15"											"Name the primary the element of @sub1."

	"tutorial_quiz_wrong_4_4_3"											"That's wrong. Find the ability or rune with that name and tell me its element."
	"tutorial_quiz_wrong_4_4_4"											"Please read your rune description and tell me which element it has."

**Comment by DeckardCainRPC** [comment]
as an additional bug, i see our good friend chalky fucked up and wrote "Name the primary **the** element of @sub1." replace it with this:
`"tutorial_quiz_question_15"											"Name the primary element of @sub1."`

we should add the magic phrase "fuck off" to the interpreter, and any time you tell Challen to fuck off, it automatically counts as a correct answer

**Comment by redledcat** [comment]
fixed next patch (tutorial "the")
element runes were added by Chalky a while ago
