### ISSUE TITLE
Galactic Arcana Caches are broken, HMM I WONDER WHY

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1059]
MAYBE IT HAS SOMETHING TO DO WITH A CERTAIN MODIFICATION TO synthesis.lua RECENTLY

(which, to your credit, that wink wink modification functions as intended)

**Comment by ChalkyBrush** [comment]
prob when i was upgrading server he tried to open it. more of a performance problem than game bug :D
