### ISSUE TITLE
Helm of the iron colossus atk spd after respawn

### ISSUE THREAD

**Issue by Chanphal** [ChalkyBrush/roshpit-bug-tracker#106]
Helm of the iron colossus doesn't force your attack speed to 100 on starting map or respawning after death. Instead it makes your attack speed 8.50s (doesn't matter how much attack speed you have).

![loading in](https://user-images.githubusercontent.com/33225763/32174630-f8cf54be-bdb4-11e7-8fc1-e0d4b06a5364.jpg)

Your attack speed number will start counting down one every 0.5s until it reach 20 then it will change to 120 attack speed like how it should be. The image show 47 attack speed but sometimes it can be 230+ so you have to wait for it to count down to 20 also for you attack speed to change to 120.

![after reach 20](https://user-images.githubusercontent.com/33225763/32174896-bd8ffda8-bdb5-11e7-9ad9-fc6d0aa9c839.jpg)

I think this has something to do with the amount of your agility because after unequipping every item except the helm, the issue is gone. The image below shows the attack speed after i respawn with no item except helm. (1000+ agi is from potions, with 20 agi the attack speed will be at 98 instead of 120)

![no equip](https://user-images.githubusercontent.com/33225763/32175033-29dc1802-bdb6-11e7-920c-339236fb02f6.jpg)

With 4700+ agi the bug will happen always after respawn. I'm not sure the exact number of agility to trigger this but with 4700 agi i have to die twice after equipping the claw with 3600 agi for the bug to trigger. If I have 10000+ agi (from wolf form) then the bug will always happen after death.

![with some agi](https://user-images.githubusercontent.com/33225763/32175185-bc84efa8-bdb6-11e7-9633-1df2720b3ffb.jpg)
NOTE: The 8.50s is not a visual bug, you will attack really slow.

**Comment by ChalkyBrush** [comment]
this should be fixed with attribute rework
