### ISSUE TITLE
Brief 7.07 reports

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#107]
1)Respawns functions, such as flags, zeus ulti, pala E1 are broken
2) Mana and HP regens broken both visually and technically
values stated when your attributes changes somehow being +0/+20, but on practice they are close to be infinite 
3)Status resist being insane

**Comment by ChalkyBrush** [comment]
these are mostly fixed with attributes rewrite (lets break down into smaller issues now if any remaning 7.07 bugs exist)
