### ISSUE TITLE
Mountain Protector W1 tooltip says it passively increases HP regen, but it's really only active during W stance

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1073]
OPTIONS:
1. make W1 passive, and completely independent on W. i like this option
2. make the tooltip match the effect. since most of you are illiterate hobgoblins, please use this nice tooltip that i wrote in advance:
"Increases health regeneration by a % of maximum health while channeling @Ability2."

**Comment by redledcat** [comment]
tooltip fixed
