### ISSUE TITLE
Can't search for Galactic Arcana Cache on the Market as of last patch

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1078]
clicking Load Filters for the cache does not actually load the filters

**Comment by ChalkyBrush** [comment]
<img width="900" alt="screen shot 2019-03-08 at 9 23 07 am" src="https://user-images.githubusercontent.com/5232984/54034063-f052f300-4183-11e9-8bd4-ea5fcf7d737a.png">
can filter by Radiance value as well now

**Comment by DeckardCainRPC** [comment]
neat
