### ISSUE TITLE
[Feature Request] Add Reanimation Stones to the Key Bank infrastructure

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1084]
Eternal Flame had been posting about some kind of "consumables bank" idea for a few months, and i kind of just ignored it as background noise, until i saw other people bitching at him about it. so i asked him what his idea was. he spelled it out for me and i actually think it would be a good feature, both because it's relatively easy to incorporate into what we already have, and because it would be very convenient.

... basically all he wants is to add Synthesis Vessels and Reanimation Stones to the Key Bank. that's literally fucking it. i cannot go into any more detail because there is none.

i guess in the future it would be neat if the Key Bank was expanded to include Glyph Books and shit too, but that is, of course, not nearly as important as first making the Glyph Books stashable and marketable.

**Comment by DeckardCainRPC** [comment]
i have an observation of my own: implementing this will have the unintended consequence of adding a neat little economic curiosity to RPC, very similar to those goddamn Turnips in most Animal Crossing games. users can buy Vessels and Stones off of the market at a low price, and hoard them in their Bank until prices rise for some reason, at which point they can "sell high," as the saying goes.

to that end, IF this idea is implemented, then i suggest raising the limit of both Vessels and Stones in a Pass user's Bank to a value much, much higher than the 20 cap given to all the keys. i'm talking hundreds of thousands, a value so insanely high that when a user manages to max it out, it'll make you shout "I'LL BE GOD DAMNED." non-Pass users should be capped at 5 to incentivize giving us money so they can hoard cyber buttons in our murder simulator.

**Comment by redledcat** [comment]
lol

**Comment by redledcat** [comment]
I once stacked full account (120 vessels) on my alt. It's not a necessity to give absurd numbers, but if it does not affect database a lot, I would like to farm them for weapon rerolling not being tied to my stash.
Increasing variablilty of synthesis recipes anyway will lead to synthesis vessel became same kind of resource as mithril shards are (they both allow rerolling)

**Comment by DeckardCainRPC** [comment]
^ i strongly agree, the more complex Synthesis Vessels become, the greater the need for more storage space for them

**Comment by DeckardCainRPC** [comment]
ladies and gentlemen, over a year later, we finally live in the future
