### ISSUE TITLE
[Boreal Granite Vest] Does not proc any of 'No Target' abilities (at least for Jex)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1088]
1. Ring of Fire (FF)
2. Cosmic Barrier (FN)
3. Oak Infusion (NN)
4. Wrath of Lightning (LL)
5. Electron Shield (LC)

Does work with FN, FC, CC, LN

**Comment by redledcat** [comment]
Does not work with Magnetic Flux (Arkimus head arcana), also no target

**Comment by redledcat** [comment]
And both Venomort Q arcana and non-arcana

**Comment by Nintai** [comment]
Fixed for next version

**Comment by redledcat** [comment]
👏
