### ISSUE TITLE
Update lore blurbs which you meant to change last year

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1089]
"npc_dota_hero_dragon_knight_lore" "A well-rounded fighter, the Flamewaker's fire rises to meet any challenge."
"npc_dota_hero_phantom_assassin_lore" "Mobile and flashy, Voltex electrifies foes faster than they can react."
"npc_dota_hero_necrolyte_lore" "Venomort loves company, his plagues growing in strength with each new victim."
"npc_dota_hero_axe_lore" "An army of one, The Red General's brutal rampage cannot be stopped."
"npc_dota_hero_drow_ranger_lore" "Astral Ranger calls down the power of the night sky against distant enemies."
"npc_dota_hero_obsidian_destroyer_lore" "Master of time and space, the Epoch Guardian is a fearsome mage."
"npc_dota_hero_omniknight_lore" "The Paladin carries out his crusade with the blessings of a higher power."
"npc_dota_hero_crystal_maiden_lore" "Many disciplines of elemental magic bend to the will of the Sorceress."
"npc_dota_hero_invoker_lore" "Attended by specialized arcane constructs, the Conjuror never fights alone."
"npc_dota_hero_juggernaut_lore" "Unseen blades of fierce wind move with Seinaru's every step - and every strike." 
"npc_dota_hero_beastmaster_lore" "The wild elements of nature roar to life wherever the Elemental Warlord may roam."
"npc_dota_hero_leshrac_lore" "A divine avatar, Bahamut brings punishment against the unclean hordes."
"npc_dota_hero_spirit_breaker_lore" "Duskbringer haunts his prey with ghastly curses and supernatural might."
"npc_dota_hero_zuus_lore" "Friend to courageous hearts, Auriun sees to the protection and support of his allies."
"npc_dota_hero_templar_assassin_lore" "A tool for every target, the Trapper lives for cunning assassinations."
"npc_dota_hero_huskar_lore" "Fallen ancestors of ages past answer the Spirit Warrior's call to battle."
"npc_dota_hero_legion_commander_lore" "A mountain is toppled more easily than the Mountain Protector is moved."
"npc_dota_hero_night_stalker_lore" "Chernobog descends upon helpless prey as the night's curtain falls over a sleeping sun."
"npc_dota_hero_vengefulspirit_lore" "Twin powers rest within Solunia, to be unleashed together in a cosmic blaze."
"npc_dota_hero_slardar_lore" "The seas rise up as Hydroxis wracks the Earth like a ship in a storm."
"npc_dota_hero_visage_lore" "Ekkan raises the dead to march across the world, fighting an endless war."
"npc_dota_hero_dark_seer_lore" "Rolling around at the speed of sound, to stop Zhonik you'll have to catch him first!"
"npc_dota_hero_antimage_lore" "Volatile magic empowers the agile Arkimus, pushing the limits of his martial arts."
"npc_dota_hero_monkey_king_lore" "A shape-shifting spirit of the forests, Djanghor is never as he seems..."
"npc_dota_hero_slark_lore" "Slipfinn darts over, around, and through crowds of enemies in a deadly dervish."
"npc_dota_hero_skywrath_mage_lore" "Howling gale and gentle breeze alike whirl around Sephyr, a thoughtful aeromancer."
"npc_dota_hero_winter_wyvern_lore" "Bitter cold and searing heat are just two of the weapons in ancient Dinath's arsenal."
"npc_dota_hero_arc_warden_lore" "The scientist Jex harvests and adapts natural elements to customize his own unique battery of spells."

**Comment by DeckardCainRPC** [comment]
these changes must also be applied to the website

**Comment by redledcat** [comment]
Well, then you could make text bigger because I personally need a magnifying glass to read these lines in game.

**Comment by DeckardCainRPC** [comment]
:muscle: :bee:
