### ISSUE TITLE
Spirit Warrior Q2 is applying less DR% than intended

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1090]
also, the tooltip is technically wrong: *casting* the spell does not actually give Spirit Warrior the stated bonuses. those are only given if he casts the spell *on himself* because they're tied to the weapon orb buffs.

STEPS TO REPRODUCE:
1. get 20 q2 on your spirit warrior
2. cast flameblood weapon (on yourself)
3. check your stats panel. you should have 67% DR, and instead you have only 62%.

i have no idea if the Evasion component has a similar malfunction, since the stats panel doesn't list your evasion.

**Comment by Nintai** [comment]
Fixed
