### ISSUE TITLE
[HOLY MOTHER OF GOD IT'S NOT FIXED YET] Spirit Warrior's W2 does not apply/stack up when W is autocast through Energy Whip Gloves while he has any Orb spear buffs

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1092]
STEPS TO REPRODUCE:
1. equip energy whip gloves
2. go attack the dummy
3. observe that you will autocast Soul Thrust (W) after every attack, as normal, and that these autocasts will activate and increment W2, up to the maximum of 3 stacks. each autocast is also accompanied by the brief multicolored explosion particle for W.
4. okay, now put on any of his Spear autoattack orbs (Flameblood, Windstrike, Rain Thingy, any or all of the above)
5. go back and attack the dummy some more
6. interestingly, the dummy IS recording the Fire/Wind damage instances from Soul Thrust, despite the fact that the animation for the spell is "partially aborted," failing to generate the aforementioned brief multicolored explosion particles. additionally, W2 is not being activated by these casts.
7. what in the fuck

**Comment by Nintai** [comment]
Tried it just now, worked perfectly, there has to be something else that blocks it, what items did u have?

**Comment by DeckardCainRPC** [comment]
https://www.roshpit.ca/players/72513648/heroes/433340

**Comment by Nintai** [comment]
Found and fixed

True bug:
W3 crashes when trying to apply the Flame/Wind/Water weapon hits

**Comment by DeckardCainRPC** [comment]
this is not yet fixed, and in fact it is creating BRAND NEW BUGS all on its own!

STEPS TO REPRODUCE:
0. load my huskar build as provided in a post above
1. go into rpc_tutorial, don't fucking cast anything yet, just teleport over to the dummy
2. start attacking it. notice that you're only dealing Physical damage. Spear of Aeris crits are also untyped Physical damage at this juncture.
3. stop attacking it. apply both of your Q buffs to yourself, then resume attacking.
4. the dummy combat log will of course be filled with colorful spam. wait a moment for your Q buffs to expire while you're attacking.
5. after the Q buffs expire, your Spear of Aeris crits are now considered Physical Fire damage, and they do in fact benefit from your Fire% bonus.
6. what the fuck?
7. begin casting your Flameblood Q on yourself, then abort the spell before the animation completes by issuing a Stop command (S by default), or cancelling it with a different order, etc.
8. the dummy now reports that your Spear of Aeris crits are now back to being untyped Physical damage.
9. cast Flameblood Q on yourself and wait for it to expire. then, cast Windstrike Q on yourself, and resume attacking the dummy.
10. observe that your Spear of Aeris crits are now Physical Wind damage, and they do in fact benefit from your Wind% bonus.
11. what the double fuck?
12. Cast E. you can also abort casting E, or use E to teleport to an existing Spirit if you already created one for some reason.
13. Spear of Aeris crits are now back to being untyped Physical damage.
14. oh also, throughout all of this madness, if you have BOTH Flameblood and Windstrike weapon equipped, Nintai's W2 fix falls apart and it resumes its old, broken functionality once more.
15. gentlemen, we are now at triple fuck

EDIT: there are conditions under which Spear of Aeris crits will become Physical Fire/Wind damage, but i'm not entirely certain how to get it to do that. i have reproduced it numerous times, however i haven't yet determined what the fuck.

**Comment by DeckardCainRPC** [comment]
[3:36 PM] sterv: i had it at Physical Fire/Wind, then i cast Windstrike on myself but aborted it
[3:36 PM] sterv: it didn't remove the Wind flag
[3:36 PM] sterv: so, i completed a Windstrike Weapon cast on myself, and THEN resumed attacking the dummy
[3:37 PM] sterv: curiously, Spear of Aeris crits are now Physical Wind
[3:37 PM] sterv: sooooo applying wind Q to myself removed the Fire flag from the Aeris crit instance

**Comment by DeckardCainRPC** [comment]
this was finally fixed, thanks @Nintai
