### ISSUE TITLE
[Jex] Essences still spawn even if lv 100 element reached

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1094]
Floods fields of view, loads servers with entities and has no profit.

**Comment by redledcat** [comment]
Me and Gokiburi-Gumi both reached already all three lv 100 elements, so it makes game only having +100 additional units on server with no actual profit.
Please implement fix asap

**Comment by Nintai** [comment]
Fixed that :) will come in next version

**Comment by redledcat** [comment]
Thanks!
