### ISSUE TITLE
Creeps which stuck in Serengaard, waiting players on spawn points

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#11]
tanari_headhunter
arena_pit_conquest_temple_explorer
tanari_thicket_priest
redfall_twisted_pumpkin - that one stands near ancient trying to projectile it to death, lazy aggro onto players.

**Comment by StillStealSteel** [comment]
Isn't this related to #16?

**Comment by StillStealSteel** [comment]
I close this one because it seems like they are related.

**Comment by redledcat** [comment]
Still not fixed, still happens regularly
