### ISSUE TITLE
All tooltips now have "Pure" damage with yellow color text. It used to be red.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1105]
![20190323102203_1](https://user-images.githubusercontent.com/32621322/54863123-9e9a9300-4d55-11e9-8d78-e4b1bfd223ee.jpg)
![20190323102320_1](https://user-images.githubusercontent.com/32621322/54863134-bd008e80-4d55-11e9-9bf2-f870fb6730a8.jpg)
![20190323102315_1](https://user-images.githubusercontent.com/32621322/54863135-be31bb80-4d55-11e9-9895-4c4a2cbb0f7a.jpg)

**Comment by redledcat** [comment]
Magical used to be white and physical used to be blue
at least in hero tooltips
Though these color codes seems fine, just say if it's bug or not

**Comment by redledcat** [comment]
Actually while we at it, I'd suggest better and more persistent color code system:
Physical is pale green (try 32C93B)
Magical is red (maybe D32015)
and Pure is blue (283FEE)
that's color scheme for Warlock+Golem miniboss, and will help a lot for new players to remember them
Same as Ancient God, green is physical, red is magical, blue is pure

**Comment by redledcat** [comment]
Color scheme works with Zealots as well, except they are vulnerable to respective color+ counterclockwise one (if we count physical-magical-pure), but maybe they should be IMMUNE to respective color, they can reduce confusion when you approach to them already knowing usual color scheme

**Comment by DeckardCainRPC** [comment]
i have confirmed that this change to the Pure damage color text is NOT just a change made to the Colorblind palette - it affects non-redledcats as well

**Comment by redledcat** [comment]
I checked it too before posting

**Comment by redledcat** [comment]
well I guess we will live with this now
very disappointing and confusing changem, shame on icefrog
