### ISSUE TITLE
Open Training Dummy button doesn't work in RPC_TUTORIAL

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1106]
i tested it on redfall ridge and it worked just fine

**Comment by redledcat** [comment]
is it fixed already?
![image](https://user-images.githubusercontent.com/32621322/54872029-b9f5b480-4dce-11e9-943c-7b9fbe47edb0.png)
fine here

**Comment by DeckardCainRPC** [comment]
ye
