### ISSUE TITLE
Voltex illusions evidently aren't benefitting from Q3's crit physical damage instance

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1110]
some reprobate phoneposter goon named OmegaZero decided to raise my blood pressure by taking a picture of his fucking screen in $currentyear and posting it in discord. he was summarily executed by whiffle ball bat and urine, but after i killed him, i squinted at his fucking abominable screenshot, and between the smudges and lens flare, i actually could tell that the training dummy was not registering Q3 physical damage instances when just illusions attacked it. (the rune is evidently functioning for voltex herself.)

**Comment by Nintai** [comment]
No idea if it is on purpose or chalky forgot, but the illusions just cant procc it:
![image](https://user-images.githubusercontent.com/5485559/55274743-2c3d2c00-52dc-11e9-8367-0c137e03efd1.png)

**Comment by DeckardCainRPC** [comment]
fixed in last update, illusions now benefit from both aspects of Q3
