### ISSUE TITLE
[Candy Crush] Reward

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1113]
if black_statue_count <= 0 then
						reward = 300

how it's possible if you always take at least 1 turn which means you get at least 1 statue?

**Comment by Nintai** [comment]
![image](https://user-images.githubusercontent.com/5485559/55291907-7b6e8400-53e4-11e9-9a56-968a645c50f4.png)

It is impossible ;)

**Comment by redledcat** [comment]
why it's a thing then?

**Comment by redledcat** [comment]
yeah was fixed
