### ISSUE TITLE
Djanghor update gripe sheet

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1114]
=== Q TREE ===

1. Q1 tooltip change:
"Casting Roar applies a buff to Djanghor that heals every 0.1 second for 12 seconds. This effect persists through shapeshifting."

2. Q3 tooltip change:
"Casting Screech adds time to ALL of Djanghor's buffs applied to himself by his own abilities, runes, and items. An individual buff's duration can only be increased 3 times, at which point it will need to be applied again in order to benefit from this effect."

=== W TREE ===

1. W2 tooltip:
increase -> increased

=== E TREE ===

1. E1 tooltip does not tell you the duration of the acid pool.

it also needs to be changed:

"After landing from Monkey Leap, leave an acidic pool of organic matter that severely weakens enemies standing within, multiplying all Nature damage dealt to them. The pool lasts x seconds."

2. E2 tooltip change:
"Jin'bo has increased base damage when cast during Monkey Leap. If the 3rd strike of Jin'bo hits at least 1 enemy, there is a chance Djanghor will receive a free cast of Shapeshift, removing its channel time. A chance greater than 100% means that multiple stacks can be gained at a time."

3. Wolf's Feral Sprint (E) tooltip typo:
buring -> during

=== R TREE ===

1. Shapeshift: Wolf (R) tooltip change:
While in Wolf form, attacks provide lifesteal equal to 0.5% of Djanghor's attack damage. -> While in Wolf form, each attack against an enemy unit will heal Djanghor for 0.5% of his total attack damage.

2. Shapeshift: Hawk tooltip does not have any text explaining Magical/Physical damage block.
"While in Hawk form, all Physical and Magical damage taken is reduced by 5 for each point of INT, applied after Armor and Magic Resistance but before other reductions."

3. Monkey Form (R) tooltip says DAMAGE TYPE: Magical. lol.

4. R1 tooltip change:
"Attributes increase base attack damage in each animal form. Bear gains damage from Strength, Wolf from Agility, and Hawk from Intelligence. Djanghor's Monkey form gains attack damage from ALL attributes, but at only half of the indicated value. This rune is activated when shapeshifting into the corresponding form."

5. R2 tooltip change:
"Gain increased maximum health in Bear form. This buff is retained when shapeshifting out of Bear form, and shapeshifting into a different form fully refreshes it while active."

6. R3 tooltip change:
"Gain increased Base Ability Damage in Hawk form, or increased Item Damage in Bear form. After shapeshifting out, these buffs are retained for 15 seconds, and shapeshifting into a different form fully refreshes them while active."

7. R4's attribute buff does not place an icon in the buff bar, so you don't know when the 25-second timer is going to expire.

=== GLYPHS ===

1. T3 tooltip: capitalize wolf and monkey

2. T6 tooltip change:
"Every 2 seconds, Djanghor cleanses 1 enemy debuff from himself. Any of Djanghor's animal form spells that make him charge to a location will apply [E3] when cast."

3. T7 tooltip change: (NOTE: MAKE SURE I'M USING THE CORRECT @special_property FOR EACH VARIABLE)
"Attacks during Bear form have a @special_property1% chance to bash the target, dealing @special_property2% increased damage and stunning for @special_property3 seconds. Additionally, War Stomp now reduces the Armor of affected targets by the same value as Wolf form's Rend."

=== ARCANA R TREE ===

1. R1 tooltip change:
attack damage -> base attack damage

2. R3 name change: Jade Voice -> Jade Scales

**Comment by DeckardCainRPC** [comment]
i also have a question: does Q3 only affect buffs on Djanghor himself? or does it also check for existing buffs applied to other allied units, which list Djanghor as the source of the effect?

**Comment by redledcat** [comment]
everything is done except Jade Voice, Chalky, rename it yourself if you are fine with it
