### ISSUE TITLE
"Heartfreezer" (QOP model enemies) spawn in incorrect positions north of Winterblight castle entrance

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1115]
one spawns secluded in trees, and another spawns on the inaccessible cliff face which forms the northern border of the courtyard

**Comment by redledcat** [comment]
Fun fact: they both meant to be spawned in the frozen lake when you activate 2 glacier stones.

**Comment by redledcat** [comment]
local positionTable = {Vector(-15616, -5760), Vector(-15355, -5120), Vector(-14720, -4873), Vector(**14080**, -4662), Vector(**13503**, -4888), Vector(-12928, -5132), Vector(-12773, -5760), Vector(-14626, -5325), Vector(-13568, -5325)}

**Comment by redledcat** [comment]
![20190407125622_1](https://user-images.githubusercontent.com/32621322/55681899-b74da000-5934-11e9-8664-43bd07fd4115.jpg)

**Comment by redledcat** [comment]
![20190407125809_1](https://user-images.githubusercontent.com/32621322/55681910-d815f580-5934-11e9-9df4-1ec46478d04c.jpg)
all other are here

**Comment by redledcat** [comment]
missing 
![20190407125938_1](https://user-images.githubusercontent.com/32621322/55681996-8a4dbd00-5935-11e9-86eb-fcee9f7a5238.jpg)
and fixed
![20190407130311_1](https://user-images.githubusercontent.com/32621322/55681997-93d72500-5935-11e9-8f52-1758f51aa090.jpg)

**Comment by redledcat** [comment]
But I'm actually going to add two heartfreezers to that last room, putting both of them in small ice puddles.
![20190407131317_1](https://user-images.githubusercontent.com/32621322/55682110-54a9d380-5937-11e9-9687-d515d1c00af9.jpg)
![20190407132154_1](https://user-images.githubusercontent.com/32621322/55682159-355f7600-5938-11e9-9860-ffbf37cf6f3d.jpg)
