### ISSUE TITLE
Check Bahamut's E1 to make sure Valve hasn't fucked something up

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1118]
another player reported that e1 wasn't healing, so at first i suggested he get at least 100 points in it and then check it out... however i went and checked, and noticed that bahamut's e1 may really be malfunctioning after all.

**Comment by Nintai** [comment]
No idea about what was wrong, but i recently played bahamut and E1 can heal
