### ISSUE TITLE
ArcaneRanger/Galaxy orb bug melee enemies ignore Q while channeling R

### ISSUE THREAD

**Issue by ShortVix** [ChalkyBrush/roshpit-bug-tracker#112]
With Arcane Ranger if you use Galaxy Orb enemies can melee you during channeling celestial burst. Q+R -> get melee smashed.

Noticed this after the attributes fix, moon shroud/Q works when cast alone.

**Comment by ChalkyBrush** [comment]
since her Q only makes enemies run out of the cloud, galaxy orb forcefully sucks them in so yes they will come at you
