### ISSUE TITLE
https://www.roshpit.ca/items/item_rpc_ghost_slippers is completely fucked

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1123]

**Comment by redledcat** [comment]
never curated or curated on Chinese version?

**Comment by redledcat** [comment]
I wish I had them, lol

**Comment by DeckardCainRPC** [comment]
i believe one way this COULD be fixed, is if the Roshpit Test ``-boots`` command was altered to include Ghost Slippers in the items it drops. someone (me) would then go create a copy that way, then curate it

**Comment by redledcat** [comment]
ok it's fixed now
