### ISSUE TITLE
Astral Ranger tooltip fixes

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1125]
chalky's love affair - with hyphenated clauses - like his fellow countryman William Shatner - comes to a dramatic end - at long last - along with some other miscellaneous tweaks

=== Q TREE ===

1. Q1: Moon Shroud -> @Ability1

2. Q3: Moon Shroud -> @Ability1

3. Q4: Moon Shroud -> @Ability1

=== W TREE ===

1. W2:
"@Ability2 has a chance to fire an additional volley of arrows with every cast. A chance greater than 100% means more than one additional volley may be fired."

2. W4: split shot -> @Ability2

=== E TREE ===

1. E1: 
"Summons an aspect of the Pegasus when casting @Ability3, which sweeps over enemies along the path between Astral Ranger and the target point. Affected enemies are rooted and take increased post-mitigation damage. This vulnerability debuff can stack up to 10 times."

2. E2:
"After casting @Ability3, gain bonus attack speed and base attack damage for 6 seconds. Additionally, a free attack will be launched against all enemies struck by the spell."

3. E3:
"After casting @Ability3, the Astral Ranger becomes cloaked in a veil that reduces all damage taken by 75%, and further adds 95% Magic Resistance. The shroud also removes any stuns and silences every 0.5 seconds while active."

=== R TREE ===

1. R1: (please apply the correct HTML color code to Cosmic, and list the duration of the debuff)
"While channeling @Ability4, numerous fallen stars rain down upon nearby enemies. Each star reduces the target's resistance to Cosmic damage by 10% for x seconds."

2. R2: 
"Increases the damage of [R1]. Each star also slams the ground on impact, dealing its damage in a small area around the primary target and stunning all affected enemies for 0.03 seconds."

3. R3:
"Summon an aspect of the Phoenix Constellation when @Ability4 is successfully cast. The aspect will attend the Astral Ranger for 20 seconds, constantly bombarding all enemies in an extreme radius around her. These attacks deal damage based on the Ranger's total attack power."

4. R4:
"Passively improves the activation chance of items and runes, by a percent of its base chance. This is not a flat bonus."

**Comment by redledcat** [comment]
supreme English tooltips in the next patch

**Comment by DeckardCainRPC** [comment]
it's live!
