### ISSUE TITLE
Ruinfall Skull Totem's roll data is not being stored when curated

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1126]
STEPS TO REPRODUCE:
1. hop in Roshpit Test
2. type -trinket
3. explode in a shower of trinkets
4. fuck
5. dig through the pile until you find a Ruinfall Skull Totem
6. go curate it
7. check its entry at https://www.roshpit.ca/items/item_rpc_ruinfall_skull_token
8. son of a bitch! it didn't update the rune rolls at all!

**Comment by redledcat** [comment]
well, yeah, it's impossible to curate items in test now

**Comment by DeckardCainRPC** [comment]
fucking why

**Comment by DeckardCainRPC** [comment]
suffering
