### ISSUE TITLE
[Sorceress] I guess it's time to report the most infamous bug left

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1129]
1) Fire arcana Q2 states it's Ability2 rune
2) Frostburn Gauntlets convert damage to ice
3) R4 converts damage to fire
4) Q2 also damages enemies based on total damage taken during burn

All these things allow to convert damage from EACH tick of Q2 in chain:
q2 arcane->fire (q4)->ice (frostburns)->fire(q4)->damage sums up into next Q2 tick -> fire (q4)....
Good timed cast of Q allows to reach infinite damage numbers.
![20190405191440_1](https://user-images.githubusercontent.com/32621322/55642480-3c23a700-57d9-11e9-95c4-4e29c7ad97ee.jpg)

Though, it's extremely slow and unefficient way to build up damage because requires Q2 timing and full Q uninterrupted cast. Good night sweet princess.

**Comment by redledcat** [comment]
This change is mandatory before any buffs to Q arcana can be done

**Comment by redledcat** [comment]
It seems I'm completely on the dark side now, what a shame

**Comment by DeckardCainRPC** [comment]
that is a very large number @redledcat

**Comment by redledcat** [comment]
@DeckardCainRPC 
<img width="331" alt="infinity" src="https://user-images.githubusercontent.com/32621322/55646568-29fb3600-57e4-11e9-958d-a5ba04a7c7fe.png">

**Comment by redledcat** [comment]
Old screenshot
![20180916223821_1](https://user-images.githubusercontent.com/32621322/55646636-5e6ef200-57e4-11e9-9567-3b58fe7e0dc0.jpg)

**Comment by redledcat** [comment]
Tbh whole arcana needs a rework, but I can't think one which would be nice and efficient, maybe do something later, but please help with this one for now.
Move Q2 to Base Ability: Q or change math

**Comment by redledcat** [comment]
hey that's fixed thanks Dragon
