### ISSUE TITLE
Solunia r4

### ISSUE THREAD

**Issue by kinglii** [ChalkyBrush/roshpit-bug-tracker#113]
For solunia body r4 the website says it provides 500 attributes per rune so 20 runes should provide 10000 attributes but my arcana only provides me 4000 attributes which means 200 per rune?!! Is it a bug????

**Comment by redledcat** [comment]
@kinglii it's not a bug, info of solunia body is outdated. It gives 200 att per r4.
It was changed in first day of release, together with buffing max roll of +All Attributes  property.

**Comment by redledcat** [comment]
close

**Comment by redledcat** [comment]
close please
