### ISSUE TITLE
[Venomort] [Pit of Trials] Black mage instakills Venomort, because it somehow counts his HP way way higher than it is in reality (E4?)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1131]

**Comment by Nintai** [comment]
Cant really be called a bug i think.

This is what happens:
You enter with X HP. You get the Aura of black mage. You hit the black mage with anything and get E4 bonus health. Aura prevents healing -> u now have X current health and X + E4 Bonus Max health. If x is too low, it probably insta kills u

**Comment by redledcat** [comment]
ah damn, it's probably E2 proc instantly applies because of aura damage and fucks veno up
