### ISSUE TITLE
Duskbringer Helm Arcana tooltip nitpicks

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1141]
1. Q1: capitalize "duskfire"
2. Q2: capitalize "terrorize" and "duskbringer." if Q2's effect is applied when units are hit by Phantom Plasma as well, then the tooltip should indicate that.
3. Q3: put a period at the end of the sentence
4. Q4: capitalize "mitigation"

**Comment by redledcat** [comment]
next patch

**Comment by DeckardCainRPC** [comment]
ok
