### ISSUE TITLE
The fucking tutorial question about Base Ability Damage is still in malformed English

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1144]
one of my irl friends did the tutorial. he has essentially no knowledge about Dota 2, so i had to walk him through some concepts, such as "no buddy, the green swoosh icon is not for your magic resistance, it's your Agility." he was also baked out of his mind, so it was a fucking nightmare even BEFORE we got to this masterpiece:

"What is the Base Ability Damage of [x]?"

what the fuck? the base ability damage for a given spell, would be *that spell*. he kept fucking asking me "yo homie what's the base ability damage for Justice Overwhelming?" and i kept fucking replying "JUSTICE OVERWHELMING" and he would be like "I KNOW DAWG BUT WHAT'S ITS BASE ABILITY DAMAGE?" it took me 3 minutes of calling my fucking friend a dipshit retard to realize that THE QUESTION ITSELF was retarded, not him. at first i thought he was stuck on a question that asked what Base Ability the damage from W1 (Holy Fire) was going to be treated as. when i finally realized what was happening, i asked him to screenshot the exact phrasing of the question, and THAT'S when we had the fucking epiphany.

please, please fucking replace the question text with this instead, which is what you're REALLY trying to ask:

"What is your current percentile modifier to damage dealt by [ability_name]?"

EDIT: OH LOL AND IF YOU FUCKING TYPE "100%" IT WON'T ACCEPT IT. it doesn't accept the % sign. imagine that. imagine fucking answering the question "What is the Base Ability Damage of Justice Overwhelming?" with the profoundly wrong and unhelpful answer "100." fucking infuriating.

**Comment by ChalkyBrush** [comment]
changed question and gusbbed '%' out of your answer input
