### ISSUE TITLE
New attributes system

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#115]
1)Glyphs do not provide any attributes, include Glyphs of Lesser/Grand agi-int-str, Jugg and MP immortal glyphs
2)Tootlip shows 0 attributes
![20171103223012_1](https://user-images.githubusercontent.com/32621322/32392416-451cf43a-c0de-11e7-84d6-83e5527813fb.jpg)

**Comment by ChalkyBrush** [comment]
![image](https://user-images.githubusercontent.com/5232984/32410595-f22c7a8a-c19a-11e7-83fc-60fbf12d9755.png)
