### ISSUE TITLE
Deckard's Omniro Gripe Sheet

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1161]
=== GENERAL ISSUES ===

1. many users will tell you the exact same thing about omniro: he causes 1 FPS for everybody while attacking at maximum (or greater) attack speed, with or without W toggled on. he's also incredibly prone to getting the "Too Fast!" W error message, and so is Arkimus. i think it may be necessary to amend that W lockout code to include exceptions for heroes with togggled W abilities. curiously, chernobog does not appear to be able to lock his W out, but Jex's Lightning/Lightning W is affected as well.

2. the element bar UI is positioned high enough so that it doesn't obscure the buff bar, but it does obscure NPC dialogue. this is a fucking nightmare for new players, who don't already know what the NPC is saying.

=== ELEMENTS ===

1. NONE of the fucking element tooltips list a damage type, and NONE of the rune tooltips tells you that the elemental hits *really do* deal Base Ability Damage appropriate to their rune tree. jesus christ chalky

2. Normal's Orb effect: affect -> effect.

also, remove the word "big"

3. Lightning's Mace effect: is it supposed to deal an instance of W Lightning damage with a base damage value equal to a % of the target's current HP? the sentence is missing a couple critical details so i have no clue

the scaling string currently says "EXTRA DAMAGE % OF TARGET'S" which is weird. change it to "CURRENT HP% DAMAGE" if that's what it's even supposed to do.

4. Poison's Mace effect: capitalize "orb effect" since apparently that's the proper phrasing used in all other tooltips.

also, 10x damage when WHO is standing in the pool? you, or the enemy with the DoT debuff?

5. Arcane's Orb effect: "pulses of the basic proc" -> "instances of the Omni Mace Effect" 

6. Ice's Orb effect: "380 and applies basic ice mace's slow." -> "380, and applies the Omni Mace Effect's slow to all enemies struck."

7. Ghost's Orb effect: it says the shroud's base duration is "400 second." you copy-pasted the HTML formatting for Undead's color, and forgot to change 400 to a different number. we love you anyway

8. Demon's Mace effect: "green" -> "percentile"

9. Undead's Mace effect: the scaling string says "disble" instead of "disable"

10. Undead's Orb effect: "everything in its path" -> "enemies in its path"

"and applies" -> "while also applying"

11. Nature's Orb effect: "and scales with levels" -> "and scales with Nature's element level"

12. Wind's Orb effect: the wind blast can push units which SHOULD be immobile, most notably the Annoying Kobold Dispenser Totem in Redfall Shipyard, which MUST be killed in order to proceed; once you've inadvertently chucked the Totem into the fucking water, you have soft-locked the game because Omniro cannot attack it anymore. please consider changing the AoE knockback to a 70% miss chance for 12 seconds instead.

13. Shadow's Mace effect: "amplified" as in just bonus damage, or post-mitigation? please specify

14. Shadow's Mace effect: "that makes removes their armor reduction" (what in the fuck?) -> "that removes their armor's resistance to physical damage"

15. Earth's Orb effect: "AOE" -> "radius." note the period at the end of the sentence.

=== Q SPELL ===

1. please add the following line to Q's tooltip: "The extra instance of damage provided passively by this ability will be of the same damage type(s) and element(s) of the rune that enhances it."

=== W SPELL ===

1. please add the following line to W's tooltip: "All effects scale with Omni Orb's level as well as that element's rune level." there is currently no indication that advancing W beyond rank 4 provides any benefit whatsoever.

=== E SPELL ===

1. E spell tooltip: from -> front

2. E spell tooltip: capitalize "omniro" in the second sentence

3. E spell tooltip: en -> an

4. E spell's buff tooltip: "and Free Pathing" -> "and free pathing"

=== GLYPHS ===

1. Glyph T7: in the event of a tie, do ALL highest-leveled elements gain this bonus?

2. Glyph T5_A (Immortal Glyph): "Highest" should not be capitalized.

since it contains several other errors, just replace the entire glyph tooltip with this:

"Omniro's four highest level elements gain a percentile damage bonus. 1st: @special_property1%; 2nd: @special_property2%; 3rd: @special_property3%; 4th: @special_property4%."

if this glyph is a post-mitigation damage amp effect (i highly doubt it), please say so

=== IMMORTAL WEAPONS ===

1. Immortal Weapon 1 (Omnichromatic Hammer): the tooltip says  "Omniro's basic elemental mace effect triggers twice on each attack." the only other place "basic elemental mace effect" is ever used, is in the tooltip for the Drakken weapon (Immortal Weapon 3). is that different from the "Omni Mace Effect" heading, which appears in the tooltip of all the elements in the hero's special UI? if it's not, then what the fuck?

instead of using the phrase "basic elemental mace effect," you can just write "@Ability1 Effect" (which will print Omni Mace Effect, the same phrase used in the element tooltips).

2. Immortal Weapon 3 (Mace of the Drakken): see above. i'd also like to add that this weapon sounds far more powerful than all of his other weapons; it's better at refreshing his elemental charges than both Immortal Weapon 2 and Glyph T6 combined...

**Comment by redledcat** [comment]
"DOTA_Tooltip_modifier_omnimace_earth_buff_Description"				"Increased armor and "	
"DOTA_Tooltip_modifier_omnimace_nature_debuff_Description"			"Rooted and taking damage each send"

**Comment by ChalkyBrush** [comment]
thank you sir
