### ISSUE TITLE
Omniro's weapon names need more variety

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1162]
so use these new names instead:

		//Weapons
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_00"		"Dull Mace"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_01"		"Iron Hammer"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_02"		"Chrome Cudgel"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_03"		"Lead Gavel"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_11"		"Faceted Club"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_12"		"Bismuth Flange"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_13"		"Silver Maul"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_14"		"Spinecrusher"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_21"		"Coruscating Flail"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_22"		"Heavy Mallet"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_23"		"Gleaming Bruiser"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_24"		"Atomic Pulverizer"
		"DOTA_Tooltip_ability_item_rpc_omniro_weapon_25"		"Martel de Fer"

**Comment by ChalkyBrush** [comment]
👍
