### ISSUE TITLE
[Omniro] item bug

### ISSUE THREAD

**Issue by nsssllllll** [ChalkyBrush/roshpit-bug-tracker#1165]
1.@Ability4 is not refreshed when equipped with Plate Of The Watcher
2.@Ability2 is not triggered when equipped with Frostburn Gauntlets

**Comment by nedamettin** [comment]
plate of the watcher says "cast"
frostburn gauntlets work (i have a build based on it)

**Comment by redledcat** [comment]
Since there are no cast procedure for omniro mace, this isn't a bug, Omniro just don't have way to proc @Ability1 casts
