### ISSUE TITLE
Drow Glyph of Splitting Arrows mistakenly says [Q1] instead of [Q2]

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1167]
discord user Left Click posted a screenshot of the issue. apparently you apply Infinity Lift to struck enemies, not Biting Stars...

**Comment by redledcat** [comment]
@DeckardCainRPC welp. EVERY glyph now has Q1 istead of whatever rune it had.

**Comment by redledcat** [comment]
https://cdn.discordapp.com/attachments/331554376181219350/575697490632900608/unknown.png

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/57385251-c4bbab80-71ba-11e9-8cbb-98c5278ba585.png)
![image](https://user-images.githubusercontent.com/32621322/57385268-cf764080-71ba-11e9-9062-dc9972c05541.png)
![image](https://user-images.githubusercontent.com/32621322/57385270-d1d89a80-71ba-11e9-84fb-3a0f48eb7185.png)

**Comment by ChalkyBrush** [comment]
@Nintai this was u :D
