### ISSUE TITLE
Silence +Flamewaker's W arcana

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1173]
In some cases you are being softlocked without any way to proceed in solo.
Maybe add some kind of timer if you are silenced for 10 consecutive seconds, W turns off?

**Comment by DeckardCainRPC** [comment]
[*in the voice of Lucifer*] but that would kill Mask of Mugato builds!

**Comment by redledcat** [comment]
-unstuck, babyyyyyyy
