### ISSUE TITLE
游戏掉线，装备删除

### ISSUE THREAD

**Issue by kapii4ever** [ChalkyBrush/roshpit-bug-tracker#1174]
要求补偿 Ancient Tanari Waterstone
今天打海图，突然掉线无法连接，而且无法连接，装备就这样不见了
![Untitled](https://user-images.githubusercontent.com/48509156/57444806-9229b580-7283-11e9-883f-73b6ce1fb720.png)

**Comment by ChalkyBrush** [comment]
any translate?

**Comment by redledcat** [comment]
![d](https://user-images.githubusercontent.com/32621322/57637472-311c1d80-75b4-11e9-9b44-2445e6812a52.PNG)
