### ISSUE TITLE
Sea Fortress can crash on load, angry purple text in console log

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1177]
the angry purple text is 2 paragraphs about something to do with failing to load a model, and it's catastrophic (causes a client crash) about 30% of the time. it causes latency in all cases regardless.

**Comment by ChalkyBrush** [comment]
which model

**Comment by DeckardCainRPC** [comment]
i am trying to find out, bear with me

**Comment by DeckardCainRPC** [comment]
first, this issue is still present:

[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings
[Client] Attempting to start non-existent soundevent: Hero_SkywrathMage.Wings

every 1 second for eternity. that has to do with Curator NPC and not Sephyr; interestingly, if a player loads in as Sephyr, this spam stops.

**Comment by DeckardCainRPC** [comment]
however, i cannot get it to replicate the angry purple text i saw. i will continue closing the client and re-making a fresh sea fort game until it occurs again. i apologize

**Comment by DeckardCainRPC** [comment]
[indecipherable old coot gibberish]
