### ISSUE TITLE
Sorceress Glyph of Scorching does not affect Arcana R3

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1178]
it's not programmed to, nor does the tooltip state that it should (it specifically says Flamestrike, not [R3]). but i believe the glyph should be improved to affect the arcana r3, out of fairness, and the tooltip should be changed to say [R3] to reflect the change

**Comment by ChalkyBrush** [comment]
👍

**Comment by redledcat** [comment]
It was fixed by me I believe when I made CM constants, now affects both [R3]
