### ISSUE TITLE
Djanghor Q3 increases cooldown of Windsteel Armor

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1180]
STEPS TO REPRODUCE:
1. be djanghor with 20 q3 and Windsteel Armor equipped
2. become bird djanghor. (advanced users can become year beast djanghor if they want.)
3. cast W to get windsteel armor refraction stacks. this will add the windsteel armor cooldown buff to your buff bar
4. cast Q
5. observe that q3 has helpfully extended the duration of that windsteel armor cooldown buff. now you get to wait longer before you can get new refraction stacks from casting W! hooray!
6. :bird: :gun: 

SUGGESTED COURSE OF ACTION:
:heart: :bird:

**Comment by redledcat** [comment]
all works fine now
