### ISSUE TITLE
silverspring gloves gives real 10% attack damage vs 1000% bonus in description

### ISSUE THREAD

**Issue by DSDampir** [ChalkyBrush/roshpit-bug-tracker#1184]
In the description silverspring gloves it's written "base attack damage is increased by 1000% of your health regen stat". But real effect equal 10%. Please check it and fix. Screenshots from game applied.  http://www.picshare.ru/view/10068734/
http://www.picshare.ru/view/10068735/

**Comment by Nintai** [comment]
First picture:
181499 dmg

Second picture:
20481 hp regen which is converted to 204810 dmg
Total (probably including some bonus from str): 470635 dmg

seems to work fine?

I hope u arent confusing 1000% with 1000x?
1000% = 10x

**Comment by DSDampir** [comment]
Oh, really! I'm so sorry! Was confused difference between 100% and 1000% (really X10, but it seems like x1000 Lol, sorry 😱)
