### ISSUE TITLE
In-game hero lore blurbs need larger font size, and center-align instead of left-align

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1185]
"""lore"""

**Comment by ChalkyBrush** [comment]
![image](https://user-images.githubusercontent.com/5232984/58374137-ad90f380-7f06-11e9-85ae-eb99be2fd6a7.png)

**Comment by redledcat** [comment]
![58374137-ad90f380-7f06-11e9-85ae-eb99be2fd6a7](https://user-images.githubusercontent.com/32621322/58374348-69711380-7f45-11e9-89e0-8fd4deca9f39.png)

**Comment by redledcat** [comment]
I think it's all fine now since Zohran's lore been removed and rewritten
![image](https://user-images.githubusercontent.com/32621322/99918545-b0052100-2d28-11eb-8924-4efe6c5d0799.png)

**Comment by redledcat** [comment]
What is more important, Rubilash is missing lore
