### ISSUE TITLE
Shipyard Veil LV3 shield stacks do not increase Q spell's BAD%

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1186]
STEPS TO REPRODUCE:
1. have like 89% BAD from an item roll
2. you now have 189% to all abilities
3. get 4 stacks of Shipyard Veil. each stack is supposed to yield 100% BAD to Q
4. check your stats panel
5. you still only have 189% to all abilities, and not 589% to Q

**Comment by Nintai** [comment]
Dmg bonus worked fine, it just wasnt shown in character sheet. Fixed it, will be in next patch
