### ISSUE TITLE
[Cytopian Laser Glove] Damage is broken

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1188]
It seeems laser gloves uses good old bug when number of targets affected square damage for each target affected, like Trapper's bomb is used to be.
Damage dealt on solo target seems to be fine, but when you include second training dummy in becomes growing exponentially.
I wonder how high it goes with only 10 targets

**Comment by redledcat** [comment]
![20190526135524_1](https://user-images.githubusercontent.com/32621322/58380774-f5268680-7fbd-11e9-8398-01a1d13c289b.jpg)
![20190526135223_1](https://user-images.githubusercontent.com/32621322/58380775-f5268680-7fbd-11e9-9f54-c36468882812.jpg)

**Comment by redledcat** [comment]
16 targets 27-28 digits

**Comment by redledcat** [comment]
13 digits solo target
![20190526135709_1](https://user-images.githubusercontent.com/32621322/58380792-328b1400-7fbe-11e9-825c-ae11a5145bfe.jpg)

**Comment by Nintai** [comment]
Will be fixed next patch
