### ISSUE TITLE
Bug with Drow Ranger's Astral Cloud

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#119]
![drow_bug](https://user-images.githubusercontent.com/15161630/32411458-d9faac2e-c1eb-11e7-962a-35ac6cc26370.gif)

**Comment by StillStealSteel** [comment]
It's still there, and works not only like that. Sometimes if you cast new arcana cloud at the same time when you fall off from previous arcane cloed disappear/

**Comment by redledcat** [comment]
Label master is back!
