### ISSUE TITLE
Arkimus E3 bonuses to Phys/Magical post-mit amp can be made permanent

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1192]
Friday, May 31, 2019

[3:32 PM]
dark:
	deckard
	wanna hear the weirdest bug

[3:32 PM]
Deckard Cain:
	yes

[3:32 PM]
dark:
	arcana am gives all damage converted to pure
	that includes the buff u gain from e3 makes it only pure
	but if u activate ur e3 buff before ur r arcana form
	magic and  physical damage buff from e3 retains for the entire r duration
	weird useless and dunno how the fuck is it coded

[3:34 PM]
Deckard Cain:
	what are you talking about
	[E3] Elevated System: Gain increased post-mtiigation damage amp for 3 seconds after landing from an Orbital Leap

[3:35 PM]
dark:
	in body arcana form
	that post amp gained
	applies to only pure damage

[3:35 PM]
Deckard Cain:
	of course it does, all damage dealt is converted to Pure during archon form

[3:36 PM]
dark:
	yes but it should list to amp all damage not only pure
	in the  stats tab

[3:37 PM]
Deckard Cain:
	what the fuck? so someone deliberately programmed the E3 buff to only apply to outgoing Pure damage during archon form, and NOT apply its bonus to Phys or Magical?
        furthermore, if you gain E3 while archon form is NOT active, THEN activate archon form and wait for E3 to time out, you will permanently retain E3's Phys and Magical post-mit amp bonuses for the rest of the game session?

[3:38 PM]
dark:
	yes

**Comment by DeckardCainRPC** [comment]
screenshot of e3 amping only Pure, when gained during archon form:
https://cdn.discordapp.com/attachments/361559146988044289/584103888504750092/unknown.png

screenshot of e3 not present on buff bar, despite giving Phys/Magic post-mit amp during archon form:
https://cdn.discordapp.com/attachments/361559146988044289/584104067845062657/unknown.png

**Comment by DeckardCainRPC** [comment]
[3:54 PM]
dark:
	CAIN

[3:55 PM]
Deckard Cain:
	what

[3:55 PM]
dark:
	u only gain magic and phys amp during archon form
	meaning this bug is usless u wrote in the report that its pernament for the game session

**Comment by redledcat** [comment]
>no more post-mitigation
>arkimus is fully remade in lua abilities
>I can't reproduce it with current E3 to bug in _any_ way
