### ISSUE TITLE
Remove the self-push from Slipfinn Arcana E1 and the enemy-push from Omniro E3

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1194]
nedamettin demonstrated that if you try to invest any amount of e1 with slipfinn's arcana, every time you fucking press Q you rocket your own ass completely out of bounds

and i think everyone, literally every player we have, all 2 million of them or whatever, have all said "fuck omniro's e3, change it immediately" in their native tongue

**Comment by nedamettin** [comment]
recommended action for slipfinn: while e1 is active, it makes you roll at your location instead of foward.

**Comment by DeckardCainRPC** [comment]
ah, so using Q would hold you in place for like 1.5 seconds instead? like putting on the brakes temporarily?

**Comment by nedamettin** [comment]
yes

**Comment by DeckardCainRPC** [comment]
omniro's e3 no longer pushes back

**Comment by redledcat** [comment]
and slipfinn's E1 changed so it slows you down instead
