### ISSUE TITLE
New tooltip

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#120]
NaN Magical Resist
![screenshot_4](https://user-images.githubusercontent.com/15161630/32412480-1c66086a-c20a-11e7-9f54-566300364e85.png)

**Comment by redledcat** [comment]
Attack range does not anymore shown as circle with radius

**Comment by redledcat** [comment]
Base ability damage of Q W E R displays incorrectly if there is 4- digit number, i.e. "1025.5%" displays as "1025..." 
(Scale text with window size/ do not display decimal parts of number?)

**Comment by redledcat** [comment]
only attack range radius is mising at this point.

**Comment by Nintai** [comment]
I think this was fixed long ago
