### ISSUE TITLE
Map disconecting!!!

### ISSUE THREAD

**Issue by jaxious99** [ChalkyBrush/roshpit-bug-tracker#1201]
idk whats wrong but after DOTA updated few days ago, something is wrong with the conection of the map. It just nonstop disconecting me from the map. And i cant play with other ppl. Me and my friends will be disconect from the map right after 2 or more players load/pick thier hero. And this happended even i play alone after 50-60m of the game. Pls fix this :(

**Comment by Nintai** [comment]
![image](https://user-images.githubusercontent.com/5485559/59180267-c33c2500-8b64-11e9-853c-6f5013647fd5.png)

![image](https://user-images.githubusercontent.com/5485559/59180270-c8996f80-8b64-11e9-87db-f5bd1540b168.png)

![image](https://user-images.githubusercontent.com/5485559/59180277-ce8f5080-8b64-11e9-81b9-e118c4bee66b.png)
