### ISSUE TITLE
[Ring of Nobility] Probably bugged after backend rework, doesn't count kills properly

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1206]
yangToday at 11:54 AM
anyone knows why the kill count of Ring of Nobility doesn't increase when i kill mobs?
tried to slain mobs at sea & serengarad
both doesnt give kill count

**Comment by GoToNightmare** [comment]
![20190623191206_1](https://user-images.githubusercontent.com/34166246/59977475-d6ca9f80-95ea-11e9-9c79-a345b82f1d1c.jpg)
![20190623191134_1](https://user-images.githubusercontent.com/34166246/59977476-d7633600-95ea-11e9-8ae6-f99c814e6130.jpg)

**Comment by redledcat** [comment]
another guy responds counter doesn't work in #general-russian

**Comment by ChalkyBrush** [comment]
might be bugged after reloading it, not immediately after equip

**Comment by GoToNightmare** [comment]
fixed
