### ISSUE TITLE
Eye of Seasons not working and question about mana vs int bonuses

### ISSUE THREAD

**Issue by halhazard** [ChalkyBrush/roshpit-bug-tracker#121]
The eye of seasons doesn't do anything. please do fix and also is int supposed to give only 5 mana per int? i got screenshot at discord #bug tab. please try looking into it

**Comment by halhazard** [comment]
and if possible buff it up a little like 4int=1.5 str & agi. to increase its value a bit more.

**Comment by ChalkyBrush** [comment]
no bugs here!
