### ISSUE TITLE
今日补修后再出问题

### ISSUE THREAD

**Issue by zhomm2013** [ChalkyBrush/roshpit-bug-tracker#1210]
疯狂生长模式下（此阶段正常传说模式没有问题），落红树林进入船厂后，船厂最后boss刷怪阶段卡死，试了两次，刷到一定阶段之后不再出怪，无法打boss，网络正常。
![QQ图片20190627011414](https://user-images.githubusercontent.com/52236400/60200579-fbd44200-9878-11e9-9e77-75fe821c9323.png)
很期待这个图能做得更好，望尽快修复！

**Comment by ChalkyBrush** [comment]
this is fixed tonight

**Comment by zhomm2013** [comment]
> this is fixed tonight

Has it been fixed?

**Comment by ChalkyBrush** [comment]
no, ~6 hours from now when I get home to deploy patch

**Comment by zhomm2013** [comment]
> no, ~6 hours from now when I get home to deploy patch

thanks
