### ISSUE TITLE
为什么刚刚更新变这样了？

### ISSUE THREAD

**Issue by zhomm2013** [ChalkyBrush/roshpit-bug-tracker#1211]
27日修复之后进入落红树林不载入城镇NPC(尝试了两次重新建立新房间)
![QQ图片20190627084008](https://user-images.githubusercontent.com/52236400/60224909-30ff8500-98b7-11e9-8ac1-25fc827ce0a3.png)
已经正常了，请忽略。

**Comment by Nintai** [comment]
Was fixed already
