### ISSUE TITLE
[Astral Ranger] R and R1 not working on magic immune

### ISSUE THREAD

**Issue by FrozenAn** [ChalkyBrush/roshpit-bug-tracker#1219]
Astral Ranger R and R1 not working on magic immune units. Not sure if it's a bug or not, but Q2 works(Same Element and Damage Type).

**Comment by redledcat** [comment]
R and R1 are spells while Q2 is an attack modifier. Read more about damage types and spell immunity on dota 2 wiki.
Pure damage doesn't matter it can pierce spell immunity effect, physical the same. And sometimes magical spell can pierce spell immunity, but won't deal damage.
https://dota2.gamepedia.com/Spell_immunity
