### ISSUE TITLE
肉山谷地图是否有兼容性问题

### ISSUE THREAD

**Issue by zhomm2013** [ChalkyBrush/roshpit-bug-tracker#1223]
![image](https://user-images.githubusercontent.com/52236400/61126616-85be1500-a4df-11e9-8e10-2ad8ca5ec2c8.png)
无论在dota2本体游戏中亦或是其他游廊游戏，隐藏伤害数字这个选项运作都很正常，在肉山谷地图里，隐藏伤害数字一旦关闭，在刚设置的一小段时间里可以看到伤害数字，但之后就会莫名的自动开启隐藏伤害数字，也就再也看不到了，尝试过诸多设置方法并没有什么效果。
求解答。

**Comment by redledcat** [comment]
was removed for better perfomance I think. There are too much damage instances going on on the screen to keep it online. more popups = more lags and higher chance for crash
Healing popups were removed intentionally.
