### ISSUE TITLE
[Winterblight 2.0] Merkurio can spawn as paragon, keeps breathing fire while not hostile

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1238]
STEPS TO REPRODUCE:
1. Merkurio can spawn as a Paragon
2. if he has any of the affixes that cause him to spit fire or explode in ice or jump around or blink around... he will continue to fucking do that even while non-hostile after opening the dungeon

SUGGESTED COURSE OF ACTION:
shock the monkey

**Comment by redledcat** [comment]
done
