### ISSUE TITLE
Sapphire Lotus is now displayed entirely in Chinese on the ENTIRE WEBSITE

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1241]
STEPS TO REPRODUCE:
1. search "sapphire lotus" on the market
2. what in tarnation

ALSO:
1. type anything into the market field
2. now delete all of it, leaving the field blank
3. Sapphire Lotus will display, in Chinese
4. conspiracy

**Comment by DeckardCainRPC** [comment]
OH GOD OH JESUS

**Comment by redledcat** [comment]
Seems to be fixed for now, until someone tries to do that prank again
