### ISSUE TITLE
Arena Prizebox has been curated and now appears, in Chinese, on website/items

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1249]
we are being pranked

https://cdn.discordapp.com/attachments/299728973380976651/616883832867782686/unknown.png

**Comment by DeckardCainRPC** [comment]
it is definitely not a coincidence that Sapphire Lotus has also been fucked with somehow #1241

**Comment by redledcat** [comment]
seems to be fixed
