### ISSUE TITLE
Stargazer is broken

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1259]
STEPS TO REAP THE GOOSE:
1. rpc_tutorial
2. put on the stargazer trinket
3. issue an attack-move order anywhere on the map:tm:
4. no cosmic aperture
5. blame nintendo

**Comment by redledcat** [comment]
should be fixed now? it was working only after fresh equip, and not on load

**Comment by DeckardCainRPC** [comment]
ok
