### ISSUE TITLE
Djanghor R ability broken

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#126]
After using it once it gets broken completely and cannot be used again.

**Comment by ChalkyBrush** [comment]
it works but the hotkey is changed

**Comment by SilentC** [comment]
I tried it out multiple times today. Bugs every time regardless of hotkey.
The hotkey isn't the problem.

![20171107152447_1](https://user-images.githubusercontent.com/32886049/32516010-e329bb10-c3cf-11e7-8ce4-7c685e71e35d.jpg)

Can only be used once and bug starts.
Other heroes R works. Posted this because he's the only one so far with this bug.

**Comment by ChalkyBrush** [comment]
https://www.reddit.com/r/DotA2/comments/7babpx/timbersaw_chakram_ability_not_active_major_bug/

valve will have to fix ASAP

**Comment by ChalkyBrush** [comment]
fixed for next patch
