### ISSUE TITLE
Add Synthesis Vessels and Reanimation Stones to the Key Bank

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1262]
why yes, this is a repost of #1084

**Comment by redledcat** [comment]
please 26 out of 46 my vessels and 5 reanimation stones need a new home

**Comment by DeckardCainRPC** [comment]
progress: 50%

**Comment by redledcat** [comment]
I wan, said the frog to the snel
