### ISSUE TITLE
Ultimate-linked item effects do not work due to last patch

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#127]
1. Watcher
2. Voyagers
3. Temporal boots
4. Signus

**Comment by redledcat** [comment]
Light Seer Robes do work
And Armor of Secret Temple
and seems all other items based on beginRchannel work too, only cooldown interactions are broken

**Comment by ChalkyBrush** [comment]
fixed this morning
