### ISSUE TITLE
[Tanari] New attack system makes puzzles behave really weird

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1276]
https://youtu.be/uQN-E-nlREc

**Comment by ChalkyBrush** [comment]
i fixed this particular puzzle, but it's not a blanket fix. The new auto attack system deals 2 instances of damage (technically).

Any other bugged puzzles that you know of?

**Comment by redledcat** [comment]
probably scepters in the wind part
