### ISSUE TITLE
Magistrate Hood bugs the stats panel

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1279]
NoticeMeSenpai (@Fed#7269) bitched about it to me, and before that, he said he discussed it in #bugs. redledcat and Tony are evidently aware of this issue, so ask them what the fuck is happening. i'm only making this ticket because Fed was too lazy

**Comment by GoToNightmare** [comment]
i believe its fixed.
