### ISSUE TITLE
[Iron Treads & Kabuto helm] Immortal bug (100% damage resistance all the time)

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1284]
Step to reproduce:
1.) Pick any hero with low ability 4 cd. 
2.) To make things easier, just wear the Signus charm for more ability 4 cd reduction.
3.) Wear Iron tread.
4.) Use ult, goes into somewhere crowded with creeps.
5.) Murdering them.

This video here, featuring bahamut on a sea run with that combo on.
https://www.youtube.com/watch?v=XvDZa96blxY

What happened: 
-Iron treads skip the channeling of your ult, and Kabuto helm grand 100% damage reduction while channeling it. Using Iron treads will skip the channeling part, but it somehow still remains the 100% damage reduction.
-Now this part is the weird one: The Kabuto helm effect always have the fixed duration of nearly 8 seconds, which is the same channeling time of Sephyr R. It seems like since the base channeling was skipped, it just look for whatever highest channeling time it can find, and then make it the 100% damage resistance effect lifetime.

**Comment by ChalkyBrush** [comment]
fixed
