### ISSUE TITLE
[Venomort] Hook of the Fetid Valley (Immortal Weapon 3) Uses current health instead of max health for dmg calculation on E2

### ISSUE THREAD

**Issue by crazybrain228** [ChalkyBrush/roshpit-bug-tracker#1289]
`e2_damage = e2_damage + e2_level * VENOMORT_IMMORTAL_WEAPON_3_E2_DAMAGE_PER_RUNE_FROM_HP_PERCENT / 100 * caster:GetHealth()`
Expected `caster:GetMaxHealth()` got `caster:GetHealth()` instead.

**Comment by redledcat** [comment]
was fixed, op now
