### ISSUE TITLE
[Elemental Warlord] Dragonborne Helm's Q1 Tooltip

### ISSUE THREAD

**Issue by crazybrain228** [ChalkyBrush/roshpit-bug-tracker#1291]
"Warlord gains increased post-mitigation damage against enemies who are stunned _**or frozen**_"
However, the following line in the tooltip only has "stunned enemies" and the code only seems to check for if the enemy is stunned.

**Comment by TheVietboi** [comment]
wait... perhaps it's only in test version only?
i can't tell, need someone to push the code here to confirm.
