### ISSUE TITLE
Particle effect of Ekkan's E teleportation

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#13]
There is a ~2000 radius ring around hero standing in E portal when effect of "Dark Rift" starts.

**Comment by redledcat** [comment]
![20171010133634_1](https://user-images.githubusercontent.com/32621322/31382378-bfd2e228-adb7-11e7-9b6a-0d73b05a3c4b.jpg)

**Comment by redledcat** [comment]
The ring's radius changes randomly.

**Comment by ChalkyBrush** [comment]
great detail thank you

**Comment by ChalkyBrush** [comment]
fixed for next patch
