### ISSUE TITLE
[Chernobog] normal R2 decrease your shadows damage, instead of increasing it

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1300]
![image](https://user-images.githubusercontent.com/51455274/68453033-f1628580-0226-11ea-8ef6-a6581a6f2a6b.png)
Normal
![image](https://user-images.githubusercontent.com/51455274/68453039-0212fb80-0227-11ea-953a-a1bcd0a4c783.png)
without r2
![image](https://user-images.githubusercontent.com/51455274/68453075-19ea7f80-0227-11ea-8225-d81c753f250e.png)
with r2 on

**Comment by redledcat** [comment]
it works and deals correct damage
