### ISSUE TITLE
[4.0] Tutorial NPC needs to be updated, Tutorial quests cannot be completed at this time

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1303]
as an example, his quest dialogue chain abruptly aborts during 2 (Hero) B (Hero Attributes): when it tries to load the 4th question, regarding your BAD%, the script just abandons ship and doesn't pop up anything.

there are *surely* more examples

**Comment by ChalkyBrush** [comment]
fixd
