### ISSUE TITLE
[4.0] Crimsyth Meepo miniboss aura fucks with Yasha/Tyrius/Sapphire etc.

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1304]
**UPDATE:** actually dying *at all* removes sapphire lotus max MP gain for the remainder of the game session, the crimsyth meepo has nothing to do with this

STEPS TO REPRODUCE:
1. wear Sapphire Lotus. this item adjusts the HP/MP gains you get from INT.
2. go fight that asshole of a meepo. his aura fucks with your attribute bonuses from equipment. observe that, as expected, your max HP/MP is reduced.
3. die while within his aura. lol
4. when you respawn, your Sapphire Lotus will affect your HP, but not your MP for some reason. you will gain only the default 5 MP per INT.
5. get clever and go to the blacksmith, and chisel off your Lotus. surely this will fix your max MP issue.
6. no, it does nothing. this issue persists for the duration of the game session. re-entering meepo's aura to kill him won't fix it either.

**Comment by DeckardCainRPC** [comment]
actually dying *at all* removes sapphire lotus max MP gain for the remainder of the game session

**Comment by ChalkyBrush** [comment]
👌
