### ISSUE TITLE
维萨吉至宝Q3不生效  Visaji Zhibao Q3 does not take effect

### ISSUE THREAD

**Issue by LiuLi233** [ChalkyBrush/roshpit-bug-tracker#1305]
维萨吉装备至宝并习得Q3后，在召唤物附近击杀敌人，召唤物无法正确获得层数
Equip with the most precious weapon and learn Q3. Kill the enemy near the summoned item. The summoned item can't get the correct number of layers

**Comment by redledcat** [comment]
should be fixed now
