### ISSUE TITLE
[4.0] Twig key item from Redfall Forest may not be dropping anymore as a result of 4.0 tweaks

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1306]
the twig i'm talking about is the one which starts the quest for https://www.roshpit.ca/items/item_rpc_autumn_sleeper_mask . ordinarily it is capable of dropping from any redfall monster, exactly once per game session.

the reason i bring this up is because i've played a good handful of complete redfall runs in 4.0, and i have yet to see the twig drop. also notable is the fact that the helm item has not yet been curated, which may indicate that i'm not the only one who hasn't been finding any twigs.

**Comment by redledcat** [comment]
I just dropped it, so maybe it just being lost in other drops?

**Comment by DeckardCainRPC** [comment]
does it drop if -junk is on?
