### ISSUE TITLE
Properties on roshpit.ca Items are unsorted

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#131]
Order of possible rolls depends on what was curated first and last, so it's complete chaos for each property.
![properties](https://user-images.githubusercontent.com/32621322/32538743-bf8c7990-c46f-11e7-9ee8-6062ea9b8b45.PNG)

**Comment by ChalkyBrush** [comment]
it's been alphabetical for about a month

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/37419030-3afcfe74-27bc-11e8-9736-0ca8e8ecac21.png)

**Comment by redledcat** [comment]
![1](https://user-images.githubusercontent.com/32621322/37419102-6bcfcac2-27bc-11e8-9df3-5a94c15aca49.PNG)

**Comment by redledcat** [comment]
this happens when you choose any property in the list

**Comment by redledcat** [comment]
bump? like every single item mixes all curated runes/stats when you choose one in the list.
I guess if at least one of them is curated in non-eng translation
![screenshot-151](https://user-images.githubusercontent.com/32621322/37987066-7e297c9a-31fd-11e8-8e3c-a8bb1e781104.jpg)
![screenshot-152](https://user-images.githubusercontent.com/32621322/37987134-a3ee603a-31fd-11e8-8617-30c39ec51c41.jpg)
![screenshot-153](https://user-images.githubusercontent.com/32621322/37987145-ad714208-31fd-11e8-9d73-68e25cec03bf.jpg)
![screenshot-157](https://user-images.githubusercontent.com/32621322/37987147-af13aab0-31fd-11e8-802d-4fc45c0260c9.jpg)
![screenshot-158](https://user-images.githubusercontent.com/32621322/37987149-b0d7ba44-31fd-11e8-8b03-0d6db81e1223.jpg)
