### ISSUE TITLE
[4.0] I can't get Temporal Warp Boots to do what they say they're supposed to

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1311]
i've tried:
1. double leftclicking on the ground somewhere that isn't in the fog of war
2. double rightclicking on the ground somewhere that isn't in the fog of war 
3. double leftclicking on the minimap somewhere that isn't in the fog of war
4. double rightclicking on the minimap somewhere that isn't in the fog of war
5. gritting my teeth so hard that my neck stiffens and my colon prolapses

**Comment by TheVietboi** [comment]
One time in test i accidentally made them working. Seems like it only function within a few seconds?
(that time was a few moments after you wrote this)

**Comment by DeckardCainRPC** [comment]
fixed now
