### ISSUE TITLE
[4.0] Remove "LV2" items from database, they interfere with Market search results

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1312]
this includes Raven Idol, Stormcrack Helm, and others

**Comment by ChalkyBrush** [comment]
but they are removed 🤔

**Comment by DeckardCainRPC** [comment]
https://www.roshpit.ca/items/item_rpc_raven_idol2

**Comment by ChalkyBrush** [comment]
> https://www.roshpit.ca/items/item_rpc_raven_idol2

what the FUCK
