### ISSUE TITLE
[4.0] Gravelfoot Treads isn't cleansing Ghost Mace

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1313]
more like asselfoot dicks

**Comment by DeckardCainRPC** [comment]
upon second inspection, it doesn't cleanse shit

**Comment by ChalkyBrush** [comment]
is this shit fixed?

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush it at least purges ghost mace and a bunch of other shit in seafort, so it's good for now
