### ISSUE TITLE
[4.0] Ruinfall Skull Token can spawn, with sockets, but it has no gem data

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1315]
https://cdn.discordapp.com/attachments/299728973380976651/662099868621340676/unknown.png

**Comment by redledcat** [comment]
Yeah, several items were added to the game, but some stuff Chalky considered as **not worthy** and haven't done any changes (and gems) for them.
Ghost Slippers, Fangs of Silitcicus, Badge of Honor and Steelbörk are also here.

**Comment by ChalkyBrush** [comment]
ya not really a bug, just cut in the name of time contraint /efficiency
