### ISSUE TITLE
base ability name on rune description for ults

### ISSUE THREAD

**Issue by ChalkyBrush** [ChalkyBrush/roshpit-bug-tracker#133]
![image](https://user-images.githubusercontent.com/5232984/32563358-0fff7c24-c47f-11e7-83c0-295d55b18a5f.png)

**Comment by ChalkyBrush** [comment]
check super ascendancy

**Comment by ChalkyBrush** [comment]
and burning spirit

**Comment by ChalkyBrush** [comment]
done

**Comment by redledcat** [comment]
@ChalkyBrush 
![20171114011129_1](https://user-images.githubusercontent.com/32621322/32755203-d6a802a4-c8dc-11e7-9293-d712e7238dc6.jpg)
