### ISSUE TITLE
[4.0] Put a stack limit on Venomort's W3

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1330]
i hate to report this, because i intended to abuse it for debugging endgame content on a hero capable of withstanding such a severe, unrelenting ass whooping...

but venomort's w3 is the game's most convenient source of +all attributes, and that is the understatement of the new decade. combined with sange boots, lifesource vessel, etc., he can deliberately aggro hundreds of creeps WITHOUT killing them, and then walk around with +5000 to all attributes while belting out **utterly retarded dps** with E2 (and W1 but that would very likely cause W to kill monsters when tagging them for W3 abuse). i am primarily reporting this issue because of its tendency to crash servers, and not its gamebreaking power - it encourages players to fly around the map and spawn inordinate numbers of monsters without killing any of them, leading to performance loss and eventually server death.

with this nerfed, the only insane damage output venomort has left is R spam + buzuki, but i don't consider that a problem since viper spam builds are a punishment unto themselves

**Comment by ChalkyBrush** [comment]
i reworked w3 because what the FUCK

**Comment by DeckardCainRPC** [comment]
![image](https://user-images.githubusercontent.com/34521754/72407140-8b194800-372c-11ea-96f9-66527f87a76c.png)

discord user MoMenTuM_KR was my favorite abuser of this while it lasted
