### ISSUE TITLE
[4.0] Sephyr E2 attack power scaling seems to be 10x lower than intended

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1334]
144 points in E2 yields only 4.32% of attack damage added to E1 puck damage. i believe this may be the same issue i brought up regarding slipfinn's arcana e2 damage scaling, which was also 10x lower than intended

**Comment by redledcat** [comment]
E2 isn't a percentile modifier. It adds 1 base attack damage per rune for each puck hit.
Maybe tooltip isn't clear enough

**Comment by redledcat** [comment]
Renamed to "Base Attack Damage per stack"

**Comment by redledcat** [comment]
Oh sorry, my bad, I looked at completely wrong value, E2 is indeed x10 lower, changed it too.

**Comment by DeckardCainRPC** [comment]
hahahaha funny this miscommunication happened to you too - when xhul pointed out the low scaling on the rune, i did the exact same thing. i'm like "oh it's not low, it gives me a lot of base damage, it's really good." then he tried again and said "no man, the attack-damage-to-puck-damage scaling is awful, 140 points for like 4%?" and i said "oh... oh. yeah wow. jeez"

**Comment by redledcat** [comment]
was fixed
