### ISSUE TITLE
[4.0] Djanghor's Year Beast E charge reduces his turn rate far longer than the duration of the charge

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1336]
resulting in him charging, then... flailing his feet comically while taking about 2 seconds to turn 90 degrees in either direction. this turn rate modifier goes away about 1 full second after djanghor arrives at his destination

**Comment by redledcat** [comment]
It's Q3 effect btw but not sure what to do about it

**Comment by redledcat** [comment]
gonna be fixed next update

**Comment by redledcat** [comment]
I'm not sure if "next update" arrived in time, I need to check it some day

**Comment by redledcat** [comment]
fixed indeed
