### ISSUE TITLE
[4.0] Chernobog's Arcana E4 shadow zones (and probably others!) attack puzzle objects via Wind Deity Crown

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1339]
it's especially annoying in the tanari wind temple's ball puzzle

**Comment by DeckardCainRPC** [comment]
and before nintai asks, no, disabling the rune(s) don't do a fucking thing. the shadow zones remain in effect around chernobog regardless.

**Comment by ChalkyBrush** [comment]
wind deity will not attack puzzle objects in next patch
