### ISSUE TITLE
PA arcana E land position and point of cast are different (as SW in #49)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#134]
Position of landing is closer than point where spell have been casted
![20171108205814_1](https://user-images.githubusercontent.com/32621322/32565540-bf8e6818-c4bf-11e7-85a8-f00859bf27aa.jpg)
![20171108205818_1](https://user-images.githubusercontent.com/32621322/32565550-c0e0087a-c4bf-11e7-91bd-88219985d3c7.jpg)

**Comment by ChalkyBrush** [comment]
not a bug, as the spell's movement is a little loose
