### ISSUE TITLE
[4.0] Epoch Guardian Time Binder lagges server to the point of crashing it

### ISSUE THREAD

**Issue by Junkus** [ChalkyBrush/roshpit-bug-tracker#1345]
Epoch Guardian's Q (Time Binder) plus Epoch Guardian's R (Eternity Flood) causes the server to lag. Time Binder on its own is enough to lag the server even when not looking at it. My friend runes a build with Boreal Granite Vest and if he gets attacked and it triggers plus he already put one down it crashes the server and game if there are more than 10 minions affected. Might also just be an infinite loop on the shard damage that is crashing the server and game.

Also, Epoch Guardian's Q Arcana have infinite range. Can literally stand in spawn and use it globally the multiplier triggers instantly doing next to nothing in damage but then he will basic attack them from spawn having the projectiles hit enemy and damage after they finish traveling to the destination.

**Comment by TheVietboi** [comment]
Uh, no. Q arcana is intended to have global cast range.

**Comment by DeckardCainRPC** [comment]
@Junkus please go to the roshpit.ca website and get a link to the non-arcana Q epoch guardian build used to cause this issue, then post that link here so we can all take a look at it

**Comment by Junkus** [comment]
Sorry about the long response time my friend who was experiencing the lag on his build hadn't been online for 2 days.
My friend said that he dismantled the build as it was causing too many problems but he said the build was Guard of Luma, Boreal Granite Vest, and Heavy Echo Gauntlet (He said the rest of the build doesn't really matter) and then using the Time Binder ability after being attack and triggering Boreal Granite Vest having 2 Time Binder effects at the same time and using Guard of Luma and Echo for extra damage.
Also about the arcana having an infinite range we thought it was a bug as it wasn't mentioned anywhere, good to know its not a bug.

**Comment by Junkus** [comment]
If you test it and don't find a problem with it, it might just be that my friend and I's computers just can't handle it disconnecting/crashing us and the server closing because nobody was on it.

**Comment by DeckardCainRPC** [comment]
@Junkus if we can't replicate the problem, we can't fix it. we need to know the exact combination of items, runes, and glyphs he was using.

**Comment by Junkus** [comment]
My friend told me it isn't worth replicating the build and told me to just close the bug report as it doesn't bother him that much as he have a new build. Sorry for ending it on that note.
