### ISSUE TITLE
[4.0] MK superslides when recieving knockback

### ISSUE THREAD

**Issue by crazybrain228** [ChalkyBrush/roshpit-bug-tracker#1347]
djanghor in any and every form, upon experiencing knockback from specific sources (Ghost Seal's Fin slap, wave blast from oracle of the sea, and boulder toss from stalacorr) will cause him to perform what can only be described as a 'super slide' in which he will, after decelerating from the knockback, steadily accelerate in the opposite direction of said knockback.

**Comment by redledcat** [comment]
https://en.wikipedia.org/wiki/Tennis_racket_theorem

**Comment by redledcat** [comment]
fixed
