### ISSUE TITLE
[4.0] Boots of Wisdom Ruby scaling makes no sense on an effect with a 0.5sec CD

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1358]
since the buff provided by the boots only goes away for 0.5 seconds, according to the boot's tooltip, even a chipped ruby (-1.2 seconds) would completely nullify the boot's drawback

**Comment by ChalkyBrush** [comment]
the base effect was bugged 🤔
