### ISSUE TITLE
[4.0] Magnetic Aether Helm (PA's head arcana) bug that cause it not functioning

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1361]
crazybrainToday at 12:47 PM
ok so investigation results
casting q arcana
applies an invisible modifier with no duration
or infinite duration
there is a thinker that executes on a 0.1s interval tied to that modifier
normally how it works is
cast q
enemy list is initialized
every 0.1s attack an enemy that is in the list (1 at a time) and remove it from said list
continue attacking enemies in said list even if q has ended (because fuck you chalky)
once all enemies in list have been depleted, it un-initializes the list which properly resets it
it then, and only then, once there is no enemies left in the attack list, and q has ended, does it remove the 0.1s thinker
however
if at any point
you die before it naturally depletes the enemy list
the thinker modifier is cleared
and you're left with an enemy list which is initialized and still full of enemies
but that aren't being attacked due to the thinker not being there
once you re-cast q
the thinker is re-applied
but the enemy list is not re-initialized
and is instead still full of enemies from before
the thinker will then resume from where it left off
and attempt to attack enemies
which may or may not alive or valid
crazybrainToday at 12:53 PM
once it empties the enemy list
it resolves normally
and starts working again
HOWEVER
when you use Q against large crowds
you will find that enemies get added to the list
faster than they can be emptied
much faster
and the thinker being removed while you're dead
means that the list is not depleted or cleared while you're dead
so once you're alive
you have to cast q
and then wait around a bit
for the list to clear itself
EACH ENEMY IN THE LIST BEFORE YOU DIED
IS 0.1S you HAVE TO WAIT FOR
BEFORE THE Q STARTS WORKING AGAIN
crazybrainToday at 12:59 PM
Oh yeah additional info
Any enemy killed by q1 split attacks that are still in the enemy list
Are not auto removed
They instead stay in the list and take up 0.1s time to check
So with high q3 and a large crowd of enemies and potentially high q spam
You can disable the q from working for a long ass time
Since each pass of the magnet from q3 re-adds the same enemy to the attack list
Which if killed before that enemy is emptied out of the list
Will still take up 0.1s to check
MAXIMUM STUPID

**Comment by ChalkyBrush** [comment]
fixed
