### ISSUE TITLE
[4.0] New Winterblight unit "Wailing snow specter" can cause particles overload

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1367]
literally freeze the game
![image](https://user-images.githubusercontent.com/51455274/72217045-d03a5000-355b-11ea-9191-dc39927881a5.png)

**Comment by TheVietboi** [comment]
![image](https://user-images.githubusercontent.com/51455274/72217053-ee07b500-355b-11ea-8aa3-4243834a67ad.png)

**Comment by ChalkyBrush** [comment]
fixed
