### ISSUE TITLE
[4.0] Dinath's Arcana spell has inordinately high mana cost

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1368]
the spell was nerfed to physical damage instead of pure (reasonable) but it costs 800 mana per second to even have it toggled on - holy fuck, batman! - and it drains ANOTHER 800 every time it launches an attack! per target! Gott im Himmel!!1

**Comment by ChalkyBrush** [comment]
what the FUCK

fixed
