### ISSUE TITLE
[4.0] Buzuki Ruby effect lasts only 2 seconds

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1369]
observe your pet's movespeed after you apply the Buzuki buff. it will gain the +120 movespeed from a Perfect ruby for only 2 seconds before the movespeed buff expires. it should last the full 30-second duration of the Buzuki buff.

**Comment by ChalkyBrush** [comment]
code seems correct here

**Comment by Nintai** [comment]
`modifier_buzuki_ms_and_as` is removed when `modifier_buzuki_powering_up` is destroyed, and this modifier only has a duration of 2.5s

`
finger:ApplyDataDrivenModifier(caster, ally, "modifier_buzuki_powering_up", {duration = 2.5})
`

			"modifier_buzuki_powering_up"
			{
				"IsHidden"	"1"
				"OnCreated"
				{
					"AttachEffect"
					{
						"Target"	"TARGET"
						"EffectName"	"particles/roshpit/winterblight/drain_blue_life_drain.vpcf"
						"EffectAttachType"	"start_at_customorigin"
						"ControlPointEntities"
						{
							"TARGET"	"attach_hitloc"
							"CASTER"	"attach_attack1"
						}
					}
				}
				"OnDestroy"
				{
					"RemoveModifier"
					{
						"ModifierName"	"modifier_buzuki_ms_and_as"
						"Target" 		"TARGET"
					}
				}
			}

**Comment by ChalkyBrush** [comment]
awesome, I put the removemodifier in the wrong ondestroy. Thanks @Nintai 😘
