### ISSUE TITLE
[4.0] BM hero statue in the Arena courtyard has a duplicated, displaced helm mesh

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1370]
![image](https://user-images.githubusercontent.com/34521754/72257467-99e2ec00-35c0-11ea-9567-9d7fcfe30fca.png)

**Comment by DeckardCainRPC** [comment]
i think this was fixed, i haven't noticed the MAGIC FUCKING FLOATING FUCKING MYSTERY HELM in recent trips

![image](https://user-images.githubusercontent.com/34521754/80060464-a00c3100-84fc-11ea-9bca-261c901aa3c2.png)

**Comment by redledcat** [comment]
lol wut
:DDDD
