### ISSUE TITLE
[4.0] Drow's Body Arcana eats 20 stacks of R3 per cast when iron treads of destruction is equipped

### ISSUE THREAD

**Issue by crazybrain228** [ChalkyBrush/roshpit-bug-tracker#1375]
The function "remove_modifier_channel_start" which is called when the channel finishes, also calls the "crystal_arrow_channel_start" function for some reason. This causes "crystal_arrow_channel_start" to be run once, when R is first pressed, and once again, after the channel finishes (which is instantly due to iron treads). 
Suggested Fix: Remove the call to "crystal_arrow_channel_start" (which is only called IF you have iron treads equipped) inside the "remove_modifier_channel_start" function.

**Comment by DeckardCainRPC** [comment]
this is fixed and you are a good boy

**Comment by ChalkyBrush** [comment]
ty
