### ISSUE TITLE
Red October Boots reduction

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#138]
It works opposite way it written.
![redoctober](https://user-images.githubusercontent.com/32621322/32606431-faf4005e-c55d-11e7-8c38-7ea65997e438.PNG)
![20171109155325_1](https://user-images.githubusercontent.com/32621322/32606419-f5a008dc-c55d-11e7-84b4-117c3662fb30.jpg)
![20171109155330_1](https://user-images.githubusercontent.com/32621322/32606421-f6194ea4-c55d-11e7-8c1f-46f39c59502d.jpg)

**Comment by redledcat** [comment]
At least tooltip says so

**Comment by ChalkyBrush** [comment]
fixed for next patch
