### ISSUE TITLE
Broken Steadfast enemies ignoring damage Amp/PDM

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#139]
I only know of two maybe three that have this problem and they are all very annoying.
If anyone has more please add them to the list. I will post pictures of these enemies later if needed.
All these enemies ignore post damage mitigation and amp.

1- Alchemist boss (Tyrant Thaldues?) in Redfall Ridge map.
2- Pudge prison guard in Tanari Jungle water temple guarding the imprisoned slarks top left part.
3- Red Slardar prison cell guards in Sea Fortress right side in pudge area. These seem to ignore a lot of damage unless you're within melee range then you do full damage to them. I have not seen any skills they have that indicate that this is either a mechanic or passive.

**Comment by redledcat** [comment]
Look at issue #92 and remove both 1) and 2) because they dont actually use "Steadfast" passive to mitigate damage.
It's similar passive "Man Eater" which lowers incoming damage to 1% instead and do not affect glyph of giant slayer

**Comment by redledcat** [comment]
*not being affect by glyph of giant slayer.
And 3) just has additional passive you described so it's hard to kill, thats all.
Btw, if you use normal post mitigation sources you wont feel the damage on 1) and 2) is significantly lower than on mobs with steadfast
