### ISSUE TITLE
[4.0] Red General's body Arcana spell still doesn't function

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1396]
nintai and redledcat and i poked around at this for a little while a few weeks ago, and we couldn't isolate the problem. load this build into the test server and cast R - it will channel, but once the channel finishes, nothing happens. Q3 doesn't launch R shockwaves either. replacing all the glyphs doesn't fix it. chiseling the arcana off and putting it back on doesn't fix it.

https://www.roshpit.ca/players/72513648/heroes/778980

**Comment by redledcat** [comment]
eh okay I don't see if it's still here and if it is, I can't reproduce it
maybe it was a glyph or something else
