### ISSUE TITLE
Ekkan's minions collision issues in Redfall Ridge

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#14]
Some of units on map have have too big collision size to fit into doorways in Farmlands, a lot of narrow places into Castle, and stairs in the beginning of Shipyard.
1)redfall_snarlroot_treant 
2)redfall_chibi_bear 
3)redfall_canyon_bull (Spirit Breaker)
4)redfall_forest_wood_dweller (Lone Druid)
(every mob tested on Farmland houses and Castle)
In example, harvester redfall_farmlands_corn_harvester has bigger visual model than chibi bear and forest dweller, but easily fits narrow passages.
Another good examples are redfall_canyon_breaker (Elder Titan) and redfall_forest_overgrowth (Furion's custom treant) which have even bigger model than redfall_snarlroot_treant, but also fits every passage on the map.
And last one, redfall_cliff_weed being donimated with arcana Ekkan has **infinite scale of model** with his custom ability. It grows to the size which transcend map size, BUT his collision size remains 24, so no issues with pathing.
Offtop: redfall_canyon_bull creeps stuck on bridge in Canyon spawner before boss, when they trying to get on bridge in pairs.

**Comment by redledcat** [comment]
In Tanari map there also are mobs with 
DOTA_HULL_SIZE_HUGE
1) terrasic_awakened_stone
2) tanari_wild_troll
3) boulderspine_rock_golem
4) water_temple_vault_lord
5) fire_temple_final_wave_mob
which have issues with pathing.

**Comment by ChalkyBrush** [comment]
Not a bug 🐛

**Comment by redledcat** [comment]
fixed, what a relief
I dont want to make another thread about  redfall_cliff_weed  but I guess I have to becs we have Slipfinn now with same mechanic
