### ISSUE TITLE
Bahamut - T1 glyph (30% phys resistance) breaks custom tooltip

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#140]
![20171110212304_1](https://user-images.githubusercontent.com/32621322/32672788-1f074576-c655-11e7-9f07-0b0bba1551e9.jpg)
![20171110212324_1](https://user-images.githubusercontent.com/32621322/32672790-20692498-c655-11e7-86ed-f6da93181854.jpg)

**Comment by ChalkyBrush** [comment]
i know why will fix when I get home

**Comment by ChalkyBrush** [comment]
fixed for next patch
