### ISSUE TITLE
[4.0] Veno R3 healing not working

### ISSUE THREAD

**Issue by ThomkuThomasGoku** [ChalkyBrush/roshpit-bug-tracker#1400]
https://streamable.com/sagx8
everything jolted down in the video

**Comment by Nintai** [comment]
Cant even look at ur own video?

Saying u dont get life when u can see that u got 100 hp

Guess we should change tooltip to 0.04% 😂

**Comment by ThomkuThomasGoku** [comment]
right i should rephrase, it doesnt heal for the 4% amount
