### ISSUE TITLE
[4.0] Puzzler's Locket not working

### ISSUE THREAD

**Issue by ThomkuThomasGoku** [ChalkyBrush/roshpit-bug-tracker#1401]
while loading a character with a puzzler's locket and all your equip
puzzler's locket effect doesnt kick in.

way to fix this as of current patch is 
>go to blacksmith, chisel all your other equips except for puzzler's locket still stays at your equipment directory.
>reequip everything else that you just chisel(ed).
puzzler's locket effect of tier 2 and tier 3 rune exchange works with this method, but by doing this will not only being a stress of using those mith shard, also if at the process when you chisel(ed) out your items, if you dc as a solo player, you'll risk of losing out items. definitely not recommended.

**Comment by ChalkyBrush** [comment]
FIXED
