### ISSUE TITLE
[4.0] CAN'T LOAD HERO

### ISSUE THREAD

**Issue by harrywilt** [ChalkyBrush/roshpit-bug-tracker#1402]
![image](https://user-images.githubusercontent.com/60404604/73296565-8d0afd00-423c-11ea-83d9-c05d3ce5cd53.png)
I can't load any hero even save when I want to create new.
I tried another account but it works normally.
I also tried relogin and restart, it won't working at all.
Please fix it, thank you.

**Comment by ChalkyBrush** [comment]
any chance you're on Japan servers? Apparently Japan servers can't communicate with Roshpit server

**Comment by harrywilt** [comment]
I'm on singapore server

**Comment by ChalkyBrush** [comment]
I believe this is fixed, let me know if you can load now
