### ISSUE TITLE
Can't save or load heroes, possible Gem Forger bug before saving character.

### ISSUE THREAD

**Issue by KirbyKain** [ChalkyBrush/roshpit-bug-tracker#1405]
Started a new game with friends, and after completing the map and went to go save, it gets stuck with "Loading" and doesn't pull up any of my other characters. Item pool works fine. Even after leaving the game and tried again with a new game the next day, the issue was still there. I did notice that the character I was playing as, according to the website, was saved to a Slot 0, which neither of my friends had. I did use the Gem Forger which might have "saved" the character before I had made a dedicated slot for them causing this issue.

**Comment by ChalkyBrush** [comment]
are you playing on Japan servers? Also you cant save a hero to slot 0. Maybe if it exists there i can put it in a real slot and you'll have your char back?

**Comment by ChalkyBrush** [comment]
ohhh, yea, its probably the gemforger b4 saving, nice pickup

**Comment by KirbyKain** [comment]
I'm not worried about the character, I can always make another. It was more not being able to play, but thanks for the quick response. <3

**Comment by ChalkyBrush** [comment]
thanks for this, was causing some mayhem. i believe it is fixed now

**Comment by Oinkhammer** [comment]
I'm also unable to save my new character right now, have also used the gem forger before trying to save, stuck at the "Loading..." screen.

EDIT: Just checked it, can't load on a new game session either.
