### ISSUE TITLE
[4.0] Hovering over a hero's status board when he's equiping Hood of the Defiler, will increase its gem effect stacks

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1407]
this apply to any allies heroes on your team

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush in english:

If any hero is wearing Hood of the Defiler, then the "fake" instance of damage dealt to a unit every time you view its stats panel will mistakenly add a stack of the helm's buff to the hero wearing the helm, behaving as if that fake damage instance is @Ability2 damage.

**Comment by ChalkyBrush** [comment]
fixd
