### ISSUE TITLE
Rubilash Gripe Sheet

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1408]
1. Glyph 3-1 castings of E don't actually deal damage, they just paint targets in the affected area around the R pet's new location.
2. Glyph 3-1 castings of E get the pet's current location when deciding where, within the 300-unit distance constraint, the pet should target the E cast. This leads to the unfortunate behavior of him just fucking blinking on top of himself repeatedly, often completely unconcerned with the location or even presence of any nearby enemies, so he mostly just stays in his own little corner in the middle of nowhere and struggles to even come within R3 targeting range of anything you're trying to fight. I recommend changing the Glyph to use Rubilash's current coordinates instead of the pet's when determining the target location for the free E cast.
3. Glyph 3-1 is treated as a legitimate cast of E, meaning every 2 fucking seconds, a splash sound plays as Grimstroke makes an "Oooh" or "Aaah" noise, like he's having his dick sucked by a god damn water balloon. The effect is magnified as you manually cast E yourself. I played for 90 minutes listening to that shit, and I had to stop and take 4 Advil and half a Phenergan when I realized I had a nauseating headache from it. Please either remove Grimstroke's vocal feedback on E casts, leaving only the relatively tame splashing noise, or restrict them to 5% chances to play on each E cast, or something, because holy fuck.
4. E3's tooltip is both grammatically incorrect (which is why I rewrote it) and inaccurate (which is something I just discovered): As it is written now, ``All enemies damaged by Paint heals Rubilash``, "heal" singular would correct the grammar error, but it would still be a lie - the heal is triggered every time any enemy unit is affected by any Paint effect, even if it doesn't deal any damage; because all of Rubilash's abilities that cause Paint to be applied will do so even if an affected unit is invulnerable or Spell Immune at the time, this means that "damage" is not at all necessary to receive the heal. You may confirm this for yourself by giving a training dummy Spell Immunity and throwing any of your spells at it, observing that it will change color regardless, and that you will still receive the heal instance. Therefore please change the tooltip to read ``"Rubilash is healed each time any Paint effect is applied to an enemy unit."``
5. R2 is not strictly "unbreakable" invisibility, unlike Venomort's E invisibility, which truly does not break until its duration ends regardless of Venomort's actions. The tooltip should probably be amended to tell the truth, which is that it has a vanishingly brief fade time and is broken by taking any action.
6. Rubilash's E spell has no protections preventing him from blinking into an object or unit, and as such he often becomes stuck inside them and cannot move. Trees are the most common object to become snagged on, but there are even some strange corners and map geometry that can also trap you, including places that appear to be sheer cliffs devoid of anything.

**Comment by ChalkyBrush** [comment]
implemented all 6 suggestions here
