### ISSUE TITLE
Mobs's models being tossed aside after death

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#141]
It started to happen since 7.07 but I did not paid attention to this fact.
It just feel strange creeps being pushed from the point of death to somewhere else, but that does not affect gameplay or perception of game.
It happens inconstantly, but I tried to srceenshot it.
In the moment of R channel ends 2 earthshakers are right here Hydroxis
![20171111015116_1](https://user-images.githubusercontent.com/32621322/32682113-7faf6f4a-c67b-11e7-9bce-df937331930b.jpg)
And here they are after death
![20171111015120_1](https://user-images.githubusercontent.com/32621322/32682088-611f22b4-c67b-11e7-8c44-12d6558a1829.jpg)

**Comment by redledcat** [comment]
here we go
![20171111020030_1](https://user-images.githubusercontent.com/32621322/32682198-d694c3aa-c67b-11e7-966e-88b9ed6a888e.jpg)
![20171111020033_1](https://user-images.githubusercontent.com/32621322/32682199-d94164fa-c67b-11e7-8719-ee5d58d13628.jpg)
![20171111020034_1](https://user-images.githubusercontent.com/32621322/32682203-de10f3ce-c67b-11e7-8e00-6c29339a164f.jpg)
![20171111020041_1](https://user-images.githubusercontent.com/32621322/32682204-e03beb9a-c67b-11e7-880f-1b15af09c347.jpg)

**Comment by ChalkyBrush** [comment]
noticed thist oo but i have no idea TBH

**Comment by ChalkyBrush** [comment]
seems like an engine change by valve, and launch velocity is based off degree of "overkill"
Since heroes do trillions of DMG, units with 1000 HP go flying so hard that it looks buggy.

This is not 100% fact but it seems correct from my observing

**Comment by redledcat** [comment]
The creeps which are 100% sure flies away are
 gargoyle familiars (pit descent), slarks (almost everywhere),
 some mobs in shipyard spawn. (nyx assasins - armored water beetle)
+broodmother's minion spider
+Necronomicon units
+bounty hunters
+some of neutral creeps
+pugnas (Avernus summons)
Mobs which do have steadfast seems to never have this issue.

**Comment by redledcat** [comment]
+ sand kings
+rubicks

**Comment by redledcat** [comment]
hey, 7.09 patch added following console commands
dota_guide_prioritize_recent | default: true
dota_npc_creep_pushback_max_damage_amount | default: 500
dota_npc_creep_pushback_max_damage_force | default: 1
dota_npc_creep_pushback_max_random_force | default: 1
dota_npc_creep_pushback_min_damage_amount | default: 100
dota_npc_creep_pushback_min_random_force | default: 0
dota_npc_creep_pushback_min_time | default: 0
dota_npc_creep_pushback_random_yaw | default: 2
dota_npc_creep_pushback_max_time | default: 0
dota_npc_creep_pushback_min_damage_force | default: 0
probably there is a way to change that push power
and also these
dota_npc_creep_pushback_height_scale 50 to 100
dota_npc_creep_pushback_scale 1000 to 200

**Comment by redledcat** [comment]
OH I feel that's already fixed! 
requires time to check all of these mobs, but I clearly see some of them stopped to being push back

**Comment by ChalkyBrush** [comment]
dota2
