### ISSUE TITLE
Gravelfoot Treads is constantly purging individual instances of E2 from Sephyr, treating them like hostile debuffs

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1412]
PROS:
1. you get to have Stone Form's 60% DR on permanently during combat, and maybe even other bonuses from gems in the boot
2. keeps your buff bar tidy and free of all those unsightly buffs!

CONS:
1. you will never, ever purge any actual debuffs applied by enemies
2. constant movespeed slow
3. keeps eating your FUCKING attack damage boosts

**Comment by TheVietboi** [comment]
in additional: it also increase server ticks, and result lags
