### ISSUE TITLE
Autumnrock Bracer appears to have a 1% chance to activate (or less!), instead of the intended 10%

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1419]
i find this humorous. have the Training Dummy attack you on 0.06-second intervals, and see just how many seconds you'll go without getting any bracer procs at all.

**Comment by Nintai** [comment]
Its fucked up in code.
Goal was to limit it to 6 procs per sec
Instead it was limited to 6 checks per sec

So 60% chance to get a proc in 1s max.

**Comment by DeckardCainRPC** [comment]
i am further amused

**Comment by DeckardCainRPC** [comment]
@Nintai was this fixed?
