### ISSUE TITLE
Attribute decreasing effects in Sea Fortress

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#142]
Medusas and Sea Oracle lowers attributes by autoattacks, but the value can be lowered below 0 after custom attributes implemented.
![20171111152135_1](https://user-images.githubusercontent.com/32621322/32689937-7147d138-c6f6-11e7-88ef-02e9dc4c5e56.jpg)
![20171108124120_1](https://user-images.githubusercontent.com/32621322/32689939-8a824714-c6f6-11e7-80b7-41ce63380ad9.jpg)

**Comment by ChalkyBrush** [comment]
fixed

**Comment by redledcat** [comment]
@ChalkyBrush not fixed

**Comment by redledcat** [comment]
![20171204234037_1](https://user-images.githubusercontent.com/32621322/33575085-3050a5be-d944-11e7-9d96-58d20b992ce8.jpg)

**Comment by redledcat** [comment]
![20171204234109_1](https://user-images.githubusercontent.com/32621322/33575124-44d7fa96-d944-11e7-91ff-0e1d4dc8470d.jpg)
