### ISSUE TITLE
[Chernobog] Chernobug Unholy Claw

### ISSUE THREAD

**Issue by ThomkuThomasGoku** [ChalkyBrush/roshpit-bug-tracker#1426]
Unholy Claw's effect (Vampiric Thirst) with Rupthold's Helm Of Gluttony (Amethyst) doesnt work. 
sames goes to the weapon with eternal essence gauntlet Emerald effect doesnt work on the healing despite the Vampiric Thirst is an hp restore. ( im not sure if this is a healing or not need clarification)

**Comment by redledcat** [comment]
Unholy Claw has an unique +1.5% health restoration, which doesn't interact with whatsoever
Tooltip was clarified
