### ISSUE TITLE
BM arcana and dummy objects

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#143]
Well, there is nothing terrible when his R2 goes for wards in Arena, except sound and effect is quite irritating, but the one really destructive interaction comes here, which completely ruins the fight with Val'Dun.
The R2 procs on orbs infinitely, and they starts to mess around, with no allowance to control them.
R2 effect goes on for the full duration of orb and basically disables it.
These two on screenshot (and more of them around) are just hung in one place, twitching up and down.
![20171108003845_1](https://user-images.githubusercontent.com/32621322/32702371-fd2adfbc-c7ee-11e7-9ac5-c0d83ecfe9f4.jpg)

**Comment by redledcat** [comment]
![20180126001749_1](https://user-images.githubusercontent.com/32621322/35413296-a893f4d4-0227-11e8-9ecb-cb987db4921c.jpg)
It lasts foreverq

**Comment by ChalkyBrush** [comment]
no longer affects dummies
