### ISSUE TITLE
Arkimus helm Arcana spell now requires a ground target for some reason

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1434]
when you cast it, the targeting interface comes up (switches your cursor icon), and you have to left-click somewhere on the ground to actually cast the spell. i would imagine this bug was introduced on accident, by a dev who has Quickcast enabled on all spells globally, meaning they'd never notice they caused this behavior after pushing whatever Arkimus patch they wrote.

**Comment by ChalkyBrush** [comment]
fixed
