### ISSUE TITLE
Mountain Vambraces' Amethyst effect fucks up Cap of Wild Nature's Sapphire effect... no, wait, Captain's Vest is causing all of this, how the fuck is that possible

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1435]
STEPS TO REPRODUCE:
1. equip Cap of Wild Nature and put a Sapphire in it. now, your Q spell's damage instances have a good chance of triggering this helm's root effect.
2. on like Zhonik i guess, his Q hits a lot so you won't have to wait long for the Sapphire root effect to proc. yes go remake the lobby and make sure to select Zhonik this time. sorry. this should have been the first step. oh and make sure to equip his T2-1 Glyph, the one that makes enemies take damage if they're carrying the Q debuff.
3. okay cast Q on the training dummy and watch the logs. everything's going good. you'll see instances of Magical Temporal damage, and then some Magical Nature damage after the root triggers.
4. wait for the Q debuff to expire on the training dummy before we continue.
5. now, equip Mountain Vambraces and put a Sapphire in it. behold! your Q spell's damage instances have a good chance of triggering this glove's blast AoE effect.
6. alright, and cast Q on the training dummy again.
7. observe that the training dummy now registers... instances of Physical Normal/Earth damage, which are coming from the Vambraces, but after each Vambrace trigger instance, it registers an instance of Magical Normal/Earth damage, with damage values identical to Q's ability damage ticks. **the Wild Nature root damage instances have vanished.**
8. sit and ponder this for a moment, because you are Deckard Cain and you're a fucking wizard. you know that when the damage log starts printing whatever ELEMENT1 and ELEMENT2 tags it was using for the previous damage instance, it means that something has gone seriously wrong, and those element tags weren't updated between then and now.
9. anyway, take this opportunity to chisel off your shitty Captain's Vest, and replace it with a much better Gold Plate of Leon, for no other reason than wanting to maximize your DPS while tabbed out reporting this bug
9. now cast Q on the training dummy again.
10. observe that the fucking damage log is now reporting the Physical Normal/Earth instances from Vambraces, **AND** the Magical Nature instances from Cap of Wild Nature, meaning everything is functioning exactly as it should. the only thing you fucking chiseled was Captain's Vest.
11. go chisel Leon off and put Captain's Vest back on.
12. cast Q on the dummy once more
13. i'll be god damned. we're back to where we were on Step 7: Physical Normal/Earth instances show up from the Vambrace, and then immediately afterward, we see that Magical Normal/Earth instance that deals the exact same damage as a regular Q tick.

something is profoundly wrong, and it would have gone undiscovered for centuries if not for me

**Comment by Nintai** [comment]
Deckard was being an idiot and forgot that without Gold Plate of Leon and Ruby converting main attribute to strength he wont deal dmg when he has 0 int, which he apparently had in reallife at this moment.

**Comment by DeckardCainRPC** [comment]
in my defense, i realized my own mistake

[3:34 PM] Deckard Cain: in this screenshot, you can clearly see that the training dummy is rooted, but the Cap of Wild Nature root damage instances are not showing up in the damage log
[3:34 PM] Nintai: ill try again :thinking:
[3:34 PM] Nintai: Works for me :thinking:
[3:34 PM] Maurdekhai: me too
[3:35 PM] Deckard Cain: oh that's because neither of you two are wearing Red Divinex Amulet
[3:35 PM] Deckard Cain: i figured out what the issue is
[3:35 PM] Deckard Cain: when i didn't have Gold Plate of Leon equipped, my hero's primary attribute was INT
[3:35 PM] Deckard Cain: and divinex was setting my int to 0
[3:35 PM] Deckard Cain: therefore, the cap of wild nature damage instances were... 0
[3:35 PM] Nintai: just wanted to say that :joy:
[3:35 PM] Deckard Cain: and wouldn't display on the dummy

anyway, for those curious, the issue with Mountain Vambraces is that its proc check is performed before the Q damage instance is dealt, so it sets ELEMENT1 and ELEMENT2 to Normal and Earth, respectively, before dealing the Vambrace damage but *after* Q tried to set its own ELEMENT1 and ELEMENT2 to Temporal and NONE, respectively. this means that the next individual Q damage displayed will be Normal/Earth. which we all already knew. that is all.
