### ISSUE TITLE
Blacksmith reroll UI sound increases in volume each time an item is dragged into the Reroll UI slot

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1438]
#1244 #1332

STEPS TO REPRODUCE:
1. open Blacksmith UI and select the Reroll option
2. drag an item to the Reroll slot
3. a "ka-chunk" sound plays. it will play again each time you reroll the item.
4. hit the Cancel button
5. select the Reroll option again
6. drag an item to the Reroll slot again
7. **TWO "KA-CHUNK" SOUNDS PLAY AT THE SAME TIME,** making it sound like the volume for the sfx has doubled. each time you reroll the item, it will play the sound twice, again simulating increased volume.
8. keep going. each time you bring up the Reroll UI, it queues up another instance of the dreaded ka-chunk to be played simultaneously for the rest of the game session, multiplying its perceived volume more and more. do this just 9 or 10 times and your reroll noises will be deafening. do it 40 times and your speakers will explode. do it 80 times and you have a sonic weapon capable of shooting down low-flying aircraft or instantly frying birds as they pass over your house.

**Comment by ChalkyBrush** [comment]
what about 160 times?

**Comment by DeckardCainRPC** [comment]
https://youtu.be/oCyXsHC-lQ4?t=16
