### ISSUE TITLE
Tiamat's boss health bar HUD element uses the wrong HP values

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1455]
STEPS TO LOOK AT THIS:
1. go club some creeps until you can fight tiamat at level like 20
2. as in a level 20 tiamat on legend difficulty
3. okay
4. now deal damage to her
5. observe that, despite the Tiamat unit having like 80% HP left, the health bar is fully red, indicating that she's at full health
6. oh, alright, Tiamat's boss HP display must have gotten her max HP value *before* it got increased by her "event" level
7. fuck her up until she's only got like 12% HP left
8. NOW her boss HP bar starts to drop
9. okay her first form is dead, and her second form is being a big fireball-dropping faggot
10. wait for her to calm down and let you fight her second form
11. okay this bug also affects her second form's boss HP bar too

**Comment by DeckardCainRPC** [comment]
nintai says this is because valve is stupid, and if you query % max HP, it returns that value, except in a smaller variable than **all other** HP values in Dota 2, which all uniformly use a larger variable. this results in an overflow and is the root cause of the display issues described here

**Comment by Nintai** [comment]
Reason for this is:
GetPercentHealth is equivalent to: GetHealth * 100 / GetMaxHealth
so if the enemy has 21.47m life, it will be 2.147b in the calculation, which causes overflow

I changed it to (GetHealth / GetMaxHealth) * 100 and it should work now
