### ISSUE TITLE
[Omniro] Multiple Omniro issues

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1458]
1. **he cannot close the Blacksmith's UI** unless he spends mithril chiseling a fucking item off
![image](https://user-images.githubusercontent.com/34521754/78037726-e88b6100-7339-11ea-9bdc-e77053cb0e8c.png)
his obtrusive Orb UI is in the way of the Close button, to say nothing of chat, NPC text, the buff bar, and yo mama
2. E4 is dealing far less damage than intended, no matter what it is you intended - the tooltip states that the root damage should deal a *multiple* of your attack power every tick, but it fails miserably in two different directions: first, it's not a multiple of his attack power, it appears to be a percentage, meaning even with 35 points in it and 40k total attack power, it deals *less damage per tick than your Normal autoattack damage*; and second, the ongoing damage from the root debuff is 0.1x the damage from the Q ability's passive on-hit damage, which is itself equal to 10% of Omniro's total attack power. i am almost positive that these are all symptoms of the "reduce all numbers by 100x" prescription for 4.0, and that they've gone unnoticed for 3 months because, after e1 got fixed, nobody has played the hero
3. E3 is hitting the primary target 8 times (???)
4. W4 is probably dealing 10x less damage than intended ("Deals a large instance of damage" but 13 points in it is just 32.5% of total attack power)
5. fix the incorrect positions of percent signs in Glyph T5-a

**Comment by redledcat** [comment]
1. is no more
![image](https://user-images.githubusercontent.com/32621322/80416998-b3911080-88dd-11ea-9927-04bbc2788b35.png)

**Comment by redledcat** [comment]
3. yes, it hits 8 times for main target

**Comment by redledcat** [comment]
<2.> I have modified values on omniro having in mind ~1m of dps in late game, as Chalky's main goal, and it's mostly possible to achieve with current values, but probably getting heavily overriden by casual normal orb-effect. I'll probably do some buffs there, but I'm not exactly sure about numbers
As for nature orb, I have no idea why it doesn't work properly, I tried to investigate it, but fail<ed.
<4.> Yeah it's kinda disappointing but it also pure damage and grants bonus damage on hit per rune, so it's scaled with all other runes along.
If you have good thougths what fair numbers are, please, you're welcome. I probably didn't consider survivability in my testing builds very well so everything is handicapped.
<5.> Done! At least it was easy

**Comment by DeckardCainRPC** [comment]
he's probably fine now, i'll go fuck with him and then make a new report if i have any further gripes. thank you 6pat)))
