### ISSUE TITLE
Slipfinn (and wearers of Neptune's Water Gliders?) cannot complete Tanari Wind Temple

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1459]
![image](https://user-images.githubusercontent.com/34521754/78174765-c839d000-7427-11ea-9eaf-8822bf5a58b4.png)
this portal's teleportation cinematic does not function correctly, the hero gets slammed against that tree repeatedly before being released back onto that island to repeat the process again

**Comment by DeckardCainRPC** [comment]
oh, and if you enter that portal in slipfinn's arcana ball morph mode, it will multiply the velocity beyond all reason, and sling your ass waaaaaaay over into the water temple

**Comment by ChalkyBrush** [comment]
fixed in next patch
