### ISSUE TITLE
【dinath】Fatal error in glyph!!!Dinath don't have the R skill!

### ISSUE THREAD

**Issue by dinathdd** [ChalkyBrush/roshpit-bug-tracker#1463]
Dinath's [T2–1] glyph can't take effect.Unable to maintain current altitude while booting R skill, unable to play properly,please repair it,Dinath need the R skill.

**Comment by redledcat** [comment]
I love and appreciate how you made an entire account just to report this bug

**Comment by redledcat** [comment]
https://youtu.be/AICmQNwz3bM
it works

**Comment by redledcat** [comment]
I have to mention, if you use Iron Treads of Destruction, which reduce your channel time to 0, your channel time will also be too small to do any effect

**Comment by dinathdd** [comment]
but the glyph T2-1 only works in the roshpit test 4.0.In the official verson,the glyph can't work when i boot R skill.Sad  o>_<o  check it plz
