### ISSUE TITLE
Arena Prizeboxes display correctly, but drop no loot when used

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1464]
arena prizebox loot, like a DEER CROSSING sign, is not a guarantee but merely a suggestion

**Comment by GoToNightmare** [comment]
![image](https://user-images.githubusercontent.com/34166246/79066034-21c6b800-7cce-11ea-9ed6-17a78fbc7c3d.png)
More info needed.

**Comment by DeckardCainRPC** [comment]
hmmmmmmm thanks for letting me know, i'll investigate harder. it may just be that i enabled -junk and forgot, but i'm pretty sure the reason i posted this bug report is because i opened a prizebox with an Arcane Crystals roll, but it didn't drop any.

**Comment by redledcat** [comment]
prove us wrong, mr. Tony
![20200412225238_1](https://user-images.githubusercontent.com/32621322/79078339-63785280-7d10-11ea-8259-ce35bc7ff0e7.jpg)
![20200412225242_1](https://user-images.githubusercontent.com/32621322/79078343-65daac80-7d10-11ea-8bad-ddaceb1f501e.jpg)

**Comment by redledcat** [comment]
![20200412225517_1](https://user-images.githubusercontent.com/32621322/79078393-b7833700-7d10-11ea-9e57-0735df5c0ce7.jpg)
![20200412225526_1](https://user-images.githubusercontent.com/32621322/79078394-b81bcd80-7d10-11ea-9a36-3a270146d5b7.jpg)
![20200412225529_1](https://user-images.githubusercontent.com/32621322/79078396-b9e59100-7d10-11ea-8aa8-807d9b6c6503.jpg)

**Comment by DeckardCainRPC** [comment]
[4:32 AM] ihatemyself: since no one updated the thread, allow me to do so
[4:33 AM] ihatemyself: some days ago, a dude accidentally "fixed" the issue ingame, by just dropping the prizebox on the ground, then pick it up again
[4:33 AM] ihatemyself: then the box just works perfectly fine

i haven't confirmed any of this ^

**Comment by GoToNightmare** [comment]
hopefully fixed in next patch
