### ISSUE TITLE
【dinath】Fatal error in glyph!!!Who can help thr Dinath!!!

### ISSUE THREAD

**Issue by dinathdd** [ChalkyBrush/roshpit-bug-tracker#1465]
The glyph [T2-1]only works in the roshpit test 4.0.In the official verson,the glyph can't work when i boot R skill.Sad o>_<o check it plz
Dinath's [T2–1] glyph can't take effect.Unable to maintain current altitude while booting R skill, unable to play properly,please repair it,Dinath need the R skill.

**Comment by redledcat** [comment]
~~Can you provide more info about your build?
Test version is the same as main, except small periods of updating it~~
Ok it's really bugged, no idea here

**Comment by dinathdd** [comment]
> ~Can you provide more info about your build? Test version is the same as main, except small periods of updating it~
> Ok it's really bugged, no idea here

repair it plz,my dear O(∩_∩)O

**Comment by GoToNightmare** [comment]
fixed in next patch pr 839
