### ISSUE TITLE
Chernobog's R3 is not considered Base Ability Damage for R; this was done by Dragon pre-4.0 for balance reasons

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1467]
but in the modern, enlightened era, this is considered racist

**Comment by DeckardCainRPC** [comment]
[12:12 AM] ihatemyself: that reminds me
[12:12 AM] ihatemyself: slardar r3 need to inherit bad% as well
[12:13 AM] ihatemyself: in 3.9, it can scale from r1 buff so it doesn't need bad% to be overpowered. but now r1 is just an armor reduction effect

**Comment by DeckardCainRPC** [comment]
both cherno's r3 and slardar's r3 were made BAD% for R, deckard wins again

**Comment by TheVietboi** [comment]
![image](https://user-images.githubusercontent.com/51455274/83392746-cee0c580-a41f-11ea-9fcd-26323c87a5e8.png)
but... only slardar is

**Comment by DeckardCainRPC** [comment]
thank you for notifying me

**Comment by redledcat** [comment]
~~it has  source = self:GetAbility() and should inherit ability3 bad%, isn't this visual only?~~
I'm wrong, I should look at sourceType  instead. Fixed.
