### ISSUE TITLE
(Visual) Effects of magic immunity of Umbral Tome of Herod vanishes 

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#147]
Debuff renews on hero on W cast, but when time of first debuff expires (10s), BKB thing effect does not appear anymore (Until debuff completely vanishes and you apply it again)
![20171112234607_1](https://user-images.githubusercontent.com/32621322/32703834-37c98c76-c804-11e7-8aae-654bcebe3052.jpg)

**Comment by ChalkyBrush** [comment]
fixed
