### ISSUE TITLE
Paragon Crimsyth Cultist Bug

### ISSUE THREAD

**Issue by WildBeBerry** [ChalkyBrush/roshpit-bug-tracker#1472]
For understanding translate from Russian. Thanks.
rus -> Не возможно пробить этого персонажа на сложности "Legend".
![Screenshot_1](https://user-images.githubusercontent.com/57450530/79728031-f5c2bc80-82f5-11ea-8a02-d81941be7721.png)

Bug_or_wtf {
 bool paragon status: true;
 double hp: 1,099,440;  // paragon skill "Gargantuan" increase his total hp
 double regen: 43977.03;  // his own skill "Corrupted heart "4% from total hp
 Shielding: true; 
}

**Comment by DeckardCainRPC** [comment]
Спасибо за этот чистый отчет! очень легко понять

этот враг огромный петух. если вы не можете убить его одним ударом, и если вы не можете отключить его регенерацию, такую как Omniro R4, то я не вижу способа убить его задницу. но, технически говоря, его долголетие не является ошибкой; все работает как задумано ...

Могу ли я увидеть страницу статуса вашего персонажа? как https://www.roshpit.ca/players/72513648/heroes/202608 ссылка на один из профилей моего героя

**Comment by WildBeBerry** [comment]
Не обращайте внимания) Развивайтесь как проект и далее!
P.S. убил после финального босса. долго бил...
