### ISSUE TITLE
New Dota 2 patch break units healing

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1473]
https://www.reddit.com/r/DotA2/comments/g5vkwt/psa_undocumented_change_regarding_heal
"Heal/regen/lifesteal amplification can no longer go below -100%, meaning you can no longer make someone get negative regen or take damage from healing by stacking negative amplification."

Meaning those little fuckers in winterblight are unkillable now, a long with some other untis.

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush SYPHISTS CANNOT BE KILLED UNTIL THIS IS RESOLVED

![syphists](https://user-images.githubusercontent.com/34521754/79970024-4d7d3700-8460-11ea-9943-29f945d05b92.gif)
