### ISSUE TITLE
[Roshpit.ca] Every single instance of "Rune Q1" on the website is secretly replaced by russian "Руна Q1", what makes this row invisible in several occurences

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1479]
Examples:
1) Market search tool
![f1f1](https://user-images.githubusercontent.com/32621322/80290749-3dab6e80-8750-11ea-8163-b93f2bf87db5.png)
![image](https://user-images.githubusercontent.com/32621322/80290817-bb6f7a00-8750-11ea-99c0-4bb1dc54db61.png)
2) Market pages, which show Rune Q1 in english normally, but search tooltip still doesn't show it properly and market pages which have Руна Q1 instead (I believe it's because of non-curated examples of specific items, i.e. tesla cuffs here)
![f1ff`](https://user-images.githubusercontent.com/32621322/80290805-a5fa5000-8750-11ea-8d6e-e79b34cbb7ae.PNG)

**Comment by DeckardCainRPC** [comment]
it has been this way since 4.0 launched and it is supremely fucking annoying. it is the greatest prank russians have pulled on america since getting trump elected

**Comment by ChalkyBrush** [comment]
should be fixed

**Comment by redledcat** [comment]
Mischief Managed!
