### ISSUE TITLE
[Epoch] Q arcana spell and E3 multipy each other, making single Q shot in crown lethal for your PC

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1483]
E3 grands splitshot, while Q launches multiple attacks in area, also Q4 increases amount of attacks lauched
1 target: 1 attack
2 targets: 2 attacks on each = 4 attack projectiles
3 targets: 3 attacks on each = 9 attack projectiles
5 targets and 10 Q4: 30 on each = 150 attack projectiles
10 targets and 10 Q4: 60 per creep = 600 atttack projectiles
short demostration on these poor 14 mr. Crabs and their nest
![image](https://user-images.githubusercontent.com/32621322/80428686-1fca3f00-88f3-11ea-8f98-31eda8d510ad.png)

**Comment by redledcat** [comment]
I don't know how to make proper code here which won't let Q arcana interact with E3

**Comment by TheVietboi** [comment]
On the bright side, this makes his q actually powerful against multiple enemies :D
