### ISSUE TITLE
Astral Ranger Glyph T6-2 doesn't list a freeze duration

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1484]

**Comment by redledcat** [comment]
Status update: now it doesn't list it only on website

**Comment by DeckardCainRPC** [comment]
![image](https://user-images.githubusercontent.com/34521754/81165891-ca300b00-8f60-11ea-99c7-bedbdc77d672.png)

**Comment by redledcat** [comment]
It's in game so it will eventually update when Chalky runs glyph updating script
Maybe, or maybe not
