### ISSUE TITLE
(Visual) Movement speed slow of Toxic Whip not shown correctly.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#149]
![20171114003209_1](https://user-images.githubusercontent.com/32621322/32750332-fe759dda-c8ca-11e7-9d2f-670a700794ee.jpg)

**Comment by ChalkyBrush** [comment]
weird, the code looks good (although missing tooltip is fixed)

**Comment by redledcat** [comment]
Could the reason be "IsDebuff" "0" instead of 1?

**Comment by ChalkyBrush** [comment]
not sure, I always thought the debuff class was purely visual (red or green border on UI). But I thought maybe. I didn't test but pushed patch 30 mins ago with that flag changed

**Comment by redledcat** [comment]
Movement slow works, but there are no changes in the tooltip. 
Same problem I think have Ekkan's minions like in #9 , it's visual bug which does not reflect current number of move speed.
