### ISSUE TITLE
Zhonik's Arcana R3 actually increases enemy Magic Armor by subtracting a negative; also, rune tooltip does not list a max stack count (which is 10)

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1490]
![image](https://user-images.githubusercontent.com/34521754/80890937-b8afe000-8c8e-11ea-80cb-641dd0f9e529.png)

**Comment by DeckardCainRPC** [comment]
and no, this is not a merely cosmetic or display issue, it very genuinely does increase a target's Magic Armor and you can see how it's progressively reducing the Magical damage they receive

![image](https://user-images.githubusercontent.com/34521754/80890965-f280e680-8c8e-11ea-9d82-80e67fbc3e7f.png)

**Comment by redledcat** [comment]
ayy lmao

**Comment by redledcat** [comment]
fixed next update, or maybe update after next update
