### ISSUE TITLE
[Trapper] Having extra cast range doesn't actually make her e during stealth jump further

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1498]

**Comment by TheVietboi** [comment]
i don't expect this to get fixed soon in any time, since it was made by Dragon's magic

**Comment by redledcat** [comment]
nah it's actually very easy to fix

**Comment by redledcat** [comment]
she still lands a bit closer than target point, just like axe's Q
