### ISSUE TITLE
Lasso being interrupted by Torrent Trap

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#150]
Here I'm trying to pull mob out of trap while he is chilling in torrents, but Lasso does not pull him.
![20171114043103_1](https://user-images.githubusercontent.com/32621322/32758307-680488a8-c8ec-11e7-8247-f0075ca218d1.jpg)
![20171114043056_1](https://user-images.githubusercontent.com/32621322/32758309-6828a148-c8ec-11e7-9f95-993353345cf4.jpg)

**Comment by ChalkyBrush** [comment]
good catch, fixed
