### ISSUE TITLE
Kol'thun (Tanari Fire Temple boss) is back to throwing his god damn loot right in the lava again

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1503]
have him throw it on his little dais/podium/sepulchre like he used to

**Comment by redledcat** [comment]
lmao #185
also has a reason why it happens, and it's still correct:
wall physics, he has a lower "z" than that pillar he throws his loot, that's why it goes to the lava
and this is made in order that enemies will never drop their loot on some unpathable terrain nearby

**Comment by redledcat** [comment]
closing as duplicate
