### ISSUE TITLE
[4.1] Having the goblin spawned inside a room in winterblight castle, and that room as a kill check condition to spawn some special units, will hard lock the game and progress can't continue

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1507]

**Comment by TheVietboi** [comment]
Update: this only bug rooms that requires conditions to spawn mini-boss-like units.

**Comment by ChalkyBrush** [comment]
I don't thin it's the goblin? Goblins won't inrease the kill requirement

**Comment by TheVietboi** [comment]
then it must be something else that's related. because of all the time the room got bugged, a goblin always spawned.

**Comment by TheVietboi** [comment]
we (me and some other solders) tried all kind of method to mess with the kill count requirement and such. there's only the time where a goblin spawn it bug the room.

**Comment by TheVietboi** [comment]
if you need more clue. i could point out which room this issue occur. perhaps it's the room's logic, not the kill count or so.

**Comment by ChalkyBrush** [comment]
yes, which rooms do you see this in

**Comment by TheVietboi** [comment]
![image](https://user-images.githubusercontent.com/51455274/82676778-20938e00-9c71-11ea-873b-4f57e4cbd758.png)
![image](https://user-images.githubusercontent.com/51455274/82676806-2ab58c80-9c71-11ea-96a3-4b17d1f0ece2.png)
![image](https://user-images.githubusercontent.com/51455274/82676821-31440400-9c71-11ea-87cd-ee4482a8463d.png)

known rooms that have issues when the goblin spawn.

**Comment by TheVietboi** [comment]
now, it's not because of the goblin appearing. it's something else that interact with the event and bugged it. as shown that there are some cases users report the room being stuck while the goblin didn't spawn.

**Comment by TheVietboi** [comment]
![image](https://user-images.githubusercontent.com/51455274/82677083-ae6f7900-9c71-11ea-98d8-aa7f314ca013.png)
![image](https://user-images.githubusercontent.com/51455274/82677093-b16a6980-9c71-11ea-825e-11085eac856e.png)
2 examples of room that still got bugged despit not seeing goblin

**Comment by TheVietboi** [comment]
we're sure that there're only some rooms that are bugged. like the treasure room with skullbone.

**Comment by TheVietboi** [comment]
![image](https://user-images.githubusercontent.com/51455274/82678480-e24b9e00-9c73-11ea-989f-820e3ac77812.png)
another room that can be bugged if a goblin spawn.

**Comment by TheVietboi** [comment]
![image](https://user-images.githubusercontent.com/51455274/82678547-fc857c00-9c73-11ea-9e91-10e7b51cd310.png)
another room that can be bugged when a goblin spawn

**Comment by ChalkyBrush** [comment]
let me know if you see it again, I think its fixed

**Comment by TheVietboi** [comment]
yeah it seems to work now
