### ISSUE TITLE
[4.1] Some of Winterblight Castle rooms are still broken, but this time it's not because of goblin

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1510]

**Comment by TheVietboi** [comment]
some users have been reporting this after the patch released, and no goblin even spawned.

**Comment by TheVietboi** [comment]
REAL IMPORTANT UPDATE: It's because of the portal activator. On some occasions it's related to if the portal is already activated or not.

**Comment by ChalkyBrush** [comment]
seems fixed now
