### ISSUE TITLE
Skyforge Flurry Plate Emerald gives 1/1000th of the intended AGI bonus

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1515]
if you have 4k STR it gives you an incredible 2 AGI

not 2k

2 individual points of AGI to rub together

**Comment by DeckardCainRPC** [comment]
nintai took a look at this and fixed it, i'll close the ticket when it gets patched in

**Comment by TheVietboi** [comment]
yeah, someone patched it ingame now
