### ISSUE TITLE
New Ekkan Arcana ability tooltips all refer to the summoned units as "Skeletons"

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1516]
i imagine what happened is, you copied them over from his default W spell as a template to build these new abilities, then forgot to replace "Skeleton" with "Plaguebringer" etc. when you were done

now, to your credit, the rune tooltips are all fine

**Comment by ChalkyBrush** [comment]
f
