### ISSUE TITLE
You can withdraw keys from your Key Bank while the lobby has cheats enabled

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1517]
STEPS TO REPRODUCE:
1. reflexively check the Enabled Cheats box in your lobby creation menu because you play on Test too often
2. get in game, completely oblivious to your own mistake
3. pull out 2 winterblight glacier stones from your Key Bank, receiving no indication that you're in a lobby that won't save
4. ignorance is bliss for like 1 hour
5. attempt to stash your neat dungeon loot, and encounter this really weird issue where you can't fucking stash anything OR save your hero
6. sit there scratching your head for 2 minutes before you think "maybe i should type -respawn and see if cheats are enabled"
7. do exactly that
8. discover that yes, as a matter of fact, your stupid ass enabled cheats, and that's why your game session prohibits saving
9. for fuck's sake
10. leave the game and go take a frustrated piss while grumbling to yourself and cursing God, then drug yourself and go to bed, like you're deliberately fucking up in one of those japanese dating sim games where you're supposed to manage your time like an extremely fastidious adult
11. come back the next day and start a new winterblight run, BUT THIS TIME, don't fuck up and enable cheats
12. as soon as you get in game, type -respawn to *ensure* that you didn't fuck up
13. okay great you didn't fuck up. now it's time to check your Key Bank and withdraw some gla...
14. WHY DO I HAVE 18 GLACIER STONES INSTEAD OF 20????????
15. question reality. if i had cheats enabled in that lobby yesterday - and i did, because -respawn worked and respawned me - then how the fuck did i manage to REALLY consume 2 glacier stones? is this real life?
16. peer behind the Veil
17. it's just Chuck Testa
18. god damn it i should have known

**Comment by TheVietboi** [comment]
![image](https://user-images.githubusercontent.com/51455274/82983846-1d0a5900-a01b-11ea-8e2a-23cf00320343.png)
you;re not alone mate. good old 3.9 times, lost this baby

**Comment by ChalkyBrush** [comment]
can no longer withdraw keys on test/cheats/debug
