### ISSUE TITLE
Boots of Temperance Amethyst gem effect disarms YOU when you attack

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1525]
STEPS TO REPRODUCE:
1. wear them boots
2. get them gem
3. attack training dummy
4. observe that attacking it disarms YOU for 2.5 seconds
5. take solace in the fact that enemies attacking you are also disarmed, as intended

**Comment by ChalkyBrush** [comment]
f
