### ISSUE TITLE
Monarch Ring's gems do not take effect until after you chisel and re-equip the item

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1526]
STEPS TO REPRODUCE:
1. equip ring
2. check your attributes
3. put gems in the ring
4. observe that your attributes don't change
5. 🤔 
6. chisel the ring off
7. put the ring back on
8. observe that your stats have now improved

**Comment by TheVietboi** [comment]
The ring's gem also doesn't increase itself attribute bonus.

**Comment by DeckardCainRPC** [comment]
this got fixed a few months ago iirc
