### ISSUE TITLE
Boots of Champions display gems incorrectly

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1529]
They do give you runes when you equipped, but it doesn't show on tooltip

**Comment by TheVietboi** [comment]
also, can we buff the boots rolls and gems? it's still weak comparing to boots that was mainly use to get runes

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/100498461-6f1b6b00-3173-11eb-85d7-2e408c5d080c.png)

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/100498468-76db0f80-3173-11eb-8dec-518ec8d23851.png)

**Comment by redledcat** [comment]
maybe was fixed earlier
