### ISSUE TITLE
Your Horn of the Triumphant Bastion zones still have their full effects even after you chisel the item off

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1533]
lol

**Comment by ChalkyBrush** [comment]
`    local ability = self:GetAbility()
    if ability.bastion_table then
        for i = 1, #ability.bastion_table, 1 do
            local bastion = ability.bastion_table[i]
            if bastion:EntityExistsAndIsAlive() then
                self:DeleteBastion(bastion)
            end
        end
    end
    ability.bastion_table = nil`

**Comment by ChalkyBrush** [comment]
`function modifierClass:OnRemoved()
	if not IsServer() then
		return false
	end
    local ability = self:GetAbility()
    if ability.bastion_table then
        for i = 1, #ability.bastion_table, 1 do
            local bastion = ability.bastion_table[i]
            if bastion:EntityExistsAndIsAlive() then
                self:DeleteBastion(bastion)
            end
        end
    end
    ability.bastion_table = nil
end`

🤷

**Comment by DeckardCainRPC** [comment]
somebody has fixed it in the intervening 3 days
