### ISSUE TITLE
World Commander boss can only "die" or change forms during his charge attack spell

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1535]
this is most easily reproduced by fighting him with an invisible hero, or one he otherwise cannot target with his charge dashy zoom jumpy spell thing, you know the one, it's the only spell he has. anyway, during his first form, you'll notice that you can make him lose health all you want, right down until he's at 1HP, but he won't react to your presence - and not just because you're invisible. after you get bored and drop invis to see if that will, you know, remind him that he's under attack, you'll be kind of startled when you discover that this actually does wake him up; he'll charge at you, then suddenly realize that he's been mortally wounded, and proceed to change into his second form.

... and of course you'll put your invisibility effects back up so that you can fight his overtuned ass. and when you finish dropping his precious HP again, he'll be right back to pretending nothing's wrong. in order for him to actually play whatever script asks "hey am i dead yet?" you have to bait him into charging at you again.

**Comment by TheVietboi** [comment]
A similar thing happens to Val'dun on sea fortress as well. And if my theory is correct, they are both bugged like this if they were killed under such debuffs like stun, freeze.

**Comment by DeckardCainRPC** [comment]
nintai looked at this and knows what's causing it. a ``return`` command needs to be moved up 1 line, since it's in the wrong code block

**Comment by ChalkyBrush** [comment]
f
