### ISSUE TITLE
Typos with CM's Helm Arcana

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1543]
1. for years, YEARS, the arcana's spell has been called "Inceration" instead of "Incineration" and nobody noticed until just now
2. arcana spell tooltip has an instance of "enemies has" instead of "enemies have"
3. arcana Q2 says "releases a a soul-burning Ring of Fire," there should be one less "a "

**Comment by redledcat** [comment]
done
