### ISSUE TITLE
Redfall castle lava destroys my fps

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#155]
Next match in Redfall after Tanari makes my pc melt when my camera is over lava pools in redfall

**Comment by redledcat** [comment]
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 227 (was 299)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 215 (was 291)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 207 (was 289)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 201 (was 280)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 194 (was 272)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 184 (was 266)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 178 (was 280)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 173 (was 249)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 161 (was 244)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 158 (was 233)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 152 (was 229)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 143 (was 223)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 68 (was 142)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
[PanoramaScript] END ROLL#itemroll-box1
[PanoramaScript] ITEM VALUES ROLL BOX:
[PanoramaScript] {"qualityColor":"#E4AE33","consumable":0,"minLevel":79,"itemDescription":"Slot: Hands","itemPrefix":"","qualityName":"immortal","rarityFactor":5,"itemName":"Berserker Gloves","itemSuffix":""}
[PanoramaScript] 1
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
[PanoramaScript] data:
[PanoramaScript] 7317
[PanoramaScript] END ROLL#itemroll-box2
[PanoramaScript] ITEM VALUES ROLL BOX:
[PanoramaScript] {"qualityColor":"#E4AE33","useDescription":"item_rpc_paladin_glyph_5_a_description","consumable":0,"minLevel":75,"stackedConsumable":1,"itemDescription":"Glyph","itemPrefix":"","requiredHero":"npc_dota_hero_omniknight","glyph":1,"qualityName":"immortal","rarityFactor":5,"itemSuffix":""}
[PanoramaScript] 2
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 305 (was 548)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 281 (was 403)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 255 (was 353)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 180 (was 279)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 180 (was 280)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 157 (was 235)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
[SplitPacket]       client =[A:1:2040737799:9305[0]:  split packet seq #5906 restarting, just received packet 0
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
[PanoramaScript] true
[PanoramaScript] playerID: 2
[PanoramaScript] true
[PanoramaScript] 2-glyph-1
[PanoramaScript] file://{images}/items/glyphs/glyph_4_2.png
[PanoramaScript] file://{images}/items/glyphs/glyph_4_1.png
[PanoramaScript] file://{images}/items/glyphs/glyph_mountain_protector_1_1.png
[PanoramaScript] true
[PanoramaScript] playerID: 2
[PanoramaScript] true
[PanoramaScript] 2-glyph-1
[PanoramaScript] file://{images}/items/glyphs/glyph_4_2.png
[PanoramaScript] file://{images}/items/glyphs/glyph_4_1.png
[PanoramaScript] file://{images}/items/glyphs/glyph_mountain_protector_1_1.png
[PanoramaScript] true
[PanoramaScript] playerID: 2
[PanoramaScript] true
[PanoramaScript] 2-glyph-1
[PanoramaScript] file://{images}/items/glyphs/glyph_4_2.png
[PanoramaScript] file://{images}/items/glyphs/glyph_4_1.png
[PanoramaScript] file://{images}/items/glyphs/glyph_mountain_protector_1_1.png
[PanoramaScript] true
[PanoramaScript] playerID: 2
[PanoramaScript] true
[PanoramaScript] 2-glyph-1
[PanoramaScript] file://{images}/items/glyphs/glyph_4_2.png
[PanoramaScript] file://{images}/items/glyphs/glyph_4_1.png
[PanoramaScript] file://{images}/items/glyphs/glyph_mountain_protector_1_1.png
[PanoramaScript] true
[PanoramaScript] playerID: 2
[PanoramaScript] true
[PanoramaScript] 2-glyph-1
[PanoramaScript] file://{images}/items/glyphs/glyph_4_2.png
[PanoramaScript] file://{images}/items/glyphs/glyph_4_1.png
[PanoramaScript] file://{images}/items/glyphs/glyph_mountain_protector_1_1.png
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 129 (was 221)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
[PanoramaScript] END ROLL#itemroll-box0
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
[PanoramaScript] update runes
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 123 (was 217)
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 113 (was 211)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 24 iterations without a present event.
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 93 (was 167)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
[Panorama] DispatchAsyncEvent backlog, failed to dispatch all this frame. Remaining queue depth: 60 (was 135)
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
[PanoramaScript] updateAbilityList
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
[SplitPacket]       client =[A:1:2040737799:9305[0]:  split packet seq #5914 restarting, just received packet 0
[SplitPacket]       client =[A:1:2040737799:9305[0]:  split packet seq #5916 restarting, just received packet 0
[PanoramaScript] updateAbilityList
[PanoramaScript] updateAbilityList
[PanoramaScript] END ROLL#itemroll-box1
[PanoramaScript] END ROLL#itemroll-box2
[PanoramaScript] updateAbilityList
CSwapChainBase::QueuePresentAndWait() looped for 21 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 22 iterations without a present event.
CSwapChainBase::QueuePresentAndWait() looped for 23 iterations without a present event.
[PanoramaScript] updateAbilityList

**Comment by ChalkyBrush** [comment]
i believe this was fixed about a month ago

**Comment by redledcat** [comment]
nah, that's just dota engine or whatever anomaly.
I took the rule to restart whole game each time I want to change the map.
Only effective solution
