### ISSUE TITLE
Flamewaker Rework Gripesheet

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1550]
1. capitalize the second instance of the word "flamewaker" in E spell's tooltip
2. capitalize both "cataclysm" and "strength" in R3's tooltip
3. in W3's tooltip, capitalize instances of the word "armor," and put an apostrophe after "enemies" (because you're making a plural possessive)
4. clarify Glyph T3-1's tooltip: "Increases the duration of Flamewaker's stun effects by <>."
5. in Glyph T4-2's tooltip, change "based damage" to "base damage" and change "Attributes" to "total attributes"
6. in Glyph T6-2's tooltip, replace "in a Diamond Pattern" (is that a proper noun?) with "in a diamond pattern around Flamewaker."
7. Gladius Immortal weapon tooltip is improperly pluralized; change "duration" to "durations" and "is" to "are"
8. consider giving all the OTHER heroes *twenty fucking thousand base damage* on their Q spells

**Comment by ChalkyBrush** [comment]
did all except 8
