### ISSUE TITLE
Epoch Guardian Rework Gripe Sheet

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1557]
1. Q ability tooltip says "% DOT DAMAGE % OF IMPACT DAMAGE TIME NUMBER OF LINKS" which is atrocious, it should instead read "DOT DAMAGE AS % OF IMPACT DAMAGE TIMES NUMBER OF LINKS"
2. R abiilty tooltip: replace "Upon successful cast" with "When channeling completes" and then "matter" with "enemies" (since the matter is referred to as a "them" toward the end of the sentence)
3. Q1 and Arcana Q1 tooltips' second sentences could be clarified to explain precisely what it does: "Aeon Strike replaces the Physical damage instances dealt by Epoch Guardian's autoattacks."
4. W3 tooltip: capitalize "intelligence"
5. E2 tooltip small rewrite: "Increases the travel speed and max distance of @Ability3."
6. R1 tooltip clarified: "Increases bonus attack damage based on Epoch Guardian's percentage of current mana."
7. R3 tooltip clarified: "Increases all damage dealt by @Ability4 based total attack power, and causes enemies frozen in time by the spell to be eroded away in 0.33-second intervals, dealing the spell's damage again on each tick."
8. Glyph T7-1 clarified: "The first enemy struck by @Ability3 during its travel will trigger a gravitational explosion identical to the one caused by successfully channeling @Ability4."
9. Glyph T5-A: replace "the main orb" with "a traveling" (or "travelling" since you canucks insist on using Commonwealth English)
10. Glyph T4-2: capitalize the second instance of "spirit"
11. Glyph T5-2 rewrite: "Each enemy caught in the final explosion of @Ability4 is targeted with a @Ability2, to a maximum of <% VARIABLE_NAME %> enemies per explosion."
12. Glyph T7-2 rewrite: "Increases the maximum channel time of @Ability4 by <% VARIABLE_NAME %> seconds, and the final explosion will occur whenever channeling stops, even if it was interrupted."
13. Arcana Q2: replace "Stats" with "Attributes" (properties like Armor Pierce and Spell Pierce are referred to as "Stats" elsewhere, e.g. Justice Greaves)
14. Arcana Q4: un-capitalize "Radius" and "Cast Range" since those do not appear as proper nouns elsewhere

AND FURTHERMORE,

15. Eye of Chronos Immortal weapon tooltip: replace "create an attack on" with "launch attacks against"
16. I rewrote this too: ``"property_epoch_immortal_weapon2_description"						"On taking lethal damage, become invulnerable for <% EPOCH_IMMORTAL_WEAPON_2_RESPAWN_DELAY %> seconds while automatically channeling @Ability4 at your position, restoring all health and mana during this time. Epoch Guardian respawns when the channel completes. This effect has a <% EPOCH_IMMORTAL_WEAPON_2_CD %>-second cooldown."``
17. and also this: ``"property_epoch_immortal_weapon3_description"						"If a @Ability3 expires without Epoch Guardian having teleported to it, the spell will not go on cooldown."``

**Comment by DeckardCainRPC** [comment]
in all i am very impressed with the rework and he looks very neat. his gameplay should now be less punctuated by his clunky mobility, alternately extremely long or extremely short range on his various abilities, and frailty without sapphire lotus or invincibility frame abuse

~~the only things i haven't seen yet are his Immortal weapon tooltips which i should go break open the vpk for~~

**Comment by ChalkyBrush** [comment]
👌
