### ISSUE TITLE
One last Epoch Guardian gripe I missed

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1559]
Arcana Q spell tooltip says "% DMG % OF ATTACK POWER," replace that with "DAMAGE AS % OF ATTACK POWER"

**Comment by ChalkyBrush** [comment]
The % sign at the start means that it shows a % symbol after the number in the tooltip. The website just doesn't pick up on it
How it shows in game:

DMG % OF ATTACK POWER: X%
