### ISSUE TITLE
Chernobog's Q doesn't appear to reduce enemy attack damage or movespeed, but enemies can't walk over it now

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1561]
STEPS TO REPRODUCE:
1. be chernobog (very hard)
2. cast Q at a group of stooges. ideally these stooges need to be able to survive a hit from your Q, since you need to observe them after the impact
3. left-click them to check their stats panel
4. observe that their attack damage readout doesn't register any negative modifiers, and furthermore their movespeed isn't slowed either. hmm
5. continue keeping an eye on them
6. notice that they are incapable of actually moving toward you while stuck in the Q murk
7. that's not supposed to happen
8. wtf

**Comment by redledcat** [comment]
possible explanation: Q contains a lot of dummy units with minimum collision radius, which, still, too large to be negligible.
no idea about Q modifier maybe it's because chernobog is fucked up

**Comment by redledcat** [comment]
should be fixed by 8neame
check if it's not
