### ISSUE TITLE
Epoch Guardian Glyph T2-2 tooltip error

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1563]
![image](https://user-images.githubusercontent.com/34521754/85876260-7513b700-b7a3-11ea-90f8-88ce0873d17c.png)

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/87245002-5d4a5d00-c44a-11ea-9c1a-6b9b77e7751c.png)
?

**Comment by DeckardCainRPC** [comment]
we talked about this in discord days later, it occurs when Epoch Guardian isn't in the current game session (for example, when viewing his Glyph text in the Glyph Enchanter NPC's shop while playing as a different hero)

**Comment by redledcat** [comment]
Ok it might be fixed next update, same trouble as Flamewaker's rework caused

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/95010267-8dac2c80-0630-11eb-8bee-e570ddffc90a.png)
