### ISSUE TITLE
Sea Fortress abilities "Heart Spike" and "Hydrogen Field" deal more damage than stated in tooltip

### ISSUE THREAD

**Issue by crazybrain228** [ChalkyBrush/roshpit-bug-tracker#1568]
Heart spike says its supposed to do 4% but code says its 12%
hydrogen field says its supposed to do 4% but code says its 7%
heart spike doing more damage than expected is especially noticable in winterblight mountain pt 3 when you get swarmed by the summoned haunters from sentry owls.

**Comment by redledcat** [comment]
ok fixed
