### ISSUE TITLE
Systhesis 2 weapons now counting them as 2 normal immortal items, so no level 100 weapon is created after the procress

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1576]

**Comment by maurdekhai** [comment]
what does "normal immortal weapon" mean?
About level 100: not sure if it was in patchnotes, but it was changed recently, so it rolls new min level based on average like with any other immortal gear

**Comment by TheVietboi** [comment]
typo on the "normal immortal weapon" part. in the past whenever you synthesis 2 immortal weapons, they always give one with level 100, so this is a weird phenomenon to me

**Comment by redledcat** [comment]
It was a bug, was fixed
