### ISSUE TITLE
New R1 of Hydroxis do not affect other runes with armor reduction debuff

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#158]
Description says "any of R runes" apply debuff, but it's only R.
![20171118191608_1](https://user-images.githubusercontent.com/32621322/32982410-083232e6-cc8d-11e7-9d32-24e35de58d44.jpg)
Neither of Q1 and R2 do not aplly it (cant test R3, too lazy, but sure it does not work either with R1 effect)
![20171118191610_1](https://user-images.githubusercontent.com/32621322/32982412-1d5afde2-cc8d-11e7-9d14-4b2d7d641dc4.jpg)
![20171118191611_1](https://user-images.githubusercontent.com/32621322/32982413-1ea0b962-cc8d-11e7-930d-1c0265ce742d.jpg)

**Comment by ChalkyBrush** [comment]
we discussed this today, and it shouldn't be affecting runesin the first place
