### ISSUE TITLE
[Astral Ranger] Equipping her W arcana will broke the stat panel, and making her unable to to revive on new checkpoints or respawn flag

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1586]
You think it's chernobog that's a bug fest? NOPE, it's Astral Ranger

**Comment by TheVietboi** [comment]
also website is heavily affected 
![image](https://user-images.githubusercontent.com/51455274/87247993-39eed480-c481-11ea-9888-015382376f84.png)

**Comment by redledcat** [comment]
Script Runtime Error: scripts\vscripts\custom_attributes.lua:4177: attempt to call method 'GetCooldownBase' (a nil value)
stack traceback:
	scripts\vscripts\custom_attributes.lua:4177: in function 'GetWCooldownModifier'
	scripts\vscripts\custom_attributes.lua:3913: in function 'CalculateAndSaveCooldownModifier'
	scripts\vscripts\custom_attributes.lua:554: in function 'CalculateAndSaveRoshpitAttributes'
	scripts\vscripts\custom_attributes.lua:3356: in function 'ApplyStatBonusesToHero'
	...pit_champions\scripts\vscripts\npc_abilities\general.lua:7: in function <...pit_champions\scripts\vscripts\npc_abilities\general.lua:1>
Message count limit of 10 hit. Subsequent duplicate messages will be squelched.

Script Runtime Error: scripts\vscripts\items\filters.lua:495: attempt to call method 'GetCooldownBase' (a nil value)
stack traceback:
	scripts\vscripts\items\filters.lua:495: in function 'ReduceWCooldown'
	scripts\vscripts\items\filters.lua:1215: in function 'ApplyWskills'
	scripts\vscripts\items\filters.lua:898: in function 'CastSkillArguments'
	...roes\moon_ranger\abilities\arcana\shot_of_apollo_lua.lua:122: in function <...roes\moon_ranger\abilities\arcana\shot_of_apollo_lua.lua:71>
