### ISSUE TITLE
Storm Spirit ally in left wing of Pit of Trials can get stuck in terrain, softlocking the game

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1597]
![image](https://user-images.githubusercontent.com/34521754/93290294-663f0e00-f7ae-11ea-9990-f268ac057bbe.png)

SUGGESTED COURSE OF ACTION:
fucking remove that tree, it's an easy fix that doesn't require you to make that spawner ward Fear-immune, push-immune, etc.

and if you really want to be proactive, you can give the Storm Spirit a 60-second maximum life span, since it will never take him that long to reach his typical destination during normal gameplay, and if the player is already capable of moving is spawner ward, then they're probably capable of adjusting the ward's position (as i've done in the screenshot above) to spawn him in a *good* location after they realize they've accidentally trapped his ass (as i've also done in the screenshot above). there are no monsters left alive to kill him with. :(

**Comment by DeckardCainRPC** [comment]
i just realized this is a duplicate of #1590 which means you need to fix the issue twice as hard

**Comment by redledcat** [comment]
Fixed

**Comment by redledcat** [comment]
more details: fix includes both flying movement for forest guide mob and dummy wards protected from certain skills

**Comment by redledcat** [comment]
#1379

**Comment by DeckardCainRPC** [comment]
bless you
