### ISSUE TITLE
Hydroxis's Glyph of Vapor (bug/intended?)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#160]
Attacks have a 15% chance for Crescent Wave to deal 400% of attack power as magic damage.
Glyph damage has no element and has no advantages over physical damage, which is quite more valuable.
![20171119192245_1](https://user-images.githubusercontent.com/32621322/32992731-de3e00da-cd56-11e7-8cd7-56c7c6a21856.jpg)

**Comment by ChalkyBrush** [comment]
fixed
