### ISSUE TITLE
New Ruby effect for Breastplate of Abjudication creates infinite Armor Pierce gain loop when equipped alongside Marauder Gloves

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1601]
great job

**Comment by TheVietboi** [comment]
![image](https://user-images.githubusercontent.com/51455274/93493337-ff4c6100-f935-11ea-97a7-468dc94cd9de.png)
it's the same reason as this one: Stat recalculation

**Comment by redledcat** [comment]
I feel no regrets

**Comment by DeckardCainRPC** [comment]
exterminated with prejudice
