### ISSUE TITLE
Epoch Guardian's E3 rune name is "Lifetream" instead of "Lifestream"

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1605]
>Whoops

**Comment by redledcat** [comment]
okay

**Comment by redledcat** [comment]
fixed next patch

**Comment by redledcat** [comment]
yes, this crisis resolved
but at what cost?
I had to delete reanimation stones from key bank in order to fix this simple issue
