### ISSUE TITLE
Having any type of gem in Cloak of the Cimmerian Priesthood will enable the Amethyst's Fear effect particle and SFX

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1607]
STEPS TO REPRODUCE:
1. put any gems in the hat EXCEPT amethysts
2. cast R
3. observe that the purple ring for the fear effect is drawn, and the accompanying WHEE noise is played. no monsters run away in fear despite the scary particle effect.
4. who is responsible for this fuckup

**Comment by redledcat** [comment]
I confirm it exists because both sound and particle placed outside of amethyst checker
Nobody is responsible for this, cimmerian hood has been created to work this way

**Comment by DeckardCainRPC** [comment]
hmmm sounds to me like chalkybrush is responsible for this then

thank you for fixing it
