### ISSUE TITLE
Hand of Midas new Ruby effect does not actually increase proc chance

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1611]
STEPS TO REPRODUCE:
1. put it on
2. put a perfect ruby in it
3. go to the target dummy
4. attack it repeatedly
5. observe that it now deals physical damage, as advertised, but its proc chance is still 20%

SUGGESTED COURSE OF ACTION:
1. fix that
2. replace ruby tooltip with "Midas Touch now deals Physical damage, pierces Spell Immunity, and has a @ruby_property1% chance to activate."

**Comment by redledcat** [comment]
It doesn't grant any improvements to proc rate, it just replaces magical midas damage with physical with said chance
perfect ruby makes it always physical, pristine makes 4 procs out of 5 physical and 5th is still magical

**Comment by DeckardCainRPC** [comment]
ohhhhhhhhhhhhhhhh okay, i got it

then replace ruby tooltip with "When Midas Touch effect triggers, it has a @ruby_property1% chance to pierce Spell Immunity and deal Physical damage instead of Magical"

**Comment by redledcat** [comment]
fixed next patch
