### ISSUE TITLE
Djanghor's new W2 tooltip issues

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1617]
1. the tooltip shows Armor Pierce gain per stack, but it does not display HP Regen gain per stack
![image](https://user-images.githubusercontent.com/34521754/99803533-a18bef00-2b07-11eb-865a-31614858ea5b.png)

2. slight adjustments to phrasing:
"which have base duration" -> "which have **a** base duration"
"and expire at once" -> "and expire **all** at once"

**Comment by redledcat** [comment]
thank you
fixed

**Comment by DeckardCainRPC** [comment]
no, thank you
