### ISSUE TITLE
Elemental Warlord Q2 has no effect

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1626]
no matter how many points you put into it, his armor won't increase during Ice Shell

**Comment by redledcat** [comment]
no way, it works for me
![fwqfwfwfwqf](https://user-images.githubusercontent.com/32621322/101287688-d9cb4700-3802-11eb-8ab5-1d6cbade65ef.png)

**Comment by DeckardCainRPC** [comment]
you are correct, false alarm; i believe the problem was that i may have had Monkey Paw equipped while testing Q2, which would have instantly destroyed the shield stacks, canceling the ability. thanks
