### ISSUE TITLE
[Paladin] W arcana is completely broken

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1635]
Seems like valve did something again

**Comment by redledcat** [comment]
or me

**Comment by redledcat** [comment]
yes, it was me, redledcat!

**Comment by redledcat** [comment]
not the subj, but I found a funny stuff while checking arcana
![image](https://user-images.githubusercontent.com/32621322/103078403-d8f82a80-45e2-11eb-9de9-4c5d4623e8f6.png)
