### ISSUE TITLE
lol i forgot that perma-disarming Spirit Warrior would make him unable to interact with most puzzle objects

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1637]
this is the only legitimate complaint i am willing to accept about my new weapons, everything else is obviously perfect and not at all stupid

**Comment by redledcat** [comment]
intended

**Comment by DeckardCainRPC** [comment]
okay i have a possible solution in mind, but i would also like to hear some alternative solutions if anybody has them

instead of the disarm, you could try to replace his autoattacks like Nethergrasp Palisade's pure damage gem does; if his autoattacks could be replaced with 0-damage Normal Physical strikes, that would sort of be like disarming him, but i am pretty sure it would still let him attack puzzle objects. i think coding this would be easier, AND more effective with less problems, than trying to enable W to affect puzzle objects.

**Comment by DeckardCainRPC** [comment]
vietboi reminded me to close this since it was fixed years ago. i probably only left it open because every time i read redledcat's snarky "intended" i laugh irl
