### ISSUE TITLE
Chernobog's weapon4 was accidentally added to the drop table despite being unfinished

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1641]
big whoops

**Comment by redledcat** [comment]
I need more info
if chernobog's weapon is somewhere in game, it means there is a way to get any of non-added weapons, because I put manually every finished one in special list
```
function Weapons:RollRandomLegendWeapon4(deathLocation)
	local classTable = {"flamewaker", "voltex", "axe", "astral", "epoch", "paladin", "seinaru", "warlord", "duskbringer", "auriun", "trapper", "spirit_warrior", "mountain_protector", "solunia", "hydroxis", "jex", "omniro", "bahamut"}
	local class = classTable[RandomInt(1, #classTable)]
	return Weapons:RollLegendWeapon4(deathLocation, class)
end

function Weapons:RollLegendWeapon4WithDotaName(class, deathLocation)
	local classTable = {"flamewaker", "voltex", "axe", "astral", "epoch", "paladin", "seinaru", "warlord", "duskbringer", "auriun", "trapper", "spirit_warrior", "mountain_protector", "solunia", "hydroxis", "jex", "omniro", "bahamut"}
	class = HerosCustom:GetInternalHeroNameMain(class)
	return Weapons:RollLegendWeapon4(deathLocation, class)
end
```

**Comment by DeckardCainRPC** [comment]
[11:32 PM] ihatemyself: also trivia you probably know: 4th weapon can spawn in test server despite not being curated
![image](https://user-images.githubusercontent.com/34521754/103177998-1d86fe80-484d-11eb-9031-f8025ea43af7.png)
[11:32 PM] sterv: no i wasn't aware of this, and it's a serious bug
[11:34 PM] sterv: cherno's weapon4 property isn't coded
[11:34 PM] sterv: if you check the patch notes, cherno isn't listed as one of the 18 heroes that received their weapon4
[11:34 PM] ihatemyself: oh yeah
[11:34 PM] sterv: it should not be in the drop table at all

**Comment by redledcat** [comment]
ok, that one shouldn't be a big problem, because unification for weapon spawns is a bit different, and chat commands use more core function than ones in real game made for item drops
Yes, we can spawn them in test, because I made them all have proper "special" rolls on property2 and all weapons share the same 3rd and 4th properties, but since they don't have their special effects yet, it's basically pointless

**Comment by DeckardCainRPC** [comment]
after speaking with vietboi, he clarified that it can only be spawned in Test; he didn't say that initially, he later went back and edited his message to include that specific information
