### ISSUE TITLE
A Legion Commander creep in Tanari Wind Temple's advanced wing has a global cast range stun spell

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1642]
vietboi claims that an LC model creep, which appears only from the waves that spawn from the trees that you have to water by killing all of the Morphling creeps at the same time, has a stun spell that mistakenly has a global cast range. the reason this has gone undiscovered for years is because the creeps themselves are extremely fragile and they almost never live long enough to actually cast this spell.

**Comment by TheVietboi** [comment]
crazybrainToday at 12:39 PM
One of the units outside the water temple has a leshrac Q stun on a 10s cd that hits through fog of war and doesn’t require aggro to cast
And it has a lot of range too
Which is what I think I was getting stunned by


Wrong creep, my bad
