### ISSUE TITLE
Losing items to Pool of Eternity

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#168]
Unstable work of servers let me test a possible way of losing an item.
When you put item in stash, the screen gets darker and item disappears from char inventory, moving to pool.
But if server has issues and delay is large, the dark does not go off, and stay so forever (waited solid 10 minutes), item is not in pool yet, but already not in char inventory.
If you click on "Save" or "Key bank", and the back to "Pool", the dark goes off, but item also does not retrieved back to inventory, being lost.
(After item is lost, pool was aviable for me to stash some other items)

**Comment by ChalkyBrush** [comment]
this is not really a bug. server has gone down bc too much traffic. Im going to have to buy more server power
