### ISSUE TITLE
Curator NPC now has global interaction range after tooltip fix patch but can we keep it this way

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1693]
crazybrain — Yesterday at 9:16 PM
i see no problems
curator npc has wings
he can fly to us to curate the item
im in

**Comment by redledcat** [comment]
It's not a bug, I manually added this years ago because some maps, tanari and arena have a little bit of a distance between blacksmith and curator
I found this appropriate to just give curator global radius, because he has no straight interactions to gameplay
