### ISSUE TITLE
Sea Fortress - Slark stucked in the wall - unknown reason

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#172]
![20171128010656_1](https://user-images.githubusercontent.com/32621322/33292237-2c22dca0-d3d1-11e7-8145-65ae09a8d656.jpg)

**Comment by redledcat** [comment]
upd - Axe did not used his E to push mob there

**Comment by ChalkyBrush** [comment]
that's devastating

**Comment by ChalkyBrush** [comment]
FIXED
