### ISSUE TITLE
Redfall lina not triggered

### ISSUE THREAD

**Issue by ablyx** [ChalkyBrush/roshpit-bug-tracker#174]
![20171129002634_1](https://user-images.githubusercontent.com/16754650/33331463-9f7df83a-d49c-11e7-92fc-74bc4b555d51.jpg)
(ignore the pause, was trying to figure out which button screenshots)

No skips were done, ta was not invis when he approached lina.

**Comment by redledcat** [comment]
Here is the video of reproduction (1:02)
https://youtu.be/oYUJc7CpP0o

**Comment by redledcat** [comment]
#79

**Comment by ChalkyBrush** [comment]
should be fixed in next patch

**Comment by redledcat** [comment]
people keeps reporting Lina still bugs somehow.
Trapper involved 100% sure

**Comment by redledcat** [comment]
@ChalkyBrush It's not caused by Vanish.
Think it's BKB state from Hope or invis from ultimate cause this

**Comment by redledcat** [comment]
Tested R invis and it seems to be ok too.
Hope of Saitaru?

**Comment by redledcat** [comment]
Should be fixed by Nintai next patch (decoy was flagged as hero unit)
