### ISSUE TITLE
Duskbringer E having incorrect cool down when leveled up

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#177]
The description says it has 4.5 seconds cool down. When used the cool down timer shows that it has over 5 seconds cool down. I also tested the cool down using blue mask of Ahn Qhir and it doesn't match. I think the cool down of the skill doesn't get reduced at higher levels and stays at 5.7 seconds at all levels.

40% CD reduction of 4.5s CD.

 4.5*0.4 = 1.8.

4.5 - 1.8 = 2.7 seconds. The cool down with the mask is over 3 seconds.
Images below will show this.

![20171130121548_1](https://user-images.githubusercontent.com/32886049/33444666-ec765c18-d5c8-11e7-8dac-67d53efbb371.jpg)
![20171130121554_1](https://user-images.githubusercontent.com/32886049/33444942-917f1e16-d5c9-11e7-9843-2e9056704f59.jpg)
![20171130121636_1](https://user-images.githubusercontent.com/32886049/33444973-a26f0aec-d5c9-11e7-891e-e6f1fa7c58e6.jpg)
![20171130123121_1](https://user-images.githubusercontent.com/32886049/33445284-71f6888a-d5ca-11e7-854b-3547eda9b6ba.jpg)

**Comment by redledcat** [comment]
no problem here.
everything works good with dusk E: dunes, HoL, blue ahnqhir
