### ISSUE TITLE
Voltex Static [W]

### ISSUE THREAD

**Issue by Colomzkie018** [ChalkyBrush/roshpit-bug-tracker#181]
Bug issue equiping Monkey Paw item in Voltex. Using Static [W] while not in Avatar [R3] triggers suicide on Voltex. Using Static [W] while in Avatar [R3], Ion Shell [W3] won't trigger the effect. I play at ridgefall map and then use key redfall ruby.

**Comment by ChalkyBrush** [comment]
monkey paw damages the shield, and then the shield reflects the damage back at the caster. Be careful what you wish for!
