### ISSUE TITLE
Arhon Armor R1 procs on any puzzle dummy units

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#190]
![20171207003125_1](https://user-images.githubusercontent.com/32621322/33687376-ba7c57c2-dae0-11e7-923b-adcb229fb727.jpg)

**Comment by redledcat** [comment]
Despite how furious his R1 is on puzzles, it's completely useful effect in game for obvious reasons.

**Comment by redledcat** [comment]
https://youtu.be/rIJ95bHaFqo

**Comment by ChalkyBrush** [comment]
fixed
