### ISSUE TITLE
Archon Armor effect pushes Arkimus in textures, trees and abyss areas

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#197]
![20171208004107_1](https://user-images.githubusercontent.com/32621322/33740321-e113bc0e-dba8-11e7-8f7a-c35d3ca192ae.jpg)

**Comment by redledcat** [comment]
![xhul](https://user-images.githubusercontent.com/32621322/33740425-502b8d88-dba9-11e7-887a-9d0d16390e00.PNG)

**Comment by ChalkyBrush** [comment]
fix
