### ISSUE TITLE
Tanari Wind Spirit cleances attack range buff from Arkimus Archon state with tornado

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#199]
also drops Drow from her arcana cloud, and cleances many other game significant buffs.
Time to rework?

**Comment by redledcat** [comment]
Also!
Djanghor visual year beast form being cleanced by that goddamn tornado.

**Comment by redledcat** [comment]
Bump! Rework is needed.

**Comment by ChalkyBrush** [comment]
this is now fixed
