### ISSUE TITLE
Arcane Crystals - part of them cannot be get even solo, due to counter mechanics

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#201]
![20171208012238_1](https://user-images.githubusercontent.com/32621322/33741733-3344fe2a-dbae-11e7-9382-80806ca82341.jpg)

**Comment by ChalkyBrush** [comment]
this is fixed now?

**Comment by redledcat** [comment]
No, it's not. 
That problem reveals on big enemy clusters, when paragons die one by one during large pediod of time.
Easy to check that on redfall shipyard/castle spawners, tanari spawner on screen above, serengaard.
Your char can pick up only last portion of crystals, then you should wait for counter, pick up another portion. If there are too many portions of arcane crystals, part of them will disappear when their lifetime expire, before player be allowed to pick up them.
So I'm forced to run over crystals again and again trying to collect them, but part of them always diasppears. Drama.
