### ISSUE TITLE
Demon Enfoncer reduces attributes to negative values

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#203]
(lol look at mana bar)
![20171209001247_1](https://user-images.githubusercontent.com/32621322/33787814-b536f0b8-dc77-11e7-861d-95f64586077f.jpg)
![20171209001248_1](https://user-images.githubusercontent.com/32621322/33787817-b74d6530-dc77-11e7-954e-ed1dc61c9c06.jpg)

**Comment by ChalkyBrush** [comment]
this should be fixed with custom attributes patch
