### ISSUE TITLE
Market - Major bug with outbids on no-buyout sales

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#205]
https://www.roshpit.ca/market/auction/37012

**Comment by redledcat** [comment]
Highest bid does not count on this
relulting in 1 mithril bid can outbid 500000 mithril
also
![lul](https://user-images.githubusercontent.com/32621322/33795323-11038c9c-dce8-11e7-9b89-294f9ba75cc7.PNG)

**Comment by redledcat** [comment]
https://www.roshpit.ca/market/auction/35432
https://www.roshpit.ca/market/auction/34152

**Comment by redledcat** [comment]
basically each sale with no buyout now is damaged

**Comment by ChalkyBrush** [comment]
fixed, and going back to sleep. Sorry about this one!

**Comment by redledcat** [comment]
![12321321312](https://user-images.githubusercontent.com/32621322/33795759-f3b082f0-dcef-11e7-9f10-3d610b7a7501.PNG)
NOOOOOO
