### ISSUE TITLE
Outbid do not return??

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#206]
https://www.roshpit.ca/market/auction/29040
I did not got my 250k back  here

**Comment by redledcat** [comment]
Капитан Дизмораль got his neither

**Comment by redledcat** [comment]
Everything rolled back, so I think it should be fine.
I dont want to test it myself, check and close if solved

**Comment by ChalkyBrush** [comment]
fixed now
