### ISSUE TITLE
[WebsiteProfiles] Same wrong  immortal weapon effect description for all weapons. 

### ISSUE THREAD

**Issue by tonygks** [ChalkyBrush/roshpit-bug-tracker#21]
https://i.imgur.com/8mAFCfZ.jpg
https://i.imgur.com/GrBPrNC.jpg

**Comment by ChalkyBrush** [comment]
you should post screen with URL so I can check it, because this doesn't show for me:

https://www.roshpit.ca/players/106304978/heroes/3

**Comment by ChalkyBrush** [comment]
fixed
