### ISSUE TITLE
Arkimus Arcana spell reliably crashing server due to particles

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#211]
STEPS TO REPRODUCE:

1. cast arcana Q spell
2. fight literally any more than 5 monsters at a time
3. the purple "lightning chain" particles that originate from AM's position and terminate at enemy unit's position have no particle limits per second, therefore they rapidly disconnect everybody and/or crash the entire server

RELATED ISSUES:

monkey paw + arcana Q1 (damage taken -> mana heal) + E2 (mana heal -> health heal) is causing 66 individual particles per second, this is probably also adversely affecting performance on its own, however that's without him fighting anything - since neither of these abilities have particle limits either, if AM kites a lot of shit - or just gets swamped, which happens all the time - each instance of damage he receives will also cause another set of particles, converting the RPC game server into a CGI rendering farm.

**Comment by ChalkyBrush** [comment]
should be fixed now, base skill 10 lightning beams /sec, Q1 at 3 particles every 0.7 sec
