### ISSUE TITLE
AGI is giving 1/10th of a point of armor, instead of 1/7th

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#212]
STEPS TO SEE THIS FOR YOURSELF:
1. get 3,000 AGI
2. look at how you have 300 armor instead of the expected 428.5

SUGGESTED COURSE OF ACTION:
1. say to yourself "holy smokes, this is causing everybody to have over 25% less armor than expected"
2. drink to center your mind
3. be skeptical of deckard, thinking "he has lied to me before. he is a sinister influence"
4a. check /resource/addon_english.txt and make sure it says "Every 7 AGI gives 1 armor"
4b. it does. it says that at like the beginning of the document.
5. deliberate the amount of effort required to unfuck this problem
6. do it anyway

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush note that you need to make the changes to your fleet of CustomAttributes.foo variables, as of course you surely recall, RPC runs on its own attribute system now. which you made

**Comment by Nintai** [comment]
Was increased to 0.14 armor per agi
