### ISSUE TITLE
Mortal strike passive WK ONESHOTS buildings in Serengaard

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#214]

**Comment by redledcat** [comment]
Also there was Sven - one with disarm or one with BKB break, they are next suspects if I was wrong about WK

**Comment by redledcat** [comment]
Flame breathing paragons seems to ignore building steadfast too (Or it was annihilator)

**Comment by DeckardCainRPC** [comment]
WK's Mortal Strike passive gained a new ability in 7.07, giving it a chance to instakill a non-hero unit - this famously ignores Fortification invulnerability, allowing WK to oneshot creeps even when they can't be damaged.

**Comment by ChalkyBrush** [comment]
lol, at least it all makes sense now

**Comment by redledcat** [comment]
I confirmed Mortal strike does not oneshot buildings, but that oneshots Sun Guardians
