### ISSUE TITLE
Silverspring Gloves has no regen cap, causing variable to underflow

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#215]
STEPS TO REPRODUCE:
1. equip Silverspring Gloves on Voltex with her arcana boot
2. get hit in Sea Fortress by basically anything; if you have trouble surviving, use her W3 shields
3. even a grazing hit will send her HP regen into insanity, and because 1,000% of insanity = impossibility, her attack damage will underflow

SUGGESTED COURSE OF ACTION:
1. cap **Voltex's Arcana E3** regen at an arbitrary value that you think is fair

**Comment by ChalkyBrush** [comment]
isn't the proper course of action to nerf voltex arcana E3?

**Comment by redledcat** [comment]
There will be a downside in sustain for build which do not use E3 as abuse factor, i.e. standard farseer arcana build.
Best way is add cap per rune.
It's controllable and balanceable

**Comment by DeckardCainRPC** [comment]
yeah, you don't need to nerf anything, just put an absolute limit on e3 such that it can never give a problematically high HP regen bonus. i think you've already put in protections like that on a whole bunch of other stuff (primarily summonable pets' attack damage, including ekkan's dudes).

**Comment by StillStealSteel** [comment]
And again there is a bug because of broken by design concept of using high numbers.

**Comment by crazybrain228** [comment]
line 160 of heroes/phantom_assassin/lightning_dash.lua. Add `ability.regen = math.min(ability.regen, (2^30)/10)` Adjust number to an 

> arbitrary value that you think is fair

**Comment by redledcat** [comment]
600000 regen is enough to compare with 120k agility far seer.
But since it's completely free, consider at least adding cap both in max regen and regen per rune.
6000-8000 cap per rune will give 120k-160k cap on 20 runes and 600k-800k with perfect e3 weapon/ 430k-570k with perfect e3 arcana.

**Comment by DeckardCainRPC** [comment]
i think this finally no longer matters, because we fixed 2.147b+ damage overflow. a fine day for canada and, therefore, the world
