### ISSUE TITLE
Axe's E now fully ignores all terrain

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#216]
STEPS TO REPRODUCE:
1. press E
2. right-click anywhere
3. go there without any further stipulations. there are no obstacles capable of stopping you. axe goes where he pleases.

SUGGESTED COURSE OF ACTION:
1. Dragon has already claimed responsibility for this boo-boo, ask him if he's had time to write a patch

**Comment by ChalkyBrush** [comment]
yes dragon did this but it's no problem, it's fixed now
