### ISSUE TITLE
Sea Fortress. This texture is higher than terrain level.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#219]
![20171206201706_1](https://user-images.githubusercontent.com/32621322/34057818-36573fe0-e1e1-11e7-97c0-13ef6c166b3b.jpg)
![20171206201700_1](https://user-images.githubusercontent.com/32621322/34057821-3726a870-e1e1-11e7-8d7d-01657d293650.jpg)
![20171206201712_1](https://user-images.githubusercontent.com/32621322/34057823-38aac366-e1e1-11e7-8847-703922d82285.jpg)

**Comment by ChalkyBrush** [comment]
i tried lowering it and parts go underground so it will stay this way
