### ISSUE TITLE
Seinaru's "Sunstrider" boot arcana spell doesn't disjoint projectiles

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#220]
STEPS TO REPRODUCE:
1. put on sunstrider boot
2. cast sunstrider while a missile is incoming
3. get owned

SUGGESTED COURSE OF ACTION:
1. fuck that

**Comment by redledcat** [comment]
But should they?
PA arcana, Bahamut's hand do not disjoing any projectiles too

**Comment by DeckardCainRPC** [comment]
they all should

**Comment by DeckardCainRPC** [comment]
if i could give one gift to the chinese internet community, it would be greater meme variety. every time i see that fucking panda with a human face, i feel kind of sad, like seeing multiple young children all huddled together on top of a single swingset. it's like looking into a post-apocalyptic world where there was only one meme, and it had nearly rotted away from JPEG artifacts caused by constant sharing and re-sharing. if taiwan is adamant about independence solely because of stale memes, then they have my sympathy.

maybe capitalism has spoiled me, with its wider selection of memes.
