### ISSUE TITLE
"Lightsworn Tabi" entry on roshpit.ca/items mistakenly says it's a Q spell

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#221]
STEPS TO REPRODUCE:
1. click here: https://www.roshpit.ca/items/item_rpc_seinaru_arcana2
2. wait patiently for page to load
3. hover over any of the four tooltips for Sunstrider's runes
4. observe that they all say [Q#] instead of [E#]

SUGGESTED COURSE OF ACTION:
1. ignore this issue entirely, and instead fix all the fucked up moon-language entries on roshpit.ca/items that have prevented users from submitting or receiving any information about those items since the service debuted
2. no, don't skip to number 2 to see if i lighten up or change my mind, go do number 1 like a good boy

but 3. this doesn't have to be a complicated fix, you can be hacky if you want: just go into the database, purge the entries for any affected items, then Curate at least one of each yourself. this ensures that their entries will be English-language. i know that might be inconvenient for foreign players, but in the words of ChalkyBrush, "Fuck colorblind people."

**Comment by ChalkyBrush** [comment]
fixed
