### ISSUE TITLE
Stormcloth Bracer fucked my dog

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#225]
this is a rollercoaster, bear with me

STEPS TO REPRODUCE:
1. equip Stormcloth Bracer and Hood of the Sea Oracle on Chernobog
2. turn W on, and attack a target 15 times, maxing the stacks on Hood of the Sea Oracle while ensuring that the target is being affected by Stormcloth Bracer's debuff as well
3. observe that the target only has its attack damage reduced by 50%. Hood of the Sea Oracle should be applying an additional 75%, for a total loss of 125%.

WHAT THE FUCK:
1. i dug around in scripts/vscripts/items/special_item_effects.lua and could not for the life of me find the code that actually defines modifier_stormcloth_bracer_effect

OKAY SO THEN I:
1. asked dragon where the fuck it was, because i wanted to see just what in tarnation was going on
2. he helpfully located it in npc_items_custom, and here is what it does:
 "modifier_stormcloth_bracer_effect"
            {
                "Passive"            "0"
                "IsHidden"            "0"
                "IsDebuff"            "1"
                "Attributes"        "MODIFIER_ATTRIBUTE_PERMANENT"
                "Properties"
                {
                    "MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE" "-50"
                    "MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE"    "-10"
                }
                "OnCreated"
                {
                    "AttachEffect"
                    {
                        "EffectName"        "particles/units/heroes/hero_invoker/stormblocth_bracer.vpcf"
                        "EffectAttachType"  "follow_origin"
                        "Target"            "TARGET"
                    }
                }

so it turns out, stormcloth bracer straight-up reduces ALL outgoing damage from affected targets. it does not modify the victim's attack damage stat in any way.

OKAY THEN, SUGGESTED COURSE OF ACTION:
1. here is stormcloth bracer's effect tooltip, emphasis mine:
"Enemies struck by @Ability2 lose 50% **attack damage** and 10% movement speed for 5 seconds."
2. just change the word "attack" to "outgoing" and you're done

UNLESS OF COURSE YOU MEANT FOR THE ITEM TO REDUCE ATTACK DAMAGE:
1. in which case, change the item's effect to match the description, instead of the other way around

**Comment by ChalkyBrush** [comment]
correct, it now reduces attack damage by 50%
