### ISSUE TITLE
Winterblight - SPIDER BOSS CRASHES (and torturok too)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#226]
[redfall winter.zip](https://github.com/ChalkyBrush/roshpit-bug-tracker/files/1566259/redfall.winter.zip)

**Comment by redledcat** [comment]
[spider boss tanari.zip](https://github.com/ChalkyBrush/roshpit-bug-tracker/files/1566312/spider.boss.tanari.zip)

**Comment by redledcat** [comment]
[torturok crash.zip](https://github.com/ChalkyBrush/roshpit-bug-tracker/files/1566323/torturok.crash.zip)

**Comment by redledcat** [comment]
[another tide in tanari.zip](https://github.com/ChalkyBrush/roshpit-bug-tracker/files/1566356/another.tide.in.tanari.zip)

**Comment by redledcat** [comment]
This one seems to not be critical atm, but there is an issue with particles

**Comment by ChalkyBrush** [comment]
well since they are out of the game right now I think this is fine. If it crashes when they show up in the new map reopen this
