### ISSUE TITLE
Local issue with roshpit.ca

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#23]
For me and several players all images on Roshpit.ca are unaviable because it's impossible for us to ping image hosted on s3-us-west-2.amazonaws.com.
That's not a big deal for me, images are not necessity, but heroes page has buttons based on image size, so simpliest way for me is add hero name in url, rather than trying to click on single pixel link.

![heroes](https://user-images.githubusercontent.com/32621322/31574371-f69b18ba-b0ce-11e7-8901-2581224c5248.png)
Other pages are technically usable.
![13132131qaa](https://user-images.githubusercontent.com/32621322/31574376-0a022d4e-b0cf-11e7-87ff-6087862a22f4.jpg)
![items](https://user-images.githubusercontent.com/32621322/31574393-48d9c2c0-b0cf-11e7-90c7-0d0d54eb132b.png)
Please, make buttons larger.

**Comment by redledcat** [comment]
and exactly the same issue with /players  pages, where all champions of player are

**Comment by StillStealSteel** [comment]
Try vpn please. Maybe something with your provider that blocks it. Don't think there something can be done.
@ChalkyBrush ? Close it?

**Comment by redledcat** [comment]
nah, vpn did not help. Changing browsers and providers and etc. It's actually bother about design of buttons rather than my connection.

**Comment by StillStealSteel** [comment]
Ye, maybe chalky needs to add some size for the buttons, and not to be dependent on size of image. Didn't understand you at first.

**Comment by bavibi** [comment]
I have the same issue, and vpn work for me.

**Comment by redledcat** [comment]
@bavibi what vpn do you use? 
also, a lot of errors for me appears in several browsers:
1)Explorer 
SEC7111: HTTPS security compromised http://cdn.steamcommunity.com/public/images/signinthroughsteam/sits_large_noborder.png
HTML1512 for several lines
HTML1503 on /heroes 5 1
2) Chrome and Opera
737990:47 Mixed Content: The page at 'https://www.roshpit.ca/players/207667482/heroes/737990' was loaded over HTTPS, but requested an insecure image 'http://cdn.steamcommunity.com/public/images/signinthroughsteam/sits_large_noborder.png'. This content should also be served over HTTPS.
3)TOR:
Your connection is not secure
The owner of www.roshpit.ca has configured their website improperly. To protect your information from being stolen, Tor Browser has not connected to this website.
www.roshpit.ca uses an invalid security certificate.
The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.
Error code: SEC_ERROR_UNKNOWN_ISSUER
(TOR browser with Canada circuit can load images, when certificate exception made (hurray), though it takes a minute to load each page)

**Comment by ChalkyBrush** [comment]
the SSL certificate expires in ~2 weeks so I have to set it up again. Will try to do it properly

**Comment by bavibi** [comment]
@redledcat I use friGate, extension for Google Chrome.

**Comment by redledcat** [comment]
@bavibi  thank you, frigate worked when I've made some exceptions for amazonaws and *.roshpit.ca
works perfect in Crome now

**Comment by ChalkyBrush** [comment]
I think SSL is properly configured now. Thanks for the reports

**Comment by bavibi** [comment]
Problem isn't solved for me

**Comment by bavibi** [comment]
Here i'm trying to connect to https://s3-us-west-2.amazonaws.com/roshpit-assets/heroes/axe.png
![screenshot_6](https://user-images.githubusercontent.com/15161630/32687365-a0ae03d2-c6cb-11e7-84ec-676f04b2dea8.png)
