### ISSUE TITLE
Drow W not benefitting from Yellow Ahn'qhir or Spellfire Gloves

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#230]
STEPS TO REPRODUCE:
1. equip either or both of those items on drow
2. get a bunch of w2
3. press W
4. observe that the rate of fire is not altered whatsoever by either item

SUGGESTED COURSE OF ACTION:
1. i understand that ahn'qhir would allow her to generate an ASTOUNDING and UNDESIRABLE number of particles, so i don't really know what to tell you. i know a particle limit on her w spell would remove too many arrows and the players wouldn't get useful visual feedback about the ability.
2. i also know that other people with multi-projectile w spells, like wolf MK, OD, and venomort with their respective "two more rays" immortal weapons can get an incredible rate of fire with these items, and that it doesn't significantly impact performance (and by that i mean it doesn't outright crash the server and/or cause people to lag out).
3. so your input on this is welcome

**Comment by redledcat** [comment]
Technically Split Shot has 0 cast point, so only changing ability from channel one to cast point (like Requiem of Souls of Shadow Fiend) would help here

**Comment by ChalkyBrush** [comment]
not bugs, you can no longer speed up W shot rate (80% would be too insane from spellfire, and 100% from ahnqhir would be TOO TOO insane)
