### ISSUE TITLE
Serengaard Sun Crystal trinket's %Elemental boost not displaying in stat popup

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#231]
STEPS TO REPRODUCE:
1. put on a Serengaard Sun Crystal
2. hover over your hero's portrait to bring up the stat popup
3. verify

SUGGESTED COURSE OF ACTION:
1. hopefully it's purely a display error and the item's %Elements is working normally

**Comment by ChalkyBrush** [comment]
actually it wasnt giving the elemental boost at all, I think I might have been asleep when this item was made
