### ISSUE TITLE
Fire Queen Staff pet has Fireball sub-ability but can never cast it

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#232]
STEPS TO REPRODUCE:
1. equip Fire Queen Staff on your CM
2. cast R once to summon the staff's pet
3. press your hotkey for "Select All Other Units" to view the pet
4. observe that the pet is spawned with 2,000 maximun mana, but that Fireball (its W spell) costs 6,000 mana at rank 7

SUGGESTED COURSE OF ACTION:
1. have it spawn with dramatically more maximum mana, as well as sufficient mana regen to sustain casting Fireball

**RELATED ISSUES:**
**1. it has Fireball even if your CM has 0 points in R1**

**Comment by ChalkyBrush** [comment]
this is fixed
