### ISSUE TITLE
Arcane Torrent not activating Q2 novas

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#233]
STEPS TO REPRODUCE:
1. put on CM's Q arcana hat
2. put on the Arcane Torrent glyph
3. toggle Arcane Torrent on
4. observe that Q2 will never activate

SUGGESTED COURSE OF ACTION:
1. Dragon swears up and down that Arcane Torrent - which he has repeatedly slaved over in an effort to improve it - should be activating Q2 novas "automatically" while toggled on

**Comment by ChalkyBrush** [comment]
fixed
