### ISSUE TITLE
Zhonik - E2 Green Streak revenants

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#235]
Damage from that rune dealt when revenant spotted instead when enemy comes to revenant.
Explosion from enemy in range/expire of 5 secons is visual and do not deal any damage.

**Comment by ChalkyBrush** [comment]
i dont understand what you're saying here

**Comment by redledcat** [comment]
@ChalkyBrush 
Сompletely forget about that thread.
I'll capture that for better explanation.
https://youtu.be/dtjqT_Gn3EE
Let's see what tooltip says and what actually happens.
Tooltip:
Every 360 distance moved during Lightspeed leaves a remnant that can explode after a 1 second delay if an enemy is within range. The remnant deals damage based on Zhonik's current mana. Explodes after 5 seconds if not detonated.
Reality:
Every 360 distance it leaves remnant, which explodes after 1 sec delay, but deals no damage instance in spot it have been placed. Instead that damage dealt around Zhonik, when remnant detonates.
I believe I improved my syntax for two and a half months.

**Comment by ChalkyBrush** [comment]
interesting nobody noticed this but you're right, the explosion happened over zonik's position and not the remnant's. fixed

**Comment by redledcat** [comment]
I guess rune itself is not attractive. It has low damage (no additional runes-amplifiers, no mana boost rune, very questionable lv90 glyph), low attack rate, depends on movement, needs enemies being kited to deal damage (instead of just facing them as many other abilities do), only source of temporal element it can use is lv 105 glyph (75% per w2 stack) and scales on mana (it means you must go for both int and mana items, leaving no survival for such a melee build, because you have to make close contacts with that rune).
Anyway, now it works as intended.
