### ISSUE TITLE
Chernobog [Q]Charon's Claw deals no listed damage

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#24]
![20171014123125_1](https://user-images.githubusercontent.com/32621322/31574605-5f75a3ba-b0d3-11e7-87d2-2650dd7f9285.jpg)
800/2800/7200/24000/80000/240000 is the damage of ability itself, right?

**Comment by redledcat** [comment]
Upd. It works without arcana. Q somehow based on R?
![20171014144722_1](https://user-images.githubusercontent.com/32621322/31575391-552afbb8-b0e6-11e7-8613-d33aeea2faa3.jpg)

**Comment by ChalkyBrush** [comment]
seems to work for me, what's going on here?

**Comment by redledcat** [comment]
It was bug which made Q to not deal instance of damage when arcana equipped.
I cant reproduce that now, but in october it was that way.
Seems to be fixed now.
