### ISSUE TITLE
Red Giant for some reason is unkillable in this setup 

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#243]
![20180101020322_1](https://user-images.githubusercontent.com/32621322/34464619-0569d472-ee90-11e7-811a-c34bcbffc30c.jpg)

**Comment by redledcat** [comment]
Probably Slark has issues with mega steadfast enemies

**Comment by ChalkyBrush** [comment]
slark + megasteadfast issue was fixed
