### ISSUE TITLE
SLIPFINN - actually not that extreme loop because of 10 attacks per second, but still OP

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#247]
1. E1 is base ability of E and attack modifier
2. Wind Deity triggered by base ability
...
3.Enjoy your inifinite power (and crashes)

**Comment by redledcat** [comment]
Thanks Ditto for testing while I'm alseep!

**Comment by redledcat** [comment]
~~(Also sorry for your wind crown died by that loop)~~

**Comment by ChalkyBrush** [comment]
fixed
