### ISSUE TITLE
Chernobog. W4 issue aka 0 hp.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#25]
I've never played before with W4 enough to meet that bug. All the victims of bug had W4 leveled.
Tested only on Crippling paragon effect, I dont know why other cases of that issue happen.
So, Crippling aura debuff with 1% negative HP regen and Ghost mace can lower your HP when you have your W Demon Hunter turned off.
Order of actions to reproduce: 1)Cherno with W4 leveled up, turned off Demon Hunter 2)Crippling paragon nearby, 3)Lower your HP to 1 with Shadow Hunt 4)Turn Demon Hunt on.
When W4 triggers from str to agi, Cherno loses HP, and that difference even on lvl 1 W4 is enough to surpass 1 hp to 0.

**Comment by redledcat** [comment]
w4 leveled up:
1 hp demon hunter off
![1 hp demon hunter off](https://user-images.githubusercontent.com/32621322/31574962-8bf89b6a-b0db-11e7-8042-2e1e29eb3e39.jpg)
1 hp demon hunter on
![1 hp demon hunter on](https://user-images.githubusercontent.com/32621322/31574964-90bb1916-b0db-11e7-8096-569a354e4c23.jpg)
 Now without w4 (and 20 str total)
![no negative regen when 1801 hp](https://user-images.githubusercontent.com/32621322/31574969-a068edac-b0db-11e7-9566-332eee21e926.jpg)
Now with additional str gained with potion, 184 str total, but toggling Demon Hunted does no bug.
![negative regen but demon hunter does not bug](https://user-images.githubusercontent.com/32621322/31574975-bbe191d8-b0db-11e7-8f33-d2781d34a65f.jpg)

**Comment by redledcat** [comment]
and now leveled up w4
![20171014131515_1](https://user-images.githubusercontent.com/32621322/31574983-e86f3bb0-b0db-11e7-934d-b19b0db3af52.jpg)
(Creeps are disappeared for no good reason also)

**Comment by redledcat** [comment]
I guess best solution is just change Crippling effect.
Wont fix other cases, though.

**Comment by StillStealSteel** [comment]
Did they really dissapear? Lol.

**Comment by ChalkyBrush** [comment]
![image](https://user-images.githubusercontent.com/5232984/31577816-6d55a574-b0e3-11e7-96aa-43926c759405.png)

**Comment by redledcat** [comment]
StillStealSteel,
yes every time, and that is not that hard to reproduce, bcs using Ruby in Redfall on legend (to have 3 affixes on paragon) almost certainly will spawn crippling paragon somewhere in forest. Cherno+W4+E4 to not being shotted while on 1 hp .
![20171014121813_1](https://user-images.githubusercontent.com/32621322/31577936-67f92a04-b117-11e7-95f7-1bfec23c5f1d.jpg)
![20171014121822_1](https://user-images.githubusercontent.com/32621322/31577937-681b7c3a-b117-11e7-8f00-dc0b6d995c3b.jpg)
like this.
More fun fact: if you toggle Demon Hunter fast enough all of them will disappear for half a second AND appear again XD.

**Comment by FortuneReborn** [comment]
This one was in the patchnotes, isn't it fixed?

**Comment by bavibi** [comment]
Did someone try to heal cherno with 0 health?

**Comment by redledcat** [comment]
Not fixed.
![20171108090826_1](https://user-images.githubusercontent.com/32621322/32533964-23268888-c45c-11e7-92fa-56c03efa2b3e.jpg)

**Comment by redledcat** [comment]
Just if I missed something:
1)In W disabled Cherno has negative regen, and do not die from it.
![20171108092648_1](https://user-images.githubusercontent.com/32621322/32534535-c09940c2-c45e-11e7-9ac2-08cacd1b6f05.jpg)
2)In W enabled Cherno has positive +1 regen for some reason and dies on W cast permanently
![20171108092650_1](https://user-images.githubusercontent.com/32621322/32534578-eb6da392-c45e-11e7-8ec1-5424a9a5f81e.jpg)
(After mobs despawned after death, regen become +37

**Comment by redledcat** [comment]
@bavibi, he always is in Demon Hunter and wont take any heal

**Comment by bavibi** [comment]
@redledcat But Chalky can try make him heal himself through enabled W if he has <0 health. I think so because his immo weapon can heal him even when W enabled.

**Comment by bavibi** [comment]
@ChalkyBrush Can you add attribute healing as an exception to W?
Whenever your max health increases you are healed to keep up you current percentage of health.
e.g. You have 100 current health and 200 max health, if your max health increases to 400, you are healed for 100. 
But Chernobog's W blocks this healing.

**Comment by ChalkyBrush** [comment]
should be fixed
