### ISSUE TITLE
MK Immortal Glyph not working on Ice Quill Carapace

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#250]
https://i.imgur.com/U0kMGyw.jpg

(to clarify: it should be adding Nature as an additional element to the damage, thereby making it Ice/Normal/Nature)

**Comment by ChalkyBrush** [comment]
changed tooltip to:
"All damage with primary element <font color=\"#DDDDDD\">Normal</font> has secondary element <font color=\"#69BC71\">Nature</font>."

SORRY!

**Comment by DeckardCainRPC** [comment]
oh

then me and some other guys (dragon, xhul'horac) humbly request you swap ice quill around from Ice/Normal to Normal/Ice, almost specifically for the benefit of bird MK, who really loves its new effect

**Comment by ChalkyBrush** [comment]
here's a 360 win


		"item_rpc_djanghor_glyph_5_a_description" 				"All damage with element <font color=\"#DDDDDD\">Normal</font> has its other element converted to <font color=\"#69BC71\">Nature</font>."
