### ISSUE TITLE
Slippfinn - Bad interaction with Tanari Wind Temple jumper vortex

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#253]
Slipfinn stucks in them

**Comment by redledcat** [comment]
That bug is not constant nor permanent

**Comment by redledcat** [comment]
![222222](https://user-images.githubusercontent.com/32621322/34520902-a034d6fa-f093-11e7-9b39-f40a940e3e03.PNG)

**Comment by ChalkyBrush** [comment]
should be fixed

**Comment by redledcat** [comment]
oh no it's not
