### ISSUE TITLE
Attack damage overflow

### ISSUE THREAD

**Issue by Solju** [ChalkyBrush/roshpit-bug-tracker#255]
If you get more than 2.17b attack damage items, runes and abilities based on attack damage stop working.
Item for example - https://www.roshpit.ca/items/item_rpc_dark_emissary_glove

**Comment by DeckardCainRPC** [comment]
That is a fundamental issue in computing called "integer underflow," and we're aware of it.

To fix it, we need to know what effects, items, abilities, or other methods you used to get 2.17b+ total attack damage.

**Comment by Solju** [comment]
For example you can get it on every hero with berserkers gloves. Other items and abilities just allow you to do it faster.

**Comment by redledcat** [comment]
someone, close it, please
