### ISSUE TITLE
Necro Q arcana server drops 

### ISSUE THREAD

**Issue by StillStealSteel** [ChalkyBrush/roshpit-bug-tracker#257]
When necro with frostvenom(maybe + geode too) uses Q on zombie model creeps at right side of sea fortress (after terrorblade miniboss and spectres). Server crashes.

**Comment by redledcat** [comment]
~Oh, these ones heals up every time they  someone heals nearby.~
Nevermind, I guess It's Q3 issue, transferring debuffs.

**Comment by StillStealSteel** [comment]
Ye, maybe Q3. 
Or maybe overheal from DECOY aura that they have. I'm playing with master's soul scythe so my heal is huge.

**Comment by redledcat** [comment]
OH that's the reason for sure, ticks are insanely fast

**Comment by StillStealSteel** [comment]
Bug is still there.

**Comment by redledcat** [comment]
Thanks to Dragon, it's fixed, Popups of healing were removed, and even if you use both Arkimus healing weapon and vampiric breastpate, attacking these zombies, nothing lags.
Veno weapon was changed.
Close please.
