### ISSUE TITLE
PARTICLES

### ISSUE THREAD

**Issue by StillStealSteel** [ChalkyBrush/roshpit-bug-tracker#259]
Please please please revise your attitude to 234234 of particles in this game.
Maybe beutiful map is improtant, but ENJOYABLE and playable map with noraml fps is better.

### Particles that cause huge lags (add in comments additional particles that you know)
- Geode especialy on axe and necro. This particle redundant overall - sounds pretty much enough.
- Stormcrack lightning bolts particles on W axe.
- Bahamut body arcana lightning bolts.

**Comment by redledcat** [comment]
HEY LABELS ARE BACK  
*sounds of satisfaction *

**Comment by StillStealSteel** [comment]
Ye dude was afk. And didn't play rpc for some time.
Sorry.

**Comment by ChalkyBrush** [comment]
reduced these 3 particles hopefully it helps
