### ISSUE TITLE
Red General's haircut. Intended or bug?

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#26]
![20171014020955_1](https://user-images.githubusercontent.com/32621322/31575012-db3e9ae8-b0dc-11e7-8f1a-42bfa31a1738.jpg)

**Comment by ChalkyBrush** [comment]
?

**Comment by StillStealSteel** [comment]
@ChalkyBrush Axe now has this white hair. For me actually too. In dota he has normal hair.

**Comment by hodor02** [comment]
It's totally intended. The Red General Immortal Axe you are wearing is called Rakash, Grandfather Axe. Hence the word "Grandfather". LOL

**Comment by redledcat** [comment]
Seems intended then
