### ISSUE TITLE
OD arcana Q2 says X instead of %

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#261]
Just tested OD's arcana Q2. My OD has Q2 at 37th level. Tooltip says, "0.37X for ever 10 base armor"
Target dummy has 1000 armor. So, it should be (1000/10 *0.37) 37X multiplier.
But the actual formula is 0.00001 *victim:GetPhysicalArmorBaseValue() *b_a_level.
So, it's (0.00001 *1000 *37) 0.37X multiplier.
Seems that it should be not X, but %.

**Comment by StillStealSteel** [comment]
Yeah,  it's a common problem for rpc. Part of runes, items, skills use percents some just X NUMBER. Seems like chalky thinks rpc isn't confusing enough. 
Some runes, items, skills use words like increased, enhanced, amplified that all can be post-mitigation or not (od w2 etc).
Some runes with increase or amplify just add to base ability power others multiplicative. So you never know how it works if you didn't test it.

**Comment by DeckardCainRPC** [comment]
i STRONGLY agree with StillStealSteel, a primary focus right now that would be of immeasurable benefit to the entire playerbase - and i'll definitely help you do this, i will be super enthusiastic to get this done - is to go through and make consistent language for all the effects in this game. the actual semantics used to describe effects needs to be accurate and consistent across all heroes and items.

**Comment by ChalkyBrush** [comment]
go ahead deckard 🗡 
:D

**Comment by StillStealSteel** [comment]
Was it changed? Because for me it's percents in tooltip.
Closed.
