### ISSUE TITLE
Drow T3 Glyph incorrect arrow count

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#264]
the glyph says it reduces each volley to a mere 5 arrows, but in fact she fires 9 per wave.

which is good. do not change that. just correct the glyph's tooltip.

**Comment by StillStealSteel** [comment]
It was changed by dragon with drow rework. And it supposed to fire 9 arrows now. Just wrong description. 
I even made PR for it, chalky didn't merge it for some reason.

**Comment by ChalkyBrush** [comment]
fixed
