### ISSUE TITLE
All sources of Ghost% add the same value to Undead%

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#265]
STEPS TO REPRODUCE:
1. add points to Duskbringer's R4
2. equip something with a little bit of STR
3. hover over your hero portrait to bring up the fancy stats panel

you will see that his R4 increases both Ghost *and* Undead damage by the same amount. this same thing occurs with sources of Ghost% from gear (Dark Emissary Gloves).

**Comment by ChalkyBrush** [comment]
FIXED ty
