### ISSUE TITLE
Slardar R1 does not reduce armor through glyphs R2 and R3

### ISSUE THREAD

**Issue by Buggestman** [ChalkyBrush/roshpit-bug-tracker#266]
The initial stomp does reduce the armor, but the Tsunami-Waves and the Poseidon's Fury do not.

There is a debuff being put on the enemies, the base debuff from Ocean Quake (attack slow and movement slow), but not the debuff from R1.

![20180106073719_1](https://user-images.githubusercontent.com/35161243/34637345-99d5e33a-f2b4-11e7-986a-3b7336609d1a.jpg)

**Comment by redledcat** [comment]
#158
#229

**Comment by StillStealSteel** [comment]
Duplicate.
