### ISSUE TITLE
Red general + chitinous lobster claw

### ISSUE THREAD

**Issue by StillStealSteel** [ChalkyBrush/roshpit-bug-tracker#267]
For some reason (i suppose it is because of E1, maybe i'm wrong) stacks of chitinous lobster claw decrising each second or so. You still can get 96 stacks, but seems like it takes more time and it visually jumps between 95 and 96 even if you don't take damage.

**Comment by Njol** [comment]
This is likely related to the fact that the claw loses stacks when you hover over your stats to check resistances (it loses 4 stack each time you do this). In particular, Red General's R4 checks resistances repeatedly which probably causes a stack to be lost.

**Comment by ChalkyBrush** [comment]
the hover effect was fixed
