### ISSUE TITLE
2 issues with Blacksmith's tablet and  Vermillion Dream Robes

### ISSUE THREAD

**Issue by ValKyle** [ChalkyBrush/roshpit-bug-tracker#269]
Somehow when you reroll Vermillion Dream Robes it will lock blacksmith
maybe it's because of tier 4 rune?

Blacksmith's tablet doesn't give 40% bonus stats and runes 
maybe if you could please add more EXP bonuses from 20% to 40% for purposely use to lvl up weapon

Thx> :D

**Comment by redledcat** [comment]
+  Blacksmith Tablet still has old description on market.

**Comment by ChalkyBrush** [comment]
fixed
