### ISSUE TITLE
Direwolf Bulwark locks the blacksmith

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#276]
STEPS TO REPRODUCE:
1. attempt to reroll a Direwolf Bulwark
2. this will fail
3. shrug, attempt to reroll something else, by dragging it to the blacksmith's UI
4. press Reroll

at this point, the blacksmith is now locked for the remainder of the game session. your item will not be rerolled (even if it was a valid, rerollable item).

**Comment by redledcat** [comment]
Exact same problem for Nobility lv2, and presumably for all of upgraded items

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush pinging you because it brings me $0.03 USD worth of glee every time i poke you

**Comment by DeckardCainRPC** [comment]
piss
