### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by ArcSklv** [ChalkyBrush/roshpit-bug-tracker#277]
_**When you log in to your account using RoshPit Steam - error.
Not ver password\login, but all right, what to do?**_Please, help.

**Comment by redledcat** [comment]
It's on the Valve's side. Nobody cant log in right now using that function, just wait when they fix that.

**Comment by redledcat** [comment]
Fixed!

**Comment by ChalkyBrush** [comment]
fixed by valve
