### ISSUE TITLE
Redrock Footwear applies 3x HP, but not 50% damage reduction

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#278]
STEPS TO REPRODUCE:
1. put on redrock footwear
2. E
3. hover over your hero's portrait to check out the swanky stat panel
4. observe that it says nothing about having 50% (more) DR.

**Comment by ChalkyBrush** [comment]
it was giving reduction but there was a tooltip error, now fixed
