### ISSUE TITLE
Roshpit vote for items bug

### ISSUE THREAD

**Issue by SatouPendragon** [ChalkyBrush/roshpit-bug-tracker#28]
![20171014160329_1](https://user-images.githubusercontent.com/32798007/31576815-0538a578-b0fb-11e7-935f-5f6428fe8996.jpg)
Beside that this bug blocks ui for new items(overlaping), players can't get some important items.
If there is wisp(not picked heroes by players) or leavers seems like chances of getting this bug incresed.

**Comment by ChalkyBrush** [comment]
it is hard to test this because I don't know how to simulated disconnected players.
I have made some changes in the code however by doing nil checkers on every object, so hopefully any crashes in the logic will be averted.

I won't mark this as closed, but hopefully next patch we see this occur less and then we can close

**Comment by redledcat** [comment]
Still happens. Just had couple of games with random items stuck. 
I want to add that most guaranteed reproduction of this issue from the very start of the game:
1)Having 3+ players, one of them disconnects and abandon the game in the difficulty choice  screen (Player which leaving should be connected in lobby, and only when team choise is aviable, he leave)
That occures permanent sticking of each immortal roll in queue.
2)Having 3+ players, one of them disconnects in the hero pick phase (being wisp).  He remains in vote as wisp.

**Comment by ChalkyBrush** [comment]
I haven't updated yet

**Comment by ChalkyBrush** [comment]
Update last night included the changes, anyone seen roll bug?

**Comment by redledcat** [comment]
Collected more info about second case (with disconnected wisp).
We also had 4th (picked and disconnected player)
So, every item got stuck in queue until wisp reconnected and **picked a hero**.
From now on all new items rolled in queue were fixed and was not stucking.
Some screens:
here he reconnected, but still on hero pick screen.
![20171017215921_1](https://user-images.githubusercontent.com/32621322/31685288-aacbe872-b382-11e7-9486-e8ff144d133e.jpg)
![20171017215926_1](https://user-images.githubusercontent.com/32621322/31685290-ac7db394-b382-11e7-9cb7-38801312a2af.jpg)
After that queue works normally:
![20171017220327_1](https://user-images.githubusercontent.com/32621322/31685359-f328902a-b382-11e7-9cf7-8c7f684de8ef.jpg)
He rolled that Yasha and Yasha's window disappeared.

**Comment by ChalkyBrush** [comment]
next patch has some more tinkering let me know how it goes

**Comment by redledcat** [comment]
Attention!
Randomly stuck items over time locked one of three queue slot, and then two of them!
I think that if we were not lucky, the roll queue would be completely inaccessible after the third jammed item.
![20171018130853_1](https://user-images.githubusercontent.com/32621322/31715927-19260540-b406-11e7-8556-765dde826846.jpg)
![20171018132807_1](https://user-images.githubusercontent.com/32621322/31715930-1d399f7a-b406-11e7-9d8e-5d229a07119c.jpg)
![20171018135704_1](https://user-images.githubusercontent.com/32621322/31715931-1f1a0474-b406-11e7-80fc-f936dccfc20d.jpg)
![20171018135752_1](https://user-images.githubusercontent.com/32621322/31715932-2091f9ce-b406-11e7-9704-e7b1fe3a93d2.jpg)

**Comment by redledcat** [comment]
https://images-ext-1.discordapp.net/external/d7WpGqxa2OG7cIHtDmssqtVW74ZlZsyENPHI1sQSczw/%3Fwidth%3D374%26height%3D498/https/media.discordapp.net/attachments/331554376181219350/481807234448490506/BpauIYYa8Cs.png
well there is a problem:
as you can see for some reason zeus won the roll on item despite it's 36 vs 83

**Comment by Nintai** [comment]
I think its fixed, should it reappear, someone will surely open a bug anyway
