### ISSUE TITLE
Djanghor - Scarf - main issues

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#281]
1) Equipping arcana in animal form makes monkey shapeshift impossible
2) R1 arcana rune works only on agility.  (by ASPlayers)
3) If  Djanghor shapeshifts out of beast form while having Feral Sprint buff, and then shapeshifts back, buff persists, but Legendary Charge being refreshed again. Does not occure additional bugs.
4)People keep reporting skillset gets bug somehow. (Rūrā - #bugs channel)

**Comment by ChalkyBrush** [comment]
fixed except #4, need more specificity anyway (new bug)
