### ISSUE TITLE
Sorceress - Glyph of Fire bolt does not fire 2nd and 3rd fireballs

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#283]

**Comment by redledcat** [comment]
Equipped items in case it works
![20180116171545_1](https://user-images.githubusercontent.com/32621322/34993307-a06e5bf6-fad8-11e7-8983-f7d111e5018f.jpg)

**Comment by ChalkyBrush** [comment]
fixed
