### ISSUE TITLE
Conjuror's E2-E4 interaction

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#289]
During my experimentations I came across this weird thing where E4 dealt less damage than E2.

After some calculations, I came to the conclusion that Base Ability damage bonus to E is added to E2 AFTER E4 takes E2's value into consideration.

**Comment by Xhulhorac** [comment]
After some more testing, it seems that E4 is not getting bonuses from Shadow damage amp, despite the tooltip stating it would OR the elemental amp as well is applied after E4's calculations.

**Comment by Xhulhorac** [comment]
![invoe2e4](https://user-images.githubusercontent.com/32672982/36258576-12b4d5e6-1253-11e8-9907-f0f9b7cbf9b3.png)

Bumping this because the issue completely ruins any possibilities of a Conjuror E-build.

**Comment by ChalkyBrush** [comment]
it's because it's not "BASE ABILITY DAMAGE" but added the flag
