### ISSUE TITLE
Hydroxis arcana tooltip typo (8 scale lvls instead of 7)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#29]
![1231232112312](https://user-images.githubusercontent.com/32621322/31578328-402e5442-b11f-11e7-9f69-125749393d07.PNG)
![20171014213435_1](https://user-images.githubusercontent.com/32621322/31578327-36b4f448-b11f-11e7-8b32-9cc33802b0ec.jpg)

**Comment by StillStealSteel** [comment]
This bug is from hydroxis arcana creation. I will fix it, thanks for remind it.
But it will have 71 res anyway. Because it is +4 per level.

**Comment by StillStealSteel** [comment]
Should be fixed in the next patch.
