### ISSUE TITLE
Arkimus Arcana Q3 DR% not reflected in stats panel

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#290]
STEPS TO REPRODUCE:
1. have arcana Q3 damage reduction stacks on your arkimus
2. hover over your hero portrait to bring up the swanky stats panel
3. observe that it doesn't display your percentile DR gain from Q3 at all

**Comment by DeckardCainRPC** [comment]
i'd say this is probably related to Redrock Footwear which was having the same issue until yesterday

**Comment by ChalkyBrush** [comment]
yes it is working but no showing in tooltip. fixed
