### ISSUE TITLE
EKKAN

### ISSUE THREAD

**Issue by Rusego** [ChalkyBrush/roshpit-bug-tracker#297]
![2](https://user-images.githubusercontent.com/35658653/35194930-50bc835c-feee-11e7-8be4-449144c77b37.jpg)
 With the hero something is wrong. The recruited minions do not do as much damage as they accumulate. At the normal level. All is well even the boss falls quickly. On the legendary. The minions have 120,000,000 physical damage. But removes 20000 damage from many mobs. Such an unpopular hero that even the developer was too lazy to check?) There is a passive Q3 for increasing the damage to minions when killing mobs. Damage accumulates huge but does not go into use. 
  If I beat the mob with minions. Begins to beat the player of this mob. That and he can not cause a lot of damage. and the mob dies for a very long time.
Damage is not calculated correctly. Suppose physical protection 95% damage should be 6kk from 120kk. But it's worth the perk STABILITY 3% for the creep which also buggy and does not work properly. From this, damage is reduced to 20k. At the same time, they beat all 7 minions. For whom such a perk set? The Archer kills this mob from one skill.

**Comment by redledcat** [comment]
Где баги, баги где?
Вижу только жалобы на перса, но в принципе согласен, без арканы - очень печально, играть сложно и медленно, ждем патча.
Что до физ урона на него вообще надеяться сложно, но как вариант можно юзать violet guard lv2 чтобы твои мобы сбивали броню мобам Q1.

**Comment by redledcat** [comment]
Ok that thread is mostly a complain about how much shit Ekkan is, can be closed.
Ekkan will be a flying creep until the end of times anyway.
