### ISSUE TITLE
Paladin non-arcana E1 es muy homo

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#298]
it "provides extra respawn immunity time" in the same way that being dead saves money on food and utilities. junk the current code and copy the functionality of phoenix emblem or something.

**Comment by redledcat** [comment]
Bump this. 
~It seems duration of "exxxtra immunity time" overlaps normal immunity after death~
It just does not work

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush penis

**Comment by DeckardCainRPC** [comment]
haha i wrote "penis"

**Comment by DeckardCainRPC** [comment]
shit

**Comment by DeckardCainRPC** [comment]
i didn't mean to close it lmao

**Comment by redledcat** [comment]
fixed

**Comment by DeckardCainRPC** [comment]
de nada
