### ISSUE TITLE
Arkimus immortal glyph

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#30]
if victim:HasModifier("modifier_arkimus_glyph_5_a") then
		if damagetype == DAMAGE_TYPE_MAGICAL or damagetype == DAMAGE_TYPE_PHYSICAL then
			filterTable["damage"] = Filters:ArkimusGlyph5a(victim, filterTable["damage"])
		end
	end
meanwhile description says:
Active Energy Cells absorb 1 instance of Magic or Pure damage and are subsequently destroyed."
And I was wondering why my ultimate cells being shedded by any enemy.

**Comment by StillStealSteel** [comment]
Will fix it.

**Comment by ChalkyBrush** [comment]
fixed for next patch
