### ISSUE TITLE
Djanghor - Scarf - Impossible to use ultimate and TP/flag spells

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#301]
If arcana  equipped in shapeshifted form (bear/wolf/bird) all channeling spells are uncastable.
I did not consider that serious bug but apparently 
http://steamcommunity.com/workshop/filedetails/discussion/469311655/1693785035826751576/
that guy had that issue (was in bear form in redfall farmlards where equipped arcana and that lead to impossibilty to tp back to base to unequip and unbug arcana)

**Comment by ChalkyBrush** [comment]
![image](https://user-images.githubusercontent.com/5232984/35604899-e951002c-0612-11e8-8df9-9f158a5a5a35.png)
I tried in every combination
