### ISSUE TITLE
Ice Quill Carapace memory leak when dying while active

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#302]
STEPS TO REPRODUCE:
1. get your Ice Quill stacks a-goin'
2. >Space created >Game is hard >Whoops >My bad
3. because it's handled by ITEM_UNIT, Ice Quill's spray will continue at your position while dead
4. repeat this a few times, and everybody will start to have latency issues
5. i am pretty sure that's what's happening, because i've done it several times with my bird MK; other people have also noticed that successive deaths while Ice Quilling causes gradual slowdown

SUGGESTED COURSE OF ACTION:
perform sorcery to make it stop on death. i think at one point you implemented this for Bladeslinger Boots? whether or not Valve has undone that fix in dota 2 updates, i do not know

**Comment by ChalkyBrush** [comment]
ice quill ends on death now
