### ISSUE TITLE
Elemental Warlord E4 tooltip misleading

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#303]
the tooltip indicates that all attributes increase Fire, Earth, and Ice damage. however, the actual effect of the rune is to increase Earth damage based on his STR, Fire damage based on his AGI, and Ice damage based on his INT.

this distinction is of critical importance to players

SUGGESTED COURSE OF ACTION:
either generalize the rune's effect so that it matches the tooltip, or be a big chicken fuckweasel and amend the tooltip so that it reflects the rune's actual effect. the reason why i don't suggest that second option is because it pigeonholes builds into using a single attribute, reducing build variety (on a hero who already only has "THE Arcana Build" and nothing else)

**Comment by bavibi** [comment]
if attacker.d_c_level then
                fireMult = fireMult + 0.0005*(attacker:GetStrength()+attacker:GetAgility()+attacker:GetIntellect())/10*attacker.d_c_level
            end

No, it increases all 3 elems by sum of all attributes

**Comment by DeckardCainRPC** [comment]
you are correct, but there is still something wrong, because when you check your attributes tooltip, you can see that Fire has a different value than Earth and Ice. see attached image:
![untitled](https://user-images.githubusercontent.com/34521754/35763468-d4d93fe6-087a-11e8-97b0-077be1e5dec2.png)

is the code for fireMult using the same value as earthMult and iceMult?

**Comment by bavibi** [comment]
Oh, somehow only fire damage was nerfed to 5%, ice and earth are still 6% per level,

**Comment by DeckardCainRPC** [comment]
thank you very much for your assistance!

**Comment by ChalkyBrush** [comment]
fixed (tooltip is 5 so ice and earth brought down to 5)
