### ISSUE TITLE
Slipfinn - W jumps in Redfall (?) always throw char to the right/ to the east of map

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#306]
https://youtu.be/E5fY18BrYaU

**Comment by redledcat** [comment]
*while issuing movement order while jumping, that's important

**Comment by redledcat** [comment]
yeah, sorry about VOD scale, I'm not quite common with OBS yet

**Comment by redledcat** [comment]
here we go, quality capture
https://youtu.be/UQT2Z6YjNB4
btw I did not tested in other maps, or did not noticed.

**Comment by ChalkyBrush** [comment]
i figured out the cause of this problem and i have it fixed for next patch
