### ISSUE TITLE
Slipfinn - my R timed out when I was dying, and it replaced with Release forever

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#307]
![20180125231213_1](https://user-images.githubusercontent.com/32621322/35410097-e6d5bc92-021c-11e8-8600-a3e96487f1e9.jpg)

**Comment by ChalkyBrush** [comment]
should be fixed now but not 100% sure, just comment here if its reported again and I'll reopen
