### ISSUE TITLE
Lobster Claw stacks decrease each time hero tooltip appears

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#312]
(It checks hero resists by dealing invisible instance of damage?)
https://youtu.be/Qo0E4YK-y24

**Comment by redledcat** [comment]
I think it decreases number of stacks by 3 each tooltip check

**Comment by DeckardCainRPC** [comment]
The Heisenberg Status Check: smacking your hero to record the results. RPC is the best game

**Comment by ChalkyBrush** [comment]
the secret is out :/
but there is a flag to not count as 'real damage', except lobster claw didnt get the memo.

Fixed for next patch
