### ISSUE TITLE
Reanimation Stone - Tooltip became a mess

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#313]
![20180128030050_1](https://user-images.githubusercontent.com/32621322/35477608-61ac7038-03cf-11e8-89f7-3f3003ef99ff.jpg)

**Comment by redledcat** [comment]
(when other consumables appear on market?)

**Comment by ChalkyBrush** [comment]
overwrote it :D 
yea I'll try to remember to add consumables to market (esp reanimation stone, others are trickier)
