### ISSUE TITLE
Arcane Torrent nonfunctional in recent update

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#319]
the graphical effects appear to be fine and working as intended, but it isn't actually dealing any damage instances whatsoever

**Comment by bavibi** [comment]
heroes\crystal_maiden\abilities\w\w_arcane_torrent line:30 says "damage" should be "arcane_explosion_damage"

**Comment by ChalkyBrush** [comment]
enjoying your complete solutions @bavibi 
I'm adding you as a collaborator on the official repo if you ever want to make a pull request, or review the code on github
all optional as what you are doing now is great
