### ISSUE TITLE
[feature request] Item damage, Evasion% in stats pop-up

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#324]
there's one space left at the bottom right of the Elements table for an Item icon (maybe just the word ITEM in a condensed font?) and i'm sure you can find a spot for evasion% somewhere

**Comment by StillStealSteel** [comment]
Bump.

**Comment by DeckardCainRPC** [comment]
gentlemen, the system works! 8 months later we got Item Damage%
