### ISSUE TITLE
Glyph of Emberstones isn't working with Rockfall

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#326]
Self-explanatory.
![glyphofemberstones](https://user-images.githubusercontent.com/32672982/35845526-83175dca-0b1b-11e8-9c22-2e525c4ebdd4.png)

**Comment by Xhulhorac** [comment]
Inscribed Sierra Blade isn't reducing the cooldown either.

**Comment by ChalkyBrush** [comment]
fixed
