### ISSUE TITLE
Thread of inescapable map sections and terrain where resources can be lost.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#33]
1)
![20171016191221_1](https://user-images.githubusercontent.com/32621322/31625258-b3fdab84-b2a5-11e7-8871-62ffc3ae6936.jpg)
![20171016191223_1](https://user-images.githubusercontent.com/32621322/31625259-b41e8fde-b2a5-11e7-958c-e41d653704f6.jpg)
2)Place near mob spawn where all drops incuding crystals can be lost.
![20171016192057_1](https://user-images.githubusercontent.com/32621322/31625260-b4421b02-b2a5-11e7-9f8a-13f5ce536da6.jpg)
3)
![20171016194856_1](https://user-images.githubusercontent.com/32621322/31625261-b4658718-b2a5-11e7-86ec-99f3d0a7c8fc.jpg)
4)Another spot with crystal loss (not sure if items can drop there)
![20171016211516_1](https://user-images.githubusercontent.com/32621322/31628028-a7e86104-b2af-11e7-97c9-38d948deb2ce.jpg)
5)Spot which player can drop by accidently jumping in there or with Drow's delayed E while teleporting.
![20171016211530_1](https://user-images.githubusercontent.com/32621322/31628154-1baa3d92-b2b0-11e7-8007-d77097065da3.jpg)
6)Still hard to escape from here.
![20171016211641_1](https://user-images.githubusercontent.com/32621322/31628214-4b4101c6-b2b0-11e7-99db-a527cf331e51.jpg)

**Comment by ChalkyBrush** [comment]
these are all fixed for next patch (except the deep pool in redfall, that's a trap for the unwary!)

**Comment by redledcat** [comment]
and another one
![20171028042036_1](https://user-images.githubusercontent.com/32621322/32129963-4560f4b8-bb8f-11e7-8849-44b9701ea3aa.jpg)
