### ISSUE TITLE
selfkilling with a Monkey paw/ Sturdy centaur horns.

### ISSUE THREAD

**Issue by malice1** [ChalkyBrush/roshpit-bug-tracker#338]
When i wear some ittems , like a Monkey paw/ Sturdy centaur horns, my paladin kill himself as u see on screenshot
"Paladin hit Paladin 45504432 dmg, using ability_datadriven."
may be some bug with paladins retrebution rune?
![image](https://user-images.githubusercontent.com/36329557/36061777-5af499cc-0e70-11e8-8be2-b8f333384579.png)

**Comment by redledcat** [comment]
Это Q3, и нет, это не баг, так и задумано.

**Comment by malice1** [comment]
redledcat, спасибо, просто в описании написано "противник разрушивший щит"
