### ISSUE TITLE
Solunia's Arcana Q1 damage%

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#34]
At 103 points, the tooltip says 309% attack damage. However, it only gives about 3%.
![q1bug](https://user-images.githubusercontent.com/32672982/31674693-1c359f66-b36b-11e7-89b7-c7a2ad463cff.png)

**Comment by ChalkyBrush** [comment]
Q1 increases attakc damage by % while the buff is active, not the comet damage

**Comment by StillStealSteel** [comment]
@ChalkyBrush look at his +attack damage.
I checked the code, and didn't find any suspicious lines for now.

**Comment by ChalkyBrush** [comment]
looks like Q1 isn't stacking, will fix tonight

**Comment by StillStealSteel** [comment]
`"MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE" "3"`
Should it be just `MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE`?

**Comment by ChalkyBrush** [comment]
Nope, Q1 doesn't give stacks based on rune level. It is essentially always LVL 1

**Comment by ChalkyBrush** [comment]
fixed for next patch
