### ISSUE TITLE
Solunia Arcana R2

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#341]
Arcana R2 dual burn doesn't work because "local b_d_level =  Runes:GetTotalRuneLevel(caster, 2, "b_d", "solunia")" sets b_d_level to 0 (supernova.lua line:152).

**Comment by ChalkyBrush** [comment]
nice, I've been trying to figure out this bug forever. Thank you

**Comment by redledcat** [comment]
Bavibi you are a mastermind :O

**Comment by ChalkyBrush** [comment]
Actually I don't see the bug here. line 152 seems fine. Where does it set it to 0?

**Comment by ChalkyBrush** [comment]
ohhh aracna r2, i get it :D fixed
