### ISSUE TITLE
Dragonwing Gauntlet bugs

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#342]
-W1 doesn't seem to work (dummy showed a ~10% increase in damage despite W1 stating 2800%).
-If you activate W immediately after deactivating it, you won't get the shield after 1.5 seconds.
-W3 and W4 show as Q3 and Q4.
-W's tooltip says that the manadrain is 10% of the activation's manacost (700 at lv7) per 0.1s, but it also shows a separate value for manadrain (500 at lv7). The actual drain seems to be the latter one. (simply removing the sentence about mana drain being 10% per 0,1s would suffice)
-Casting E allows you to move while W is active (I recommend keeping this function however since you can't attack in W anyway and W3 doesn't increase the range of W's flames)

On a side note, W's base damage is a mere 20000 and W's attack power multiplier is too low, considering that W3's scaling is awful. The arcana gives a nice tankiness but it really seems to lack damage.

**Comment by Xhulhorac** [comment]
Apparently W1 isn't its own multiplier, but simply Fire amp? Would explain the mere 10% increase. It would also mean that the rune is not worth investing into, considering how strong R4 is.

**Comment by ChalkyBrush** [comment]
-not bug
-hmmm
-fixed
-it makes sense, the tooltip says MANA DRAIN PER SECOND
-you think that's a freak accident?? :P (FEATURE!)
