### ISSUE TITLE
Vita's Spirit Scroll and Shadow Bind interaction

### ISSUE THREAD

**Issue by xypherenc** [ChalkyBrush/roshpit-bug-tracker#343]
Shadow Bind still goes on cooldown despite having Insight stack from Vita's Spirit Scroll. 

Also, Vita's Tooltip specifically mentions Shadow Bind (I guess that part is hooked with Q) but the buff only mention Heaven's Shield (more or less description typo but I will mention it anyway).

**Comment by ChalkyBrush** [comment]
fixed
