### ISSUE TITLE
[Perfomance] Djanghor's Rend and bleeding effect

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#344]
Monkey King Rend has terrible issues with perfomance, and should be particle-limited as hard as it possible.
Look at this gore and violence
![20180212204351_1](https://user-images.githubusercontent.com/32621322/36128849-1f3a39d8-106d-11e8-9ee3-6a0e52495fa0.jpg)
![20180212204255_1](https://user-images.githubusercontent.com/32621322/36128851-200b5fea-106d-11e8-8ea7-2e6a8c8a8b66.jpg)
The whole team dropping fps to 0 and if it meets pure resist, it goes even worse. Pure resist (#323) is another biggest trouble for long runs.
Also MK arcana has way too many particle effects even not taking Rend particles into account, it feels and represents as complete, chaotic particle cluster.
Pleace have mercy and fix both of these #323 and #344. That's totally in your power, not like random fps drops in arena and redfall.

**Comment by DeckardCainRPC** [comment]
bumping this because holy FUCK

**Comment by ChalkyBrush** [comment]
reduced soundlevel and added particle cap of (9 / 3s)

**Comment by redledcat** [comment]
MUCH BETTER
