### ISSUE TITLE
Is it ok? Feronia shield

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#345]
"modifier_feronia_shield"
			{
				"IsHidden"	"0"
				"IsBuff"	"1"
				"EffectName"	"particles/roshpit/items/feronia_shield.vpcf"
				"EffectAttachType"	"attach_hitloc"
				"Properties"
				{
					"MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE" "-100"
				}

**Comment by redledcat** [comment]
I cant confirm if that really has 100% reduction.
Update does not install and I cant jump into lava wearing Feronia.
Please still check it in case it's bugged

**Comment by ChalkyBrush** [comment]
fixed
