### ISSUE TITLE
Keys (and wind/fire/water essenses of Tanari) breaks Pool of Enernity

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#346]
Several reports are on steam page, and also I did tested it myself
![20180213140415_1](https://user-images.githubusercontent.com/32621322/36146775-69c5b968-10be-11e8-896f-a4816f1a597e.jpg)

**Comment by redledcat** [comment]
Time to add keys to the market?

**Comment by ChalkyBrush** [comment]
fixed
