### ISSUE TITLE
Feronia E shield blocks 100 % damage.

### ISSUE THREAD

**Issue by 1fmn1** [ChalkyBrush/roshpit-bug-tracker#349]
https://youtu.be/1S4bKREmWBM

On this video you can see E shield blocking 100% damage, while R shield only 95%. 

Update :https://www.youtube.com/watch?v=FGLl3FGOh9k watch this. Something wrong with Whirlwind, it used to block some amount of damage in the past, maybe it wasn't removed?

**Comment by 1fmn1** [comment]
![image](https://user-images.githubusercontent.com/17130245/36168381-96ef6360-1101-11e8-8cb2-3a00c13a07ce.png)
In case if it's not clear on a video u can easily use logs, I totally forgot about it. No hits before feronia goes off.

**Comment by ChalkyBrush** [comment]
damage logs are inaccurate

**Comment by 1fmn1** [comment]
I used lobster gautlets with same reduction I took damage on every hit. Do u think 95% +80% +50% which result in total 99.8% is enough to take 0! from morfling? It is not, you take above 100. And I even have raven Idol here. Other Axes run on 1900 hp taking absolutely no damage around the map with only 99,6%. Didn't you see on video that I take absolutely no damage in E for no reason?

**Comment by DeckardCainRPC** [comment]
the Dota 2 Combat Log is completely inaccurate. Roshpit Champions uses damage calculation steps that the Dota 2 Combat Log does not take before printing its information, so it is always inaccurate. please listen to the developer.

the game's tooltips also have some small rounding errors in the case of extreme values of damage resistance - for example, the "Black Leshrac" secret boss in Sea Fortress appears to have 100% Percentile Damage Reduction if you view his custom statistics tooltip (by hovering over his animated hero portrait), but in reality, he actually has something like 99.9999985% damage reduction (before defenses like Armor and Magic Resistance), but the game's graphical representation rounds up for simplicity, causing an inaccurate reading.

**Comment by 1fmn1** [comment]
I know that. It's not the main thing. I am trying to say that E Feronia for some reason has more resistance than it shows. Maybe it negates damage twice, 95% is not enough to make hp bar not moving at all.

**Comment by 1fmn1** [comment]
I hate you , guys.
https://www.youtube.com/watch?v=FGLl3FGOh9k
And don't look at the damage, I intensionally removed all the damage to demonstrate 100 % resist. In fact this build is the fastest clear of Sea map. He solo removes last boss from map before he gains first shield.

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush i do see one anomaly in the video this guy just posted - at the 0:32 timestamp, he mouses over the stats block, and it only shows the 95% DR from feronia, which is odd because it should also be factoring in the 80% DR from the Whirlwind state.

he is definitely correct that something unintended is going on. if you apply Feronia a second time while an instance of the buff already exists, is it providing additional instances of 95% DR that keep stacking on top of each other indefinitely?

**Comment by 1fmn1** [comment]
@DeckardCainRPC I have no E4 in that video. So I dont have these stacks. I have -100 % physical resistance from armor and 95 % phhysical block, getting damaged by tons of phys damage over 50 million a second.

**Comment by DeckardCainRPC** [comment]
whirlwind grants 80% DR while it's active, this is independent from E4

however i do agree with you that you should still be taking lethal damage even with those effects active, so this does need to be examined

**Comment by 1fmn1** [comment]
@DeckardCainRPC @ChalkyBrush Yes it is but it is not supposed to. It used to reduce damage by 80%, now it does not say so. Also it gives 100% reduction only in combo with feronia shield, but feronia can be seen in stats unlike wirlwind, so I think feronia reduces damage twice. 1st with old formula like wirlwind, 2nd with new one like all other stuff.

UPd: couldn't find anything else with direct "INCOMING_DAMAGE_PERCENTAGE" property. I belive it's only feronia and whirlwind additive dota formula modifier.  Everything else is calculated somewhere where I couldn't find.


![image](https://user-images.githubusercontent.com/17130245/36996340-4678a5d6-20bf-11e8-8539-bdd5ab0b2c60.png)

![image](https://user-images.githubusercontent.com/17130245/36996061-798cf338-20be-11e8-8358-e74ca9928515.png)
![image](https://user-images.githubusercontent.com/17130245/36996093-96d7722e-20be-11e8-91e2-1b35177d92fb.png)

**Comment by ChalkyBrush** [comment]
fixed

**Comment by redledcat** [comment]
and more news to the thread.
1) Axe has 80% reduction on E skill, which is not meant to exist. (lines 980-981 game_state)
2) Feronia shield applies twice due to lines 977-978 and 1099-1100 in game_state
