### ISSUE TITLE
Movespeed cap interaction

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#35]
Sonic boots increases ms cap to 750.
Shadow Hunt of Chernobog sets cap to lower value, even is "Sonic Speed" buff is active.

**Comment by StillStealSteel** [comment]
Checked the code, didn't find something wrong in it.

Can be some problem with dota itself, how it applies modifiers. If so then adding(interaction) speedcap modifiers should be explicitly written in the code.
Need help @ChalkyBrush

**Comment by redledcat** [comment]
tbh they are super useless and outdated, there is literally no reason to keep them in game in current state, because:
1)Do no shit against slows
2)Give you no damage amp or potencial to increase your outgoing damage (Zhonik actually has arcana which gives him much more, and also that 750 cap restricting him from making any further progress by e4 cap)
4)no runes
