### ISSUE TITLE
Conjuror improvement [High priority, cause I play it]

### ISSUE THREAD

**Issue by 1fmn1** [ChalkyBrush/roshpit-bug-tracker#350]
1. Aspects with Sphere of Avernia have only 5% SteadFast on all dificulty lvls. Make it 3 % on legend please. 
2. Conjuror arcana summon 3 % is too low, back in the days it was imposible to kill it because of hp pool and armor. Now hp is irrelevant, it dies to one solo dragon in Sea and cant facetank, a lot of enemies also have combinated attack with multiple instances with pure damage. Upgrade it to MegaSteadfast!
3. For some reason Pudges in sea oneshot a GOD OF ELEMENTALS. How is it even balanced. It's a GOD!
4. Conjuror arcana summon white damage 268kk cap is outdated. U can't kill a boss with such damage in sea. Please remove it. 
5.  Make E3 rune usable. Let it add "white damage" instead of "green". Currently E build is weak af. Thats why conjuror can't do anything to magic immune units. His non arcana build used to negate armor and pierce magic immune units with pure crits. Now he has no pure crits, and no phys damage. 
6. W2, W4  is weak.  It can be good is you swap positions of them and make W4 to stack WHITE damage.  Or just completely remove and replace with new concepts.
7. R runes used to be good back in my days. Now just sad, no reason to skill them.
8. Bring back immortality, I want fun gameplay as monkey king has.

**Comment by ChalkyBrush** [comment]
not bugs
