### ISSUE TITLE
0.1 fps and crash caused by hitting pure resist mobs serengaard Issue

### ISSUE THREAD

**Issue by 1fmn1** [ChalkyBrush/roshpit-bug-tracker#352]
![image](https://user-images.githubusercontent.com/17130245/36274273-d7e9b976-128f-11e8-974f-a397c2f3f6b5.png)
Literally 1 screenshot in 5 seconds game, everybody in my team and crash after some time. 
How to recreate: 
1. Have mass pure damage, equip echo gauntlet. (Maybe it's immolation effect with echo gauntlet).
2. Hit pure resist mobs.
Literally makes game unplayable.

**Comment by redledcat** [comment]
That mostly was fault of my build and, what is more important, PURE RESIST mobs.
I had here AM with watercrown and echo gloves, so each hit of R1 hits ~8 times ( I dont know why, it's how it works)
EACH of these hits procs Pure Resist particle effect.
#323 #344

**Comment by 1fmn1** [comment]
Don't blame yourself. I had pretty much same build and always experience this. First time playing with am in my team, never played with him before. First time 0.1 fps though, was at least 1.

**Comment by ChalkyBrush** [comment]
well pure resist has no particle now

**Comment by redledcat** [comment]
THAT'S THE VICTORY GUYS :champagne:
