### ISSUE TITLE
Arkimus Head Arcana + Base Ability damage% effect

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#357]
If I'm right line 75 in arcana_zap_field
Filters:TakeArgumentsAndApplyDamage(enemy, caster, damage, DAMAGE_TYPE_MAGICAL, 0, RPC_ELEMENT_ARCANE, RPC_ELEMENT_LIGHTNING)
should have 1 instead of 0 because it's Q skill and takes slot 1

**Comment by ChalkyBrush** [comment]
yes this is correct
