### ISSUE TITLE
[I WIN THE PRIZE] Placing a Respawn Flag while Trapper is in her Stealth state breaks her abilities

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#359]
for the remainder of the session

**Comment by DeckardCainRPC** [comment]
NB: she can't target herself with Backstab to correct the issue either

**Comment by redledcat** [comment]
@DeckardCainRPC 
I dont see anything broken, she just leaves invisibility, skillset remains normal and usable
There should be another trigger

**Comment by redledcat** [comment]
That broken skillset is the most mysterious bug atm
I've tested all kinds stealth interruption, including death while jumping E, death while charging Backstab.
My main suspect here is death while entering steath, or death in the moment skillset switches to the alternative.
I've managed to catch the bug which removes key binds, but still not sure if I'm right #354 #239

**Comment by DeckardCainRPC** [comment]
i was in a Sea Fortress run with... ProoF, I think, and he managed to do it to his own Trapper during that game. he said he did it by going into Stealth, then plating a respawn flag. is that not a consistent way to do it?

i DO know there are other ways to do it on accident, but like you said, this is the most mysterious bug. it happens under very obscure conditions, and always accidentally

**Comment by redledcat** [comment]
put another half of an hour in bug reproduction, got nothing.

**Comment by DeckardCainRPC** [comment]
this remains the most mysterious bug in RPC. one day, friends, we will track this down. but not today.

**Comment by redledcat** [comment]
Well, what we have right now is my thread #354 and the indisputable fact Boots of Destruction make you kill your team as well.
