### ISSUE TITLE
Arkimus - Glyph of Mana Shield

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#363]
Even if damage instance is absorbed, mana still consumes
![20180220225015_1](https://user-images.githubusercontent.com/32621322/36445931-5ee299ce-1688-11e8-8547-91de5de47e0d.jpg)
![20180220225016_1](https://user-images.githubusercontent.com/32621322/36445933-5ffc0890-1688-11e8-9ebc-8a4e90b71393.jpg)

**Comment by redledcat** [comment]
I know, mana shield effect comes before any mitigations, right?

**Comment by ChalkyBrush** [comment]
yea so it needs to be moved to final operation so this is in fact a bug (not fixed yet just commenting)

**Comment by ChalkyBrush** [comment]
fixed next patch
