### ISSUE TITLE
Massive Fire Deity explosions cause huge lags. The most laggy thing in the game.

### ISSUE THREAD

**Issue by 1fmn1** [ChalkyBrush/roshpit-bug-tracker#364]
Literally unplayable. Get w1 on invoker and Fire Deity, jump in mobs, that do not die instantly and you will get permanently frozen untill fire elemental or mobs die. Please fix.

**Comment by redledcat** [comment]
Bump this.
Most of combination of frequent W damage produces incredible lags.
Paladin's W1, Invoker's W1, arkimus W (that's just terrible).
Worst effect shows on clockwerk's cogs when attacked by arkimus
