### ISSUE TITLE
Drow Q2 not affected by ability power bonus.

### ISSUE THREAD

**Issue by 1fmn1** [ChalkyBrush/roshpit-bug-tracker#365]
https://www.youtube.com/watch?v=hZHjqvphBnc&feature=youtu.be

**Comment by redledcat** [comment]
code for normal Q2:
 Filters:TakeArgumentsAndApplyDamage(target, caster, pureDamage, DAMAGE_TYPE_PURE, baseAbilityFor, RPC_ELEMENT_COSMOS, RPC_ELEMENT_NONE)
Is that baseAbilityFor even mean anything?
should it be for arcana Q2:
if caster:HasModifier("modifier_astral_arcana1") then
slot = 1
?
and 0 for non-arcana?

**Comment by ChalkyBrush** [comment]
In the tooltip, her Q2 does not have base ability label either - this is because it is intended to be this way. If you think it's a balance issue, that is separate from bugs. 

Drow was made this way by Dragon and it was intentional

**Comment by redledcat** [comment]
you must have forgotten that arcana q2 now flagged as base ability for Q

**Comment by redledcat** [comment]
Update: 11 Dec, 2017 @ 5:41am
Astral Ranger
-Fix glyph of crescents
-Buff W base damage
-Buff W3 damage
-R3 damage increase
-Arcana Q2 now considered Base Ability
-Fix E4

**Comment by ChalkyBrush** [comment]
ok the code looks fine so I'll move the base ability check but it'll be in next patch

**Comment by ChalkyBrush** [comment]
actually i found bug, dragon never moved the code over to the new Q2

**Comment by ChalkyBrush** [comment]
yep def fixed for next patch
