### ISSUE TITLE
Duskbringer Wraithform(E4) and Glyph of Second Chances Interactions.

### ISSUE THREAD

**Issue by silenciaco** [ChalkyBrush/roshpit-bug-tracker#366]
1) E4 and Glyph of Second Chances both state the term allies. E4 works on everyone including Duskbringer, whereas the glyph works on everyone, EXCLUDING duskbringer. If this is intended, the wording should be changed on the glyph to avoid consistency issues.

2) The Wraithform(E4) is currently overwriting Ankh and World Tree Flower Cache atm. This is a source of grief to teammates that rely on those items. Even setting E4 to 0 points does not prevent this interaction atm. Something needs to change here. On the other hand, Phoenix Emblem is overwriting wraithform, preventing it from triggering at all. This happens even when the emblem is on cooldown, rendering E4 useless to heroes that use that trinket.

**Comment by ChalkyBrush** [comment]
fixed all these in the last patch
