### ISSUE TITLE
Dk hand arcana W4 bug

### ISSUE THREAD

**Issue by Theodrath** [ChalkyBrush/roshpit-bug-tracker#367]
1. 63 runes w4 24x agility to attack power is too low. Probably its a huge bug.
2. Hero does no dmg without geode. It is a proof that w4 needs huge buff

Optional
Buff or change e4 , it is kinda useless. Ty!

**Comment by Theodrath** [comment]
![its-huuuge](https://user-images.githubusercontent.com/36769849/36605904-62b44048-18c2-11e8-8948-76a20db40e58.jpg)

**Comment by ChalkyBrush** [comment]
![trumpavatar](https://user-images.githubusercontent.com/5232984/36611927-123c3716-18a3-11e8-88c1-bf55f61ee248.jpg)

**Comment by Theodrath** [comment]
![5440993294_8ce1bc6d9e_b-998x666](https://user-images.githubusercontent.com/36769849/36625194-58ec2ee6-191b-11e8-8308-3e66f7796715.jpg)

**Comment by ChalkyBrush** [comment]
a lil buff to W3
