### ISSUE TITLE
E4 Conjuror Bug, does not respect ability power.

### ISSUE THREAD

**Issue by 1fmn1** [ChalkyBrush/roshpit-bug-tracker#368]
![image](https://user-images.githubusercontent.com/17130245/36621598-7c889ca0-1901-11e8-96f1-28bd1cd24812.png)
E4 does not respect abilitypower because damage output of E4 is a Shadow, not Conjuror. However description says "Base ability: Shadow Gate". Need fix.
Haven't tested but pretty sure it also does not respect elemental power.

**Comment by crazybrain228** [comment]
Line 589 of heroes/invoker/aspects.lua
`function shadow_attack_strike(event)	
	local ability = event.ability

	local caster = event.caster
	  local damageTable = {
	    victim = event.target,
	    attacker = ability.attacker,
	    damage = ability.damage,
	    damage_type = DAMAGE_TYPE_PHYSICAL,
	  }
	  if ability.attacker:HasModifier("modifier_shadow_aspect_c_d_slow_attack") then
	  	apply_c_d_slow(ability.attacker, event.target, ability) 
	  end   
	  ApplyDamage(damageTable)
	  ApplyDamage({ victim = event.target, attacker = ability.attacker, damage = ability.pureDamage, damage_type = DAMAGE_TYPE_PURE})
end`
Uses ApplyDamage instead of Filters:TakeArgumentsAndApplyDamage and so doesn't include base Ability Damage. 
Proposed fix by someone who has no experience in lua programming:
`function shadow_attack_strike(event)	
	local ability = event.ability
	local caster = event.caster
	local shadowAspectAttacker = ability.attacker
	local conjurorAttacker = caster.conjuror
	local damage = ability.damage
	local pureDamage = ability.pureDamage
	local target = event.target

	if ability.attacker:HasModifier("modifier_shadow_aspect_c_d_slow_attack") then
		apply_c_d_slow(ability.attacker, event.target, ability)
	end
	Filters:TakeArgumentsAndApplyDamage(target, shadowAspectAttacker, damage, DAMAGE_TYPE_PHYSICAL, 0, RPC_ELEMENT_SHADOW, RPC_ELEMENT_NONE)
	Filters:TakeArgumentsAndApplyDamage(target, conjurorAttacker, pureDamage, DAMAGE_TYPE_PURE, 3, RPC_ELEMENT_SHADOW, RPC_ELEMENT_NONE)
end`
Tweak and fix as needed. I don't know lua XD

**Comment by crazybrain228** [comment]
Line 589 of heroes/invoker/aspects.lua
`function shadow_attack_strike(event)	
	local ability = event.ability
	local caster = event.caster
	  local damageTable = {
	    victim = event.target,
	    attacker = ability.attacker,
	    damage = ability.damage,
	    damage_type = DAMAGE_TYPE_PHYSICAL,
	  }
	  if ability.attacker:HasModifier("modifier_shadow_aspect_c_d_slow_attack") then
	  	apply_c_d_slow(ability.attacker, event.target, ability) 
	  end   
	  ApplyDamage(damageTable)
	  ApplyDamage({ victim = event.target, attacker = ability.attacker, damage = ability.pureDamage, damage_type = DAMAGE_TYPE_PURE})
end`
Uses ApplyDamage instead of Filters:TakeArgumentsAndApplyDamage and so doesn't include base Ability Damage. 
Proposed fix by someone who has no experience in lua programming:

`function shadow_attack_strike(event)	
	local ability = event.ability
	local caster = event.caster
	local shadowAspectAttacker = ability.attacker
	local conjurorAttacker = caster.conjuror
	local damage = ability.damage
	local pureDamage = ability.pureDamage
	local target = event.target
	if ability.attacker:HasModifier("modifier_shadow_aspect_c_d_slow_attack") then
		apply_c_d_slow(ability.attacker, event.target, ability)
	end
	Filters:TakeArgumentsAndApplyDamage(target, shadowAspectAttacker, damage, DAMAGE_TYPE_PHYSICAL, 0, RPC_ELEMENT_SHADOW, RPC_ELEMENT_NONE)
	Filters:TakeArgumentsAndApplyDamage(target, conjurorAttacker, pureDamage, DAMAGE_TYPE_PURE, 3, RPC_ELEMENT_SHADOW, RPC_ELEMENT_NONE)
end`
Tweak and fix as needed. I don't know lua XD

**Comment by crazybrain228** [comment]
Line 589 of heroes/invoker/aspects.lua

```
function shadow_attack_strike(event)	
local ability = event.ability
	local caster = event.caster
	  local damageTable = {
	    victim = event.target,
	    attacker = ability.attacker,
	    damage = ability.damage,
	    damage_type = DAMAGE_TYPE_PHYSICAL,
	  }
	  if ability.attacker:HasModifier("modifier_shadow_aspect_c_d_slow_attack") then
	  	apply_c_d_slow(ability.attacker, event.target, ability) 
	  end   
	  ApplyDamage(damageTable)
	  ApplyDamage({ victim = event.target, attacker = ability.attacker, damage = ability.pureDamage, damage_type = DAMAGE_TYPE_PURE})
end
```

Uses ApplyDamage instead of Filters:TakeArgumentsAndApplyDamage and so doesn't include base Ability Damage. 
Proposed fix by someone who has no experience in lua programming:

```
function shadow_attack_strike(event)	
	local ability = event.ability
	local caster = event.caster
	local shadowAspectAttacker = ability.attacker
	local conjurorAttacker = caster.conjuror
	local damage = ability.damage
	local pureDamage = ability.pureDamage
	local target = event.target
	if ability.attacker:HasModifier("modifier_shadow_aspect_c_d_slow_attack") then
		apply_c_d_slow(ability.attacker, event.target, ability)
	end
	Filters:TakeArgumentsAndApplyDamage(target, shadowAspectAttacker, damage, DAMAGE_TYPE_PHYSICAL, 0, RPC_ELEMENT_SHADOW, RPC_ELEMENT_NONE)
	Filters:TakeArgumentsAndApplyDamage(target, conjurorAttacker, pureDamage, DAMAGE_TYPE_PURE, 3, RPC_ELEMENT_SHADOW, RPC_ELEMENT_NONE)
end
```

Tweak and fix as needed. I don't know lua XD
