### ISSUE TITLE
Duskbringer's "cleanse" Glyph malfunctioning

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#369]
i'm talking about the Glyph of the Wraith

check to make sure that 1) its effect is actually being applied, 2) its effect is actually working, 3) that it's being restored to Duskbringer whenever he respawns, and 4) that it isn't being interfered with by one of his other conditions

i say this because i've been playing a lot of duskbringer recently and i've noticed that this glyph either has no function, or is liable to completely stop functioning at some point over the course of the game

i reported this on one prior occasion but i manually closed the ticket, after second-guessing myself. now i'm leaning back more towards "yeah something's not right"

**Comment by ChalkyBrush** [comment]
fixed
