### ISSUE TITLE
Tanuri jungle water temple bug

### ISSUE THREAD

**Issue by mustdrop** [ChalkyBrush/roshpit-bug-tracker#37]
when i was go to the last place in the water temple the golden statue seem missing ...
![image](https://user-images.githubusercontent.com/7087267/31737487-e214c66a-b471-11e7-9245-13025359f2f0.png)

**Comment by StillStealSteel** [comment]
Never happens to me. I think this kind of bug required at least some logs to attempt to fix it. 
Need confirmation if someone else had this bug. 
If you can apply more info.

**Comment by ChalkyBrush** [comment]
if you skip walls and activate triggers before the game is ready, nothing will spawn. I assume that is what happened here
