### ISSUE TITLE
Arena Razor guards permastunning again

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#371]
you know the drill:

1. hop on over to the arena and start Pit of Trials
2. get your idiot ass tased by the Razors while the game state is changing to Pit, despawning all of the arena NPCs
3. the stun applied to you is now permanent. plead with your allies to kite something into you and allow it to end your suffering.

this is one of the oldest recurring bugs, like a staph infection in our first teddy bear. i have lost track of how many times you've fixed it, only for it to return

**Comment by redledcat** [comment]
#136 
plz fix

**Comment by 1fmn1** [comment]
It can be easily fixed by adding suicide command. It also fixes many other issues. You can be permastunned if your survivability is better than enemy damage almost everywhere. Please do this, we don't want to suffer anymore! Let us die.

**Comment by redledcat** [comment]
is it fixed actully? Tried twice so far, and my teammate did not stuck (damn)

**Comment by ChalkyBrush** [comment]
is this actually fixed? can I close this shit? 

tbh I've tried to fix this many times so maybe it was an engine bug the whole time?? 🤔

**Comment by ChalkyBrush** [comment]
alright im closing this until someone sees it again :D

**Comment by redledcat** [comment]
I've got lucky and 2, ehm, "testers" entered my game.
BOTH are permastunned, also I've captured rare link particle bug to 0;0.
What a day!
![20180321112709_1](https://user-images.githubusercontent.com/32621322/37699991-9c40e868-2cf2-11e8-8b50-1135c10f5297.jpg)
![20180321112801_1](https://user-images.githubusercontent.com/32621322/37700003-a44d18ec-2cf2-11e8-8b8c-c8f2cb7f5d6a.jpg)
![20180321112807_1](https://user-images.githubusercontent.com/32621322/37700004-a5f6e4de-2cf2-11e8-9583-ffb67a238a66.jpg)
![20180321112859_1](https://user-images.githubusercontent.com/32621322/37700023-b6225258-2cf2-11e8-8dc7-ba92c9dbb979.jpg)

**Comment by redledcat** [comment]
btw, LC entered a little bit (~1s) after when I've actually opened pit of trials, and still got stuck
