### ISSUE TITLE
[Sephyr] Venomous Gale particle

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#373]
Is that really supposed to be here?
https://youtu.be/kV9YLJ01hlc

**Comment by ChalkyBrush** [comment]
how to recreate this?

**Comment by redledcat** [comment]
Well, I'll put some time investigating this.

**Comment by redledcat** [comment]
Solved!
Put your video settings Effects Quality from "high" to "med" or "low".
It starts to spawn that gale particle.

**Comment by redledcat** [comment]
Probably there are more of those hidden particles which load our videocards?

**Comment by ChalkyBrush** [comment]
wow good find, and no to your last comment, its very specific to this
