### ISSUE TITLE
Chernobog body arcana attack speed and range dispelled by tanari wind spirit.

### ISSUE THREAD

**Issue by jxlah** [ChalkyBrush/roshpit-bug-tracker#376]
When you get knocked up by the tornado, you end up with 0.21 attack speed + 150 attack range rather than 0.11 + 850 attack range. This persists until you recast your ultimate. Note: R runes still works just that the attack speed and attack range is bugged.

**Comment by redledcat** [comment]
it cleanses most of shapeshift abilities and a lot of buffs
#199

**Comment by ChalkyBrush** [comment]
fixed
