### ISSUE TITLE
Paladin Arcana (Oathkeeper) W4 bug

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#38]
There is a very crippling bug with Paladin's Arcana Gloves. His W doesn't bounce correctly. 
If I have 20 points in W4, it is supposed to bounce twice, so if I self-cast it near one monster, it will hit me, go to that monster and then back to me. As intended.
If I then self-cast again, it won't bounce at all. No matter how often I try.
If I then cast it on the enemy, it will go to the enemy, to me, and back to the enemy, as it should, casting on the enemy again won't do anything, same thing as selfcasting multiple times in a row.
Conclusion: If you cast W on the target that was hit by ANOTHER W which hasn't hit anything since, it won't bounce. This happens a LOT. In a 1v1, you have to alternate between casting on the enemy and yourself, which is a huge pain, and it seriously limits its usability.

**Comment by ChalkyBrush** [comment]
fixed for next patch
