### ISSUE TITLE
[Sephyr] [SERVER CRASH] Nefali DR% causes summoned pets to resist "expiration timer" self-damage

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#380]
R's percentile damage reduction aura causes summoned units to strongly resist their
"expiration timer" self-damage, making them immortal. this is most obvious with
the Wolfir Druid Spirit Helm, and after summoning about 50 wolves, the server
will reliably crash, always, 100% of the time, do not pass go, do not collect $200

SUGGESTED COURSE OF ACTION:

whereas having permanent pets is marginally helpful, considering how much pets
suck today due to the fact they haven't been touched in almost a year, it's easy
to accidentally crash a server doing this even if you're not trying to - you can be
aware of this issue, and try to keep only ~48 wolves active at a time... but as soon
as 49 and 50 show up, you can spoil the entire run in an instant.

**Comment by ChalkyBrush** [comment]
fixed
