### ISSUE TITLE
[Sephyr] Push effects from W and E not activating Giant Hunter's Boots BKB

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#381]
the push effects from W and E's repositioning don't activate Giant Hunter BKB :(

(i acknowledge that this is probably deliberate, but it still makes me sad. Paladin and Arkimus and many other heroes have very similar directional push effects which DO activate Giant Hunter, so i thought MAYBE if i reported it...)

**Comment by ChalkyBrush** [comment]
intended, because there is no associated root effect
