### ISSUE TITLE
[Sephyr] Dying may cause active Flurry Pucks to hang indefinitely

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#383]
dying while a Flurry Puck is active can potentially lead to the puck lingering
forever, hovering uselessly wherever this glitch occurred. this may be dependent
upon having the +1 Concurrent Puck glyph, or the Emerald Skyblade immortal
weapon, but i am not positive

**Comment by DeckardCainRPC** [comment]
additional info: pucks can hang no matter how alive or dead you are. i believe pucks might hang when they attempt to move toward and damage a unit which dies before it arrives?

**Comment by ChalkyBrush** [comment]
FIXED
