### ISSUE TITLE
[Sephyr] Start an Arena fight with his E toggled on and facing anywhere but East and see what happens

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#388]
it is maximum humor. i honestly think this should be considered a feature, and the benefit of this is that you don't have to wrack your brain thinking of a way to fix it

**Comment by redledcat** [comment]
![20180228152453_1](https://user-images.githubusercontent.com/32621322/36787621-7038a19e-1c93-11e8-9771-cac57ad36db0.jpg)
![20180228152449_1](https://user-images.githubusercontent.com/32621322/36787629-76e990e8-1c93-11e8-83a2-83178dd1e233.jpg)
Creepy

**Comment by DeckardCainRPC** [comment]
so majestic

**Comment by DeckardCainRPC** [comment]
i have decided this is a feature
