### ISSUE TITLE
Talents can be chosen for disconnected players; some talents are OP

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#390]
STEPS TO REPRODUCE:

1. have a player disconnect. his selected hero must be level 119 or lower
2. level his hero up until he reaches a level that is a multiple of 5, at which point a spell can be ranked up one level. because the hero is disconnected, this causes shit to become FUBAR for whatever reason - you may assign any of his hero's available spell points into the Talent Tree while you've got his hero left-clicked.

3. one of Outworld Devourer's level 10 talents, at the very bottom of the tree, is 15% Spell Lifesteal. unexpectedly, this actually does work, having exactly the same effect as it does in normal Dota 2 matches, including activating the Octarine Core particle effect on the hero every time health is restored from the effect.

because Epoch Guardian is still, narrowly, capable of dealing enough damage to heal himself for over 2.14 billion HP, he is capable of doing a variety of absurd shit through the use of this glitch.

do note however that it doesn't appear to be possible to assign spell points into a *connected* player's Talent Tree, which is good

**Comment by DeckardCainRPC** [comment]
i suspect that some heroes may have valid Talent data in the current version because, when Talents were first released, you briefly dicked around with them for a few hours, couldn't think of a way to implement them yet, then shelved the idea and moved on. the majority of the entries in Talent lists simply state "name_#" as an empty placeholder...

**Comment by Tantalass** [comment]
i saw some other rpg custom maps have their own bonus in talents. mb try somth?) make some from old/new glyphs in this tree

**Comment by DeckardCainRPC** [comment]
arfenhouse rules
