### ISSUE TITLE
[Sephyr] Being in E toggled on + UI boards on Arena has bad interaction

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#393]
UI continously being opening and closing multiple times a second, producing lags.
Not really critical but when you accidently touch donate board game freezes.

**Comment by 1fmn1** [comment]
On every map with any UI things. ex. Redfall Ember exp quest.

**Comment by ChalkyBrush** [comment]
FOUND A WORKAROUND AND FULLY FIXED FOR ALL TRIGGERS
