### ISSUE TITLE
Water Mage Robes deal no damage, and cause any monsters slowed by it to become immune to all damage

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#397]
Still Alive: I finally got water mage robes. They're bugged and not only do no damage, but prevent any unit affected by them from taking damage.

**Comment by ChalkyBrush** [comment]
i just tested and its working fine, this requires more info

**Comment by DeckardCainRPC** [comment]
thank you, i'll insist on having Still Alive post here

**Comment by ChalkyBrush** [comment]
closing this until this has more reports or more info

**Comment by ChalkyBrush** [comment]
![image](https://user-images.githubusercontent.com/5232984/36823666-398c44e6-1ccc-11e8-9ee0-9030b3717e73.png)

**Comment by ChalkyBrush** [comment]
fixed finally

**Comment by redledcat** [comment]
https://youtu.be/DE7sF1JDF8w

**Comment by redledcat** [comment]
@ChalkyBrush bump

**Comment by redledcat** [comment]
bump? reopen?

**Comment by redledcat** [comment]
I can actually explain what happens here.
1) First wave deals damage and applies debuff, and every wave after just reapplies debuff of slow and post-mitigation damage. 
2) Robe's debuff makes targets 100% immune to damage while it's active
every target which can tank single water wave will be immortal for next several second.
what an item!

**Comment by redledcat** [comment]
(You have to test it on steadfast, I suppose. If creeps dies to wave №1 it looks like it's fine)

**Comment by ChalkyBrush** [comment]
fixed
