### ISSUE TITLE
[Sephyr] Sephyr usability improvements

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#399]
i've seen a couple people express RAGE and FRUSTRATION with some aspects of Sephyr, and i've experienced them a little myself, so here's a trio of bullet points to consider that would solve the issues and put this hero's neat gimmick where you want it to be:

**1. Issuing a new move command while in E will abort the current move and start a new one.**

i've noticed that, while playing this positioning-critical hero, i can't reposition myself dynamically because he insists on executing the first order fully before accepting any others. this is not how people control their heroes in Dota - they spam click and have 590,000 APM as they juke/chase through trees and uphill. this is naturally also true in RPC, and i can personally understand how people will get frustrated when they issue an order that their hero ignores, like they're taunted at the exact X/Y coordinates they rightclicked a second ago.

**2. Give the player a visual indication of the number of E1 Pucks they have available. For example, you could give Sephyr floating green Invoker orbs, one for each available Puck (0 by default, 1 with any points in E1, +1 for the T1 Glyph, and +3 for the Emerald Skyblade Immortal weapon). A simple buff counting available Pucks will not be sufficient, since E2's method of operation ensures that Sephyr only ever has E2 instances on his buff bar, and can't see anything else.**

this is a very important point, and ties in with the above somewhat: if you issue an attack command, and you don't have any more Pucks available, *you will fucking sit there with your dick in your hand instead,* almost universally resulting in an unheroic death. this is especially true if you're trying to click around when the screen is full of badguys, items cluttering the floor, or as is most often the case, both.

as an additional measure, of course, just having a visual indication that the hero has no Pucks to give is not FULLY addressing the problem... because even then, you can still click around trying to move, or attack, or do anything besides sit there and get owned. so what i recommend as a second step to solving this issue, is make it so that Sephyr will perform his "retreat" away from the attacked unit *regardless* of whether or not he has a Puck available to throw. THAT would be fucking MAGICAL and people would shower you with ribbons and kisses.

**3. Give the player a visual indication of the range at which Sephyr can meaningfully issue autoattack commands during E.**

this is the third and final RAGE-INDUCING element; you click on a monster 620 units away, only to find out that he has to be within 615 for Sephyr to throw a fucking Puck at him. this is exactly as infuriating as calling a customer support line at 6:58PM just before the day shift clocks out, meaning they are invariably going to ignore your problem, blow you off, forward you to another department, pack their shit and run to their car as fast as they can.

anyway i don't think this issue is very difficult to solve, especially if the E1 range is static (and by that i mean, it isn't affected by modifying Sephyr's attack range, via Helm of the Iron Colossus, Super Ascendency Mask, or Epsilon's Eyeglass). you can just make it so that E has a faint green windy laser circle or some fuck. i don't think it would be too obtrusive to make it visible to all connected players, either, especially in light of how little anyone gives a shit when Seinaru's Duelist Rings are everywhere.

**Comment by ChalkyBrush** [comment]
1. Committing to your strafe position is intended :/
2. Done, and the part about retreat movement even if no pucks to throw
3. Range of E1 can be seen by hovering over strafe (vermillion dream robe extends the range but it does not reflect on this circle)

**Comment by DeckardCainRPC** [comment]
thanks for giving this a read, i'm happy for the changes and i look forward to seeing less bitching about it. i'll keep you posted
