### ISSUE TITLE
Djanghor-Wolf's Rend doesn't pierce Spell Immunity with Sabertooth Daibo Immortal

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#40]
Rend (Wolf-W) pierces spell immunity, but no longer does so when equipping the immortal. 
It might be intended this way, but it seems more like an oversight than anything. Admitting it as a bug.

**Comment by ChalkyBrush** [comment]
It was intentional but I hear it a lot so I'm caving, it hits magic immune enemies now
