### ISSUE TITLE
going to low health with golden skullbone in a possession bubble permanently changes slipfinn's model

### ISSUE THREAD

**Issue by ChalkyBrush** [ChalkyBrush/roshpit-bug-tracker#400]
^

**Comment by redledcat** [comment]
~~did not experienced that nor in serengaard neither in arena, maybe it depends on dying while possesing the mob, which is the most weak part~~
nevermind, it definetely works this way
![20180302115623_1](https://user-images.githubusercontent.com/32621322/36890923-77e4697a-1e08-11e8-90f6-472f102296ae.jpg)
beautiful

**Comment by redledcat** [comment]
hahaha, that's so funny!
https://youtu.be/vNnbatGEi1Y

**Comment by DeckardCainRPC** [comment]
FEATURE

**Comment by crazybrain228** [comment]
For some reason line 267 of heroes/slark/bubble_possession.lua doesnt prevent the adding of the golden skullbone ai, which then causes the model change when slark's health reaches <40% (ai/desert_ruins/desert_ruins.lua - line 501). Fun. Could maybe change line 503 (ai/desert_ruins/desert_ruins.lua)  from 

`if caster:GetHealth() < caster:GetMaxHealth()*0.4 and not caster:HasModifier("modifier_golden_skullbone_injured") then 
`
to
`if caster:GetHealth() < caster:GetMaxHealth()*0.4 and not caster:HasModifier("modifier_golden_skullbone_injured") and not caster:GetUnitName() == "npc_dota_hero_slark" then`

Idk if you can actually check names like that in lua dota.

**Comment by ChalkyBrush** [comment]
fixed next patch
