### ISSUE TITLE
Game is weird (Dota patch 7.10)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#401]
![20180301232449_1](https://user-images.githubusercontent.com/32621322/36867917-64971f20-1d9f-11e8-96e4-031694f83b82.jpg)
![20180301232451_1](https://user-images.githubusercontent.com/32621322/36867921-65819140-1d9f-11e8-9f32-c4c8ccbee383.jpg)

**Comment by redledcat** [comment]
Hero has sudden strike cooldown, fervor and other stuff from cherno (in buff panel)
+and random items modifiers

**Comment by redledcat** [comment]
hell.
![20180301234126_1](https://user-images.githubusercontent.com/32621322/36868895-6ac28396-1da2-11e8-953b-7633d2da99f7.jpg)
![20180301234633_1](https://user-images.githubusercontent.com/32621322/36868900-6e9ccf62-1da2-11e8-89f3-0dff425c2ca4.jpg)

**Comment by redledcat** [comment]
Probably it's just serengaard or it's self-fixed. I dont know, and I dont any time to test further due to sleep deprivation.

**Comment by ChalkyBrush** [comment]
did this TOTAL MESS fix itself? Haven't seen any other reports

**Comment by redledcat** [comment]
ok so far I did not seen any issues while playing
closing.

**Comment by ChalkyBrush** [comment]
thank RNGesus
