### ISSUE TITLE
Xp bounty for certain creatures is dramatically tiny. Intended?

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#402]
I mention only super insignificant values for certain types of enemies, such as minibosses and just powerful mobs. I dont know if you made it that low intentionally or just copied unit template and _forgot about XP_. 
1. fire_temple_siege_hulker
big warlock golem in the end of middle tp path in fire spirit zone
 "BountyXP" "12"
2. Wind spirit **boss**
 "wind_temple_spirit_boss"
 "BountyXP" "0"
3. "tanari_water_spirit_boss"
 "BountyXP" "0"
4. "flamerider_gorthos" quite a big guy guarding entrance to fire spirit spawners.
"BountyXP" "60"
5. One of the most irritating mobs, pudges with "chain hook"
"serengaard_hook_flinger" 
"BountyXP" "18"
6. "redfall_soul_scar"
rubicks with fade bolts in redfall.
"BountyXP" "95"
(at the meantime crimsith mages have 3875 and 5875 for elite version )
7.  redfall_snarlroot_treant
One of the most dangerous enemies on normal difficulty, treant with giant attack damage, slow and vision loss, also Steadfast. Unfair as life.
"BountyXP"  "240"
8. "redfall_ashen_treant" 
It's technically miniboss which even has it's own item to summon it and has it's own special drop
"BountyXP"  "240"
9. "water_temple_boss"
really?
"BountyXP" "95"
10.  "siege_dragon"
These Jakiros from world_1 have spawn both in redfall spawners and serengaard. XP number looks like a joke, even if they are not really strong.
"BountyXP" "12"
11. "arena_lies_arbiter_of_truth"
that's a statue of golden antimage
"BountyXP" "18"

**Comment by ChalkyBrush** [comment]
bosses dont award XP
fixed the others
