### ISSUE TITLE
solunia arcana r2 wrong dmg calculation 

### ISSUE THREAD

**Issue by Tantalass** [ChalkyBrush/roshpit-bug-tracker#403]
arcane cascade hat, again i not agree with dmg calculation ) R2 arcana solunia make final dmg from final item dmg, but its not work how it must be
![screenshot_11](https://user-images.githubusercontent.com/36903932/36925298-e8edbea6-1e7a-11e8-8258-d52ac24e3f93.jpg)

**Comment by redledcat** [comment]
#224 ??

**Comment by Tantalass** [comment]
not, just staying arround i changed glyphs for ele dmg. and end-dmg from r2 have wrong calculation - because in description its saying what deal dmg based on  what dmg item was deal!!! so it must increase x3.5 times aswell, but this doesnt happened.!!!
