### ISSUE TITLE
Silverspring Gloves and Cobalt Serenity Ring do not combine their passives correctly

### ISSUE THREAD

**Issue by Destroya1103** [ChalkyBrush/roshpit-bug-tracker#406]
Silverspring: "Your Attack Power is increased by 1000% of your Health Regen stat."
Cobalt Serenity: "Health Regen is increased by 800% of Intelligence."

Are these intended to work together?

The Health Regen is calculating correctly, it seems, but it's not working with the gloves.

Thank you.

- Destroya

**Comment by DeckardCainRPC** [comment]
uh, i just tested it, and it's working fine. sephyr's q1 and those two items let him sit at around 9 million base attack damage, even with no stacks of e2.

post a link to your build, i'll look at it to see if there's another item causing problems

**Comment by DeckardCainRPC** [comment]
here, just for the sake of completeness, i confirmed that these two items, as well as Rooted Feet, are all interacting together correctly:

![untitled](https://user-images.githubusercontent.com/34521754/37106928-020b61fc-2201-11e8-8b74-675f78206443.png)

**Comment by ChalkyBrush** [comment]
seems i can close this then

**Comment by DeckardCainRPC** [comment]
well if he's got something else equipped that's fucking something up, i'd kind of like to see it, both out of curiosity and out of a misguided sense of thoroughness

**Comment by ChalkyBrush** [comment]
he can post in a closed bug, and then I can reopen it if there's a problem

**Comment by Destroya1103** [comment]
http://prntscr.com/io629n

I was originally using Sange boots, I switched over to Rooted Feet just now.
Int*8 = 297,424 * 3 = 892,272 (Current HP Regen is 902,880)
