### ISSUE TITLE
Djanghor Glyph Bug Sea Encounter

### ISSUE THREAD

**Issue by Theodrath** [ChalkyBrush/roshpit-bug-tracker#408]
1.In sea, after dual victory(right side Legion Commander encounter) Djanghor`s glyph of animal acoustics *reduce cd of Q by 3 seconds , stops working.
2. Further info: Arcana chest was equipped.

**Comment by redledcat** [comment]
Glyph of Acoustics sometimes just randomly stops to work for me. It's hard to notice mostly.
These randomly occured breaks also do not work with Q3.

**Comment by redledcat** [comment]
Also: duel victory prevents Q3 to sustain Dark Reef helm buff duration
