### ISSUE TITLE
Serengard Sun Crystall

### ISSUE THREAD

**Issue by MonsterCrabb** [ChalkyBrush/roshpit-bug-tracker#410]
Serengard sun crystall all elem dmg amplification doesent work (dot give any dmg and also not shown at hero description window) tested on training dummy twice in a different games.
![image](https://user-images.githubusercontent.com/37240786/37241662-03517906-246e-11e8-81e8-99ffea381160.png)
![image](https://user-images.githubusercontent.com/37240786/37241683-35929aa8-246e-11e8-9d0f-4ece091c5989.png)

**Comment by redledcat** [comment]
check valdun helm too

**Comment by MonsterCrabb** [comment]
Valdun helm works properly 
![image](https://user-images.githubusercontent.com/37240786/37269295-d1f7b9c4-25da-11e8-957b-b5f82bc8809a.png)

**Comment by ChalkyBrush** [comment]
fixed
