### ISSUE TITLE
Arkimus W cooldown goes more than 2 mins with mask of phantom sorcerer

### ISSUE THREAD

**Issue by venosbringer** [ChalkyBrush/roshpit-bug-tracker#412]
when mana runs out w automatic toggle off then W go CD more than 1 mins, I already test it 5 times and still do the same when he runs out of mana while W still on

![arkimus bug](https://user-images.githubusercontent.com/37253258/37247241-0ce2cf8e-246d-11e8-9b7f-5ec9874addb5.png)

**Comment by venosbringer** [comment]
update... it's not when out of mana... but, now whenever he hits with W still on, everytime the attack landed it will add 4 more seconds to cooldown
![arkimus bug 1](https://user-images.githubusercontent.com/37253258/37251837-26deb5e2-24cc-11e8-8ca5-5a831d82424b.png)

**Comment by ChalkyBrush** [comment]
phantom sorcerer adds 4 seconds to W cooldown whenever it is 'cast', so sadly for arkimus this is intended :(

**Comment by ChalkyBrush** [comment]
(astral ranger also cries over this)
