### ISSUE TITLE
[BUG] Axe Feronia gives double reduction effect. Axe E still reduces damage by 80 %.

### ISSUE THREAD

**Issue by 1fmn1** [ChalkyBrush/roshpit-bug-tracker#413]
Feronia now gives double resistance (twice 95%), 
Axe E still reduces damage by 80% mention it in description, or remove.
![image](https://user-images.githubusercontent.com/17130245/37252292-83508bce-2527-11e8-8b28-ea74fec81097.png)

**Comment by ChalkyBrush** [comment]
fixed
