### ISSUE TITLE
Blacksmith eats gear if there is no empty slot in inventory

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#414]
eats when rerolled with full inventory
mentioned in #96 
still needs to be fixed

**Comment by redledcat** [comment]
HAHAHAHA!!
I found out if your inventory is full and you try to reroll an item THAT BURSTS ON A LIGHTSPEED to item unit somewhere on the map.

**Comment by redledcat** [comment]
sadly, cant capture that right now, but I'm just throwed 8 pairs of harvester boots to the farmlands in red ridge

**Comment by ChalkyBrush** [comment]
fixed
