### ISSUE TITLE
[Dota+] Redfall Ground Triggers

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#423]
Redfall
~~spawn scripts are broken (one creep camp works in redfall, just to the right)~~
~~gold for creep kills does not count~~ gold is okay, just no more sound and effect, wait what
~~**Gold sound is missing**~~
~~dummy lost it's model~~ rip

**Comment by redledcat** [comment]
~~Buttons in sea fort are broken~~

**Comment by redledcat** [comment]
~~Teleporter to farmlands does not work in redfall~~

**Comment by redledcat** [comment]
Arena:
~~arena NPC do not interact with player~~
~~boards are broken (donate one and leaderboard)~~
~water elemental mini-game dialog broken~~

**Comment by redledcat** [comment]
~~arena match board is broken~
~~colour puzzle before pit is broken
presumable, pit board is broken too~~

**Comment by ChalkyBrush** [comment]
All ground triggers are broken

**Comment by redledcat** [comment]
Monkey king becomes "naked" after shifting out of arcana year beast form (shifted several times changing mark, and he got his clothes back)

**Comment by ChalkyBrush** [comment]
<img width="993" alt="screen shot 2018-03-12 at 1 54 18 pm" src="https://user-images.githubusercontent.com/5232984/37300687-f6302c5a-25fc-11e8-9eab-88b6a0b2a839.png">

**Comment by ChalkyBrush** [comment]
<img width="963" alt="screen shot 2018-03-12 at 1 56 18 pm" src="https://user-images.githubusercontent.com/5232984/37300785-3ec3e52e-25fd-11e8-8c08-7453689c6fe7.png">

**Comment by redledcat** [comment]
~~also it seems arcane crystals stopped to collect while mithril is collecting normally
number +n on counter never adds to your arcane crystals value~~
I'm wrong, it's ok

**Comment by venosbringer** [comment]
one of tree in redfall near dummy didnt trigger's mobs 
![redfall tree](https://user-images.githubusercontent.com/37253258/37331472-46e86888-2661-11e8-8ec7-14963cad5e48.png)

**Comment by redledcat** [comment]
![20180314001432_1](https://user-images.githubusercontent.com/32621322/37370304-70809536-2714-11e8-9eef-8a7dd7c32339.jpg)
broken

**Comment by ChalkyBrush** [comment]
ok I get that some triggers dont fire but need more info

**Comment by ChalkyBrush** [comment]
sometimes people initiate that fight just fine...

**Comment by redledcat** [comment]
My paladin was in BKB state when approaching sadist. I should try that again tomorrow.
And also he was in midair bcs I've rushed in that room like SWAT.

**Comment by ChalkyBrush** [comment]
I think you may have nailed it then

**Comment by ChalkyBrush** [comment]
Try using a magic  immune hero, walking north of tanari camp and see if
weavers spawn

**Comment by redledcat** [comment]
Okay. but it will be last thing I do today. Also I had no issues with vermillion trees using pala
upd. works perfectly. tanari ambusm, weavers, everything

**Comment by redledcat** [comment]
Silver Fangs also reported of Axe breaking interaction. Axe's E has stun cleaning is it?


Среда, 14 марта 2018, 1:27 +03:00 от Ryan Racioppo <notifications@github.com>:
>Try using a magic  immune hero, walking north of tanari camp and see if
>weavers spawn
>

**Comment by ChalkyBrush** [comment]
pushing an update that changes trigger areas back to what they were before (valve fixed them today)
we'll see if it fixes

**Comment by ChalkyBrush** [comment]
seems that it's still going, thanks dota PLUS
not sure how to fix atm

**Comment by redledcat** [comment]
Well, I've tested Redfall with Paladin arcana boots.
Everything seems fine.

**Comment by redledcat** [comment]
EXCEPT my pc BSOD and died when I did it so I'm out of roshpit for s.d.

**Comment by redledcat** [comment]
Well still a lot of reports, and no good idea why it breaks. 
My only thought are Giant Hunter boots, which were next in queue.

**Comment by ChalkyBrush** [comment]
i think this is fixed now
