### ISSUE TITLE
Bahamut Q spell dinosaur code

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#426]
hooray for archaeology!

**1. Wall duration does not always match the particle effect. This problem appears to be exacerbated by any of the following items: Glyph of +2 wall duration, the Immortal Weapon which gives a free cast of Q every 4 seconds ("Origin Rune"), and Q Mask of Ahn'qhir.**

when attempting to reproduce this, take note of when the wall damages enemies, and/or the rate at which it applies Q1 stacks. also note that the discrepancy can go either way, temporally speaking - i occasionally see walls "expire" yet they still continue to deal damage at their location, howsoever briefly; and i've also seen walls suddenly stop working a second or two before they visually disappear.

**2. Q1's tooltip doesn't adequately explain what it does. It doesn't mention the 600-stack limit on the mana buff, nor does it convey to the user that the mana buff even needs to stack up first.**

better tooltip: "Standing next to a summoned @Ability_1 restores mana every 0.1 seconds, and increases Bahamut's maximum mana pool by the same amount. The maximum mana boost stacks up to 600 times."

then i think rephrasing the two descriptors underneath would be appropriate:
"Mana per tick:" (has finer resolution than "mana per second")
"Maximum mana increase at 600 stacks:" (this clarifies that, at 200 Q1, you don't get tens of millions of maximum mana, lol; it's simply telling you what the full bonus is at max stacks)

these are small but important changes that should help users understand what the rune actually does a little better

**Comment by redledcat** [comment]
#285

**Comment by DeckardCainRPC** [comment]
mr gorbachev, tear down my ass
