### ISSUE TITLE
Proud Gloves don't proc at all

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#428]
I can guarantee that it's not just the 3% proc chance. I used Drow with Boots of Great Fortune, 67 R4 and Fortune's Talisman of Truth and I got no procs whatsoever. I switched to Midas afterwards, which started proccing immediately.

**Comment by redledcat** [comment]
I've though there is something wrong with proc chance, ty for posting

**Comment by DeckardCainRPC** [comment]
i am pretending that Proud Gloves stopped working because there's no more Kappa Pride in the universe

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush **EMERGENCY**

**Comment by redledcat** [comment]
effect was changed
