### ISSUE TITLE
Paladin's Arcana W (Penance) is completely broken. Major bug.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#43]
The old bug got resolved, it now bounces correctly, but at some point (it happened to in 2 minutes for me) your W will no longer cast, you will do animation, spend mana, but no lance will come, it won't proc W2 and that means that you can't play, this is a major bug.

**Comment by ChalkyBrush** [comment]
fixed before I go to work 😄
