### ISSUE TITLE
Monkey Paw spends money even if it's not enough to generate an item.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#431]
![20180318114154_1](https://user-images.githubusercontent.com/32621322/37564182-44b0e1b2-2a99-11e8-8690-1f50667ba2df.jpg)
![20180318114157_1](https://user-images.githubusercontent.com/32621322/37564183-4530aeb0-2a99-11e8-88a2-3707b190b56c.jpg)

**Comment by ChalkyBrush** [comment]
fixed
