### ISSUE TITLE
[Math] Tachion Shell Q4 reduction

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#432]
![dave](https://user-images.githubusercontent.com/32621322/37564283-33c9a15c-2a9b-11e8-9725-21755541f209.PNG)
math says on 20 runes it is
(1-20*0.005) = 0.9 which is correct, 10% reduction on 20 runes
but
1149 gamestate says
reduction = reduction/2, which makes 0.9 reduction 0.45 reduction, 55% reduction on 20 runes.
on 1 rune it will be 50.25% because (1-0.005)/2=0.5025
reduction = 1-(1-reduction)*2 should fix the problem

**Comment by redledcat** [comment]
Though, there is downside - Zhonick is defenseless even with that bugged q4, remaining melee-type hero in most cases.
Issue with disappearing arcana E should be fixed, and several survivabiliy improvement should be made.
Really, hero which designed to punch everything and roll into groups of enemies forced to play as safe as he can.

**Comment by GoToNightmare** [comment]
Fixed.

**Comment by redledcat** [comment]
wonderful
