### ISSUE TITLE
[Ground Event]  That particular vermillion tree is not functioning properly

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#437]
![unknown 1](https://user-images.githubusercontent.com/32621322/37817774-a8b94696-2e80-11e8-8fd7-c725137388be.png)
![unknown](https://user-images.githubusercontent.com/32621322/37817776-aa2f022c-2e80-11e8-885e-154254d7aa58.png)

**Comment by redledcat** [comment]
I have not found cause so far, and it works properly for most of the heroes

**Comment by ChalkyBrush** [comment]
should be fixed
