### ISSUE TITLE
Paladin's Arcana W (Penance) still has issues.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#44]
Replication steps: Go to a training dummy, have some distance between you and it, repeatedly cast W on it, never hit it.
If you so much as start the cast of a new W, every old W stops doing anything. They won't hit, proc attacks, proc W2 or bounce. This is, of course, crippling. Suddenly you deal no damage, get no healing, no damage prevention stacks from Q3 and you're likely to die.

**Comment by FortuneReborn** [comment]
For clarification, I was testing whether the old bugs were resolved and I spammed W, noticing that if you had too many going on, your W went on cooldown.
Later, that didn't happen, but the new bug kicked in.
Both states are annoying, though maybe the first state is intended?

**Comment by ChalkyBrush** [comment]
should be fixed
