### ISSUE TITLE
Aurora's Touch W4 works exactly once per game session and never again

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#447]
courtesy of King:
"[11:44 PM] King: Cain I found a huge bug with drow arcana w4
In the very first target of your game it works just once and then you switch to another target and the buff disappears forever and doesn’t reset, and after that drow cannot get any w4 for the rest of the game"

**Comment by DeckardCainRPC** [comment]
oh the arcana is fucking cool as fuck, by the way. it is in that sweet spot where new stuff should be, "useful and different without being absurdly overpowered"

**Comment by ChalkyBrush** [comment]
fixed
