### ISSUE TITLE
Curated database losing item info

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#448]
Aphotic Dominion Helm missing Q2 and Q4 first line, Q4 bottom line
https://www.roshpit.ca/items/item_rpc_ekkan_arcana1
Giveaway arcana was Q2 and Q4, and I've curated it myself a while ago.
I've just curated W4 oathkeepers which I alredy curated before.
Helm of Molten knight Q3 which was my first arcana I've got - missing. 
There are a lot of same items which missing info for no reason.
Every time you saying translation bugs are fixed, and they shouldn't affect base, but that's what I see.
I would not worry and would not accent that problem if that wouldnt affect market search.
I'll try to call community to help, but i'm not sure it wont aggravate the problem

**Comment by ChalkyBrush** [comment]
its because you curate it on a russian client
only curating in english works. Data isnt disappearing

**Comment by redledcat** [comment]
I never played roshpit on russian translation
At least curator part

**Comment by redledcat** [comment]
Well, anyway, I've put a full list of missing arcana properties. If any of these will be curated and disappear in future, it will be confirmed.
