### ISSUE TITLE
Omega Ruby STILL turns Slipfinn's E1 into Fire damage

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#449]
![slarke1bug](https://user-images.githubusercontent.com/32672982/38031567-0aa69aa8-328b-11e8-80eb-304131655862.png)

The image was taken today

**Comment by DeckardCainRPC** [comment]
confirmed

**Comment by redledcat** [comment]
That's interesting.
I thought that could works the same for Divine Purity glove, and it does:
![screenshot-178](https://user-images.githubusercontent.com/32621322/38084326-b999dcde-334c-11e8-8acb-6b798ddcc387.jpg)
But check this out, last instance dealing via wind deity is shadow

**Comment by redledcat** [comment]
purity glove + wind deity
https://youtu.be/rtadXW6J8MQ

**Comment by redledcat** [comment]
Isn't that just visual?

**Comment by DeckardCainRPC** [comment]
i don't think it's just visual, because this doesn't happen on any other hero with similar effects

**Comment by Xhulhorac** [comment]
It seems to be visual. E1's damage was the same as Shadow and as Fire, with no added E1 from Ruby. If it wasn't visual, it should've been lower due to Slipfinn's innate Shadow amp.

**Comment by redledcat** [comment]
fixed
