### ISSUE TITLE
Spirit Warrior 1 HP 

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#45]
I've managed to reproduce it.
I looked in that reddit report
https://www.reddit.com/r/roshpit/comments/6fy1vs/my_spirit_warrior_is_stuck_at_one_hp_all_the_time/
And fresh steam report
![3922](https://user-images.githubusercontent.com/32621322/31783976-6e91d98c-b500-11e7-91c3-e3f102f475fd.PNG) 
The thing which causes bug is Arbor Dragonfly.
In the end of R1 buff Dragonfly effect trying to prolongate the heal and drops HP to 1 permanently.
Skill/itemset:
![20171019201409_1](https://user-images.githubusercontent.com/32621322/31784381-c45eea52-b501-11e7-9529-8421f91707fc.jpg)
![20171019201411_1](https://user-images.githubusercontent.com/32621322/31784387-c7042ac4-b501-11e7-8617-45438958fc50.jpg)
![20171019201417_1](https://user-images.githubusercontent.com/32621322/31784403-d3669734-b501-11e7-85af-c8ab79e59e00.jpg)

**Comment by ChalkyBrush** [comment]
wow great find, you managed to isolate the culprit!

👍 

will fix asap

**Comment by ChalkyBrush** [comment]
fixed for next patch, nice work
