### ISSUE TITLE
[Trapper][Tooltip] Items which use dynamic line for "R" Stealth and Backstab shows this

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#453]
![20180329170358_1](https://user-images.githubusercontent.com/32621322/38093396-1c3c26da-336b-11e8-952c-78936685a3a2.jpg)
![20180329170400_1](https://user-images.githubusercontent.com/32621322/38093397-1ce4afee-336b-11e8-8282-a88ad002629e.jpg)

**Comment by ChalkyBrush** [comment]
fixed
