### ISSUE TITLE
Vermillion Dream Robe reroll often shows "Cannot be rerolled" ???

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#459]
![20180402011908_1](https://user-images.githubusercontent.com/32621322/38178101-c2a814be-360b-11e8-8927-8fc71cdf5bb3.jpg)

**Comment by redledcat** [comment]
Also that one NEVER rolled me a T4 rune, if that rolls T1-T2 everything is fine

**Comment by redledcat** [comment]
#269

**Comment by bavibi** [comment]
function RPCItems:SetPropertyValues(item, propertyValue, propertyName, propertyColor, propertyNumber)

line:3004 RPCItems:SetPropertyValues(item, item.property2, "rune", "#7DFF12",  4)
should be 2, not 4. Don't know if that's what breaks reroll.

**Comment by ChalkyBrush** [comment]
bavibi has nailed it, also why it never rolls the t4 rune. fixed for next patch
