### ISSUE TITLE
Drow's W costs mana multiple times.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#46]
Whenever you cast your W, you spend your mana, then you lose mana for every volley you shoot, including the first one (0 points in W2).
You don't require the extra mana to shoot, you'll just go to 0.

**Comment by FortuneReborn** [comment]
By the way, the amount you lose every volley is not identical to the cost. It's a greater number.

**Comment by redledcat** [comment]
Dragon said, yes, it will be fixed later, reaching 0 mana will stop W2 procs. But now W build will take a huge punch, because there is no way to keep up that mana regen

**Comment by ChalkyBrush** [comment]
i dont think this is a bug
