### ISSUE TITLE
Stats panel only shows bonus mana from INT, and no other sources

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#463]
![untitled](https://user-images.githubusercontent.com/34521754/38412791-216254c0-3958-11e8-9318-0ed051357bed.png)
suffice it to say that, with over 450 Q1, i have **substantially more** than just 253,550 maximum mana

(the reason why i have 50k INT in that picture is because i was standing next to a CM with almost 300 W3, i only really have ~20k INT natively)

**Comment by bavibi** [comment]
20000 * 5 = 100000, 100000 > 65536.
Your int makes your mana pass the 65536 UI mana limit even without Q1.
Thus, you can't see mana from Q1

**Comment by redledcat** [comment]
It's not about mana UI, it's about tooltip info missing other sources

**Comment by DeckardCainRPC** [comment]
correct. the expanded stats tooltip says i only have +253,550 bonus mana, which is not accurate - the stats tooltip should include bonus maximum mana gained from other sources, including gear, runes, and any future immortal item effects.

because i am Deckard Cain, i am obviously aware of the purely visual limit of 65536 maximum mana

**Comment by redledcat** [comment]
That issue wasn't defeated and probably never will be really closed, but since you need quite a lot of effort to hit 65k mana right now, it's obsolete
