### ISSUE TITLE
Djanghor pit weapon

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#465]
It doesn't change element of W

local element1 = RPC_ELEMENT_NORMAL
	local element2 = RPC_ELEMENT_NONE
	tornado_start(event)
	if caster:HasModifier("modifier_djanghor_immortal_weapon_1") then
        local pfx = ParticleManager:CreateParticle( "particles/roshpit/dreghor/jinbo_heavy.vpcf", PATTACH_POINT, caster )
        ParticleManager:SetParticleControl(0, pfx, caster:GetAbsOrigin())
        -- ParticleManager:SetParticleControl(1, pfx, caster:GetAbsOrigin()+endFV*range)
        ParticleManager:SetParticleControl(2, pfx, Vector(range, 0, 0))
		Timers:CreateTimer(4, function() 
		  ParticleManager:DestroyParticle( pfx, false )
		end)
		**local element1 = RPC_ELEMENT_NATURE
		local element2 = RPC_ELEMENT_NONE**  (there should be no "local")
		local endFV = caster:GetForwardVector()
		local range = 1200
		EmitSoundOn("Draghor.RendRange", caster)
		enemies = FindUnitsInLine(caster:GetTeamNumber(), caster:GetAbsOrigin(), caster:GetAbsOrigin()+endFV*range, nil, 240, DOTA_UNIT_TARGET_TEAM_ENEMY, DOTA_UNIT_TARGET_ALL, DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES)		
	end

**Comment by ChalkyBrush** [comment]
you are correct here, fixed
