### ISSUE TITLE
Helm of the Iron Colossus W mana cost bugged

### ISSUE THREAD

**Issue by CallMeCatman** [ChalkyBrush/roshpit-bug-tracker#466]
Helm of the Iron Colossus seems to add more than 1000 to the mana cost of W in this situation. Level 4 Arcana W costs 500 mana, plus the 1000 from Iron Helm equals 1500 mana. Since I have 16,725, I shouldn't dip below 15,225, but it looks like it goes to 14,225, an extra 1000 more mana.
[https://imgur.com/a/sEcOu](https://imgur.com/a/sEcOu)
[https://www.roshpit.ca/players/64396597/heroes/424252](https://www.roshpit.ca/players/64396597/heroes/424252)

**Comment by redledcat** [comment]
@ChalkyBrush 
it costs 2000 additional mana 
here is the test with Zhonick W cast using 160 mana, which costs 2160 mana actual.
https://youtu.be/NiYQCaWh-AY
also:
filters.lua says
    if caster:HasModifier("modifier_iron_colossus") then
        local ability = caster:GetAbilityByIndex(1)
        local manaCost = ability:GetManaCost(ability:GetLevel())
        caster:ReduceMana(2000)

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/39516517-7163690a-4dfd-11e8-8429-441c4514d11b.png)
160 mana drained from skill (22940)
![image](https://user-images.githubusercontent.com/32621322/39516607-b19fc536-4dfd-11e8-9cd2-be97c3e3df0a.png)
142 mana regenerated from mana regen (23082)
![image](https://user-images.githubusercontent.com/32621322/39516633-ca9a8e4a-4dfd-11e8-9af9-eb6291fc3ba3.png)
and 2000 mana drained from hit (21082)

**Comment by redledcat** [comment]
fixed
