### ISSUE TITLE
Paladin's Q's Bonus Damage doesn't actually work.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#47]
Reproduction steps: Cast E with points in E3, note your damage.
Cast Q, gain bonus attack damage, cast E, you'll deal the same damage.
Gain any other source of bonus attack damage, cast E, you'll deal more damage.
Conclusion: Q doesn't actually give bonus attack damage.

**Comment by ChalkyBrush** [comment]
Interesting, great find. This is a very sneaky bug that apparently nobody noticed until now.
This is fixed for next patch!
