### ISSUE TITLE
Voltex - Immortal glyph does not increase Q/Q1 duration

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#472]
Can't believe I did not posted that yet. Or did I?
T5_a increases duration of T2_1 glyph, but does not affect nor Q duration, neither Q1 duration
https://www.youtube.com/watch?v=WwcY9-6-gck

**Comment by redledcat** [comment]
5_a also affects 1_1 (80% evasion while overcharge)

**Comment by redledcat** [comment]
Also: modifier_gods_strength_datadriven has no tooltip

**Comment by bavibi** [comment]
Also, base damage of Q is dealt separately, and it has no element or any other amp because it uses ApplyDamage

**Comment by redledcat** [comment]
Thank you!
