### ISSUE TITLE
Slipfin - portal bugged

### ISSUE THREAD

**Issue by jasonZZZ888** [ChalkyBrush/roshpit-bug-tracker#473]
sea fortress - unable to use portal after kill vengeful spirit ( the first boss open the portal in early game)           tanari jungle - unable to use portal in wind temple ( keep stuck and return, the portal open by 3 colour element)

**Comment by redledcat** [comment]
https://youtu.be/ECTYSvoj7SA

**Comment by redledcat** [comment]
^ Also wind vortex jumppads are bugged when you jumping right before entering it (1:01 - 1:45)

**Comment by redledcat** [comment]
If you press jump before three-coloured teleport, slipfinn goes through the first abyss and being stuck in next island border
