### ISSUE TITLE
Dark Reef Shark Helmet

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#475]
My Cherno kills the tombstones in the pit with one auto-attack under buff of the helmet, but can't do that while rapidly auto-attacking.

Perhaps, it happens with every hero that has too high attack speed.

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush this is a deceptively important bug, btw

**Comment by bavibi** [comment]
![screenshot_13](https://user-images.githubusercontent.com/15161630/39191820-74aac64e-47e0-11e8-97ca-f87cdf393158.png)
It happens with every ranged hero.

**Comment by redledcat** [comment]
fixed because of rework.
great success!
