### ISSUE TITLE
Bladeslinger Boots launches attacks against Invulnerable units (like those caught in Possession Bubble)

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#479]
meaning if Slipfinn wears them and possesses a creature, he will abort his current orders every 0.5 seconds to adjust his facing arc and do nothing

i believe the correct solution to this is to add another clause to bladeslinger boots' code block that says "if the unit is INVULNERABLE or HIDDEN then don't attack it," right after the block that says "don't attack out your ass while you're dead, either"

**Comment by ChalkyBrush** [comment]
they actually aren't flagged as invulnerable so I just hard coded an exception for possessed units

**Comment by redledcat** [comment]
300 issues closed, hurray (most of them were actual bugs)
