### ISSUE TITLE
Bug on Juggernaut's damage.

### ISSUE THREAD

**Issue by oCCFANo** [ChalkyBrush/roshpit-bug-tracker#48]
In map Redfall Ridge, Juggernaut cannot hurt one of the boss.

Sorry I'm not able to tell the name of that boss in English because I'm not using an English version, but I did upload a video, please check Youtube here: https://youtu.be/DRpZkWD_0lI

Ps. I'm new to Github, and I don't have an idea about attaching a video link, so I just simply posted the link.

**Comment by ChalkyBrush** [comment]
"DOTA_Tooltip_ability_redfall_moloth_passive"					"Essence Shell"
		"DOTA_Tooltip_ability_redfall_moloth_passive_Description"		"Moloth is immune to all damage unless his 3 orbiting spheres match color. If all blue, Moloth can take pure damage. Green, physical and red magical."

**Comment by oCCFANo** [comment]
Where can we find tips or guides like this?

**Comment by ChalkyBrush** [comment]
If you hover your mouse over enemy tooltips you get information like this

**Comment by oCCFANo** [comment]
Thanks. I'll try.
