### ISSUE TITLE
Axe T7 Glyph coded by a lipstick testing gerbil; should be CDR instead

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#484]
STEPS TO REPRODUCE:

1. put that glyph on and cast Q
2. for some reason - and i'm sure you have (or had) a very good reason to do it this way - the CD of Q remains at 7 seconds for about 0.5 seconds, then spontaneously switches over to a 1.5sec CD
3. why
4. this means the glyph's actual effect is to reduce the CD to ~2.1 seconds

SUGGESTED COURSE OF ACTION:

just change the glyph's script to 78.6% CDR for Q. that would result in a CD of 1.498 seconds, which is accurate to within 0.03 seconds. since CDR stacks multiplicatively, wearing it alongside the Q Ahn'qhir helm would only raise it to 87.16% CDR, resulting in a 0.8988sec CD, which is perfectly fine because Hood of Lords would reduce it to 0.5sec anyway (provided, of course, that its effect is applied after percentile CDR).

**Comment by redledcat** [comment]
yeah iirc Dragon had problems with arcana R integration to work with Q and making it aim correctly
I told it starts cooldown from landing point instead of cast, but got no responce.
