### ISSUE TITLE
Glyph of Dragon Skin + Berserker Gloves

### ISSUE THREAD

**Issue by OlDor** [ChalkyBrush/roshpit-bug-tracker#486]
With a combination of (Glyph of Dragon Skin + Berserker Gloves) hero can still die from 1 hit, while hero should only be damaged for 15-30% of max health.

Also, could you please add Blacksmith to Serengaard map?

**Comment by DeckardCainRPC** [comment]
the blacksmith should definitely NOT be added to Serengaard in the map's present state - currently, the map immediately ends and prevents further player input after the Ancient is destroyed, so people could EASILY be left unable to save their hero's equipment status after performing an inopportune chisel, among many other obvious concerns.

as for Glyph of Dragon Skin's interaction with Berserker Gloves, that might actually be a bug. Chernobog and Slipfinn can both have Steadfast abilities while wearing that item and they aren't susceptible to oneshots when doing so (minding the mana cost for Cherno's Steadfast).

could you post a link to the exact build you used for your DK? this is important, as perhaps some other item or effect present on you might be causing this interaction to happen.

**Comment by nedamettin** [comment]
just a side note, slipfinn indeed takes amplified damage while berserker stacks are active, even if you have steadfast. the reason why I and nobody is using berserker gloves anymore.

**Comment by ChalkyBrush** [comment]
Berserker gloves apply 'post-mitigation' so if that's how it works against enemies (breaking steadfast limits) I think it makes sense to apply to heroes in the same way
