### ISSUE TITLE
possible dupe?

### ISSUE THREAD

**Issue by nedamettin** [ChalkyBrush/roshpit-bug-tracker#488]
https://www.roshpit.ca/players/96622358/heroes/733558

https://www.roshpit.ca/market/auction/372430

https://www.roshpit.ca/market/auction/363355

all three bladedancer bushidos have identical stats, possible dupe action? they popped out in the last a few days but i think hakod's was the original one

**Comment by redledcat** [comment]
according to ChalkyBrush, there is no active dupe methods, because of ID tether.
if someone can dupe, he will also be able to make new ID's for items which is much ~~better~~ worse

**Comment by ChalkyBrush** [comment]
Pretty sure those were duped a long time ago, I recognize those stats
