### ISSUE TITLE
Venomort's immortal glyph and E1 interaction

### ISSUE THREAD

**Issue by nedamettin** [ChalkyBrush/roshpit-bug-tracker#489]
when you cast E's glyph version (ghost warp), e1 procs momentarily when you launch but instantly ends when you land. Also e1 capping at 3.7 seconds is... weird since slark's e3 scales infinitely with better skillset than Venomort.

A small recommendation would be giving ghost warp two charges so people may play Venomort if they use glyph of festering. This is a completely off the topic suggestion.

**Comment by redledcat** [comment]
e1 was changed 20 years ago, close
