### ISSUE TITLE
Other Spirit Warrior issues.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#49]
1)Ancient Bug of Ancient Fury [R4]
It does not work, dunno,since 7.00 or even further in past.
Listed attack speed does not add to spirits (BUT [W2] of Voltex actually buffs them, pretty sure Radiant Leather can no this too, but I cant test it)
![20171019214608_1](https://user-images.githubusercontent.com/32621322/31788518-3db70fbc-b50f-11e7-8e1e-109a11e62200.jpg)
Just spirit attack speed, with R4 skilled or not skilled.
![20171019214615_1](https://user-images.githubusercontent.com/32621322/31788552-57aaebc8-b50f-11e7-88c3-94802235cb1e.jpg)
Under R3 effect also no changes.
![20171019214626_1](https://user-images.githubusercontent.com/32621322/31788567-666eab0e-b50f-11e7-85d3-2ac14333b7da.jpg)
*(Even if it will be fixed, in current state damage still is extremely insignificant. Last _good_ use of it I can remember was killing King Kraethas avoiding his bubble, but it was a year ago, some changes of spirits mechanics should be done.)
2)Spirit actual position always is closer than point of cast.
(No mouse movement perfomed here)
![20171019214519_1](https://user-images.githubusercontent.com/32621322/31788834-50cf2d7c-b510-11e7-90f3-65ec40ea401b.jpg)

**Comment by ChalkyBrush** [comment]
This is fixed, thanks for noticing.
Surprised it made it this long
