### ISSUE TITLE
Venomort E2 doesn't proc Wind Deity Helm

### ISSUE THREAD

**Issue by nedamettin** [ChalkyBrush/roshpit-bug-tracker#491]
Venomort's E2 (poison damage when Venomort attacks) doesn't proc Wind Deity Helm even though it counts as a Base Ability. Expected same interaction that Slipfinn has with his E1, but it doesnt work.

**Comment by redledcat** [comment]
If you read it carefully you can actually figure out that is:
![20180506203429_1](https://user-images.githubusercontent.com/32621322/39676102-e59b4968-5164-11e8-903c-4192c392b521.jpg)

**Comment by ChalkyBrush** [comment]
redledcat's got it right (It is unintuitive though)
