### ISSUE TITLE
Mask of the Phantom Sorcerer + Flamewaker Arcana W

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#492]
You get about 15 seconds of cooldown to W per second while Fireborn is active.
![firebornphantom](https://user-images.githubusercontent.com/32672982/39761707-4cad3dfa-52c8-11e8-873d-366d7381d1a0.png)

**Comment by ChalkyBrush** [comment]
not a bug since 'oncast' effect is triggered every 1 second while W is active
