### ISSUE TITLE
Crystalline Slippers is weaker than tooltip says

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#493]
Game_state, line 2648

	if attacker:HasModifier("modifier_crystalline_slippers") then
		if victim:IsRooted() then
			filterTable["damage"] = filterTable["damage"] * 3
		end
Description:
Enemies who are rooted deal 80% reduced damage to you and take **5x** amplified damage.
Right?

**Comment by ChalkyBrush** [comment]
fixed
