### ISSUE TITLE
Elemental Warlord's glyph t3 has secret buff

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#494]
if attacker:HasModifier("modifier_warlord_glyph_3_1") then
		if attacker.warlordElement then
			if attacker.warlordElement == "ice" and damagetype == DAMAGE_TYPE_MAGICAL then
				filterTable["damage"] = filterTable["damage"]*1.4

Description: Removes movement slow from stone form. 
I checked it manually in game, and that works for sure. Please make this feature lol.
![image](https://user-images.githubusercontent.com/32621322/39783687-27778fb0-5316-11e8-81f7-8a26a7b626c5.png)

**Comment by ChalkyBrush** [comment]
removed
