### ISSUE TITLE
[Museum of Valve updates] International 2018 aka Blackout update

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#495]
https://youtu.be/cKMUFAV1_LI

**Comment by redledcat** [comment]
Darkness can be unbugged by setting video settings "Shadow Quality" from "Off" to sth else.
![image](https://user-images.githubusercontent.com/32621322/39787066-ba5b2078-5323-11e8-9b7c-c0e745feab3c.png)

**Comment by redledcat** [comment]
Oracle Stash does not work, that more important.
(Stash is accessible, but you can't move any item inside stash or add new to the stash)

**Comment by ChalkyBrush** [comment]
fixed oracle, and apparently shadows is a graphics thing that valve will fix (because map is black in regular doto as well)
