### ISSUE TITLE
Mountain Protector E1 and Arcana R interaction

### ISSUE THREAD

**Issue by nedamettin** [ChalkyBrush/roshpit-bug-tracker#496]
damage from arcana R and E1 (casts one blast of R at landing point with amplified damage) has a huge difference even though E1 is an "amplified" version of the R. I think the problem is that E1 only counts base damage and doesn't add STR multiplier from arcana R damage to the calculation. That's my wild guess but damage numbers for E1 are 3 times lower than R damage.

**Comment by bavibi** [comment]
You're right, hope Chalky will fix it in Winterblight patch.
![e1_bug](https://user-images.githubusercontent.com/15161630/40309605-b7a7e2d2-5d12-11e8-8262-3d05a20fb7ca.png)
![e1_bug_2](https://user-images.githubusercontent.com/15161630/40310308-ff81e308-5d14-11e8-9571-854f3ec31777.png)
