### ISSUE TITLE
[Feature Request] Ekkan can target E2 familiars with Q in emergencies

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#497]
"emergencies" like single-player Arena and starting out in Sea Fortress, places where you're waaaaaaaaaay up shit creek without a paddle in regard to available pets

to clarify, Ekkan's spells already have various context-sensitive effects programmed, including some that check to see if you have points in a rune first before activating in that context (like E1 and R3). i propose that an additional context-sensitive function be added to Q and Arcana Q, which is an extension of the existing context of targeting an allied Dominion unit to unsummon it - if the targeted unit is an E2 familiar, the spell claims it as a Dominion pet, counting towards Ekkan's normal Q summon caps just like it was any other creep.

this change will not only address instances of ACUTE PETLESSNESS as described above; it will also address the extremely niche *but not impossible* corner case wherein Ekkan (and his teammates) have managed to extinct the map of all enemy units except for the end boss, and during the course of fighting this boss, also managed to get his horde of Q pets killed, resulting in a completely helpless Ekkan with no access to new pets.

additionally, it will add support for the otherwise seldom-used Immortal weapon that causes the familiars to deal pure damage with every attack. i realize that having an army of potentially like 7 to 9 mayhem-minded bats that shit excruciating pure damage at unbelievable speeds *SOUNDS INSANE* until you slow down and realize that they have mediocre HP and no Steadfast... now, of course, using the Arcana can get you one *with* Steadfast, but that's just one bat and an E2 familiar isn't even close to being a powerful pet when you look at all the other options available (Priests of Kar'zhun being a fantastic example). at best, a new E2 build might potentially open up and become popular, which doesn't sound like a bad deal considering Ekkan has a whopping 1 build anyone ever uses anyway.

**Comment by redledcat** [comment]
welcome to the future, now you can cast Q on familiars.
