### ISSUE TITLE
Paladin ult NEVER heals allies.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#50]
He doesn't. Knight's Disciple will NEVER heal another ally. He'll heal Paladin though.
Also, R2 has a maximum amount of stacks (30) that's listed nowhere.

**Comment by ChalkyBrush** [comment]
he won't cast it on an ally if the duration remaining on the buff < ability base cooldown

**Comment by FortuneReborn** [comment]
Causing him to also not cast it when Paladin is dead, but that's fine.

**Comment by ChalkyBrush** [comment]
fair point, added a check to make sure paladin is alive when considering his remaining buff duration
