### ISSUE TITLE
Fire amp bugged

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#504]
![firecrownbug](https://user-images.githubusercontent.com/32672982/40575178-4456f0c8-60cf-11e8-9b05-a6cd8c288dff.png)
I don't know what causes that.

I tried chiseling the gear pieces one by one to see if they affect it. The fire amp only went even lower due to the str in the items (I think)

The only way I managed to bring the Fire amp back to its supposed 5400% was to equip the body arcana.

**Comment by Xhulhorac** [comment]
Edit: Tests tell me that it is not just a visual bug. The Fire amp truly is that low for some reason.

**Comment by redledcat** [comment]
Hi there.
For me fire arcana give 0 bonus fire amp. Instead, water arcana gives both water and fire amp bonuses.
![image](https://user-images.githubusercontent.com/32621322/40577319-14f9d87e-6104-11e8-8afd-bab86b4afa1b.png)
![image](https://user-images.githubusercontent.com/32621322/40577320-1b7dd678-6104-11e8-9939-8aba4792695b.png)
![image](https://user-images.githubusercontent.com/32621322/40577323-293694c6-6104-11e8-9bf9-c19818b90ce3.png)
![image](https://user-images.githubusercontent.com/32621322/40577329-3a171a36-6104-11e8-8985-a790bcaf0a1f.png)

**Comment by GoToNightmare** [comment]
fixed, that was bug in filters, fire dmg was checking wrong arcana.
