### ISSUE TITLE
Flamewaker: Glyph T4 doesn't effect W1

### ISSUE THREAD

**Issue by OlDor** [ChalkyBrush/roshpit-bug-tracker#506]
Flamewaker's Glyph T4 (Glyph of Blue Flame) doesn't effect damage of W1 (Incendiary Blade).
Also, target's Movespeed and Attack Speed are not reduced by 120 with hits of W1.

**Comment by DeckardCainRPC** [comment]
this is working as intended; the glyph doesn't specify @ability2, it says Second Heartbeat, meaning the effect only applies to the spell itself and not all damage dealt by @ability2.

i will note, however, that i'm pretty sure his T4 glyph has a hard-coded interaction with his glove arcana, which may possibly mean a slight tweak to the glyph's tooltip may be in order

**Comment by ChalkyBrush** [comment]
yea this isn't a bug, sry ^_^
