### ISSUE TITLE
Manacosts too high with Cerulean Highguard

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#509]
At lv4, Dusk's W uses 1,500 mana. With Cerulean Highguard, that should be 7,500.

However, it drains 13,500 mana.

Leads me to think that Cerulean Highguard's 400% extra manacost is bugged to 800%.

**Comment by redledcat** [comment]
I have to mention here #466
Cerulean highguard has (line 2987 filters.lua)
function Filters:CeruleanHighguard(caster)
    local ability = caster:GetAbilityByIndex(1)
    local manaCost = ability:GetManaCost(ability:GetLevel())
    caster:ReduceMana(manaCost * 4)

Could it be another function which drains another portion of mana?

**Comment by bavibi** [comment]
It takes mana cost of next level
![screenshot_16](https://user-images.githubusercontent.com/15161630/40653877-2efd6324-6345-11e8-83b2-68020637a48e.png)
![screenshot_17](https://user-images.githubusercontent.com/15161630/40653875-2ed90f74-6345-11e8-81d0-d77095bb5175.png)

**Comment by redledcat** [comment]
bavibi is an alien confirmed

**Comment by ChalkyBrush** [comment]
didn't even realize feeding it -1 would give current level, will have to start using hthat more often. Thanks Bavibi

**Comment by bavibi** [comment]
@ChalkyBrush btw, how to do pull requests? ^^

**Comment by ChalkyBrush** [comment]
@bavibi check your discord messages

**Comment by ChalkyBrush** [comment]
![image](https://user-images.githubusercontent.com/5232984/40690300-5e26fa5a-6374-11e8-89c4-209674938a14.png)
fixed for next patch (-1 hype)
