### ISSUE TITLE
Paladin Arcana W bug

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#51]
Paladin W sometimes bugs out and cannot be used when reviving with E passive.
![20171019222603_1](https://user-images.githubusercontent.com/32886049/31802710-9d1b4c4e-b51d-11e7-844a-edc1e2f05000.jpg)

**Comment by redledcat** [comment]
Same. Pretty sure it bugged when I was pulled with water ancient god form ability, while my spear was in air.
![20171020155352_1](https://user-images.githubusercontent.com/32621322/31821891-f273c25a-b5a6-11e7-8abe-90e5dfa2e524.jpg)

**Comment by FortuneReborn** [comment]
I don't think the bug has anything to do with E1. It just kept happening to me too. The following message appears when attempting to use W when it can't be used.
![570_20171020210840_1](https://user-images.githubusercontent.com/3812172/31842196-32221bea-b5ed-11e7-8ef3-7aff29c5d18c.png)

**Comment by ChalkyBrush** [comment]
alright WE GOT IT THIS TIME!!

**Comment by FortuneReborn** [comment]
I love your optimism, Chalky.
![570_20171021130114_1](https://user-images.githubusercontent.com/3812172/31851159-31c11ae8-b660-11e7-8f45-b2f39c817ab6.png)
Morphling Wave-dashed while my W was going to him. Ye 'olde bug.
