### ISSUE TITLE
New Huskar T7 Glyph doesn't actually increase R duration

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#511]
although curiously, it appears to give him a ~15% crit chance for 4x damage? is the glyph applying the correct effect?

**Comment by redledcat** [comment]
~~Also there seems to be no changes at all while update says
-Spirit Warrior t7 glyph x10
wrong hero? wrong glyph? 
should it be 40 seconds increase? probably yes~~
Oh damn it actually is 40 seconds, but it coded only for **waterheart weapon and ancient rain, not ancient vigor.**

**Comment by redledcat** [comment]
if caster:HasModifier("modifier_spirit_warrior_glyph_7_1") then
		duration = duration + 4
still 4 sec for vigor

**Comment by redledcat** [comment]
@DeckardCainRPC it's your weapon, isn't it?

**Comment by redledcat** [comment]
By the way, making difference that giant is weird

**Comment by DeckardCainRPC** [comment]
@redledcat Spear of Aeris doesn't list a crit chance in its tooltip, i don't know how it could be related

**Comment by redledcat** [comment]
fixed
