### ISSUE TITLE
Suggestion: `Only Immortal Items Drop`

### ISSUE THREAD

**Issue by OlDor** [ChalkyBrush/roshpit-bug-tracker#512]
When choosing between `Normal`, `Elite` & `Legend`, wouldn't it be better to also add a subset of options like:
1) `Only immortal Items Drop` -- would decrease the lags. People lvl 30+ never pick those anyways...
2) `Pick/Drink potions automatically`
and stuff like that

**Comment by GoToNightmare** [comment]
1. Im agree, we need option/vote system for this, but its on chalky's side ;)
2. Check gourmand after the patch.

**Comment by OlDor** [comment]
@ChalkyBrush i think this can be closed now (both 1 and 2 are now implemented).
thanks for the great job

**Comment by GoToNightmare** [comment]
implemented.
