### ISSUE TITLE
Dying and being resurrected in Val'dun's arena will eject you south over an impassable wall

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#514]
STEPS TO REPRODUCE (and this is fucking bizarre):
1. get owned by val'dun
2. get resurrected, either by Auriun's ult or by effects like Paladin's E1 (both arcana and non-arcana)
3. you will respawn, and then get teleported over the impassable wall which forms the southern border of Val'dun's massive waterlogged arena complex

xhul'horac says that Paladin's E1s are also causing strangeness in Pit of Trials, might need to follow up with him about it for more specific information

**Comment by DeckardCainRPC** [comment]
4:43 PM] Medivh: @Deckard Cain any blink or appearance in impossible area near Val'Dun's arena will cause you teleported south
[4:44 PM] Medivh: you can achieve this with axe leap  or drow blink

**Comment by GabrielZinatoSP** [comment]
Ekkan's portal also causes people to randomly teleport to that position when you put it anywhere after the last gate in Sea as well. In fact, if Ekkan puts a portal in that area, people don't even need to step in the portal to be randomly teleported to south of Val'dun's arena. Pretty annoying.
