### ISSUE TITLE
Sorceress: Glyph of Arcane Torrent + Seraphic Soulvest

### ISSUE THREAD

**Issue by OlDor** [ChalkyBrush/roshpit-bug-tracker#515]
Seraphic Soulvest says "Every `cast` of @Ability2 also launches a Seraphic Lance".

However, when Arcane Torrent is active, Seraphic Soulvest doesn't launch the Seraphic Lance.

I thought maybe active Arcane Torrent is not interpreted as a `cast`, but... Q2 (Frost Nova) also reads about `casting @ability2` and it procs all the time when Arcane Torrent is active.

**Comment by redledcat** [comment]
Q2 is hardcoded to work 
#233

**Comment by redledcat** [comment]
Also using Seraphic on hero without both cosmic amp and high attack damage is not right move.
Seraphic is semi-modified to work with astral ranger, but even for her it's relatively bad choise.
