### ISSUE TITLE
Flamewaker: Dragonwing Gauntlet + Fireborne (W skill) cooldown

### ISSUE THREAD

**Issue by OlDor** [ChalkyBrush/roshpit-bug-tracker#516]
Fireborne cooldown increases when it is active (by 2-3 seconds per second).
So, if player activates W for 1 minute, he would now have to wait for 2-3 minutes of cooldown.

Also, it looks like the most useless arcana in roshpit anyways...
Maybe rebuild it a bit?

**Comment by redledcat** [comment]
It's sorcerer's mask and also that's not a bug.
#412 
#492

**Comment by redledcat** [comment]
Also it's going to be changed capping coldown increasement.

**Comment by ChalkyBrush** [comment]
fixed
