### ISSUE TITLE
Duskbringer "Glyph of Scathing Phantoms" cancelled by other root effects on the target

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#517]
STEPS TO REPRODUCE:
1. equip that glyph
2. shoot a bad man with W
3. observe that he doesn't gain any Q1 stacks
4. observe that he gains stacks of both Jack and Shit

**Comment by DeckardCainRPC** [comment]
5. test it again to make sure
6. okay, so the VERY FIRST TIME a unit is trapped by W, they will gain 3 stacks per second, but *never again* for the remainder of the game session after the W debuff expires (maximum 15 stacks at spell rank 7)

SUGGESTED COURSE OF ACTION:
change the glyph's effect to "Haunted Hallow [W1] applies 1 stack of Duskfire Flail every time it hits an enemy unit." this maintains the 3 stacks per second status quo

**Comment by DeckardCainRPC** [comment]
**7. get a private message from redledcat saying it works fine**
**8. make a >;[ face in both confusion and frustration**
**9. discover that the problem is Cap of Wild Nature: if a target is rooted by that helm's effect, they can't be rooted by duskbringer's W, preventing stacks from being gained for the duration of that debuff (which, due to W1's tick rate, that root gets refreshed constantly)**
**10. thank redledcat profusely**

**Comment by DeckardCainRPC** [comment]
i recommend checking to make sure this bug doesn't cancel W2 as well.

**Comment by redledcat** [comment]
creep rooted once cannot be rooted by trap effect until it LEAVES zone covered by traps and enter new one (not connected with previous trap zone)
https://youtu.be/ZHc4wPCMbZ8

**Comment by DeckardCainRPC** [comment]
ฅ^•ﻌ•^ฅ: I found important thing which magically trasferred even after full rework of W code
ฅ^•ﻌ•^ฅ: if I make a road of W root traps
ฅ^•ﻌ•^ฅ: and keep spam them one by one before enemy when root effect ends on it
ฅ^•ﻌ•^ฅ: enemy wont get root
ฅ^•ﻌ•^ฅ: until
ฅ^•ﻌ•^ฅ: mob leave the trap zone

yeah the immunity period applied to mobs after they're done being rooted needs to be handled differently behind the scenes. it shouldn't only be checked when a mob registers having (re-)entered a W zone

**Comment by redledcat** [comment]
Creep still being attacked by w1 rune, but since root effect does not affect it Q1 from Scathing Phantoms has no effect too

**Comment by DeckardCainRPC** [comment]
i think this has been fixed by a recent patch. no further changes are required at this time
