### ISSUE TITLE
Arcane Charm's property 3 not adding arcane amp

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#519]
![arcanecharmbug](https://user-images.githubusercontent.com/32672982/40903941-a1a13644-67c8-11e8-9e9f-de9da80f7fe2.png)
It may or may not apply to 2nd property as well.

I have the 300% elemental glyph equipped.

**Comment by ChalkyBrush** [comment]
fixed by bavibi
