### ISSUE TITLE
CM immortal weapon illusion getting trapped

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#52]
Not a bug but general enhancement to the weapon. When the hero dies the illusion doesn't teleport back to the hero and gets stuck in area that require teleportation to escape.
Or sometimes the illusion blinks into some trees and stays there until the hero comes back.

Can you please add a Leash range on that illusions? Let's say 2500?
Sorry for not providing an image to help show this issue will provide one if needed as it happens very often in maps like Tanari.

**Comment by SilentC** [comment]
I feel like this has been ignored for a long time and not being taken seriously. This bug makes the effect of the immortal near useless. Here are some images to show how useless it can be.

The second image shows the illusions trapped in the water near the boat. The last image shows that after I move back to it, it escapes but it still gets left in the area if I teleport out.

![20171031093433_1](https://user-images.githubusercontent.com/32886049/32229298-dda25ed0-be26-11e7-923e-be41ffc31e8e.jpg)
![20171031095907_1](https://user-images.githubusercontent.com/32886049/32229302-e24a24cc-be26-11e7-909f-9eea4c080f79.jpg)
![20171031102822_1](https://user-images.githubusercontent.com/32886049/32229313-e5fe71a4-be26-11e7-9c35-dd7d7ecedddc.jpg)

**Comment by ChalkyBrush** [comment]
when avatar distance > 1500 from Sorceress it teleports beside her

**Comment by ChalkyBrush** [comment]
should be fixed for sure now
