### ISSUE TITLE
Flamewaker: Dragonwing Gauntlet range from W3

### ISSUE THREAD

**Issue by Secretov** [ChalkyBrush/roshpit-bug-tracker#522]
W3(splitfire) dont work or work bad. Just look at range in description and real range( real about 400-450)
![dk](https://user-images.githubusercontent.com/20336263/41161252-e4cd5630-6b3a-11e8-9a1e-edaa0a49f698.png)

**Comment by Secretov** [comment]
how to delete this issue? :0

**Comment by redledcat** [comment]
it works only for casted W, right?

**Comment by redledcat** [comment]
you can choose "Close" in comment section just near "Comment" button
