### ISSUE TITLE
Bahamut Arcana W4 wrong tooltip

### ISSUE THREAD

**Issue by Nintai** [ChalkyBrush/roshpit-bug-tracker#523]
Tooltip says 0.2% of missing mana per level, but in truth its 500% (or 5x) of missing mana per level

**Comment by redledcat** [comment]
Haha
https://steamcommunity.com/sharedfiles/filedetails/changelog/469311655?p=10
Update: 11 Dec, 2017 @ 4:41am
**Bahamut Arcana W4 x25**
That meant to be 5%, I see how that came here.
