### ISSUE TITLE
Training Dummies can inherit global DR% from map difficulty settings

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#524]
which of course renders the numbers output by an affected dummy almost entirely worthless

EDIT: github's file server is currently TAKING A SHIT and "we can't process that file" whenever i try to upload a screenshot of the conversation wherein this was reported to me, so the gist of it is this:

STEPS TO REPRODUCE:
1. load up the Arena map
2. don't even start Pit of Trials, just walk over to the training dummies
3. left-click a dummy and check out its amazing 40% DR

**Comment by Xhulhorac** [comment]
This is also easily witnessed in Tanari and Redfall and comparing the damage numbers before and after turning it into Spirit Realm/Equinox

**Comment by GoToNightmare** [comment]
can you check arena dr that is not just visual, i pretty sure it is, not about other maps.

**Comment by StillStealSteel** [comment]
You can't check it on the arena, because when you you open pit dummies disapper.

**Comment by redledcat** [comment]
game state.lua
if Events.SpiritRealm then
      	if victim:GetTeamNumber() == DOTA_TEAM_NEUTRALS then
      		filterTable["damage"] = filterTable["damage"]/6

**Comment by redledcat** [comment]
![20180710174638_1](https://user-images.githubusercontent.com/32621322/42517798-e4158aac-8460-11e8-9f98-1dbe83621a6d.jpg)
![20180710174652_1](https://user-images.githubusercontent.com/32621322/42517799-e43d177a-8460-11e8-994e-a51fdd8e9200.jpg)
