### ISSUE TITLE
Colorless rune tooltips

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#525]
![20180613121720_1](https://user-images.githubusercontent.com/32621322/41342029-87da572e-6efb-11e8-8147-b0bf4d7df71a.jpg)
![20180613121052_1](https://user-images.githubusercontent.com/32621322/41342032-891a1d0e-6efb-11e8-880d-5d613ef71a29.jpg)

**Comment by ChalkyBrush** [comment]
this is pretty upsetting, while take some time to fix

**Comment by ChalkyBrush** [comment]
fix inc,
rebuilt from scratch. Looks better now though I think

**Comment by redledcat** [comment]
Looks stunning.
Now the problem is new tooltips do not respect any rune level higher than 20.
Values always say as it is 20 independent of actual rune value.
![20180614111936_1](https://user-images.githubusercontent.com/32621322/41400228-ddbe0868-6fbc-11e8-8734-02c3f5547561.jpg)
![20180614112030_1](https://user-images.githubusercontent.com/32621322/41400229-dde79778-6fbc-11e8-91f9-eb7be30a3442.jpg)
![20180614111941_1](https://user-images.githubusercontent.com/32621322/41400230-de0deba8-6fbc-11e8-92ae-77e39fca3e79.jpg)

**Comment by ChalkyBrush** [comment]
fixed
