### ISSUE TITLE
[EXTREMELY SERIOUS] Heavy Echo Gloves entirely disrupts programming of items with proc chances

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#526]
having interviewed like eight people about this, i want to make it clear that this is an extremely complex issue and that it will require you @ChalkyBrush to spend time reading what in the blue fuck is going on. to that end, i need you to use the RPC Discord chat's search feature, and type the phrase ``gravy cinderella``. since i am the only person in chat to have ever typed ``gravy cinderella`` for any reason, it will bring you to the top of the conversation relevant to this topic.

Tony has been aware of this issue for several months, and intends to address it (possibly with your attention as well), but deliberately put it off because you're concentrating on 3.8 at the moment.

i cannot understate how fucked up all of this is, and how far-reaching its consequences are. i was going to include a short list of the most important bullet points to take away from the issue, but all nineteen of the ones i wrote all ended with "MOTHER FUCKER THIS IS NOT GOOD."

**Comment by bavibi** [comment]
In what way is this suppose to work?


LIVE
![screenshot_23](https://user-images.githubusercontent.com/15161630/41371020-d2ecd934-6f51-11e8-8168-d440f24ee05b.png)

MODIFIED 1
![screenshot_24](https://user-images.githubusercontent.com/15161630/41371068-f3665d34-6f51-11e8-95db-03c80e1ae4c1.png)

MODIFIED 2
![screenshot_25](https://user-images.githubusercontent.com/15161630/41371095-0315ec7c-6f52-11e8-8e53-52a4932db9f7.png)

! Chance of fire deity proc is increased to 100%

**Comment by DeckardCainRPC** [comment]
@bavibi beloved compatriot, talk to Tony for more information

**Comment by GoToNightmare** [comment]
fixed, only 3 instances now

**Comment by ChalkyBrush** [comment]
Addressed by Tony (@GoToNightmare )
