### ISSUE TITLE
Duskbringer's Q and Q3

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#529]
Q ability deals damage only after 0.3s from channel start
Q3 does not affect Q damage at all.
probably issue is here
	local distance = WallPhysics:GetDistance(enemy:GetAbsOrigin(), caster:GetAbsOrigin())
			local damageBonusMult = 1 - (distance/ability.radius)
			local distanceDamage = damage * damageBonusMult * (1 + ability.c_a_level * Q3_AMPLIFY_PERCENT/100)
			Filters:TakeArgumentsAndApplyDamage(enemy, caster, damage, DAMAGE_TYPE_PHYSICAL, 1, RPC_ELEMENT_NORMAL, RPC_ELEMENT_GHOST)

**Comment by GoToNightmare** [comment]
fixed
