### ISSUE TITLE
Mithril shards overlapping

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#53]
While acquiring mithril shards from one boss and then killing another boss that gives more mithril shards, the result is the game giving you the shards from only the highest boss instead of the combined total of both bosses.

For example, my team kills Lord Scarloth and we receive 10k shards. I kill Treant in less time than it takes for us to receive those 10k shards. Treant gives 16k shards. We receive only 16k shards instead of 26k shards.

**Comment by ChalkyBrush** [comment]
fixed 100% and looks really awesome, enjoy rain of mithril next patch
