### ISSUE TITLE
Paladin W1 stacks expire MUCH faster than their tooltip indicates

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#531]
STEPS TO REPRODUCE:

1. be paladin with a bunch of points in W1. the rune's tooltip will probably say something like "Burn Duration: 52.5 seconds" or a similarly high value
2. equip Glyphs T2, T5, and T7. this is only important because the user who demonstrated this issue to me in-game was using them, meaning they may be responsible for the issue.
3. activate Q buff, then attack something several times. just beat the shit out of them. keep beating the shit out of them, and left-click them to watch their debuff bar.
4. observe as the W1 stacks expire almost immediately

**Comment by Nintai** [comment]
Could it be because of this lines in holy_wings.lua in function wing_attack( keys ):
```	if #enemies > 0 then
		local holyCone = caster:FindAbilityByName("holy_cone")
		if holyCone then
			if not holyCone.a_b_level then
				holyCone.a_b_level = 1
				holyCone.a_b_damage = 80
			end
		end```

Maybe holyCone.a_b_level is null and its then set to lvl 1?

**Comment by DeckardCainRPC** [comment]
F I C C s'd
