### ISSUE TITLE
Inspecting enemy units no longer brings up status panel, and it also aggros them

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#533]
probably volvo

**Comment by redledcat** [comment]
Haha, sometimes it deals damage HIGH ENOUGH TO ONESHOT creep.
Spamming tooltip build is here.

**Comment by DeckardCainRPC** [comment]
i have just received another report confirming that the status panel check can oneshot enemy units

Headhunter: So if i hover over the profile picture of an enemy in roshpit he just dies or takes an insane amount of dmg ..i just over over their pictures rapidly and they die
Headhunter: easy seafort lvl 1 i guess

...

Headhunter: nevermind i tested it a bit and it seems like its a flat amount of damage .. i used a 37k base dmg character and a character with 100 million dmg and its still nearly 0 to most enemies in sea fort so this bug is nothing to worry about i guess .. you can only do legend to some point

**Comment by redledcat** [comment]
Steadfast effectively blocks that "tooltip damage".
Post-mitigation tooltip damage please and some amps to make it feature.

**Comment by ChalkyBrush** [comment]
fixed
