### ISSUE TITLE
Lost item because cann't save and cann't reconnect to game? can return item?

### ISSUE THREAD

**Issue by amity111** [ChalkyBrush/roshpit-bug-tracker#534]
when i will save my character but cann't and then game was out. 
i reconnect again but it loading screen cann't see in game. my friend see me can reconnect but my screen cann't 
My friend can capture my item

..
![1](https://user-images.githubusercontent.com/40340165/41510236-27415af0-728b-11e8-87fb-a057a2d5ad14.png)
![2](https://user-images.githubusercontent.com/40340165/41510238-29bd6fc6-728b-11e8-8535-a07ce62ae578.png)
![3](https://user-images.githubusercontent.com/40340165/41510239-2b63f94e-728b-11e8-9581-54f02b4d613f.png)
![4](https://user-images.githubusercontent.com/40340165/41510240-2c92fa68-728b-11e8-9573-9162f9abfdd7.png)
![5](https://user-images.githubusercontent.com/40340165/41510242-2e280990-728b-11e8-9368-7a06168f3932.png)
![6](https://user-images.githubusercontent.com/40340165/41510243-30342714-728b-11e8-89c8-d8c54b7e2ac5.png)
![7](https://user-images.githubusercontent.com/40340165/41510245-31a2d15e-728b-11e8-985d-a1e32c765e18.png)
![8](https://user-images.githubusercontent.com/40340165/41510246-3369d3d4-728b-11e8-8e23-6fe82ac177fc.png)

**Comment by ChalkyBrush** [comment]
sorry mate
