### ISSUE TITLE
[Visual] Zhonik's arcana E shown radius and actual do not match

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#535]
It uses old pre-nerfed radius number 
![20180617211527_1](https://user-images.githubusercontent.com/32621322/41510917-62368bf8-726d-11e8-84f0-e5ac5e633d1b.jpg)

**Comment by redledcat** [comment]
It also seems "purple burst" particle has that bigger radius too

**Comment by bavibi** [comment]
Stange, I clearly remember myself changing it from 800 to 550

Oh, I remember now, I changed radius only in test version

**Comment by ChalkyBrush** [comment]
fixed by bavibi

**Comment by redledcat** [comment]
not fixed

**Comment by redledcat** [comment]
![20180621114910_1](https://user-images.githubusercontent.com/32621322/41708425-dcf92dfc-7540-11e8-83bb-4cf4c974e437.jpg)

**Comment by redledcat** [comment]
Frankly it's super minor bug
