### ISSUE TITLE
[Zhonik] Times Dilation stacks are lost sometimes when E cast with 1000 stacks

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#537]

**Comment by bavibi** [comment]
Everything is fine for me, something else is the problem

**Comment by redledcat** [comment]
I'll capture it

**Comment by redledcat** [comment]
Max distance does not matter apparently, but fully stacked 1000 stacks matter.
https://youtu.be/IDbRYxmSPKQ
https://youtu.be/QhENif3QqcU

**Comment by ChalkyBrush** [comment]
should be fixed now
