### ISSUE TITLE
Gorewreck 

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#54]
That's truly meme bug, which is constantly being reported.
100% deserves to be here.

![gorewreck1](https://user-images.githubusercontent.com/32621322/31817816-d397239c-b595-11e7-93b1-905c4e85906f.PNG)
![gorewreck2](https://user-images.githubusercontent.com/32621322/31817817-d3b598d6-b595-11e7-9450-266d127fff8a.PNG)
![gorewreck3](https://user-images.githubusercontent.com/32621322/31817818-d3d4d12e-b595-11e7-82e9-d721057b0059.PNG)
![gorewreck4](https://user-images.githubusercontent.com/32621322/31817815-d36d0c7e-b595-11e7-962e-ff2bcf98532a.PNG)

**Comment by redledcat** [comment]
probably it applies here
```Arena.ChampionsLeague.currentBattleRank == 11 then
	  	 	hero.ChampionsLeague.rank = 11
	  	 	Arena.ChampionsLeague.state = 19
	  	 	FindClearSpaceForUnit(Arena.Coach, Vector(-2524, -8576), false)
	  	 	local fv = ((hero:GetAbsOrigin() - Arena.Coach:GetAbsOrigin())*Vector(1,1,0)):Normalized()
	  	 	Arena.Coach:SetForwardVector(fv)
	  	 	Timers:CreateTimer(2, function()
	  	 		basic_dialogue(Arena.Coach, {hero}, "champion_assistant_dialogue_41", 6, 5, -30, true)
	  	 		Timers:CreateTimer(6, function()
	  	 			basic_dialogue(Arena.Coach, {hero}, "champion_assistant_dialogue_42", 6, 5, -30, true)
	  	 			Timers:CreateTimer(6, function()
	  	 				basic_dialogue(Arena.Coach, {hero}, "champion_assistant_dialogue_43", 6, 5, -30, true)
	  	 				Arena.ChampionsLeague.state = 18```

and 

``` if Arena.ChampionsLeague.state == 18 then
		Arena.ChampionsLeague.state = 19
		Arena:OgreSequence(hero)
		return false```

**Comment by Nintai** [comment]
Made a fix for this, should chalky decline, it just means that he was supposed to hit the noobs twice 😂

**Comment by redledcat** [comment]
oh no

**Comment by DeckardCainRPC** [comment]
6 OCTOBER 2016
