### ISSUE TITLE
Conjuror Arcana pet not inheriting correct attack damage from Halcyon Soul Gloves

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#545]
STEPS TO REPRODUCE:
1. equip any glove besides Halcyon Soul Glove to conjuror, alongside his body arcana
2. observe that the Elemental Deity pet inherits the correct attack damage
3. now, chisel off that glove, and replace it with Halcyon Soul Gloves
4. observe that the amount of attack damage the pet inherits is almost 2/3rds less than what it should have

player Zinato should be posting screenshots of this issue below

**Comment by bavibi** [comment]
Summon's attack damage is capped

**Comment by GabrielZinatoSP** [comment]
My conjuror's atk with Halcyon:
![conjuror atk halcyon](https://user-images.githubusercontent.com/40676510/42063351-a8f06ea4-7b07-11e8-8c50-3f43331efcf9.jpg)

Deity summoned with the conjuror having the same atk and buffs from the screenshot above:

![deity atk halcyon](https://user-images.githubusercontent.com/40676510/42063418-f0d221b8-7b07-11e8-84a6-0b0d2cc9b9dc.jpg)

Same build but with Echo gauntlet:

Conjuror's atk:
![conjuror echo gauntlet](https://user-images.githubusercontent.com/40676510/42063649-0712628e-7b09-11e8-9af2-8d0d3ddce6e3.jpg)

Deity's atk:
![deity echo gauntlet](https://user-images.githubusercontent.com/40676510/42063684-2ab8cdae-7b09-11e8-94ba-01c1c0b387de.jpg)

I was also under the suspicion it's not really Halcyon but some cap so I wanted to try something else. Wind Deity Crown afk at the dummy lol:

Conjuror's atk
![wind deity conjuror](https://user-images.githubusercontent.com/40676510/42064364-5b7ea8de-7b0c-11e8-8d75-4b949d9bc764.jpg)

Deity's atk:

![wind deity crown](https://user-images.githubusercontent.com/40676510/42064395-714815ce-7b0c-11e8-8e74-610336d7ce28.jpg)


And yes, I think you're right, bavibi. After 268m/13 atk (on the conjuror), which is around 20 648 880, the deity will always have those 268m.

Link to my build: https://www.roshpit.ca/players/124213765/heroes/320866

**Comment by bavibi** [comment]
It's not a theory, but a fact.
`damage = math.min(damage, (2^28)-10)`

**Comment by DeckardCainRPC** [comment]
@bavibi i knew it had a cap (and i told that to ALL THREE USERS who have reported Elemental Deity to me in the last 7 days), but i surely did not think it was as low as 268m. why is it that low? are other attack damage caps, like the one on Wolfir Druid Spirit Helm pets, also that low?

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush see above

if pet base attack damage is capped at 268m, and that value seems balanced (neither overpowered nor underpowered), then this can be closed. it just seems low to me - total attack damage has to exceed 2.14b in order to cause a highly undesirable underflow, and i can't think of many items or effects that could give 10x damage to the Elemental Deity pet (an allied sephyr's wolfir druid spirit helm is the only thing i can name off the top of my head)

**Comment by StillStealSteel** [comment]
Closed for now. Because it is intended and not a bug.
