### ISSUE TITLE
[Inventory] Something wrong with glyph books

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#548]
Well I see there is two issues right now
1)Books now missing tier and have "undefined" in tooltip
2) If book is taken out of pool and then put back, pool stucks and eats book. rip. please no more.

**Comment by redledcat** [comment]
![20180705003300_1](https://user-images.githubusercontent.com/32621322/42294685-347c3766-7fe3-11e8-89b4-63697619070c.jpg)

**Comment by GoToNightmare** [comment]
![20180710153727_1](https://user-images.githubusercontent.com/34166246/42505218-915ca2ae-8457-11e8-8d7d-439ce730cedb.jpg)
Maybe it is that sneaky bug when tooltips are goes crazy?

**Comment by redledcat** [comment]
well, ALL of my stored books are undefined now
