### ISSUE TITLE
Axe E3 and jugger E2 vs BKB

### ISSUE THREAD

**Issue by StillStealSteel** [ChalkyBrush/roshpit-bug-tracker#549]
Chalky i know that you made like year ago or so by someones request for some reason that slardar R3 hits magic immunes (rune skill that actually looks like magic, ok it activates by attack (hello gauntlet of the high flame)) skill that was already op and that still op for now. And totally forgot about phys based and actually looks like phys attacks: jugger E2 and axe E3, skills that not so op if you compare them to slardar R3.

Thank you.

**Comment by DeckardCainRPC** [comment]
the logic was that R3 is essentially a cleave effect, and like other cleave effects in Dota (and in RPC!), it should pierce Spell Immunity. 

if seinaru's E2 is Physical damage then it should pierce Spell Immunity despite being based on juggernaut's Blade Fury (which has no effect on Spell Immune units). Axe's E3 is similar, and deals Pure damage just like slardar's R3, so i think that's also a reasonable request.

**Comment by GoToNightmare** [comment]
Can you check it after the patch, ty.

**Comment by StillStealSteel** [comment]
I will test on axe for sure. Dunno about jugg, because i don't have one. Only if i will have time.
Thank you anyway.

**Comment by StillStealSteel** [comment]
Axe working confirmed (hit magic immune creeps). 
But at the same time i can hit invisible balanars on arena map.
And need to check how it interact with 3 balls (redfall ridge) summoner room, will it hit the balls? And on winterblight 3 in a row pazzle (didn't have time for this too).

**Comment by StillStealSteel** [comment]
Closed. Seems like working. If there is some weird interaction - new issue can be opened.
