### ISSUE TITLE
[Voltex] Cast of Static interrupts autoattack

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#550]
It has really long animation of "jumping" and while it plays Voltex wont autoattack her target.
Breaks Q and R2 builds.
https://youtu.be/APMl34lb9tk

**Comment by redledcat** [comment]
Can anything be done with that animation about a 1 second long?

**Comment by redledcat** [comment]
No idea where this delay spotted
(animation changing in pr 349 has no effect)

**Comment by redledcat** [comment]
Okay, any chance it's 
"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
because Seinaru's W is theoretically the same but uses instead
"AbilityBehavior" "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_AOE"
https://dota2.gamepedia.com/Cast_animation/Cast_backswing

**Comment by redledcat** [comment]
But you can still manually break this animation delay by manual orders. It breaks only dota autoattack.

**Comment by redledcat** [comment]
Problem spotted, it's AbilityBehaviour
"AbilityBehavior" "DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
will solve the thing

**Comment by ChalkyBrush** [comment]
actually I don't think it should be changed
