### ISSUE TITLE
[Winterblight] Hungry Ghost model is at least twice smaller than game thinks it is

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#553]
I cant capture cursor, but when ghost grows it makes really hard to actually hit on the ground, because message says "Target cannot be attacked"

**Comment by redledcat** [comment]
Also stuns work on this guy, at least Arkimus Q stuns him for 10s. Give little guy stun immunity please

**Comment by redledcat** [comment]
I think he is ok for now

**Comment by ChalkyBrush** [comment]
yea made him unselectable thx
