### ISSUE TITLE
[Winterblight] "Bejeweled" puzzle bugs

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#554]
![20180713234356_1](https://user-images.githubusercontent.com/32621322/42713080-6807c688-86ee-11e8-8986-82847b0acadc.jpg)

**Comment by redledcat** [comment]
![20180713234707_1](https://user-images.githubusercontent.com/32621322/42713145-b75e1b60-86ee-11e8-9e08-d67a71685548.jpg)

**Comment by redledcat** [comment]
we solved that 
![20180713235553_1](https://user-images.githubusercontent.com/32621322/42713488-f13b3272-86ef-11e8-9c17-6301fdc9e19c.jpg)
but bugged statues still remain

**Comment by redledcat** [comment]
and nothing happens

**Comment by StillStealSteel** [comment]
i think it fixed.
It should spawn a cup on the place of the grew crystall. And previously there was bug with cups and not this pazzle.

**Comment by redledcat** [comment]
The part with solving is fixed, but bugged figures remain

**Comment by redledcat** [comment]
They always start to bug in upper lines, where new figures "fall"

**Comment by redledcat** [comment]
![20180715161025_1](https://user-images.githubusercontent.com/32621322/42734681-8a410bd2-8848-11e8-884f-f0500415c067.jpg)

**Comment by redledcat** [comment]
Also bladesinger boots are hilarious.

**Comment by redledcat** [comment]
https://media.discordapp.net/attachments/299728973380976651/468054004488994836/unknown.png?width=261&height=198

**Comment by redledcat** [comment]
![20180718224944_1](https://user-images.githubusercontent.com/32621322/42904351-11faa964-8ad5-11e8-9946-4450fb4a7b24.jpg)

**Comment by redledcat** [comment]
![20180718225641_1](https://user-images.githubusercontent.com/32621322/42905120-62a0af2e-8ad7-11e8-84cd-14654f3010b6.jpg)

**Comment by StillStealSteel** [comment]
Yes, the bug remains. But you still can complete the pazzle.

**Comment by redledcat** [comment]
I captured the move which breaks the column of puzzle.
![20180801193216_1](https://user-images.githubusercontent.com/32621322/43535208-07d41fea-95c2-11e8-8772-423d51a48db3.jpg)
![20180801193219_1](https://user-images.githubusercontent.com/32621322/43535209-0925a04e-95c2-11e8-93f5-dbf75386ac64.jpg)
![20180801193225_1](https://user-images.githubusercontent.com/32621322/43535211-0a3a4ff2-95c2-11e8-985b-8376a5986730.jpg)
![20180801193226_1](https://user-images.githubusercontent.com/32621322/43535213-0b720d42-95c2-11e8-8983-698128b57ee0.jpg)

**Comment by redledcat** [comment]
And that part glitched and remained after puzzle solution
![20180801194028_1](https://user-images.githubusercontent.com/32621322/43535494-d9f34d02-95c2-11e8-994e-44c085e1124c.jpg)

**Comment by redledcat** [comment]
I noticed one more thing, sometimes "combos" do not count correct number of statues in line, had 5 statues dropped vertically and only 4 combined

**Comment by redledcat** [comment]
Yeah. Combo logic does not include if several lines combined in one turn.
I'll leave an example below.
It goes turn by turn, and table checks if there are combo lines above the previous line.
That leads in situation, if lower line makes combo using line far above the previous, mathes in between won't proc.
Here:
Red: triggered by player
Green: Second combo just little above the main trigger
Purple: Third combo after table found it
That third combo broke other two potencial matches, because they were below.
Yellow, which should be matched as well, and dark red, which should be the chain after yellow combo.
![20180812114607_1](https://user-images.githubusercontent.com/32621322/44000473-e84db3ba-9e28-11e8-8861-dea2101727a7.jpg)

**Comment by redledcat** [comment]
Sometimes 4-in-a-row lines from combo chain count as 3-in-a-row

**Comment by redledcat** [comment]
![unknown 2](https://user-images.githubusercontent.com/32621322/44047209-6655e0e4-9f36-11e8-885f-cd8711631e37.png)

this situation does not work either

**Comment by redledcat** [comment]
This type of combo is confirmed to make a glitched table.
If that appears in combo, vertical line breaks and statues merge one with others.
![unknown](https://user-images.githubusercontent.com/32621322/44049642-5793436a-9f3d-11e8-96c4-3438acf1fb1c.png)

**Comment by redledcat** [comment]
4-in-a-row combo issue visualized:
![unknown 1](https://user-images.githubusercontent.com/32621322/44313368-62463380-a410-11e8-81a1-1e46f1138d1e.png)

**Comment by redledcat** [comment]
![20180824215342_1](https://user-images.githubusercontent.com/32621322/44602559-9a6ebd00-a7e8-11e8-9b5e-a662ed85b657.jpg)

**Comment by redledcat** [comment]
Again, table break confirmed
![20180824220028_1](https://user-images.githubusercontent.com/32621322/44602761-34366a00-a7e9-11e8-91db-86240a451c96.jpg)
![20180824220035_1](https://user-images.githubusercontent.com/32621322/44602762-37315a80-a7e9-11e8-8354-0facec81c2bd.jpg)

**Comment by redledcat** [comment]
Somehow I broke puzzle completely.
Statues do not respond on hits, no links appear, nothing.
send help
![20181001220833_1](https://user-images.githubusercontent.com/32621322/46309982-bd9a4280-c5c6-11e8-9952-a3119b1bef0c.jpg)
Might be I killed something using warlord?

**Comment by redledcat** [comment]
pretty sure all old bugs are fixed by Nintai's rework!
one left is that total breaking the puzzle with W spam during link creation, maybe
