### ISSUE TITLE
[Winterblight] Paladin's Penance can target cups and accidently TP him

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#555]

**Comment by ChalkyBrush** [comment]
only if you have wind deity :P

**Comment by redledcat** [comment]
?

**Comment by redledcat** [comment]
His hand arcana ability called "Penance"
It does not interact with wind deity in any way
But it has its own "attack proc on hit", which makes cup activate

**Comment by GoToNightmare** [comment]
fixed by bavibi, now required attack command?
