### ISSUE TITLE
[Winterblight] Rerolling crystall in "Jewels" puzzle can be hit with any aoe 

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#556]

**Comment by ChalkyBrush** [comment]
only if you attack it, you must have wind deity

**Comment by ChalkyBrush** [comment]
nvm its on take damage not on attacked. is it really a bug though?

**Comment by redledcat** [comment]
dunno, just if you have arcane cascade or omni Q2 you cant approach top-right corner

**Comment by ChalkyBrush** [comment]
alright changed to onattack
