### ISSUE TITLE
Winterblight tooltip issues

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#558]
you did very well, only a couple of niggles

1. Boreal Granite Vest: targetted -> targeted

Energy Whip Gloves: targetted -> targeted

http://www.future-perfect.co.uk/grammar-tip/is-it-targetted-or-targeted/

2. Boreal Granite Vest tooltip change:

"[...] Targeted abilities are cast at the attacker (or the attacker's position), if they are within cast range."

(this one was requested by xhul'horac and 2 other people)

**EDIT: a similar change needs to be made to Energy Whip Gloves**

3. Orthox helm

"[...] Each stacks lasts 10 seconds" <--- should be "stack" singular

**Comment by redledcat** [comment]
well then
		"Focusing on a single target, Astral Ranger increases all post-mitigation damage dealt towards the targetted enemy for 8 seconds, stacking up to 50 times. Changing targets with Shot of Apollo resets this effect."
	"DOTA_Tooltip_modifier_stargazer_aura_Description"			"Targetted by Stars"

**Comment by DeckardCainRPC** [comment]
in my defense, the original document read as follows:
```
= ARCANA W4: Focus Fire =

"Focusing on a single target, Astral Ranger increases all
post-mitigation damage dealt every time she lands an attack,
stacking up to 40 times. Changing targets resets this effect."
```
so i didn't do it

**Comment by redledcat** [comment]
fixed next patch
