### ISSUE TITLE
Stargazer Orin

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#559]
He can jump through the will in this spot
![screenshot_11](https://user-images.githubusercontent.com/15161630/42729588-2d90b13e-87e5-11e8-909e-9c29ebc15651.png)
![screenshot_9](https://user-images.githubusercontent.com/15161630/42729587-2d730a3a-87e5-11e8-9614-27dc33bbc43b.png)

**Comment by DeckardCainRPC** [comment]
![untitled](https://user-images.githubusercontent.com/34521754/42731006-39a3f61a-87d2-11e8-8276-1cc3717ae5d1.png)

it's also possible (somehow) for his "bombard the target player with endless stars" effect to become permanent. maybe check resurrection effects such as world tree flower cache?

**Comment by redledcat** [comment]
@DeckardCainRPC I've seen that effect which causes it and I find it kinda funny.
Something debuffs your hero in these last rooms, and each cast of spell adds some stars to your counter.
After counter expires (or after death I guess) star shower begins. I got about 700 stacks of stars playing without hard spam and it lasted ~40s.

**Comment by redledcat** [comment]
that wall jump is fixed, even if he leaves area, he will correctly take his place after timer expires
