### ISSUE TITLE
Ancient God Water Form

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#56]
I remember it used to be _far far less painful_ before.
We reached 1 hp water god, as always, but even dealing multiple pure damage instances did not killed him.
His healing HP was jumping from 1 to 30000 several times per second, but he have not died for full water phase time.
![20171020155412_1](https://user-images.githubusercontent.com/32621322/31822003-62e85992-b5a7-11e7-95af-371339cb9d3e.jpg)
![20171020155413_1](https://user-images.githubusercontent.com/32621322/31822005-632c3c48-b5a7-11e7-8d16-5bc829cbed78.jpg)
![20171020155412_2](https://user-images.githubusercontent.com/32621322/31822004-63086cbe-b5a7-11e7-982a-d44c0973aba5.jpg)
I know it builds up the rarity of water deity, but so far we have a giant amount of these among community and there could be a function for water god to die if HP <1000

**Comment by ChalkyBrush** [comment]
should be fixed
