### ISSUE TITLE
[Winterblight] "Bejeweled" puzzle room instability

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#560]
this is one of those amorphous reports where we know the following facts to be true:

1. over the course of "normal" gameplay, the puzzle's game state can lose sanity. symptoms i have personally seen and reproduced include multiple statues occupying the same tile (*almost* always congregating at the left half of the very top row), and rendering the entire puzzle permanently inoperable.
2. "normal" gameplay in RPC consists of heathen barbarians completely failing to treat puzzles like puzzles, engaging them with frustrated beatings instead of patience and logic.

the barbarian responsible for completely breaking the puzzle, which truly impressed me, is my good friend [Sweet]. because of differences in russian phonetics, he referred to the room as a "pazle," so now every time somebody destroys one of these nice puzzles you've painstakingly brought into the world, i call the smoldering remains a "pazle" instead. he sure pazled the shit out of it.

i strongly suspect that the first issue i described is a result of the board resetting during a long "combo," wherein one move taken by the player results in a cascade effect of multiple pairs being cleared in sequence - i believe while the cascade is resolving, if a pair is generated and enters the board along the top row, that may be responsible for placing two statues on the same tile. since i have also seen "statue stacking" in other zones of the board, i'm reasonably sure that a cascade's resolution can proceed **WHILE** the board is being cleared automatically as a result of using up all of your "tries" along the bottom-most row. i'm sorry i can't offer more information, but maybe this will help an actual genius find the problem.

and i believe [Sweet] killed the pazle by just attacking the fuck out of every element on the board in a fit of caveman violence. when he was through, the game wouldn't respond to anything the player did, including attacking the white Reset Crystal.

**Comment by redledcat** [comment]
ok this pazle is half-fixed but I believe there still is a way to break it while randomly spamming skills
