### ISSUE TITLE
typo in arcana drop function ?

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#562]
line 1609 arcanas.lua
local item = RPCItems:CreateVariantArcana("item_rpc_astral_arcana3", "arcana", **"Astarl Arcana 3"**, "body", true, "Slot: Body", "npc_dota_hero_drow_ranger", 0)

**Comment by redledcat** [comment]
line 1648
local item = RPCItems:CreateVariantArcana("item_rpc_sephyr_arcana1", "arcana", **"Spirit Warrior Arcana 2"**, "hands", true, "Slot: Hands", "npc_dota_hero_skywrath_mage", 0)

**Comment by ChalkyBrush** [comment]
+
