### ISSUE TITLE
[Winterblight] Lion mob (Azalea Demon Spirit) swaps E and R abilities of PA and Bahamut

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#563]
E button misses its bind after that for remaining session.

**Comment by redledcat** [comment]
And it can actually swap it back (for PA at least, if I cast E3 nearby)

**Comment by redledcat** [comment]
It just twitched it like 10 times in a second when I casted E3

**Comment by ChalkyBrush** [comment]
pretty sure i fixed bahamut ( didn't test though) I'll do PA as well

**Comment by redledcat** [comment]
okay
![20180715161615_1](https://user-images.githubusercontent.com/32621322/42734446-47cb19e0-8844-11e8-9ca4-55ed2f488b43.jpg)
there also was super ancient rare bug which sometimes swaps these skills, I presume it is bash while switching between E and alt E.

**Comment by ChalkyBrush** [comment]
should be fixed now
