### ISSUE TITLE
Auriun's Shadow Flay glyph particle remains permanently when killing non-standard units

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#570]
https://i.imgur.com/KycFSCt.png

STEPS TO REPRODUCE:
1. be auriun with the shadow flay glyph on
2. go shadow flay one of the above units, as an example; they're the floating, breakable ice shards in Winterblight, and breaking them spawns a shitload of AA mobs with temporary BKB
3. observe that the shadow flay laser particle remains zapping them for the remainder of the game session, no matter how far away you go and no matter how many times you die

**Comment by redledcat** [comment]
#65
