### ISSUE TITLE
Paladin's E2 is not working

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#571]
The non-arcana E2 isn't damaging enemies at all.

**Comment by GoToNightmare** [comment]
![20180720020119_1](https://user-images.githubusercontent.com/34166246/42969829-e720aaf8-8bc0-11e8-9585-344c31917e05.jpg)
Can you provide more info how to reproduce it, please.

**Comment by Xhulhorac** [comment]
I just load into a map, go find mobs and watch as E2 isn't dealing any damage.

https://www.roshpit.ca/players/118352521/heroes/581112 you might wanna try for some item incompatibilities.

**Comment by GoToNightmare** [comment]
Well it probably was fixed but not realesed yet, can you check it after the patch.

**Comment by StillStealSteel** [comment]
Can someone check if this is fixed?

**Comment by Xhulhorac** [comment]
Still broken

**Comment by StillStealSteel** [comment]
It works. Just checked. How much damage do you have? Maybe it overflows?
