### ISSUE TITLE
[Winterblight] Spawn point for heroes is too close to Curator NPC, causing dialogue to pop up immediately upon connecting

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#574]
my suggested course of action is to move the spawn point about uh, 270 units east of its present position, for each of the 4 players

**Comment by ChalkyBrush** [comment]
in next patch

**Comment by DeckardCainRPC** [comment]
nop nop nop, Player 3 still has it pop up for them: https://i.imgur.com/ts3olwY.jpg

**Comment by redledcat** [comment]
![20180727154039_1](https://user-images.githubusercontent.com/32621322/43325427-4e47fc14-91bf-11e8-8248-6e8991194486.jpg)
Same as Player 2

**Comment by DeckardCainRPC** [comment]
i think this has been fixed for all players now
