### ISSUE TITLE
Energy Whip Gloves/Boreal Granite Vest interrupt previous orders when triggered

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#575]
STEPS TO REPRODUCE:
1. play as Sephyr and wear Wind Deity Crown with Energy Whip Gloves, and/or just a Boreal Granite Vest
2. get hit (if vest) or hit something with e2 (if glove) or both (if both), WHILE ALSO channeling R
3. as soon as either item's effect is triggered, Sephyr will stop channeling his ultimate immediately, surely resulting in an unheroic death

SUGGESTED COURSE OF ACTION:
i know that both items *currently* require that your hero actually be able to cast the spell (not disabled, spell is not on CD), and whereas those conditions are fine and good, having them interrupt orders - due to the fact that it attempts to manually cast the spell, instead of just resolving its effect instantaneously and independently - leads to spasticity like this.

there are plenty of examples, not at all limited to just Sephyr. Voltex using the Energy Whip Gloves has to be played by issuing attack-move orders instead of selecting specific targets. other heroes have W cast animations that are so long that the gloves have no effect or greatly diminished effect at maximum attack speed (Zhonik, monkey-mode Djanghor).

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush did you (or anyone else) remedy this by making Energy Whip Gloves remove the cast point on W when equipped? i need to know because of #629 

if this is the case, was the same thing done for Boreal Granite Vest?

**Comment by CallMeCatman** [comment]
@DeckardCainRPC [(Gif)](https://my.mixtape.moe/ixtaal.gif) I did some testing, and the vest **does not** remove cast point.

**Comment by DeckardCainRPC** [comment]
i no longer care
