### ISSUE TITLE
[Voltex] E1 illusions have a hardcap on their attack damage

### ISSUE THREAD

**Issue by darienchong** [ChalkyBrush/roshpit-bug-tracker#584]
PA's E1 illusions have a hardcap of 2^28 - 10 attack damage.
This is not indicated anywhere in the E1 rune description.

The relevant code can be found in electric_jump.lua (ConjureImage:234-235) and filters.lua (Filters::SetAttackDamage:289-293)

electric_jump.lua:234-235
```
local newDamage = caster:GetAverageTrueAttackDamage(caster)*5
    Filters:SetAttackDamage(illusion, newDamage)
```

filters.lua:289-293
```
function Filters:SetAttackDamage(unit, damage)
    damage = math.min(damage, (2^28)-10)
    unit:SetBaseDamageMin(damage)
    unit:SetBaseDamageMax(damage) 
end
```

is this intentional or is this a bug?

**Comment by DeckardCainRPC** [comment]
it is intentional, and similar hard damage caps are in place on various other units in RPC, including Conjuror's Arcana pet, and the wolves summoned by Wolfir Druid Spirit Helm, among others. this is to prevent the damage from underflowing when exposed to sufficient (often percentile) bonus damage; many heroes in RPC (specifically astral ranger and especially voltex) were easily capable of causing a summoned unit's attack damage to exceed 2.17 billion, causing it to underflow into the negatives. voltex is still capable of doing so with excessive W2.

**Comment by darienchong** [comment]
It doesn't work in preventing overflow though (e.g wih 97 W2 my illusions easily went over 2^31-1 AD), and it unnecessarily caps damage (since it doesn't work in preventing overflow).

Additionally, at 2^28 - 10 AD (the current cap), it takes only 15 W2 (!) to reach 2^31 - any more than 15 W2 and the illusion's AD will overflow anyway.

(2^28 - 10)\*(1+0.45\*15)/(2^31) ~= 0.9687
(2^28 - 10)\*(1+0.45\*16)/(2^31) ~= 1.0249

If this cap is designed to prevent overflow from happening it's not doing that job, so (in my opinion) it should either be fixed or removed.

**Comment by DeckardCainRPC** [comment]
i agree with your position entirely

EDIT: the underlying problem is very real; the present countermeasures against it are both insufficient and too restrictive, even in the course of normal gameplay. i invite suggestions by anyone as to adequate solutions

**Comment by darienchong** [comment]
To be honest I think a stat squish would be one of the better long term solutions, but that's not a fix that'd be limited to Voltex. 

In the meantime just limiting the illusions' white damage to (2^31-1) would prevent the standard overflow issue; the player would just have to be careful not to give them any further attack damage buffs.

**Comment by ChalkyBrush** [comment]
number reduction is currently in planning phase

**Comment by StillStealSteel** [comment]
Closed. Not a bug.
