### ISSUE TITLE
Zefnar can spawn as a Paragon unit; Regen Aura/Flash Heal make him unkillable

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#587]
now, if he's just Gargantuan, then he just gets 10,500 HP and the only problem there is that he's even more annoying. however if he gets Flash Heal or Regen Aura, then it actually ends the entire Winterblight run right there, because players have no means of defeating him, and he MUST be killed in order to progress.

**Comment by DeckardCainRPC** [comment]
if you want to still allow him to be a Paragon unit (which i think is extremely funny and therefore OK), then just set a flag on him that makes him unable to heal. that will fix this issue

**Comment by ChalkyBrush** [comment]
he already has "disabled healing" as part of his passive, are you sure that flash heal or regen does anything on him?

**Comment by DeckardCainRPC** [comment]
no somebody bitched at me about the *possibility* while they were bitching at me about him being able to be Gargantuan. i felt bad about laughing at their party's misfortune so i humored them with this thread as a karmic exercise
