### ISSUE TITLE
Missing info in hero tooltips

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#59]
Ekkan's arcana Q2
dominated unit also gains movement speed with each corpse charge 
Paladin Q
also gives additional movement speed
Solunia W4
Bleed deals magical damage

**Comment by redledcat** [comment]
![20171025180041_1](https://user-images.githubusercontent.com/32621322/32006161-4a38d536-b9a6-11e7-9035-1d08b23b535d.jpg)
It's x10 Sorc's heath, as well as armor of elemental is x10 of Sorc's

**Comment by ChalkyBrush** [comment]
fixed these

**Comment by redledcat** [comment]
@ChalkyBrush 
Bahamut's Wal of Impunity misses it's duration.

**Comment by redledcat** [comment]
![20171028182635_1](https://user-images.githubusercontent.com/32621322/32135821-71902cae-bc05-11e7-866a-44e21da42c6d.jpg)
It's Max Stacks count, not reduction per stack
