### ISSUE TITLE
Immortal Bug level requirement issue

### ISSUE THREAD

**Issue by DeckardsPet** [ChalkyBrush/roshpit-bug-tracker#593]
Moving immortal glyphs around in your stash causes the level requirement to change arbitrarily, and hold the level requirement when you attempt to equip it. 

To test, just move an immortal glyph around in your stash and watch the level requirement change.

Sorry for no pictures, my screen captures are too fat to upload.

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush i instructed him (Still Alive) to post this. the issue by itself (immortal glyph required levels going nuts) isn't too dramatic, but the underlying cause needs to be determined because it could have far-reaching implications.

**Comment by redledcat** [comment]
it's gone, I think
