### ISSUE TITLE
[Guard of Luma] Doesn't activate when victim is magic immune

### ISSUE THREAD

**Issue by darienchong** [ChalkyBrush/roshpit-bug-tracker#594]
As title states. 

Guard of Luma states:

Damage Type: PURE 
Element: Cosmic
ABILITY AUGMENT: @Ability1 damage instances have a 70% chance to be converted into lucent beams instead, dealing 400% of the ability's damage and providing flying vision over the target for 4 seconds. This item caps your Cosmic elemental damage bonus at 5000%.

However, it doesn't activate when the victim is magic immune.

Steps to reproduce:
Equip Guard of Luma.
Attempt to use (preferably magic damage) Q hit against a magic immune mob.
Notice that it doesn't proc.

**Comment by StillStealSteel** [comment]
You can't damage magic immune targets, if ability damage is magic.
`@Ability1 damage instances have a 70% chance to be converted into lucent beams instead, dealing 400% of the ability's damage` 
If ability doesn't affect magic immunes why luma should does (there is NO/0/ZERO damage from ability)?
And actually on some abilities luma procs even on magic immunes (at least it was, do not use it novadays on my builds).

**Comment by redledcat** [comment]
yes
In dota, there are 2 different flags "pure damage" and "pierces magic immunity"
Having one does not mean having the other.
In example, Bara Q1 is magical damage but also pierces magi immunity and applies on targets with immunity, so if you equip Luma on him, he will also damage them.
On the other hand, in Dota 2 there are A LOT of physical and pure skills which do not pierce immunity as well and you can easily find them out on wiki.
Look on damage classification here
https://dota2.gamepedia.com/Damage_types
and look on list of abilities which do not pierce spell immunity
https://dota2.gamepedia.com/Spell_immunity/Enemy_Interactions

**Comment by redledcat** [comment]
just small list of examples to make your searches easier
https://dota2.gamepedia.com/Slardar#Slithereen_Crush
https://dota2.gamepedia.com/Anti-Mage#Mana_Break
https://dota2.gamepedia.com/Pangolier#Swashbuckle
https://dota2.gamepedia.com/Outworld_Devourer#Arcane_Orb
https://dota2.gamepedia.com/Omniknight#Purification
https://dota2.gamepedia.com/Bane#Brain_Sap

**Comment by darienchong** [comment]
@StillStealSteel @redledcat 

My good friends,

Damage Type: **_PURE_**
Element: Cosmic
ABILITY AUGMENT: @Ability1 damage instances have a 70% chance to be **_converted_** into lucent beams instead

Damage that has been converted to **_pure_** damage should always be able to penetrate spell immunity.

For more information, see https://dota2.gamepedia.com/Damage_types#Pure

(taken from https://dota2.gamepedia.com/Damage_types#Pure)
> ...Pure damage affects spell immune units (since spell immunity does not block damage by itself)...

<br>

Steel, your points are completely irrelevant as they pertain to targeting issues, and not applying damage.

(taken from https://dota2.gamepedia.com/Damage_types#Pure)
> ...but that does not mean that a spell with pure damage can target spell immune units...

<br>

redledcat, all the spells that you have listed explicitly do not go through spell immunity; they are the exception, rather than the rule; see: https://dev.dota2.com/showthread.php?t=147086

In general, pure damage is known to penetrate spell immunity unless specifically stated otherwise (on the skill).

Hence, Guard of Luma, which does **pure** damage, should always penetrate spell immunity regardless of the original damage type (as it is converted, and not added on).

If the reliance on the original damage type is intentional behaviour, the tooltip should be amended to reflect this. Else, the item should be amended to always penetrate spell immunity.

**Comment by StillStealSteel** [comment]
I laugh so hard right now.
It's like always some dude who thinks he is smarter then everyone else appears and wanna teach someone else with his askew knowledge.
As you say, dude, as you say.

@snajef 
I have a quest for you. Go check how many RPC abilities and items have type damage: pure and how many of them actually pierce magic immunity.

**Comment by DeckardCainRPC** [comment]
@snajef i read through this thread, and i was about to reply when i realized @redledcat already said what i was going to add:

> In example, Bara Q1 is magical damage but also pierces magi immunity and applies on targets with immunity, so if you equip Luma on him, he will also damage them.

the fact is that, as the other developers have pointed out, much of the spell immunity interactions in Dota are implemented on a case-by-case basis. therefore RPC behaves in a manner consistent with the core game's mechanics.

**Comment by redledcat** [comment]
Problem is not Luma does not hit immune targets, it just inherits "piercing" or "not piercing" state from abilities. In current way as it's coded, if ability does not have this flag DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES
there is no way to change it by items.
Otherwise, changing the core of all abilities to have this flag on makes them, including **magical** pierce  spell immunity  (except they wouldn't deal damage but still would apply status effects like stuns or slow which makes no sense).
Moreover, changes to most of pure abilities came not that far ago. I.e. Trapper R and Seinaru R3 was not able to pierce BKB, DK w1 was not able, and in one of last patches from 20th of July axe E3, jugg E and OD arcana got piercing.

**Comment by darienchong** [comment]
@redledcat @DeckardCainRPC

Yeah, but this behaviour (inheritance of spell immunity piercing) isn't documented in the tooltip, so if it's intentional it should be mentioned in Guard of Luma's tooltip, much like how standard Dota 2 skills have the tag "Pierces Spell Immunity" listed in the tooltip.

I understand that most of RPC's spell immunity interactions are on a case-by-case basis, but isn't the general rule (inherited from Dota 2) that pure damage typically pierces spell immunity if the spell can target the enemy and it is not specifically listed that the spell does not pierce spell immunity? 

In any case, there should be some way to determine from the tooltip itself if the item/spell pierces spell immunity imo. 

@StillStealSteel 

Stop embarassing yourself.

**Comment by StillStealSteel** [comment]
What part of 
> Problem is not Luma does not hit immune targets, it just inherits "piercing" or "not piercing" state from abilities

you do not understand? How it should be mention in the tooltip?
And now you don't insist that PURE damage type MUST pierce spell immunity and didn't even mention that you was wrong. Now it's problem with tooltips, not your lack of knowledge or more like logic (that is even worse). Ok.

Closed.
