### ISSUE TITLE
[Winterblight] Stargazer battle room - bugged spawn of creeps

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#599]
When you normally go through Tri boss fight and open gates to that room, nothing will spawn until you reach end of the room.
Is it normal? Is it inteded?
![20180727130828_1](https://user-images.githubusercontent.com/32621322/43318908-66f43228-91ab-11e8-8c6d-286e9c444a28.jpg)
![20180727130901_1](https://user-images.githubusercontent.com/32621322/43318912-6a464970-91ab-11e8-822d-a1e36601f7bb.jpg)
![20180727130908_1](https://user-images.githubusercontent.com/32621322/43318915-6e112854-91ab-11e8-8475-f55cdf228550.jpg)
And here spawn starts
![20180727130916_1](https://user-images.githubusercontent.com/32621322/43318925-7792b9ba-91ab-11e8-8069-985dd8dffb1e.jpg)

**Comment by ChalkyBrush** [comment]
this has happened to me before, I was confused

**Comment by redledcat** [comment]
Well, that happens every single time when you dont skip to the stargazer

**Comment by ChalkyBrush** [comment]
actually fixed the trigger wasn't touching the ground
