### ISSUE TITLE
Venomort Immortal Glyph + Signus Charm bug.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#60]
Venomort's Immortal Glyph (The one that gives another skill to use on E) makes Signus Charm apply the double-cooldown on E twice, causing the cooldown to be quadrupled, rather than merely doubled.
Bug originally reported by Discord's Davi. I do no longer own the Immortal Glyph to confirm.

**Comment by ChalkyBrush** [comment]
interesting find, confirmed. and fixed!
