### ISSUE TITLE
Geode of lags

### ISSUE THREAD

**Issue by StillStealSteel** [ChalkyBrush/roshpit-bug-tracker#601]
I wrote it already any fast damage per second cause huge fps drops. It even procs on new void creeps from winterblyght because you can't do damage to them = 1 fps.
Geode sounds and particles should be removed.
I have 2 suggestions:
- Remove them completelly ( will be confusing for new players), but better overall.
- Remove sounds, and make particles of geode spawns not on mobs but on caster with some delay to it like 5 per sec at max for visibility that your geode works.

Your thoughts? Make venomancer great again.

**Comment by redledcat** [comment]
I like that one, sounds and particle effect spoils field of vision.
Roshpit heavily overloaded with particles, almost every rune has one, spells have complex particle effects, as well as items and mobs' spells and passives.
Speaking of which, new Sephyr arcana is a mess which covers whole vision, you barely can see a thing except HP bars.

**Comment by redledcat** [comment]
But the worst thing is passives of enemies which make high load on server.
Such as healing zombies in Sea fortress and armor stacking CK in shipyard.
Vampiric + Veno is destructive as well.
Add internal cooldown on these too, and probably rework Vampiric, it current state it's balancing between being useless at one hand and healing to full on the other.

**Comment by StillStealSteel** [comment]
> Roshpit heavily overloaded with particles, almost every rune has one, spells have complex particle effects, as well as items and mobs' spells and passives.

Dota wasn't designed around 123123 casts per second, so yes it is actually chalky's mistake to add so many particles.

> new Sephyr arcana is a mess which covers whole vision, you barely can see a thing except HP bars.

Even without arcana only with immortal weapon his W actually makes fps drops too and wide as half of the screen.

**Comment by ChalkyBrush** [comment]
geode can only have 4 particles every 1.5 seconds so I'm unsure why that causes lags?

**Comment by StillStealSteel** [comment]
I dunno, but every player experience this. And it is 100% around geode.

**Comment by redledcat** [comment]
maybe it's on math side? it appeart to be the most cancerous on some dummy units and high resistant mobs

**Comment by StillStealSteel** [comment]
I will test it today or tomorrow if it is related to math or particles.
But I had watching the task manager when there is fps drops from geode and CPU wasn't so load at all. Server side load?

**Comment by redledcat** [comment]
Hey just checked on AM with geode, only cogs are pretty laggy by themselves. Taky enemies like pudge or venge are ok. 
(Using fire crown though, so less particles and instances than water)
I'll put the cogs issue in different thread

**Comment by StillStealSteel** [comment]
Ye, seems like bavibi patch should fix the issue depends on the code (didn't test it yet though).

**Comment by StillStealSteel** [comment]
Now i almost don't even see geode procs.
So bavibi patch is working, but too low particles per second. Actually i still with necro have lags when there is 35+creeps or so and i have for gaming not that powerful laptop (dota itself on mid video setting has ~80 fps). But rpc on low graphics has from start like 50-60 fps.
