### ISSUE TITLE
Impossible to perform disabling junk loot if you have 3/4 and fourth player leaves

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#602]

**Comment by StillStealSteel** [comment]
@GoToNightmare 
`-disabling_junk_loot` should be reworked with some button/checkbox on hero pick the same as with music mute at least. Not sure if we have access to this ui in repository.

**Comment by DeckardCainRPC** [comment]
i worked with Tony on that, and i suggested, at some point in the future when the feature was finished, that the command be changed to ``-junk`` instead; many non-native English speakers play RPC and the string "disable junk loot" may be too much for them to remember.

i also strongly agree that (when the feature is finished!) it should probably be added to the UI, just like StillStealSteel suggested.

**Comment by StillStealSteel** [comment]
@DeckardCainRPC Isn't it already finished (the logic behind `-disable_junk_loot`)? Works fine for me.
