### ISSUE TITLE
Flamewaker arcana Q has trouble casting

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#605]
For the first 1-2 cast attempts, it fails during the cast point, leaving you to spam the Q button in order to actually cast it.

Probably caused by the Q3 improvement patch.

**Comment by Xhulhorac** [comment]
And sometimes it goes on cooldown and plays the sounds without actually doing anything.

**Comment by ChalkyBrush** [comment]
@bavibi

**Comment by redledcat** [comment]
@Xhulhorac 
Arcana Q now uses some kind of vector targeting.
It uses two points to build a vector and cast Q3 in a line.
![20180729092459_1](https://user-images.githubusercontent.com/32621322/43363624-7f945f3a-9311-11e8-92b0-af3bf7928872.jpg)

**Comment by redledcat** [comment]
However, @bavibi 
If you alternate ~movement order~ any other order and order to cast Q, nothing will happen, because it erases last point set, so you have to stand completely still.

**Comment by redledcat** [comment]
Now, how to put it on CD without anything happened, as Xhulhorac mentioned, 
You have to make any order in the moment of second point setting (Casting Q, casting Q second time and immediately make, i.e. movement order or attack order, or cast a spell)

**Comment by redledcat** [comment]
Isn't it better to use DK position always as vector's starting point?
Without proper vector targetting it makes usage of Q pretty difficult in battle, when you have to focus on casting R and W as well to survive. Q is important to in order to CC stunning crowd and sustaining Q2 buff, it's bad if we have to do 2 cast points to hake it happen once.

**Comment by redledcat** [comment]
At least put a remark in description that skill needs double cast to be performed

**Comment by redledcat** [comment]
that was super improved and became one of the sickiest skills in the game
close?
