### ISSUE TITLE
Purchased GYLPH disappear

### ISSUE THREAD

**Issue by jimmybilly** [ChalkyBrush/roshpit-bug-tracker#606]
I wanna purchase a GLYPH , i bought it but it didn't appear in my inventory

**Comment by DeckardCainRPC** [comment]
https://www.youtube.com/watch?v=J3ywroqsgPk

**Comment by DeckardCainRPC** [comment]
in seriousness, i've fielded a couple of reports over the last 4 days, where the Glyph Enchanter NPC has just frozen and stopped working for the remainder of the game session.

here's what i know about this bug so far:
1. it isn't constrained to any specific map
2. it isn't constrained to any specific hero, or purchase
3. once it occurs, it will lock up the NPC for that specific player for the rest of the game session

that's all i've got. it may be a server communication error, and if it is, @ChalkyBrush you'll have to take a look at it to figure out whether it's valve's fault or ours

**Comment by ChalkyBrush** [comment]
fixed!
