### ISSUE TITLE
Magnetic Aether Q4 doesn't work (new voltex hear arcana)

### ISSUE THREAD

**Issue by StillStealSteel** [ChalkyBrush/roshpit-bug-tracker#609]
If there is more then one orb of Q (thermion magnet) flying then Q4 doesn't buff you if one of them ends. Only when the last one ends you receive the buff.

**Comment by ChalkyBrush** [comment]
it was intentional this way, to encourage something other than spamming Q. If it's really bad it's a balance issue more than a bug
