### ISSUE TITLE
Auriun's R4

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#61]
It works only on alive targets, but not on revived teammates, even if they are resurrected in ability range.

**Comment by FortuneReborn** [comment]
Worked fine for our party just a few hours ago.

**Comment by redledcat** [comment]
I've returned with proofs.
MK died 
![20171021130237_1](https://user-images.githubusercontent.com/32621322/31850754-5be06c00-b658-11e7-8073-651ff5b5de28.jpg)
MK revived 
![20171021130255_1](https://user-images.githubusercontent.com/32621322/31850755-5e61e42c-b658-11e7-8143-f6249475a38b.jpg)
Both teammates freshly revived
![20171021130331_1](https://user-images.githubusercontent.com/32621322/31850757-6d341650-b658-11e7-8877-e2857b29f80b.jpg)
MK again
![20171021130224_1](https://user-images.githubusercontent.com/32621322/31850763-8bd8c97a-b658-11e7-9301-41ec697d544c.jpg)

**Comment by redledcat** [comment]
But I cant reproduce it 100% being sure it wont work. Distance doesnt matter, had that bug both in close and ranged distance.
Something occures it, but much more tests needed.

**Comment by StillStealSteel** [comment]
Did you tried it without this immortal weapon? Think it can be related to it.

**Comment by redledcat** [comment]
Update. Created new Auriun, got those items while leveling. Bug still breaks through.
![20171025135733_1](https://user-images.githubusercontent.com/32621322/32015721-398760a6-b9c2-11e7-90eb-abc8892382e7.jpg)

**Comment by Nintai** [comment]
Already fix this some time ago :)
