### ISSUE TITLE
Red General's arcana R3 doesn't seem to work

### ISSUE THREAD

**Issue by Xhulhorac** [ChalkyBrush/roshpit-bug-tracker#618]
Enemies don't get the debuff and the damage is lower than it should if it worked.

**Comment by redledcat** [comment]
#518 
is damage truly lower?

**Comment by Xhulhorac** [comment]
If I didn't mess up my calculations. Dummy shows what I calculated, without R3's bonus.

**Comment by StillStealSteel** [comment]
I will look to it closely.

**Comment by StillStealSteel** [comment]
The debuff is just hidden.
Maybe you do not see a lot of damage increase because it addictive to other normal damage Q4/%normal damage from immortal weapon?

What desctiption says about the duration of r3? In game, not on the site for sure.

**Comment by redledcat** [comment]
6 seconds in tooltip.
meanwhile ARCANA1_R3_DURATION = 9

		"modifier_axe_rune_c_d_arcana1_invisible"
			{
			    "IsDebuff"  "1"
				"IsHidden"	"1"
				"TextureName"	"axe/axe_rune_c_d_arcana1"

no visible modifier, _but hidden one has icon_

**Comment by redledcat** [comment]
meanwhile ARCANA1_R3_DURATION = 9

**Comment by StillStealSteel** [comment]
> meanwhile ARCANA1_R3_DURATION = 9

Yes. That's why I asked.  And you are sure about invisibility of the debuff? 
For the first glance I didn't find any wrong logic in the code.

**Comment by Xhulhorac** [comment]
My R3 currently shows 1800% increase so I should get at least some damage if it worked. But when I calculate how much R should deal, and I leave R3 away from it completely, I get what dummy shows.

**Comment by bavibi** [comment]
Everything fine for me

5169(attack dmg) * 7(attack mult) * 4.8(r1) * 1.3(r3) * 0.05(q3) = 11289.096

5169 * 7 * 4.8 * 1.3 = 225781.92
![screenshot_30](https://user-images.githubusercontent.com/15161630/43571695-4b198d42-9646-11e8-8a85-e5004a20a05d.png)

**Comment by redledcat** [comment]
![20180802112215_1](https://user-images.githubusercontent.com/32621322/43571783-80ebfdf6-9646-11e8-9e56-0599c320c8ed.jpg)

**Comment by redledcat** [comment]
so, just make visible modifier and we done here?
calculated damage too, all amplifiers are fine for me as well

**Comment by StillStealSteel** [comment]
Should be fixed in the last patch (or when Chalky will update).
