### ISSUE TITLE
Pause screen tips are god damn annoying

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#619]
especially for the Math Puzzle

this is another one of those problems where we figure out how to undo some evil that Valve has inflicted upon us

**Comment by redledcat** [comment]
please

**Comment by bavibi** [comment]
![screenshot_28](https://user-images.githubusercontent.com/15161630/43414197-c67b5cd0-943a-11e8-869f-f9445357dcf6.png)
This also affects pause tips

**Comment by DeckardCainRPC** [comment]
jesus christ. thank you
