### ISSUE TITLE
[Tooltip][Andromedaeus Proxy Hemet] Q3 Compression

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#621]
Enemies hit by comets receive a stacking debuff that increases all post-mitigation damage taken from all sources for 6 seconds. Max 10 stacks and the ~~comet~~ **lunar** and solar debuff can be active at the same time. Additionally a portion of attack damage is added to comet damage.

**Comment by ChalkyBrush** [comment]
+1
