### ISSUE TITLE
Bug of feature? arena_riki_ult used by riki in sea as well hits 6 instances with 0.03 interval

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#624]
iirc riki had intervals in arena league battle before in 2016-17
![20180731103708_1](https://user-images.githubusercontent.com/32621322/43445030-f82756f8-94ad-11e8-89c6-b96de1d71890.jpg)

**Comment by StillStealSteel** [comment]
Found them painful too if you you are playing as melee. So much damage.

**Comment by redledcat** [comment]
well I won't talk about them being paiful, most of mobs are "kill or be killed"
just think 6 instances of pure damage in 0.24s is questionable

**Comment by DeckardCainRPC** [comment]
questionable indeed

**Comment by StillStealSteel** [comment]
This riki "oneshots" through frozen heart.

**Comment by redledcat** [comment]
probably fine for now
