### ISSUE TITLE
Vision broken by unacceptable amount of effects.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#627]
Preamble. 
Me and my friend picked arcana Sephyr (!) and  arcana OD (!!) for doing Winteblight (!!!).
These three things are known to produce a lot particles just by themselves.
Main story.
Apart from locking out FPS on low values, that did following. At one moment of a time, while we were spamming especially intensively, vision we both had was gone. (Just as vision disable by snarlroot trees in redfall. After some blind kills we managed to return vision partially, but all enemies and treasure chests remained invisible for us, unless they reveal invisibility by attacking us as a target.
I had same issue on high serengaard waves, when number of junk loots and bugged arcane crystals get to critical point.
Some screenshots to show a problem. Red circles = invisible enemies.
![20180802173509_1](https://user-images.githubusercontent.com/32621322/43592551-767aefd4-967e-11e8-839a-194378ae5b1a.jpg)
![20180802173521_1](https://user-images.githubusercontent.com/32621322/43592445-3f517fb4-967e-11e8-9e01-b90b2222bc79.jpg)
![20180802173520_3](https://user-images.githubusercontent.com/32621322/43592451-40d4fce4-967e-11e8-9af1-68f3017878a1.jpg)

**Comment by GoToNightmare** [comment]
I don't know the truth but i think max particles amount is restricted by dota, since some other custom games have same issue.

**Comment by redledcat** [comment]
good old entities issue

**Comment by ChalkyBrush** [comment]
wow this was the darkest period, I'm so happy we solved this
