### ISSUE TITLE
my fire queen staff dissapeared and got replaced by a default normal staff even tho i saved the game 

### ISSUE THREAD

**Issue by zululwarrior123** [ChalkyBrush/roshpit-bug-tracker#631]

**Comment by DeckardCainRPC** [comment]
can you please post a link to your profile on roshpit.ca? for example, here is mine: https://www.roshpit.ca/players/72513648

**Comment by redledcat** [comment]
well, my theory is 
1) loading function sometimes fails and doesn't load items properly, and after that player saves empty slot
or else
2) Saving fucntion can fail and actually doesn't work. I saw this on new account when timer goes on cooldown, but character is not saved (checked on website)
