### ISSUE TITLE
[Winterblight] Normal difficulty - Stalacorr

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#634]
That Stalacorr enemy has 750000 (Sea Fort value) on normal difficulty, in area you reach with lv 15 character
![20180805141009_1](https://user-images.githubusercontent.com/32621322/43685385-d7fb5aa8-98ba-11e8-948f-1954eb57781c.jpg)

Usually at this point character has 500-100 armor dependant on gear rolls, and about 30-50k HP.
The values of armor should exceed 1500 armor to tank that damage.
Other units in this area have lower than 1000 attack damage, except frozen CK with moon beam field, he has 2000-3000 damage.

EVEN if it's designed to be monster with good damage to force the player for ranged battle, he must have much lower attack damage. For some other units, damage, on the contrary, should be buffed slightly.
And I have to mention that Stalacorr has 1600 exp gain base. Several deaths put into effort of killing it aren't worth it.

**Comment by redledcat** [comment]
I think optimal range for normal is under 100k of attack damage in first half of an hour of game.
Some redfall mobs need balance changes as well.

**Comment by DeckardCainRPC** [comment]
mm, i see what you mean. yes i think the suggested course of action should be giving Stalacorr permanent haste and free pathing, and each of his autoattacks should be accompanied with the same giggling noise that Juggernaut mob in the Fire Temple spams constantly.

**Comment by redledcat** [comment]
I found out it's actually 10 times lower than sea fortress lesser stalacorrs (my bad), but still it's pretty op.
