### ISSUE TITLE
Sorceress + Astral Ranger malfunctioning interaction

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#64]
Game frequently crashes when new reworked cm+drow are in one lobby.
How to reproduce the crash:
1) Arena map to have better chance of crash
2)Distance between heroes less than 3000 for firts casts
3)Sorceress casts Blink
4)Astral Ranger casts E
6 dupm files included
[crash dumps.zip](https://github.com/ChalkyBrush/roshpit-bug-tracker/files/1403954/crash.dumps.zip)

**Comment by StillStealSteel** [comment]
You need to have E1 on astral as far as i know. Because my drow (without any point in E1) never does crashes with cm.

**Comment by redledcat** [comment]
True, pegasus needed, forgot about that.
That seems to be particle issue, since pegasus model was changed.

**Comment by ChalkyBrush** [comment]
wow 3 hours later I got it fixed. Really obscure bug
