### ISSUE TITLE
[Drow Ranger]:bug or?  Twisted yellow mask of Ahn'Qhir

### ISSUE THREAD

**Issue by Secretov** [ChalkyBrush/roshpit-bug-tracker#640]
have mask or no but drow need 0.8 sec(2 sec with arcana glove) to use W...That bug or i just dont understand what this item doing?

**Comment by redledcat** [comment]
Drow's W has no cast point, it's channel ability.
You basically change cast point from 0 to 0.05, channel remains 0.8s
		"AbilityCastPoint"				"0"
		"AbilityChannelTime"			"0.8"

**Comment by StillStealSteel** [comment]
Closed. Not a bug.
