### ISSUE TITLE
Axe has a Mythical weapon also named Red Battlefury

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#642]
i suggest renaming *it* (the mythical weapon) instead of the Immortal Red Battlefury, simply because the Immortal version is the one players most associate with the name. nobody will care if we rename the mythical one.

**Comment by redledcat** [comment]
"DOTA_Tooltip_ability_item_rpc_warlord_glyph_6_1"		"Glyph of Elements"
		"item_rpc_warlord_glyph_6_1_description" 				"Increases the maximum Fire, Ice, and Earth charges to 25."

"DOTA_Tooltip_ability_item_rpc_neutral_glyph_2_3"	"Glyph of Elements"
		"item_rpc_neutral_glyph_2_3_description" 			"Increases all elemental damage by @glyph_property1%"

**Comment by ChalkyBrush** [comment]
fixed both (next patch)
