### ISSUE TITLE
Dinath's E2 only recalculates on gear equip, not respawn or adding more E2

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#644]
and it's pissing me off super bad

**Comment by DeckardCainRPC** [comment]
like every time i load into a game, and every time i die, i'm short several MILLION attack damage, so i have to go back to the Blacksmith and chisel all my Bonus Attack Damage shit off and put it back on just to get E2 to recalculate

**Comment by ChalkyBrush** [comment]
working on this one now, off work early today 🚶

**Comment by ChalkyBrush** [comment]
fixed so it calculates every second (next patch)
