### ISSUE TITLE
Specific cell in SeaFort right wing can fail to create exit portal when completed

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#648]
https://i.imgur.com/2qZ4Owo.jpg

**Comment by redledcat** [comment]
that specific cell spawns enigmas with midnignt pulses HP removal.
can they kill portal spawm by any chance?

**Comment by ChalkyBrush** [comment]
wow high IQ @redledcat that's probably it, because why would this start happening now?

**Comment by redledcat** [comment]
It does not appear to happen normally, but I could try to bug it somehow.
I guess everyone tries to kill these enigmas before they even think about cast midnight pulse, but maybe if you fail and keep they alive for excessive 0.1 seconds, they will cast it and kill portal. Just a theory.
..
This it quite hard to reproduce tho, even if it's possible.

**Comment by redledcat** [comment]
No, it does not affect spawn by any means.
![20180814171058_1](https://user-images.githubusercontent.com/32621322/44096952-41ce1c46-9fe5-11e8-8d66-087880431a6d.jpg)

**Comment by redledcat** [comment]
I have one more theory, maybe axe could move it or move enigmas somewhere with his E

**Comment by DeckardCainRPC** [comment]
well gentlemen, if my president can blame russians for a complete mystery, that they know even less about than we do, then so can i
