### ISSUE TITLE
Auriun R2 causes recursive loop with Stone of Gordon + Captain's Vest

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#651]
@ChalkyBrush the community has known about the fact that Auriun's R2 does not exclude rolls to **multiple** runes (e.g. Stone of Gordon and Aquastone Ring) for probably two years, and we've all simply elected not to inform you of it because there just wasn't any way to abuse it.

with the introduction of Captain's Vest, however, you can now slap on some big R2 gear in helm, hands, and boot... then equip Captain's Vest with +T2 runes, then equip Stone of Gordon, and observe a preposterously high R2 along with massive bonuses to every other rune.

aaaaaaand then you chisel off Stone of Gordon, CREATING CHAOS: you will lose an amount of R2 which is definitely higher than the +16 or +17 your slick Gordon had. THEN, when you RE-EQUIP said Gordon, your R2 value will be restored, **PLUS SOME** (!!!). you may then chisel off the Captain's Vest, and witness another huge drop in R2, and if you re-equip it, you will again observe a net increase in R2. you may continue to alternate equipping and unequipping these two items, back and forth forever, ))<>((, until you run out of mithril shards OR your stats overflow. or both.

**Comment by ChalkyBrush** [comment]
made all + multiple runes not work with R2.
kinda sad for aquastone but if I just stop "All t2 runes" from being boosted it will be too inconsistent
