### ISSUE TITLE
Dummy in Redfall does not work properly

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#66]
1. Armor function does not work
![20171021132105_1](https://user-images.githubusercontent.com/32621322/31850849-81088dda-b65a-11e7-8caf-643bb7026faf.jpg)
2. DPS meter does not work
![20171021132118_1](https://user-images.githubusercontent.com/32621322/31850850-874c75a8-b65a-11e7-85ae-ce902ea75c6e.jpg)

**Comment by ChalkyBrush** [comment]
fixed
