### ISSUE TITLE
Axe's Arcana still crashes servers

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#668]
https://www.roshpit.ca/players/72513648/heroes/778980 singlehandedly destroys a server with no assistance from any other player, let alone enemy targets

the issue is the Elder Titan ult particle itself, Spur Shock does the exact same thing but it exists for a shorter amount of time and is smaller in scale

**Comment by redledcat** [comment]
I'm going to copy it and try myself

**Comment by redledcat** [comment]
OOOOOOH I SEE NOW
but that's different kind of a bug, Deckard, isn't it XD

**Comment by redledcat** [comment]
https://youtu.be/ZNwLhv0hPnQ

**Comment by redledcat** [comment]
By the way, server is alright, and moreover, my client is all right!
150 fps back when turned off obs and stopped spam, but yeah, 5 fps guaranteed with hard spam
manual spam without macro only 24 fps, so I guess we are going in right direction
just some particles need to cut off

**Comment by DeckardCainRPC** [comment]
i tested this after Dragon changed the T7 glyph's implementation, and it's mostly fine. the issue has gone from "absurd" to merely "unreasonable" and i think that's where we want it. spamming the ability in its present form doesn't generate as much latency as slardar or E1 voltex builds, for example, so we're good.
