### ISSUE TITLE
Boards in Arena missing textures.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#674]
![image](https://user-images.githubusercontent.com/32621322/44312993-35425280-a409-11e8-98fb-492def7e136e.png)

**Comment by ChalkyBrush** [comment]
volve removing textures again, nice

**Comment by redledcat** [comment]
yeah
![image](https://user-images.githubusercontent.com/32621322/44313015-6a4ea500-a409-11e8-9184-d9573e93bb7a.png)

**Comment by redledcat** [comment]
btw some columns here and in winterblight are transparent-black color

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/44313022-85b9b000-a409-11e8-8da3-57ff96a14fba.png)
like this one

**Comment by ChalkyBrush** [comment]
pretty sure is fixed
