### ISSUE TITLE
Spawners' mobs do not inherit reductions from glacier stones buff.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#675]
Nintai found it and reported, and probably it's already in pull requests, but anyway.
Creeps on any spawners: that spawner with gravelfoot, zealot spawners, first spawner room in castle.
Maybe even stargazer battle, they all do not inherit any reductions except difficulty ones.
![20180819082056_1](https://user-images.githubusercontent.com/32621322/44313257-cb787780-a40d-11e8-802c-41386c05fc2f.jpg)

**Comment by ChalkyBrush** [comment]
fixed
