### ISSUE TITLE
[Venomort] Reapers (Phantasmal Killers) trying to rape any dummy unit in game

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#677]
including ghost food 
![image](https://user-images.githubusercontent.com/32621322/44363761-ca0e8400-a4cd-11e8-88ec-18d23db4402f.png)

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/44363855-16f25a80-a4ce-11e8-87c3-7f9c852db78d.png)
and ghost too

**Comment by redledcat** [comment]
WHERE IS JOHNNY
![image](https://user-images.githubusercontent.com/32621322/44364640-325e6500-a4d0-11e8-89e6-dfb1b3641def.png)

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/44365430-7488a600-a4d2-11e8-81dc-a01fda030bd5.png)

**Comment by ChalkyBrush** [comment]
lol fixed for next patch
