### ISSUE TITLE
Conjuror skill "E"

### ISSUE THREAD

**Issue by Maxyahiko** [ChalkyBrush/roshpit-bug-tracker#678]
The ability "E" says that it deals pure damage, deals magic. And rune "E2" deals pure damage, and written magic.

**Comment by 1fmn1** [comment]
Can confirm E deals magic damage. E2 works normally, it has E4 pure damage interaction. But something wrong with damage calculation.
![image](https://user-images.githubusercontent.com/17130245/46243370-36897680-c3dc-11e8-9e8e-e0c3056ae5b0.png)
As you can see there is only E4 x3 damage bonus. No BAD and element bonus applied on E4.
![image](https://user-images.githubusercontent.com/17130245/46243376-515beb00-c3dc-11e8-9fdc-1000fed64bb1.png)
