### ISSUE TITLE
Winterblight Skull ring has old descriptions of glyphs in hero profile

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#679]
i.e. seinaru glyphs shown as super old ones, t1 says it increases konokaze distance but it was changed to lifesteal a while ago.
Same for many other glyphs. Update?

**Comment by ChalkyBrush** [comment]
ALL glyphs descriptions have been updated
also every skill and rune have been updated as well

**Comment by redledcat** [comment]
@ChalkyBrush 
orly?
https://www.roshpit.ca/players/91933876/heroes/733981
check ring property

https://www.roshpit.ca/players/91933876/heroes/216641
check glyphs on bottom, gian slay3r and gourmand

**Comment by redledcat** [comment]
Hero pages profiles do not receive updates

**Comment by redledcat** [comment]
moreover,
https://www.roshpit.ca/heroes/Auriun 
t3 glyph
https://www.roshpit.ca/heroes/Ekkan
t5_a glyph

**Comment by redledcat** [comment]
spirit warrior t7
https://www.roshpit.ca/players/91933876/heroes/570379
https://www.roshpit.ca/heroes/Spirit%20Warrior
