### ISSUE TITLE
Seafort "Venomous Dragonfly" mobs severely overtuned

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#680]
10k magic damage every 0.03 seconds is absurd anyway, but the fact that it receives the map's global creep damage amp on top of that makes it instakill anybody who doesn't have permanent magic immunity

**Comment by ChalkyBrush** [comment]
it's dodgeable :)

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush i'm reporting this only because i've had 7 users who spoke 4 different languages (persian, russian, indonesian and malay) report this to me as a "bug" that i should "fix" just in the last month

**Comment by redledcat** [comment]
if it's dodgeable your hero must cover about 2500 distance with i-frames here in order to "dodge" all these gales flying.
https://youtu.be/0K7TQs-Qrug?t=2103
only way is face them in battle and kill before they kill you or win in tanking.

**Comment by redledcat** [comment]
and other perfect spot is here.
https://youtu.be/0K7TQs-Qrug?t=2311
you must go DIRECTLY in direction these gales are shooting from, so yeah, most of players use **dodge** to **dodge** that whole venomous part using vertical jumps over walls

**Comment by redledcat** [comment]
I guess main purpose of these must be "shield removal" effect to exposure hero before other powerful enemies (like these pure strike goat ladies in the same room, or OD with huge damage, etc.)
It's not a bug, but heroes overall dont have enough *reliable* ways of sustain to cover such an amount of periodical damage, check how my Zhonik vaporizes after single hit, and it requires whole HP collected by potions, and 96 stacks of crabbo glove.
I mean, Zhonik not even bad in survival, he has good resist from E sphere and Q4.
But most of heroes just physically cant facetank it. Cherno? Paladin? Trapper? Slardar? BKB is must have here for melee ranged spells and attacks, or death.
