### ISSUE TITLE
Duskbringer R2 has unwritten 20 stack limit

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#684]
it shouldn't

the tooltip says nothing about it, and his R is not good anyway; the spell itself is great, and r2 and r3 are great, but r1 is 1% per level, far far far far faaar lower than similar abilities on many other heroes. this is compounded by the fact that the spell doesn't deal *a multiple* of duskbringer's attack power, like axe's arcana or venomort's arcana, it's just 1x total attack power.

**Comment by ChalkyBrush** [comment]
fixd
