### ISSUE TITLE
[Pit of Trials] Pitlord has brand new secondary weapon from Grimstroke

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#688]
![20180826201830_1](https://user-images.githubusercontent.com/32621322/44630902-53f69b00-a96d-11e8-9780-687c51f490e8.jpg)
![20180826201752_1](https://user-images.githubusercontent.com/32621322/44630904-5fe25d00-a96d-11e8-8355-48d5895a7bb5.jpg)

**Comment by ChalkyBrush** [comment]
i guess they changed item definitions, I should be able to fix this

**Comment by redledcat** [comment]
got it.
"666"
		{
			"name"		"Grimstroke's Weapon"

**Comment by ChalkyBrush** [comment]
fixed
