### ISSUE TITLE
[Tooltip] Paladin Q

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#691]
"DOTA_Tooltip_modifier_holy_wings" 								"Heroic Fury"
		"DOTA_Tooltip_modifier_holy_wings_description" 					"Enemies are damage and knocked back in an area on attack. Attacks also heal the Paladin."

Knockback was removed long time ago (hand arcana iirc)
**damaged**

**Comment by ChalkyBrush** [comment]
fx
