### ISSUE TITLE
[Cooldown] Legion T1 glyph + Hood of Lords wrong cd reduction

### ISSUE THREAD

**Issue by CallMeCatman** [ChalkyBrush/roshpit-bug-tracker#694]
Hood of Lords combined with Mountain Protector's T1 glyph reduces the cooldown of her Q by 3 seconds when it should be 2 seconds.
![test_legion_q_cd](https://user-images.githubusercontent.com/22331658/44806301-951cc400-ab94-11e8-99fa-d3884c02a53d.gif)

**Comment by redledcat** [comment]
it's not a thing anymore, glyph changed and cd changed too
