### ISSUE TITLE
Glyphs tooltip typo

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#70]
Glyphs of lesser str and agi have old numbers in description (500 is current value)
![20171021184328_1](https://user-images.githubusercontent.com/32621322/31853398-fdaa02d8-b687-11e7-9bca-0d7da678ceaf.jpg)
![20171021184329_1](https://user-images.githubusercontent.com/32621322/31853399-fdca9e4e-b687-11e7-9b8d-8e7a4e1f3684.jpg)

**Comment by ChalkyBrush** [comment]
fixed!
