### ISSUE TITLE
Bavibi broke OD Arcana Q1

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#700]
everyone (but me) was already aware of this, so i'm just putting on the tracker for visibility. he's already written a fix, it just needs to be pushed

**Comment by ChalkyBrush** [comment]
https://github.com/ChalkyBrush/Roshpit-Champions-Hero-RPG/pull/150

**Comment by DeckardCainRPC** [comment]
thank you
