### ISSUE TITLE
New Winterblight + 3 glacier stones star probably broken

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#701]
![20180903002436_1](https://user-images.githubusercontent.com/32621322/44960874-d522d480-af0f-11e8-8293-02817c1299c8.jpg)

**Comment by redledcat** [comment]
![20180903002620_1](https://user-images.githubusercontent.com/32621322/44960881-013e5580-af10-11e8-9b26-b60e1bc42a53.jpg)

**Comment by ChalkyBrush** [comment]
damn sry, it's fixed locally and will work next update
