### ISSUE TITLE
[Tooltips] Several arcanas and weapons which refer to abilities are messed up.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#706]
![20180903224657_1](https://user-images.githubusercontent.com/32621322/45000188-8b97bf80-afcb-11e8-8951-08105d96edb3.jpg)
![20180903224650_1](https://user-images.githubusercontent.com/32621322/45000191-90f50a00-afcb-11e8-9a02-26e1954c7b22.jpg)

**Comment by Nintai** [comment]
Fixed for Flamewaker Q and E, Voltex Q, Venomort E, Red General Q

It could be that some worked, but i adjusted the name in code anyway ;)

Comming in next patch
