### ISSUE TITLE
Auriun E state + root effect

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#71]
Auriun affected by Overgrowth of Ashen Treant miniboss still remains to be in vulnerable state for autoattacks. (IF you push E while rooted)
(It has minimal affect on gameplay, because you have 100% uptime on higher levels, but having it on normal was surprising, wonder if that works same with with all rooting effects.)

**Comment by ChalkyBrush** [comment]
Treant ulti reveals invisible units as per dota 2 base rules
