### ISSUE TITLE
Seinaru glyphs are being eaten from our save slots.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#714]
spirit  has Dota 2 25 minutes ago 
5 september.
After hero load. Missed 2 of 3 glyphs on seinaru.
1 missed glyph - Ring of Duelist
2 missed glyph - Glyph of giant slayer
https://www.roshpit.ca/players/86838780/heroes/920725

my Seinaru lost it too
![20180905111645_1](https://user-images.githubusercontent.com/32621322/45080726-3c9e7700-b0fe-11e8-9b92-060094e364f1.jpg)

**Comment by ChalkyBrush** [comment]
fixed, as long as you didn't save again :S
