### ISSUE TITLE
Seinaru DPS drop 

### ISSUE THREAD

**Issue by spirittsp** [ChalkyBrush/roshpit-bug-tracker#718]
Seinaru get DPS drop after missing glyph "Glyph of the Arena" (now my hero with that glyph).
On hit training dummy (before missing glyph patch) i get 16 digits number around 1.900.000.000.000.000 damage. But now i hit maximum for  6.142.000.000.000dmg (13digits). All these attacks was Pure Holy /Normal damage. 
Not only me get this problem. 

Tested on last boss Sea Fortress. To kill him i need more than 10-15 mins with these dmg loss. 

Thank for attention!

**Comment by Nintai** [comment]
Please provie some more information, like what items u are using, which glyphs and ur runes :)

**Comment by ChalkyBrush** [comment]
https://github.com/ChalkyBrush/Roshpit-Champions-Hero-RPG/pull/163 fixed for next patch
