### ISSUE TITLE
Junk Loot vote works incorrectly sometimes when there are disconnected or players which abandon the session.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#725]
![20180909230928_1](https://user-images.githubusercontent.com/32621322/45269270-af5b7980-b493-11e8-8777-1c95c6a239aa.jpg)

**Comment by redledcat** [comment]
I believe it has same origin as queue bugs.

**Comment by GoToNightmare** [comment]
try after the patch

**Comment by redledcat** [comment]
probably fixed?
