### ISSUE TITLE
Pathing in Sea Fortress

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#73]
This room has a lot of corners where collision burrows your hero underwater, and you are not be able to get out of there.
Issue exists not only for heroes, but also for tinker mobs.
![20171022005146_1](https://user-images.githubusercontent.com/32621322/31856210-e1fb329e-b6bb-11e7-872b-bde5b715512a.jpg)
![20171022005134_1](https://user-images.githubusercontent.com/32621322/31856211-e21e37f8-b6bb-11e7-95e4-3244dc1c4c73.jpg)
![20171022005039_1](https://user-images.githubusercontent.com/32621322/31856212-e240e352-b6bb-11e7-8dd0-a9c909246a52.jpg)
![20171022005027_1](https://user-images.githubusercontent.com/32621322/31856213-e2624362-b6bb-11e7-9683-780e02df61a9.jpg)
![20171022004950_1](https://user-images.githubusercontent.com/32621322/31856214-e2831880-b6bb-11e7-9f85-dcd5016e5231.jpg)
![20171022004939_1](https://user-images.githubusercontent.com/32621322/31856215-e2a493d4-b6bb-11e7-8c18-0ac01dcc704e.jpg)
![20171022004918_1](https://user-images.githubusercontent.com/32621322/31856216-e2c5e8d6-b6bb-11e7-95bd-23f537f1f5be.jpg)
![20171022004855_1](https://user-images.githubusercontent.com/32621322/31856217-e2e6bfb6-b6bb-11e7-86ed-e3a73fec4f67.jpg)
![20171022004825_1](https://user-images.githubusercontent.com/32621322/31856218-e30b5844-b6bb-11e7-94f0-e9b10fe7f163.jpg)
![20171022004754_1](https://user-images.githubusercontent.com/32621322/31856219-e32e2446-b6bb-11e7-8d4b-010b5efc8d21.jpg)
![20171022004746_1](https://user-images.githubusercontent.com/32621322/31856220-e352a474-b6bb-11e7-859c-995190a631fd.jpg)
![20171022005217_1](https://user-images.githubusercontent.com/32621322/31856232-00a48bd2-b6bc-11e7-84f0-c49b46874651.jpg)

**Comment by redledcat** [comment]
Shoulder cam looks great though
![20171022005657_1](https://user-images.githubusercontent.com/32621322/31856242-4dbf7cd8-b6bc-11e7-8761-1074bcb5dfe4.jpg)
![20171022005436_1](https://user-images.githubusercontent.com/32621322/31856243-5c72a0de-b6bc-11e7-9649-a3e5bf337999.jpg)

**Comment by redledcat** [comment]
plz
![20171101132433_1](https://user-images.githubusercontent.com/32621322/32270723-b9a1f610-beff-11e7-96f5-80bd413cea54.jpg)

**Comment by redledcat** [comment]
That one was kinda surprising
![20171110232220_1](https://user-images.githubusercontent.com/32621322/32680265-86b626fc-c672-11e7-8579-21b27169da54.jpg)

**Comment by DeckardCainRPC** [comment]
i have reason to believe that it's caused by specific, slim gaps between certain edges in the terrain map. there's similar behavior in the Arena map's various "water features," the little ponds along the paths - if you hop into one, attempting to hop back out can cause you to... get pressed against the wall of the embankment, rise about 300 units into the air, and then fall through the bottom of the map... after about 7 seconds, you teleport back up to "ground level," either on top of the embankment or back into the water.

**Comment by redledcat** [comment]
Yeah same as walls in Serengaard fortress. Anyway that sea fortress room is the most cancerous trap ever existed.
Even conquest zone in pit of trials wasnt that bad.

**Comment by redledcat** [comment]
Dumb!
![20180909151426_1](https://user-images.githubusercontent.com/32621322/45269189-5212f880-b492-11e8-9f99-b2c271fb3aa0.jpg)

**Comment by redledcat** [comment]
Often happens with bahamut and dk

**Comment by ChalkyBrush** [comment]
🎉
