### ISSUE TITLE
Onimaru tooltip errors

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#731]
1. Wind should be capitalized to conform with every other tooltip in the game
2. since the item does an instance of damage, it needs to formally have the DAMAGE TYPE and ELEMENT tags at the bottom
3. it also needs to explicitly inform the player that its instance of damage will apply R1 to targets struck
4. finally, it says "100% physical" but 100% of what? 100% of total attack damage? then say so

**Comment by redledcat** [comment]
But since Onimaru neither of item damage or ability augment, that will only confuse people, as ekkan weapon does.

**Comment by redledcat** [comment]
how should it look like?
Attacks deal additional 100% physical Wind damage based on total attack damage in a 250 radius, and apply [R1] effect on affected targets.
or can we just assume "Attacks" mean total attack damage and
Attacks deal additional 100% physical Wind damage in a 250 radius, and apply [R1] effect on affected targets.

**Comment by Nintai** [comment]
Attacks deal an additional 100% of attack damage as physical Wind damage in a 250 radius and apply [R1] to all enemies hit.


My Suggestion 😝

**Comment by DeckardCainRPC** [comment]
--- September 11, 2018 ---

[4:16 PM] sterv: no problem, i understand

[4:16 PM] sterv: yeah very few issues so far

[4:16 PM] ChalkyBrush: ive got the pull requests for the small fixes ready for tonight

`[4:32 PM] sterv: "property_seinaru_immortal_weapon_description"                        "Each attack stirs up a 250-radius gust, dealing 100% of total attack damage as Physical <font color=\"#7AE2A7\">Wind</font> damage and applying [R1] to all enemies struck."`

**Comment by DeckardCainRPC** [comment]
@redledcat it isn't an instance of item damage? why not?

**Comment by redledcat** [comment]
I don't know about Ekkan weapon, but Onimaru does not inherit any item damage amps because of balance reasons.

**Comment by redledcat** [comment]
Now it's item damage
