### ISSUE TITLE
Pause unaviable!

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#736]
Is there any restrictions Valve did to pause?
I've paused game like 2 times and now it resticted be to pause for the 3rd time
Can we do anything to this?
![20180911231642_1](https://user-images.githubusercontent.com/32621322/45387203-01300b00-b61e-11e8-8031-850f69f8fd65.jpg)
(translation: You are not able to pause the game anymore)

**Comment by DeckardCainRPC** [comment]
there is a limit to number of pauses allowed per player, per game session... even if you are solo. praise gaben

**Comment by redledcat** [comment]
ffs
