### ISSUE TITLE
Mask of Mugato was silently changed, needs new tooltip

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#740]
`"property_mugato_description"				"Casting any spell silences you for @special_property1s seconds, and attacking silences you for @special_property2 seconds. While silenced from any source, your post-mitigation damage is increased by @special_property3%."
`

**Comment by ChalkyBrush** [comment]
thanks, fixeda

**Comment by DeckardCainRPC** [comment]
no it isn't @ChalkyBrush it still has the old "Dragon English" tooltip as of 6:30AM EST 9/18/2018

**Comment by DeckardCainRPC** [comment]
good now, and i curated it so the correct tooltip appears on roshpit.ca/items

**Comment by ChalkyBrush** [comment]
I didn't run the builder last patch 😭

**Comment by DeckardCainRPC** [comment]
i love you anyway
