### ISSUE TITLE
[Ekkan] Disabling of rune using Alt+left click does not disable their effects on present dominated units

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#741]
Disabling any of Q arcana runes (not tested for normal runes), while dominated creep was created while runes were enabled, will inherit their effects. Works only if you dominate new creep replacing old one.
This creep with disabled runes wont be able to activate their effects, and needs to be replaced with another creep in case you need rune effects again.

**Comment by Nintai** [comment]
Im not sure this can be counted as bug, we do give the abilities to the units at the start of skill

Chernobog R Arcana has the same, if u deactivate while u still have R, it wont count for current R, but if u activate R while runes are deactivated, it wont have the runes

**Comment by GoToNightmare** [comment]
fixed if chalky approve pull/229
