### ISSUE TITLE
[Pit of Trials] Probably UI broken for a long time

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#742]
Found it because started to play on russian translation.
I checked addon and it has actually 3 lines of parameters:
"tooltip_pit_enemy_damage"										"Enemy Damage"
"tooltip_pit_enemy_resistance"									"Enemy Resistance"
"tooltip_pit_enemy_paragon"										"Paragon Spawn Rate"

"tooltip_pit_enemy_damage"										"Урон врагов"
"tooltip_pit_enemy_resistance"									"Сопротивление врагов"
"tooltip_pit_enemy_paragon"										"Частота появления Парагонов"

But they seems to be dramatically spaced, and "enemy_paragon" appears to be right under "Open Pit: button.

![20180915160303_1](https://user-images.githubusercontent.com/32621322/45586540-96bee980-b901-11e8-8143-346ebc9f48fd.jpg)

**Comment by ChalkyBrush** [comment]
fixed
