### ISSUE TITLE
Blue paragon packs lost blue color

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#744]

**Comment by redledcat** [comment]
![20180923133546_1](https://user-images.githubusercontent.com/32621322/45927042-aeb3f000-bf35-11e8-90c9-fb4d06f05adc.jpg)

**Comment by redledcat** [comment]
![20180923134204_1](https://user-images.githubusercontent.com/32621322/45927109-9d1f1800-bf36-11e8-990d-682e177b85b7.jpg)

**Comment by redledcat** [comment]
It seems it partially fixed, but they became dark-blue

**Comment by redledcat** [comment]
![20181016133856_1](https://user-images.githubusercontent.com/32621322/47018578-ae39fe00-d15d-11e8-80fb-500922915a23.jpg)
![20181016133500_1](https://user-images.githubusercontent.com/32621322/47018590-b4c87580-d15d-11e8-90bc-a10ea3b33a59.jpg)
![20181016133428_1](https://user-images.githubusercontent.com/32621322/47018592-b7c36600-d15d-11e8-9c08-f27670def8c6.jpg)
Looks good, but previously they were much more teal.

**Comment by ChalkyBrush** [comment]
stuck with the blue for now
