### ISSUE TITLE
Spawn trigger for "Ruins Guardian" PL creep group in Pit's left wing spawns 1 extra PL creep... in Lies wing

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#765]
just in front of the bridge leading to the Fortune Talisman area

**Comment by redledcat** [comment]
local guardianVecTable = {Vector(-13184, 15424), Vector(-13440, 15552), **Vector(13376, 15360),** Vector(-13504, 15232), Vector(-13440, 15040), Vector(-13504, 14912), Vector(-13376, 14848), Vector(-13504, 14720)}

**Comment by DeckardCainRPC** [comment]
i vaguely recall seeing this fixed in a patch note

**Comment by redledcat** [comment]
no, I don't think it was fixed

**Comment by redledcat** [comment]
added in pull, also want to check wisp in tanari and clockwerk in sea, who also lost their coordinate

**Comment by DeckardCainRPC** [comment]
oh really? well then, let me push the "Reopen" button on this

**Comment by ChalkyBrush** [comment]
i forgot to merge your PR

**Comment by redledcat** [comment]
fixed
