### ISSUE TITLE
Someone hilarious changed the name of a unique Centaur Warrunner creep in Pit to "Lord of Bowel"

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#766]
which was my nickname as a high school wrestler

**Comment by ChalkyBrush** [comment]
supposed to be Lord Bovel 😓

**Comment by DeckardCainRPC** [comment]
HMMMMMm and the german language pronounces W like V, wonder which GERMAN collaborator is responsible????? @Nintai

**Comment by Nintai** [comment]
Since im not german u cant mean me, also i didnt do anything with names there

**Comment by redledcat** [comment]
lmao, that was me.
Now when your attention attracted, please check all other tooltips of Arena recently added :D

**Comment by redledcat** [comment]
That was not meant to be a joke, and I personally haven't seen anything wrong in "pit_conquest_lord_of_bovel"	except "v" letter because conquest path is likely to be a huge bowel.
Now I'm crying

**Comment by redledcat** [comment]
Also I think only missing creeps' names now are in Serengaard first 30 waves.
Tanari and Arena fully covered now, Sea and Winterblight done very well.
Redfall should have no issues too.

**Comment by DeckardCainRPC** [comment]
i just played pit several times and checked the names of stuff i saw, and all of it seems to be fine. excellent work

**Comment by ChalkyBrush** [comment]
lord of the bowel is no more

**Comment by DeckardCainRPC** [comment]
[5:18 PM] redledcat: I think it's only an improvement
[5:18 PM] sterv: lol
[5:18 PM] sterv: LORD OF BOWEL
[5:18 PM] sterv: like an easter egg for people who actually left-click him
[5:21 PM] redledcat: ok I'm in hysterical laughter every time I'm reading 
`which was my nickname as a high school wrestler`
🤼
1
[5:22 PM] sterv: my finishing move was called `DESTROYASS`
[5:22 PM] redledcat: enough
[5:22 PM] redledcat: I'm dying
