### ISSUE TITLE
[Pit of Trials] Trial of Lies floor and door bug

### ISSUE THREAD

**Issue by ezlf** [ChalkyBrush/roshpit-bug-tracker#768]
i cant seem to get across to the room that's on the right and the door over here wont open, and  i've tried restarting and it's still the same
![20180928021127_1](https://user-images.githubusercontent.com/21014613/46181087-28e0cd80-c2c4-11e8-801f-2c871b686102.jpg)
![20180928021206_1](https://user-images.githubusercontent.com/21014613/46181088-28e0cd80-c2c4-11e8-83d2-7b760447c0b5.jpg)

**Comment by Nintai** [comment]
did u try using the dust u get from the wards? 😏

**Comment by ezlf** [comment]
yes i did, i even tried using it PLENTY of times xD

**Comment by Nintai** [comment]
Really? Then why is the antimage statue still there?

And why didnt u use it in the library in the top left corner?

**Comment by ezlf** [comment]
i used the dust everywhere possible.. but will try again today when i get back

**Comment by ChalkyBrush** [comment]
these are not bugs XD
sounds like you've been befuddled by the trial of lies 😏
