### ISSUE TITLE
[ITEM LOSS] Use an equip item while standing next to Blacksmith AND while his UI is open

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#769]
the result is that the Blacksmith UI closes spontaneously, and the "Equip this?" UI only appears for a fraction of a second before spontaneously closing.

when this occurs, it also locks up the Blacksmith itself, rendering the player unable to open the Blacksmith UI for the remainder of the game session. (standing next to him still causes him to intermittently print his "I can forge a solution to all of your bullshit!" dialogue bubble, but not the NPC's UI itself.)

**Comment by redledcat** [comment]
Lock of Blacksmith can be solved with any other item equip window.
I can't believe there is no duplicating issue, because I clearly remember I figured it out months ago.
