### ISSUE TITLE
Zhonik can't reach big crystal to change color of puzzle

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#772]
![20180929182947_1](https://user-images.githubusercontent.com/32621322/46247556-cef01d00-c415-11e8-8ed7-0b2ed4d125ea.jpg)

**Comment by redledcat** [comment]
well he can do it using E and attacking it in mid-air

**Comment by DeckardCainRPC** [comment]
how strange. why does this affect only zhonik and no other melee hero?

**Comment by redledcat** [comment]
did that with no problem using bara

**Comment by redledcat** [comment]
maybe it's colossus fault

**Comment by Nintai** [comment]
Zhonik:		"AttackRange"   "180"
Iron Colossus: 150

Could be 😛

**Comment by DeckardCainRPC** [comment]
that must indeed be the reason
