### ISSUE TITLE
A loading screen tip references the Trade UI

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#775]
which, in case you forgot, was killed for a life of crime and insubordination

**Comment by redledcat** [comment]
tip 20, remove for all translations please.
Actually it's tip 20 for russian and english, not for chinese
Chinese translation transformed it in tip of arcana items, it has green beam, rare drop, etc.

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush see above

**Comment by redledcat** [comment]
spoonfoy revised all the tips
