### ISSUE TITLE
Huskar's "Spear of Aeris" crit creates particles which lag like a motherfucker

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#777]
**I ORIGINALLY THOUGHT IT WAS BARON'S STORM ARMOR**

STEPS TO REPRODUCE:
1. be super durable and regenerate to full health nearly instantaneously, but have basically 0 fucking offensive capability, like so https://www.roshpit.ca/players/72513648/heroes/542016
2. wear baron's storm armor
3. go stand in a big crowd of shit in Winterblight 3-stone. the more units with defensive passives which generate a particle effect, the better!
4. disconnect everyone and lag the game to a halt

**Comment by DeckardCainRPC** [comment]
actually i tested it further and whereas Baron's Storm Armor does generate a significant number of lag-inducing particles, it is not itself a cause for concern; however, in conjunction with particle-generating defensive passives, AND with other heroes killing shit and generating their own particle spam, it can contribute significantly to mass disconnects

**Comment by DeckardCainRPC** [comment]
it also helps if you're standing in a crowd of those "Softwalker" Dark Seer creeps, the ones that are virtually invulnerable unless slowed *and* who can easily reach maximum attack speed

**Comment by DeckardCainRPC** [comment]
just kidding i fucking figured it out, it's huskar's god damn Spear of Aeris crit, it's just as laggy as Bladeforge Gloves bloodspray spam

**Comment by ChalkyBrush** [comment]
can't figure out why spear of aeris would cause lag, other than just the sheer quantity of attacks. The crit only does a small glow effect on the weapon and makes a sound

**Comment by DeckardCainRPC** [comment]
*angry deckard noises*
