### ISSUE TITLE
When viewing any player's Dinath via roshpit.ca/players, it displays 8 W spell runes

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#780]
https://www.roshpit.ca/players/72513648/heroes/749233

it displays her typical runes... *beneath* her Arcana's W runes, even in spite of the fact that i don't have one

**Comment by redledcat** [comment]
Cool.
Can we have this bug for "Heroes" pages instead?

**Comment by DeckardCainRPC** [comment]
i believe this was fixed
