### ISSUE TITLE
Fire temple key says it's for normal only

### ISSUE THREAD

**Issue by PerceptivePride** [ChalkyBrush/roshpit-bug-tracker#781]
Whether you get a key in normal, elite or legend, it says in the description it's for normal,but it works in legends (and prolly in any,didn't test tho)

**Comment by PerceptivePride** [comment]
Actually,after test, happens only when you store it and use it later

**Comment by redledcat** [comment]
they were splitted before Key Bank Feature was added. It's just old description.

**Comment by redledcat** [comment]
fixed in next patch, I guess

**Comment by redledcat** [comment]
It have been fixed, close
