### ISSUE TITLE
Glyph of the Shadow Hunter has dragon english and needs to be fixed ASAP

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#783]
the second sentence, ``Reduce all base ability damage except @Ability3 by 2x`` doesn't make sense to english speakers because we don't use the syntax "reduce by 2 times." 2 times what?

here is the fixed translation: ``Reduce the total damage dealt by all abilities except @Ability3 by 50%.`` in order to make this work correctly, you'll have to change Chernobog's ``constants`` file, find the variable that is currently set to ``2``, and change it to read ``50``.

**Comment by redledcat** [comment]
Will the "Total Base Ability Damage divided by 2 for all abilities except @Ability3" or "Base Ability Damage equals 1/%constant% of total except @Ability3" work the same?
Numerals are difficult.
How it can be written for divider of 10 or 20? Divided by 10/20? 
Construction like "to reduce by several times " is incorrect?

**Comment by redledcat** [comment]
In russian there is a noun "раз [rʌz]" which can be freely used to designate number both of multiplier or divider, and as the numeral in meaning of "one". Multiply by 20 = multiply 20 раз, 4 times increase = increase 4 раз, divide by 100 = divide by 100 раз.
That's why when it approaches to dragon language, it transforms into "times" which is the raw translation of this world.
Actually I see A LOT of people struggle with this construction all over the Internet. Lol?
I think here is a good description:
Increased by 5 times can mean 
"X was increased by a factor of 5" and "X was increased by 5 times its initial value" or even "X was increased 5 times, but each time it was increased by a different value"

**Comment by redledcat** [comment]
I'm still confused.
Should we teach the Dragon a construction of "by a factor" instead of "times" and we are fine?

**Comment by DeckardCainRPC** [comment]
no, no, i understand the syntax differences between languages, they are glorious and i embrace them! also, i don't mind fixing them when i see them, that's my job. the issue here is that i *did not* see it before it got patched in, so i never had the opportunity to adjust it.

i do see a second problem you illustrated for me, which is that the russian and english translations may not be able to use the same numbers in the ``constants`` file in order to construct a good sentence - if we change it from ``2`` (times) to ``50`` (percent), then that's fine for the english tooltip, but constructing a sentence using 50 might look alien and strange to a culture that expects the *raz* syntax.

is it acceptable to use the 50% construction in both languages?

**Comment by redledcat** [comment]
there is no problem with translation
"percent" is a part of international lexics
I just guess it's easier to make, change and use constants as non-percentile numbers, so with chance that issue will be ignored is pretty high rather than making changes in calculations

**Comment by DeckardCainRPC** [comment]
OH, is the effect currently programmed using the mathematical operation ``/ 2``? if that's the case, then the sentences can just read ``divided by x`` whenever you fine people would write ``reduced x times``. that syntax is perfectly acceptable.

that would make the translation ``Divide the total damage dealt by all abilities except @Ability3 by 2.``

**Comment by ChalkyBrush** [comment]
I dont see a problem with this descript 
"Shadow Hunt doesn't drain health while health is less than or equal to <% CHERNOBOG_GLYPH51_DRAIN_HP_CAP_PCT * 100 %>% of max. Reduce all base ability damage except @Ability3 by <% 1 / CHERNOBOG_GLYPH51_BAD_MULT_EXCEPT_E%>x."

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush you also don't see a problem every time you use an apostrophe when it's not a possessive, and in a dozen old tooltips - like Super Ascendency Mask - that use hyphens - to separate multiple clauses - instead of commas. but i love you anyway. i have never worked with a programmer who decided to put some of his spare skill points into English Literacy, and neither did my father before me. it has been a long-running, father-son joke between the two of us, and ever since my childhood we've both just assumed that it must be something about how the brain of a programmer works. i recognize this universal truth, and instead of lamenting the cruelty of an uncaring God, i offer my services in fixing that kind of shit. which is what i am trying to do right now.

there are two issues with that description. the first is that it's using the specific term "base ability damage." you've used the term elsewhere, both on item tooltips and especially throughout the entire tutorial (which needs much more copy editing than i did on it; i need to reiterate that language skills are not your forte), to refer *specifically* to the total percentile increase recorded in the expanded stats panel. that is a severe problem, because the glyph doesn't work by reducing a player's Base Ability Damage bonuses, it reduces *the final, total damage output* of affected abilities. that is why i suggested an entirely different phrasing. i've already had people ask me "yo decka is that cherno glyph working? i check my stats and it doesn't reduce my BAD% with QWR so ???"

the second issue is that, as i said, "reduce by 2x" is not valid english syntax. if you walked up to a cashier at Starbucks and said "i'd like one of your 12oz Pumpkin Spice enema bags, except reduce it by 2 times," they would give you an even dumber look than what baristas already wear 24/7. you would not get a 6oz enema. you would be at least 5 more sentences away from it, and even then, both of you would be thinking the exact same thing at the end of that conversation, which is "damn, there's a reason the word 'half' exists."

the reason why people run language-related stuff by me first is very similar: it is because it's my job and it's why i even fucking exist. so in conclusion, use this tooltip instead:

``"Shadow Hunt doesn't drain life while current health is less than or equal to <% CHERNOBOG_GLYPH51_DRAIN_HP_CAP_PCT * 100 %>% of max. The total damage dealt by all abilities except @Ability3 is reduced by <% 1 / CHERNOBOG_GLYPH51_BAD_MULT_EXCEPT_E%>."``
