### ISSUE TITLE
[Balanced?] Blacksmith Tablet has too high chance to roll 200+ k damage compare to properties 3 and 4 on gloves

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#784]
value = RandomInt(maxFactor*100, maxFactor*700)
versus 
RPCItems:RollAttribute(xpBounty, 10, 150, 0, 0, item.rarity, false, maxFactor*300)
RPCItems:RollAttribute(xpBounty, 10, 300, 0, 0, item.rarity, false, maxFactor*500)
for gloves

**Comment by DeckardCainRPC** [comment]
i strongly believe that every other attack damage property should be upgraded to Blacksmith Tablet's chances, instead of reducing its chances to match the gloves

**Comment by redledcat** [comment]
it became meaningful ONLY because of wyvern e2
there are no way to get enough profit from damage roll on gear, and it almost always better to get stats or mana regen on glove roll instead

**Comment by redledcat** [comment]
ok whatever
