### ISSUE TITLE
Arctic Wings of Drakkus split attack searching for secondary target arount main target instead of around Dinath

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#787]
I'm not sure what type of attack split is intended, but that's how it is right now
![asdasd](https://user-images.githubusercontent.com/32621322/46581519-c8c7f500-ca42-11e8-858c-16c5ea6ab538.png)
In case it's intended tooltip should specify range shown is radius around primary target

**Comment by ChalkyBrush** [comment]
it's intended

**Comment by ChalkyBrush** [comment]
updated english description
