### ISSUE TITLE
Dummy

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#789]
1. Giant Slayer actually makes instances cap on 50% (500) for steadfast and 25% (250) for mega steadfast.
![image](https://user-images.githubusercontent.com/32621322/46721898-e41e4480-cc7c-11e8-806e-a022ac893517.png)
2."Remove magic immunity" does not fit in button. It can only contain 18 symbols. Goes even more difficult to fit in Russian localization
![20181010110931_1](https://user-images.githubusercontent.com/32621322/46721961-09ab4e00-cc7d-11e8-9881-fc80567ba02e.jpg)

**Comment by DeckardCainRPC** [comment]
then i suggest replacing it with a picture icon, just like the two Steadfast icons. just use something that players would visually identify as meaning Spell Immunity, such as the icons for BKB or Gorudo. when disabled, the icon would be replaced with a desaturated (grayscale) version, indicating that Spell Immunity is now in the OFF state.
