### ISSUE TITLE
Redfall Lina cutscene bugged

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#79]
Lina didn't move and didn't trigger enemy spawn to continue map
Had an image but it was saved for some reason. If anyone experienced this please confirm it so it isn't just my say without an image.

**Comment by redledcat** [comment]
I can approve it!
No skips or glitches been used in my run, and Lina was bugged.
![20171102224351_1](https://user-images.githubusercontent.com/32621322/32348460-7eef8438-c01c-11e7-9c89-98cf951a3071.jpg)
Finished part 1, runned through some farmlands, then changed decision and went to castle zone, then lina got bugged and we turned back to farmlands and shipyard.

**Comment by redledcat** [comment]
+two my friends reported that apart of each other

**Comment by ChalkyBrush** [comment]
should be fixed in next patch
