### ISSUE TITLE
Sephyr mana regn BUG

### ISSUE THREAD

**Issue by EdelweissCjw** [ChalkyBrush/roshpit-bug-tracker#791]
Before death：mana regen == 20000

![1](https://user-images.githubusercontent.com/38028363/46749203-cfc36180-cce7-11e8-91ba-99a2232033c2.jpg)

After death：mana regen == 10000
![2](https://user-images.githubusercontent.com/38028363/46749308-026d5a00-cce8-11e8-9820-e073eb69bf88.jpg)

THIS bug cause Sephyr  less then 10000000 Attack value.

**Comment by redledcat** [comment]
hahahaha thanks mate

**Comment by redledcat** [comment]
@ChalkyBrush W1 applies three times, because it does not remove w1 effect after unequip
upd. no, it seems it  multiplies initial value or something.

**Comment by redledcat** [comment]
![20181010194345_1](https://user-images.githubusercontent.com/32621322/46752043-e0aeab80-ccc4-11e8-8ca1-47d047c17624.jpg)

**Comment by redledcat** [comment]
AH! got it.
normal W1 rune does not disable its effect when arcana equipped.
So in the beginning of the run, it applies R4+W1 mana regen, then it gets new W1 and adds the value.
Until death, when effect of normal W1 disappears.

**Comment by Nintai** [comment]
So basically a "feature" that was not intended was reported? 😛

**Comment by redledcat** [comment]
yeah. Understanding a bug is really important unless you don't need to harm yourself

**Comment by EdelweissCjw** [comment]
So，It's only a display trouble？Is it necessary to repair?
