### ISSUE TITLE
Monkey King wolf form immortal weapon

### ISSUE THREAD

**Issue by StillStealSteel** [ChalkyBrush/roshpit-bug-tracker#8]
First of all weird description "@Ability2 hits enemies in a line and his primary element nature while in Wolf Form." Hard to understand what is "his primary element".
If i understood right then W with this this weapon and in wolf form should do NATURE damage. But it doesn't/ If i wrong just correct me and change description to something that explain what it does better.

**Comment by ChalkyBrush** [comment]
had typos, meant to be "has primary element"

rewored: "Additional @special_property1 attack power for each point of Agility while in wolf form. @Ability2 has primary element nature and hits enemies in a line while in Wolf Form."
