### ISSUE TITLE
Yellow Ahn'Qhir mask + Duskbringer arcana

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#80]
The mask does not affect the W interaction when used with Duskbringer arcana.
Not sure if this is intended or a bug. Image of the mask attached.
![20171023114110_1](https://user-images.githubusercontent.com/32886049/31900709-62372efe-b7ed-11e7-9605-c891df00cf7e.jpg)

**Comment by ChalkyBrush** [comment]
You mean trapper arcana?

**Comment by SilentC** [comment]
No, I attached a picture of the item I was talking about.
I meant Duskbringer (Spirit Breaker) Arcana.
It works with Trapper arcana, just posted the only picture I had of the item
I didn't figure a picture of Duskbringer would matter since it would need to be a video to show how it works when used with the arcana and without.

**Comment by ChalkyBrush** [comment]
Duskbringer arcana ability does not have a cast point

```
"duskbringer_arcana_ability"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_AOE"
		"FightRecapLevel"				"1"
		"AbilityTextureName"			"duskbringer/duskbringer_arcana_ability1"
		"RequiredLevel"          		"-5"
		"LevelsBetweenUpgrades"  		"10"
		"MaxLevel"				 		"7"
		"AbilityCastAnimation"			"ACT_DOTA_SPAWN"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AOERadius"						"300"
		"AbilityCastRange"				"300"
		"precache"
		{

		}

		"AbilityCastPoint"				"0"

```
