### ISSUE TITLE
[MAP UNPLAYABLE] "Azalea Zealot" (Arc Warden) bosses unleash instant volley of thousands of autoattacks

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#803]
STEPS TO SHIT YOUR PANTS:
1. queue up Winterblight on any difficulty, and make your way to those three multicolored pillars
2. these pillars summon the Azalea Zealots
3. go ahead, mother fucker. let one of them get within range to autoattack you. see what happens.
4. what happens is not good. hopefully, you die, because otherwise your client and/or the server will crash, demolished by a flood of bullshit somewhat similar to my old Infinite Autoattack Venomort debacle.

**Comment by ChalkyBrush** [comment]
fixed

**Comment by ChalkyBrush** [comment]
bavibi!! 👀

**Comment by DeckardCainRPC** [comment]
@bavibi i am impressed with this bug. i am proud of you
