### ISSUE TITLE
[Astral Ranger] Her R3 tooltip says the phoenix stays for 10s, it stays for 20s in reality

### ISSUE THREAD

**Issue by PerceptivePride** [ChalkyBrush/roshpit-bug-tracker#805]

**Comment by redledcat** [comment]
30 Jul

Astral Ranger
-R1 from 1000 -> 10000
-R3 from 24-> 40, duration 10->20

**Comment by redledcat** [comment]
both aren't updated lol

**Comment by redledcat** [comment]
I think  we solved it?
close

**Comment by redledcat** [comment]
whoops, astral ranger on roshpit.ca still has 1000 per r1
r2 is old one too
and r3 duration says 10 there
fixed only in the game
