### ISSUE TITLE
[Tutorial] lv85 arcana cache from the 2week web premium?

### ISSUE THREAD

**Issue by mythly** [ChalkyBrush/roshpit-bug-tracker#807]
The tutorial is misued to farm arcana cache. Please check this https://www.roshpit.ca/players/343172381 @ChalkyBrush

**Comment by DeckardCainRPC** [comment]
great job. you posted this on the public bug tracker, which spooked that player and made him hide whatever evidence you wanted us to see. thanks for your cunning foresight

**Comment by DeckardCainRPC** [comment]
in the future, please just send me a private message through the game's official Discord server. i realize chalkybrush is often busy and can't reply to all reports, which may have been why you tried posting here to get his attention.

**Comment by ChalkyBrush** [comment]
well actually I deleted all the caches xD no response from valve on valid accounts so I'm thinking next cache giveaway will have a 'miminum Stars requirement' (something low like 50, but would take forever on fresh new bot accounts)

**Comment by redledcat** [comment]
I'm going to test how much it takes to solo 50 stars.
Sandboxing probably can give 50 stars in X matches:
1)Redfall legend equinox 9 stars + 2 stars for leveling a hero = 11 per run
2)4 runs with leeching char on second account = 44, 5th can be done without leveling = 44+9=53 stars. 
3)Three more you get from tutorial itself.
Without sandboxind:
1)Level a hero on normal, then get into legend for 11 stars = 2 runs on powerful chars.
2)do it four times for 44 stars (8 runs, 40 minutes solo each, or 4 runs leeching on random players)
3)Buy 4 cheap immo weapons and equip = 48 stars
4)+3 from tutorial = 52.
