### ISSUE TITLE
Предметы

### ISSUE THREAD

**Issue by StanislavYan** [ChalkyBrush/roshpit-bug-tracker#814]
После каждого выхода из игры пропадают рандомные экипированные предметы! В основном пропадает trinket

**Comment by GoToNightmare** [comment]
Разработчик англоговорящий, перед выходом из игры надо сохраняться у оракла, если не уверен, что сохранил, проверь сайт https://www.roshpit.ca/players/(твой id).

**Comment by StanislavYan** [comment]
> Разработчик англоговорящий, перед выходом из игры, который должен сохраниться у оракла, если не уверен, что сохранил, проверь сайт [https://www.roshpit.ca/players/(твой](https://www.roshpit.ca/players/(%D1%82%D0%B2%D0%BE%D0%B9) id).

I save each time, often even several times, as there are precedents for friends with whom I play
