### ISSUE TITLE
[Venomort] Unmodified E2 procs a single instance of damage instead of a 5 second DoT.

### ISSUE THREAD

**Issue by Ryusajin** [ChalkyBrush/roshpit-bug-tracker#816]
Acts like a thorns type effect, no debuff on enemy.

**Comment by DeckardCainRPC** [comment]
by any chance, do you have this immortal weapon equipped? https://www.roshpit.ca/items/item_rpc_venomort_immortal_weapon_3

**Comment by Ryusajin** [comment]
Nope, unmodified E2, as written in the title. Bug can be tested on a fresh Venomort, no gear.
In addition, while E2 acts as if you have the immortal weapon equipped, you do not get the damage bonus from max health. Have not tested to see if it is still treated as a DoT or not.

**Comment by DeckardCainRPC** [comment]
thank you for confirming what you meant by "unmodified"

i worked directly with Dragon on the venomort rework which included this "new" E2 rune, as well as all his other goodies. that means i wrote all the english text for the patch, and that i tested the vast majority of it myself while writing the tooltips. therefore i am very surprised to see that this simple but monumental fuckup somehow made it past both me and Dragon (and surely some other people!) and went unnoticed for months... which leads me to suspect this issue may have been introduced in a recent patch

**Comment by Ryusajin** [comment]
Ahh, I feel you there. Can be frustrating to see something so simple having potentially slipped by. I mainly noticed because I happen to have a high Q3- should have been seeing more than one tick per enemy attack when they attack once every several seconds. 

I have to give my complements for the rework, having much more fun with him now than I did the previous version. Q, W4, and Heavy Echo Gauntlets has been pretty amusing!

**Comment by redledcat** [comment]
fixed
