### ISSUE TITLE
Advice on Dinath's damage balance

### ISSUE THREAD

**Issue by faner2018** [ChalkyBrush/roshpit-bug-tracker#822]
Hello, ChalkyBrush, I am a veteran Chinese player in roshpit. At present, Dinath damage is very low, and everyone can't play difficult maps. I hope you can strengthen this hero! List some suggestions for you: 
1: increase R1X10, R4X3. 
2: increase Q and W based damage. 
3: Q3 changed to take increase post-mitigation from Dinath damage. 
4: Basic Q's CD reduced to 3S. 
5: Increase W4X5. 
6: W2 changed to all damage types. 
Thank you very much!!!

**Comment by ChalkyBrush** [comment]
sort of implemented
