### ISSUE TITLE
[Tutorial] "tutorial_quiz_question_6_answer"	answer button broken

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#825]
It's not possible to answer that question atm

**Comment by redledcat** [comment]
Actually I can't press any of these answer buttons. Help?

**Comment by redledcat** [comment]
And multiple question buttons broken!

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/47743149-6ce23c00-dc8f-11e8-8e68-40be72d4bb83.png)

**Comment by ChalkyBrush** [comment]
yea woops fixed
