### ISSUE TITLE
Venomort is a fustercluck

### ISSUE THREAD

**Issue by PerceptivePride** [ChalkyBrush/roshpit-bug-tracker#827]
After a talk with Redlecat, turns out that Base Q and venomblight seems to bug in weird ways.
You keep your BAD when you unequip the weapon, even if the BAD is enhanced by something like blacksmith tablet, you actually keep the BAD even when unequipping everything.

Oh and Glyph of Melancholy adds 100 or 200 BAD, depending on some unknown factor.

**Comment by redledcat** [comment]
Fixed with acceptable damage 😅

**Comment by redledcat** [comment]
Close now
