### ISSUE TITLE
[Veil of Gaia] Bugs

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#832]
Q2 does not recalculate for shadow and fire deities until respawn
R1+Grand Guardian makes earth deity jump on target, but "captured" hero stay on previous place
Throwing ability has no name and description

**Comment by redledcat** [comment]
q1 missing magical damage flag

**Comment by ChalkyBrush** [comment]
cant change q2 recalculate but others fixed
