### ISSUE TITLE
Conjuror's rank 7 non-Arcana ult gives 264 movespeed, not 220

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#835]
STEPS TO REPRODUCE:
1. you can probably just go source diving instead.

but if not,

1. get yourself a pair of -300MS ablecore greaves
2. put them on. your movespeed will be reduced from 420 to 120. math is a miracle.
3. now cast R at rank 7. the tooltip says you should gain 220 movespeed, which ought to put your speed at 340, because 120 + 220 = 340. math continues to be a miracle.
4. okay but look! your movespeed is 384 for some reason?
5. why

SUGGESTED COURSE OF ACTION:
i can't decide whether the buff should match the tooltip (which would mean the spell would be nerfed), or whether the tooltip should match the spell. i will leave that up to you.

**Comment by DeckardCainRPC** [comment]
i would also like to note that the movespeed gain is different from the tooltip at ALL ranks, not just 7. you gain 120 movespeed at rank 1 instead of the stated 100. and rank 2 grants 144 instead of the stated 120.

**Comment by redledcat** [comment]
I think it's a multiplier, not an additive value.
Invoker doing really well agains any slows

**Comment by DeckardCainRPC** [comment]
ahh, well uh, i'm trying to run him with ablecore greaves... which can only roll up to -300ms... sooooo fuck

**Comment by ChalkyBrush** [comment]
fixed
