### ISSUE TITLE
Conjuror boot arcana issues

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#837]
1. E1 doesn't make it clear that it grants the pet an active spell; it sounds like it's a permanent "thorns" passive.
2. E2 tooltip should capitalize instances of the word "shadow" as well as giving them the purple color HTML tags
3. I've tested E2 on the dummy for several minutes and it appears to be malfunctioning. It never logs damage instances to the dummy's interface. Yes, I made sure to invest at least 1 hard point in it.
4. E3 itself is working fine, however E3's tooltip is busted: The first property, "x% for each 10 points of Agility" will always read 0 no matter how many points you have in E3.
5. The second instances of the word "agility" in E3's tooltip should be capitalized (the first instance already is).

**Comment by GoToNightmare** [comment]
3,4 fixed

**Comment by ChalkyBrush** [comment]
fixed
