### ISSUE TITLE
Conjuror non-Arcana ult grants 4000 HP regen to self, but only 1000 to pets

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#842]
is there a visual cap of +1k HP regen on non-hero units? i've noticed that a LOT of units, e.g. Syphists, often have bugged HP bars which display the value "+-1000" when you're beating their ass

**Comment by redledcat** [comment]
just visual, it's dota cap

**Comment by ChalkyBrush** [comment]
ya dota cap. The technology isnt there to display true HP regen on non hero units (we track HP regen and override UI for heroes specifically but would be too much effort for minions)

**Comment by DeckardCainRPC** [comment]
piss

**Comment by DeckardCainRPC** [comment]
wait i knew that why did i even report this
