### ISSUE TITLE
Paladin Penance still bugs hard when lances get disjointed.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#85]
Lances get disjointed all the time, on every map. This causes them to permanently lower the amount of lances you can have. In almost every game, you'll get 10 lances in no time. Even some allies can disjoint lances (Drow with E, for example) causing him to not be able to party play with any of those characters with Arcana equipped, and it needs a serious fix.
Currently, when you don't cast your W for some amount of time (feels like 20 seconds), the "buff" that says how many lances you have will disappear, causing you to be able to at least throw one lance, proving that the buff is what limits your lances.
It is a bandage fix, but if it proves unfixable, could you make the "buff" set the lance-count to 0 when it runs out? You'd have to not be casting lances for 15 seconds, you won't have lances out. This means that in a fight you still might go to 10 stacks, but at least you can reset by not casting W for some time. It's imperfect, but it would be way better than the current state of things.

**Comment by FortuneReborn** [comment]
![570_20171025003603_1](https://user-images.githubusercontent.com/3812172/31972616-d23746d2-b921-11e7-868a-49ceb5ff9b21.png)
Pic 1 has no buff. Casting lances brings it back with 9 stacks (I had 9 at the time.)
![570_20171025003605_1](https://user-images.githubusercontent.com/3812172/31972642-e6e6e934-b921-11e7-8b43-269f663843aa.png)

**Comment by redledcat** [comment]
I am here to emphasize the number of reports.
![merge_from_ofoct 5](https://user-images.githubusercontent.com/32621322/31993921-029d9666-b97f-11e7-8e79-74fdb267f6ce.jpg)
And also for this
![peanuts](https://user-images.githubusercontent.com/32621322/31993926-089378ce-b97f-11e7-93a0-b34cb212989a.jpg)

**Comment by FortuneReborn** [comment]
It's your own ult! Lances that are going to Knight's Disciple when it ends are lost to the void.
![570_20171025180155_1](https://user-images.githubusercontent.com/3812172/32009197-a9382732-b9ae-11e7-9106-605890bfc945.png)

**Comment by ChalkyBrush** [comment]
this is fixed now, i even improved the "30 second timer" thing so penance is 'perfect' now!
