### ISSUE TITLE
DPS meter digits

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#853]
it can't hold more than 18 digits (100 quad), 19 and 20 digital numbers are cut. 21 not sure, should be e+21 if I remember correctly.
![sadsd](https://user-images.githubusercontent.com/32621322/48305623-49e14300-e53f-11e8-9216-ecad1a12be21.png)

**Comment by redledcat** [comment]
offtop: yep, that's balanced, nothing to discuss here

**Comment by redledcat** [comment]
actually I think using scientific notation even for quadrillions will be fine.
humans are not really good in reading large numbers, 1 000 000 000 000 is easy to read, but 1 000 000 000 000 000 already better in 1e15

**Comment by GoToNightmare** [comment]
There is cultural difference in ways of naming a number, let it be as is, in most common way.
https://en.wikipedia.org/wiki/Names_of_large_numbers

**Comment by Nintai** [comment]
There is no difference in using scientific annotations, u know?

**Comment by GoToNightmare** [comment]
Oh i tought he wanna make short text annotations like "100 quad", sorry, then it makes sence.

**Comment by redledcat** [comment]
well Nintai implemented scientific notation a while ago, thanks
