### ISSUE TITLE
red general arcana R4 not working on ruptures from Q3

### ISSUE THREAD

**Issue by mythly** [ChalkyBrush/roshpit-bug-tracker#855]
With Lv60 R4
Q3: 4 ruptures and shorter
![b](https://user-images.githubusercontent.com/9605204/48358327-7b8c1280-e6d5-11e8-9571-36b060772b01.png)
R:   7 ruptures and longer
![a](https://user-images.githubusercontent.com/9605204/48358210-3ff14880-e6d5-11e8-92c2-91348be0f925.png)

**Comment by redledcat** [comment]
Can you read last sentence in R4?

**Comment by Nintai** [comment]
I think theres a mistake in the chinese translation. Here is what i got out with google translate:
"There is a chance that the big move will cause a crack in the ground. If the chance is more than 100%, you can tear a lot. And additionally increase the tear distance of each ground crack."

**Comment by redledcat** [comment]
Well I like it more than current English one, can we replace it?

**Comment by mythly** [comment]
Got it.
I would like to correct the Chinese translation. 
How should I contribute? I found only an out-of-date [repo](https://github.com/ChalkyBrush/roshpit-champions-localization/projects)

**Comment by ChalkyBrush** [comment]
@mythly I will add you as a collaborator to the offical roshpit champions repo, the file you're looking for is here:

https://github.com/ChalkyBrush/Roshpit-Champions-Hero-RPG/blob/master/Game/scripts/vscripts/heroes/axe/localizations/axe_schinese.txt

**Comment by DeckardCainRPC** [comment]
@mythly thank you for contributing, i don't know if we've had a chinese translator since songcx moved on to other things

**Comment by mythly** [comment]
I do love this game and want to make it better.

Submitted a [PR](https://github.com/ChalkyBrush/Roshpit-Champions-Hero-RPG/pull/285) to fix this.
