### ISSUE TITLE
Astral Ranger：Q2 won't trigger “Guard Of Luma” and “Demon Mask” and “Shipyard Veil”

### ISSUE THREAD

**Issue by powersong1988** [ChalkyBrush/roshpit-bug-tracker#863]

**Comment by redledcat** [comment]
it's not "Base Ability: Q", so it won't trigger any of these

**Comment by DeckardCainRPC** [comment]
correct, this is not a bug

the Arcana helm's version of Q2, however, *is* treated as Base Ability: Q damage... and would trigger those effects if you weren't already wearing a different hat instead

**Comment by powersong1988** [comment]
that sucks for Astral Ranger，but alright
