### ISSUE TITLE
Movement Speed cap broken

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#866]
Movement speed slow works as far as I know, but effects which increase movement speed work bad.

**Comment by ChalkyBrush** [comment]
i think its fixed, didnt test lul have to go

**Comment by ChalkyBrush** [comment]
most pressing issue atm, I have messaged valve
![image](https://user-images.githubusercontent.com/5232984/48808004-5870ec80-eced-11e8-8901-ba40aee21694.png)

**Comment by redledcat** [comment]
fixed, I guess
