### ISSUE TITLE
Valve fucked with cleave damage, add that to your list of things to check

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#867]
they made it so that cleave damage is no longer exempt from damage mitigation. this will have far-reaching consequences for a lot of shit, and i think the most important things to check would be Val'dun, and the Splash% weapons available to certain heroes. other cleaves i can think of include the Tome of Chaos pet, and maybe the gigantic Sven bosses in Winterblight who spawn inexplicably from attacking equally massive swords.

**Comment by redledcat** [comment]
I've checked valdun and he dealt magical damage with his custom cleave.

**Comment by redledcat** [comment]
There are 6 units which use sven_great_cleave ability, total copy of dota sven's cleave
1)redfall_mist_knight (just svens in redfall)
2)serengaard_ancient_guardian (lancers who defends the ancient)
3)serengaard_nightmare_raider (svens in serengaard, wave ~25)
4)winterblight_azalea_frost_titan (yeah, these ones)
5)azalea_armored_knight (svens in winterblight, with that armor softening passive and spell immune break)
and 6) is sven from world1 (rip) desert dungeon, where he jumped from throne and nailed whole team with one hit. good times.

**Comment by redledcat** [comment]
Splash weapons are aviable only for Elemental Warlord, and it uses custom function, already counts armor reduction

**Comment by DeckardCainRPC** [comment]
thanks for checking that out good buddy

yeah i remember that Throne Sven, he was notorious for killing your entire party if you were pubbing with a noob invoker player. if he didn't micro his pets away, Sven's cleave would wipe out all life in the entire room with just one swing, because the pets had pitiful armor. it was the height of computer gaming.

**Comment by ChalkyBrush** [comment]
noob build,no armor,poor gaming experience

**Comment by redledcat** [comment]
Time passed, he pumped up and captured sea fortress, takind dumb nickname of XxX_Val_Dun_XxX and custom outfit.
Still loves to jump and wipe entire team with one hit

**Comment by redledcat** [comment]
well, nothing here is essentially broken
