### ISSUE TITLE
Astral Ranger：Q2(no arcana) doesn't benefit by base ability damage

### ISSUE THREAD

**Issue by powersong1988** [ChalkyBrush/roshpit-bug-tracker#869]
Please tell me it's  a bug,if it isn't then i shall quit try play astral ranger with q2.Forgive my poor english,haven't learn it in a very long time.

**Comment by DeckardCainRPC** [comment]
@powersong1988 This is the second time you have created a topic about this: https://github.com/ChalkyBrush/roshpit-bug-tracker/issues/863

We have already told you that this is not a bug. Do not ask again.

You can easily see which runes will benefit from Base Ability Damage by just reading the rune. Look at this picture I made: https://i.imgur.com/8Xy24Oz.png

Do you see the part that I put a red box over? Do you see where the rune says "BASE ABILITY: (x)"? We put that in the game to tell people if a rune will benefit from Base Ability Damage and other effects, like Guard of Luma or Frostburn Gloves.

Please complete the Roshpit Champions Tutorial map (rpc_tutorial). It will tell you a lot of other important information.
