### ISSUE TITLE
redfall runner buff lasts less than 7 seconds even if ability2 is not cast

### ISSUE THREAD

**Issue by mythly** [ChalkyBrush/roshpit-bug-tracker#871]
When redfall runner is used on Flamewaker, the buff (ability2 20x) lasts much less than 7 seconds even if ablity2 is not cast. The buff just disappears randomly. Sometimes 1 second and sometimes 3 seconds.

**Comment by DeckardCainRPC** [comment]
this is because the ACTUAL effect of the boots is that it only affects the *very next instance* of W damage dealt; that means it's activating on W1 cleave damage. the tooltip needs to be changed to match the buff's effect.

``"Casting @Ability3 applies a buff that multiplies your next instance of @Ability2 damage by 20. The buff lasts 7 seconds, and is consumed immediately when damage is multiplied."``

**Comment by mythly** [comment]
Would this boot be too weak in this way? Say that Mask of the Phantom Sorcerer has durable ablity2 25x with the only cost of extra cooldown.

Could we update the actual effect to match the tooltip? "Lasts 7 seconds and is removed on cast."

**Comment by DeckardCainRPC** [comment]
Mask of the Phantom Sorcerer applies its effect by adding 2,500% to W's Base Ability Damage stat. this means its effect is persistent, and remains in memory for all W damage calculations.

but Redfall Runners works as a temporary buff. if this buff WERE to be removed when the user cast the W skill, that would remove the 2,000% Base Ability Damage bonus before the spell actually dealt damage to enemy units... so in fact, if the item worked in a way that matched its description, it would not have any function at all.

**Comment by mythly** [comment]
It could have some function as some heros could benefit from the 2,000% Base Ability Damage without casting W skill. 
Like Flamewaker W1 triggerred from attack, toggle abilities (W of Chernobog, arcane torrent of Sorceress) ...

**Comment by Nintai** [comment]
`        if attacker:HasModifier("modifier_redfall_runners_buff") or attacker:HasModifier("modifier_redfall_runners_hidden_buff") then
            attacker:RemoveModifierByName("modifier_redfall_runners_buff")
            attacker.foot:ApplyDataDrivenModifier(attacker.InventoryUnit, attacker, "modifier_redfall_runners_hidden_buff", {duration = 0.2})
            damageMult = damageMult + 24
        end`

It does actually work for the first dmg instance of W and not the first cast of W
That kinda means if u hit more than 1 enemy, only the first enemy will get higher dmg

**Comment by redledcat** [comment]
so do we change description?

**Comment by mythly** [comment]
I prefer to change the behavior to match the description.
Otherwise no one would use this boot for just one damage instance 20x.

**Comment by redledcat** [comment]
**Like it is right now**
well, that could be really HUGE buff, because it's not base ability damage %, it's different multiplier.
Maybe better way will be "next 10 instances", and that's all, otherwise - just huge multiplier basically for free, without any counterparts and restrictions.

**Comment by DeckardCainRPC** [comment]
x stacks of 20x W damage is probably fine, sure

**Comment by redledcat** [comment]
obsolete
