### ISSUE TITLE
Damage reduction buff from Aion Eternus removed if Epoch Guardian teleports to the orbs before the buff ends

### ISSUE THREAD

**Issue by mythly** [ChalkyBrush/roshpit-bug-tracker#872]
![c](https://user-images.githubusercontent.com/9605204/48927791-12e23880-ef14-11e8-838c-0c51aef0bb15.png)

According to the description, damage reduction buff should always last 2.7 seconds.

**Comment by DeckardCainRPC** [comment]
you have a keen eye for technicalities, my friend. i agree that your interpretation of the words, as written, is entirely correct

**Comment by mythly** [comment]
Hhhha..

![image](https://user-images.githubusercontent.com/9605204/48928116-d19f5800-ef16-11e8-8527-841abbb2b6f9.png)
Could fix this by moving this line to somewhere else?

**Comment by redledcat** [comment]
is it fixed?

**Comment by redledcat** [comment]
fixed
