### ISSUE TITLE
Dying from missing invisible monster

### ISSUE THREAD

**Issue by csyviroy** [ChalkyBrush/roshpit-bug-tracker#873]
In the middle of a game session, all monster and item on the map will bug and disappear but still can attack player
![untitled](https://user-images.githubusercontent.com/37576331/48929935-f6e89200-ef27-11e8-97d4-901649a3d812.png)

**Comment by redledcat** [comment]
a lot of reports of this problem
probably valve decreased number of entities which can be successfully cached in game, and now they just disappear.
it usually happened on extreme levels of arcane crystals, so chests, mobs and other units just disappear and became unckickable and invisible

**Comment by csyviroy** [comment]
Thank you for the reply. I recall see-ing item de-spawning; is it possible to decrease the interval between de-spawning those entity to free up the number of entities cached in game?

**Comment by redledcat** [comment]
That is actually devastating
![706e00c85e667994](https://user-images.githubusercontent.com/32621322/48955356-96c11280-ef5e-11e8-8512-89c1433173ba.png)
![alf](https://user-images.githubusercontent.com/32621322/48955453-0800c580-ef5f-11e8-8742-547370fc15f6.PNG)

**Comment by redledcat** [comment]
![unknown 2](https://user-images.githubusercontent.com/32621322/48955554-9117fc80-ef5f-11e8-908f-e3fcc35a875c.png)

**Comment by redledcat** [comment]
maybe something is not clearing properly? arcane crystals or chests?

**Comment by ChalkyBrush** [comment]
maybe recent armor change fixes, let me know. If it's not the armor change then it's something deep from 7.20 which might be really hard to fix

**Comment by redledcat** [comment]
![unknown 3](https://user-images.githubusercontent.com/32621322/49167962-99997a00-f347-11e8-8909-8a79dd755b45.png)
![unknown 4](https://user-images.githubusercontent.com/32621322/49168037-bc2b9300-f347-11e8-970d-567bdbcd1af1.png)

**Comment by redledcat** [comment]
I believe this crysis is fixed for now, at least while we don't have 1500+ simultaneous entities in game session.
