### ISSUE TITLE
Items stuck on loot window(s)

### ISSUE THREAD

**Issue by aegilgut** [ChalkyBrush/roshpit-bug-tracker#88]
Items get suck on the loot window after everyone has needed/passed on them and eventually all 3 'slots' are stuck and no other item can be looted. reconnecting doesnt help and entire map has to be remade for the bug to go away

**Comment by redledcat** [comment]
Sure it's closed? Still experience that pretty often, when disconnected wisp-player is in the game while item puts in a queue.

**Comment by ChalkyBrush** [comment]
https://github.com/ChalkyBrush/roshpit-bug-tracker/issues/28
