### ISSUE TITLE
Holding Alt to switch Armor value display to percentile queries old Armor system, not RPC's new one

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#880]
STEPS TO REPRODUCE:
1. get like 1500 armor
2. hold Alt and look at your armor
3. it now reads ~106%
4. hover over your portrait to bring up RPC's custom stats panel, and you'll see that your actual physical resist is ~98.675% instead

**Comment by Nintai** [comment]
Cant to anything about that, since the stats u see at the window is vanilla dota, and we are now using "ignore physical armor" on most dmg instances and then calculate with custom armor

Blame Volvo

**Comment by DeckardCainRPC** [comment]
i am obviously aware of the fact that it's displaying volvo's communist armor physical resist, because i put that in the topic title

i also know that chalky was able to change that anyway, with a very recent patch, because of #870 - he used the wrong color green when printing the bonus armor value to that field

i suspect chalky was not aware of the fact that holding Alt changes the armor readout to display a percentile physical resistance instead of the armor value, as is sometimes the case with our good canadian pal, therefore this topic is intended to bring that to his attention

**Comment by redledcat** [comment]
we have a new one
