### ISSUE TITLE
Flamewalker arcana Q2 bug?

### ISSUE THREAD

**Issue by bustersss** [ChalkyBrush/roshpit-bug-tracker#882]
flamewalker arcana q2 skill doesnt give movespeed again. it was fixed after update (25 nov 2018), but now it doesn't give ms again.

**Comment by DeckardCainRPC** [comment]
ah, thank you, this is a helpful report

just to be certain, can you post a link to your DK's build on roshpit.ca?

**Comment by redledcat** [comment]
ms works
