### ISSUE TITLE
Tidehunter helmet model stuck in ground near Redfall Swamp turret

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#884]
https://i.imgur.com/IX6ogw2.jpg

**Comment by ChalkyBrush** [comment]
detailed ambience taken to be a bug :(

**Comment by DeckardCainRPC** [comment]
oh i thought it was an incident like "Underlords having paintbrushes hovering next to them," i had legit never noticed it before @ChalkyBrush 

it looks nice. leave it
