### ISSUE TITLE
Siltbreaker shreds 12,000 Armor, the equivalent of 80k AGI

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#889]
and that is fucking preposterous

SUGGESTED COURSE OF ACTION:
the Templar Assassin creeps in Sea Fortress can shred ~6500 with their Meld attack debuff, which is already very severe.

an Armor shred of 8k is worth ~53,334 AGI, which is still very mean but much more manageable, through Dragon Armors, Helm of the Iron Colossus, and other shit. anything more than that is just too rude

**Comment by redledcat** [comment]
but siltbreaker almost never attacks you, and and his laser beam instakills.
I think armor shred is not a problem, but unused feature

**Comment by redledcat** [comment]
well he still shreds armor, but I guess it's intended and kinda less important
