### ISSUE TITLE
Game crashes cannot connect and lose progress as well items equipped during session.

### ISSUE THREAD

**Issue by XaosKoltron** [ChalkyBrush/roshpit-bug-tracker#892]
During session of Sea Fortress, I was running with Red General and game crashes due to too much entities in one area. Cannot reconnect and I lost progress from the session, but weirdly enough the items that were saved on the character seems to disappear if you equip new ones during the session if you try to load the old save. Sounds like "yeah you would lose your items"
but I loaded my old save which I used the SAME items before, but I tried to use different method and I came back to it afterwards, old items, then I logged on and the items I equipped, during the swapping out, is gone. I know it's a bug because you can't just lose items from your old save

**Comment by redledcat** [comment]
yes
