### ISSUE TITLE
Can fortify structures

### ISSUE THREAD

**Issue by XaosKoltron** [ChalkyBrush/roshpit-bug-tracker#893]
I accidentally fortify on The Battle of Serengaurd Map and the structures weren't taking damage at all for the entire session.

**Comment by redledcat** [comment]
sadly (happily) it's not true
maybe you used anything else

**Comment by XaosKoltron** [comment]
Possibly I bugged out in my session

**Comment by redledcat** [comment]
not a thing, at least Fortify button is not the cause
