### ISSUE TITLE
Galactic Arcana Cache Open nothing

### ISSUE THREAD

**Issue by trlq001** [ChalkyBrush/roshpit-bug-tracker#894]
My Galactic Arcana Cache Open nothing
My ID：156695706（鱼塘水深）
我在市场领了一个至宝箱，打开什么都没有。然后铁匠罢工（无法领取每日收益，无法洗装备脱装备）

**Comment by ChalkyBrush** [comment]
since you have web premium, I've reset your status for
www.roshpit.ca/secret.

So go grab one there!
