### ISSUE TITLE
Update the website's Glyph tooltips you large Canadian egg fucker

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#895]
you egg fucking son of a bitch

**Comment by redledcat** [comment]
fixed at last

**Comment by ChalkyBrush** [comment]
I now demand an official retraction of "Large Canadian Egg Fucker"

**Comment by redledcat** [comment]
@ChalkyBrush not so fast
https://www.roshpit.ca/items/item_rpc_neutral_glyph_4_2
