### ISSUE TITLE
[Tutorial] tutorial_quiz_question_4 - attack range @sub is broken

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#899]
I see there are 2 variants of question.
Armor one works, but attack range seems to be broken (at least for PA)
![20181207002852_1](https://user-images.githubusercontent.com/32621322/49612951-41055500-f9b7-11e8-852b-91ec2710c15f.jpg)

**Comment by redledcat** [comment]
FIX

**Comment by redledcat** [comment]
please

**Comment by ChalkyBrush** [comment]
done

**Comment by redledcat** [comment]
thanks
