### ISSUE TITLE
FPS decreases with time.

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#91]
I was playing at Arena as Cheronbog and doing the Pit in a solo match.
After a few minutes I realised that my fps was getting lower and lower.
I guess it happens because of an animation that does not dissapear and stacks with it self.

**Comment by redledcat** [comment]
I just want to add two zones here, which mostly always have lower FPS than other on map.
1) Arena Trial of Lies after you push the button to open that section, decreases your FPS when camera howered over there
2)This zone in Redfall rarely decreases fps to 0 when camera is there. It returns to normal if you hower camera away
![20171028022747_1](https://user-images.githubusercontent.com/32621322/32129198-c37fbf88-bb84-11e7-945b-a3f8b573a502.jpg)
(It starts after 3 balls pullze, but also affects room before Scarloth.
