### ISSUE TITLE
Sorceress Q2 (Frost Nova) tooltip lists Magical damage type, but does not deal damage

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#914]
anymore

**Comment by noor-latif** [comment]
Can I re-open this? I'm having this exact same issue atm
I also applied glyph of torrent. At least it applies the damage of lvl 1 frost nova (120dmg) but it never scales higher than that (even after -suicide)

![Frost Nova](https://cdn.discordapp.com/attachments/331554376181219350/700092124166750218/unknown.png)
