### ISSUE TITLE
Tanari "Onibi" guide can get stuck in Wind Temple Key path

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#915]
i have no idea what the fuck causes it

https://imgur.com/a/amey5va

i can only imagine that it's somehow related to Grasp of the Elders but i have 0 evidence of any kind

**Comment by redledcat** [comment]
that part is triggered by titan's death (the one with magical attack modifier), maybe he saw naga princess from water path key and  went for extremely important series of slapping her butt

**Comment by DeckardCainRPC** [comment]
understandable
