### ISSUE TITLE
Deckard's 3.8b Gripe Sheet

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#917]
=== EPOCH GUARDIAN ===

Q3's image is broken on the website, it's been fucked up for ages

=== PALADIN ===

Glyph T2_3: Glyph of Gold Sparkle -> Glyph of Conviction

Glyph T2_3: "has a 20% lifesteal" -> "heals Paladin for 20% of the damage it deals."

Glyph T2_4: Glyph of Hyper Justice -> Glyph of Fanaticism

Glyph T2_5: tooltip clarification

"@Ability4 may now attack, dealing Pure Holy damage equal to 10x Paladin's attack power."

Glyph T2_5: Glyph of Penitence -> Glyph of Smiting

Glyph T2_6: Glyph of Vestigial Value -> Glyph of Poverty

Glyph T2_6: tooltip clarification

"For each item equipped that is Mythical rarity or lower, all post-mitigation damage output is increased by 240%."

Glyph T2_7: Glyph of Heaven's Sentinel -> Glyph of Salvation

=== ELEMENTAL WARLORD ===

i didn't see any text in his tooltips which inform players
about the new axe throw mechanics during his E jumps.

i recommend appending this blurb to the bottom of each of
his W tooltips, or else each of his E tooltips:

"While executing @Ability3, each Throwing Axe spell has no cast point or cooldown, and will not change Elemental Warlord's element."

=== AURIUN ===

it still takes 140 points of R1 to be the equivalent of Sapphire Dragon armor.
throw him a bone, buff that 5% rune scaling.

=== SPIRIT WARRIOR ===

Q tree: neither Flameblood nor Windstrike Weapons list a buff duration

Q2: capitalization in tooltip

"Casting Flameblood or Windstrike Weapon applies Fire or Wind Shield to Spirit Warrior. Fire Shield reduces all damage taken, and Wind Shield adds evasion."

Q3: tooltip mentions "flametongue," something huskar does not have

"After casting Flameblood Weapon, it is replaced with Windstrike Weapon. Windstrike attacks deal additional pure damage based on the recipient's attack power. Windstrike has an additional 1% damage amplification for each point of Armor that the target has. Windstrike and Flameblood Weapons cannot be active at the same time on the same target."

W3: typo: sould thrust -> Soul Thrust

E1: DOTA_Tooltip_Ability_spirit_warrior_rune_e1_property_two is undefined,
and so is its accompanying _suffix_two

=== MOUNTAIN PROTECTOR ===

R tooltip: can you use "@Ability3" instead of saying "[E] ability?"

=== CHERNOBOG ===

E3: "takes increased postmitigation" -> "takes increased post-mitigation damage"

=== EKKAN ===

W2: the _suffix_two needs to have a % appended to it,
so that it reads +8% per rune rank instead of just +8

R2: "This damage ignore Steadfast." -> "Damage dealt by this rune ignores Steadfast."

=== ZHONIK ===

Glyph T5_A (Immortal Glyph): Glyph of Sage's Eyes -> Glyph of Bare Knuckle

and then curate it. the website still displays the old effect.

(Bare Knuckle is the japanese title of Streets of Rage)

=== SEPHYR ===

Q3: capitalize all instances of "lightbomb" and "clearfire"

**Comment by DeckardCainRPC** [comment]
=== SPIRIT WARRIOR ===

the website curiously omits Q1's armor shred scaling information

**Comment by DeckardCainRPC** [comment]
=== SPIRIT WARRIOR ===

W3: clarify tooltip

"A % of Spirit Warrior's total attack damage is added to the base damage of @Ability2. If Flameblood or Windstrike Weapons are active on him, @Ability2 also slams all enemies struck with an amplified hit from those weapons. The stated bonus is multiplied by @Ability2's level."

then change _suffix_two: "Weapon Strike Bonus"

**Comment by DeckardCainRPC** [comment]
=== CHERNOBOG ===

Q2: tooltip is phrased in a confusing way, most notably by using
the word "total" when it actually means "base"

replace it with this:

"@Ability1 burns enemies walking through it every 0.5 seconds. The coals also increase Demon damage dealt to these targets, by multiplying any of an attacker's existing Demon damage bonuses against them."

**Comment by redledcat** [comment]
SPIRIT WARRIOR
W ability says ".Cast" in the end of description. I bet it's about his new interaction with E spirits

BAHAMUT
W3 says Judement

**Comment by ChalkyBrush** [comment]
done

**Comment by redledcat** [comment]
how its done if FIRST step in this list is not done
https://www.roshpit.ca/heroes/Epoch%20Guardian
