### ISSUE TITLE
Huskar's T7 Glyph does not cast his various spear buffs on himself when casting Arcana R

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#918]
but it does increase his ult's duration by 40 seconds, including the duration of his arcana's Waterheart Weapon

check base R too, see if it's applying his other two spears to himself on-cast

**Comment by DeckardCainRPC** [comment]
ETA: i just checked myself, and no, neither of his R spells are casting Q or Q1 or even R3 on himself, despite the glyph's assurances

**Comment by ChalkyBrush** [comment]
actually i changed the addon_englsih but never implemented after deciding it wasn't necessary, so reverted the change on the text
