### ISSUE TITLE
Huskar's new Q3 amp based on target's current armor has anti-synergy with Q1 armor shred

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#919]
despite the fact that two glyphs, an Immortal weapon, and multiple runes (like his new W3 perk) encourage stacking the two on huskar

SUGGESTED COURSE OF ACTION:

make q3 use target's base (unmodified) armor, just like epoch guardian's arcana q2

**Comment by ChalkyBrush** [comment]
not a bug, windstrike is insurance in case you cant burn through armor to get big flamebloods (that was the idea anyway)
Any necessary changes would be for balance, not a bug fix

**Comment by redledcat** [comment]
Well, maybe there should be a glyph which allow to INCREASE enemy armor in order to make it viable.
Paragon enemies with high armor are rare, and most of other units don't have much armor.

**Comment by redledcat** [comment]
Also most of troubles which make huskar relatively "bad" are not solved.
Such as inredibly long cast points and low mobility.
I had started table for huskar changes past year last autumn then this year made another concept, but never got to finish it.
At least you made first steps to make him better
