### ISSUE TITLE
Glyph of Giant Slayer

### ISSUE THREAD

**Issue by bavibi** [ChalkyBrush/roshpit-bug-tracker#92]
Glyph of Giant Slayer does not work against redfall_shipyard_boss

**Comment by redledcat** [comment]
Tyrant also has "Man Eater" passive, which gives 1% steadfast. Probably it overrides steadfast, and I'm completely ok with it. It's boss after all, and fight should take a while

**Comment by ChalkyBrush** [comment]
not a bug here. Man Eater != steadfast! :D
