### ISSUE TITLE
New BM axe-throwing functionality + Wind Deity Crown + Energy Whip Gloves + E2 causes "Too Fast!" W spell lockout

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#920]
i don't know if there's a way to address this that won't break the fucking game. i think it's strictly "working as intended" and i can fucking guarantee that E2 sliding into thick mob clusters will chuck enough axes to crash a server...

**Comment by ChalkyBrush** [comment]
i think the lockout is good in this case :P
