### ISSUE TITLE
[Flamewaker] Arcana W still deals Magical damage

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#921]
Filters:TakeArgumentsAndApplyDamage(target, caster, damage, DAMAGE_TYPE_MAGICAL, 2, RPC_ELEMENT_FIRE, RPC_ELEMENT_NONE)

"Arcana W now deals physical damage, also burns armor"

**Comment by redledcat** [comment]
E1 is magical too

**Comment by ChalkyBrush** [comment]
🤦‍♂️

**Comment by ChalkyBrush** [comment]
fixed
