### ISSUE TITLE
Duskbringer's autoattacks interrupt damage from current Duskfire stacks

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#925]
It cancels current tick of Duskfire and replaces it with damage equal to 1 stack, then it calculates stack and if you don't attack and reapply buff it will deal damage properly
![image](https://user-images.githubusercontent.com/32621322/50423230-c9af3c80-0863-11e9-806c-d07a484ac4d3.png)

**Comment by redledcat** [comment]
![image](https://user-images.githubusercontent.com/32621322/50423261-2c083d00-0864-11e9-985c-89814c7a7b32.png)
or maybe it just deals additional damage instance

**Comment by redledcat** [comment]
And also you have to cast Q after respawn in order to make Q1 work properly

**Comment by ChalkyBrush** [comment]
fixed
