### ISSUE TITLE
Flamewaker

### ISSUE THREAD

**Issue by calltobat9** [ChalkyBrush/roshpit-bug-tracker#927]
Arcane-W  does not damage immune targets! E(Heat Wave) does not reduce armor!

**Comment by Nintai** [comment]
While E not reducing armor is indeed a bug, Arcana W doesnt say it pierces spell immunity. Phyiscal does not mean piercing ;)

**Comment by redledcat** [comment]
I think it's needed to emphasize if spell or rune has immunity pierce or not.

**Comment by calltobat9** [comment]
> While E not reducing armor is indeed a bug, Arcana W doesnt say it pierces spell immunity. Phyiscal does not mean piercing ;)

Djanghor W-skill(physical)breaks through immunity.....Flamewaker has properties too!Immunity only affects magic!

**Comment by Nintai** [comment]
You are mistaking "Spell immunity" with "Magic immunity"
Spell Immunity makes u immune to being hit by spell that dont pierce it, no matter what damage type
Magic Immunity gives u 100% magic resistance, making u immune to the magic damage type

**Comment by calltobat9** [comment]
> You are mistaking "Spell immunity" with "Magic immunity"
> Spell Immunity makes u immune to being hit by spell that dont pierce it, no matter what damage type
> Magic Immunity gives u 100% magic resistance, making u immune to the magic damage type

Exactly physical damage has nothing to do with it!DPS meter there is a function to give immunity to magic, it is to magic and after that, Flamewaker does not cause damage anymore, although it has physical damage, this is a bug!

**Comment by Nintai** [comment]
Alright, so the bug is that the dummy calls it "Magic Immunity", but in truth its "Spell Immunity AND Magic Immunity", found the bug :)

**Comment by calltobat9** [comment]
> Alright, so the bug is that the dummy calls it "Magic Immunity", but in truth its "Spell Immunity AND Magic Immunity", found the bug :)

how do you then explain that the spell Djanghor W- (physical) breaks through immunity?

**Comment by calltobat9** [comment]
> Alright, so the bug is that the dummy calls it "Magic Immunity", but in truth its "Spell Immunity AND Magic Immunity", found the bug :)

haha read the new patch)))

**Comment by Nintai** [comment]
Look, if u report something that is 1001384092830487% a bug, i will say "yes its a bug". But here, there is always the possibility of Chalky saying "No, its intended" and thats when i say "Not a bug".

You have to choose for each spell if it pierces spell immunity or not, and Flamewaker arcana W didnt have that, while djanghor W has it, thats all there is to it.

And yeah, Chalky seems to decide its a bug and its fixed, good for you ;)
