### ISSUE TITLE
120 lvl 

### ISSUE THREAD

**Issue by calltobat9** [ChalkyBrush/roshpit-bug-tracker#935]
make sure that the battle in the serenghard and the sea fortress cannot in any case be entered by players below level 120

**Comment by redledcat** [comment]
use discord for suggestions
I could spam my shitty thoughts here as well, but I'm not doing this often
Because it's a **bug-tracker**

**Comment by ChalkyBrush** [comment]
not a bug! and we've discussed such possibilities before and decided it was not a good idea
