### ISSUE TITLE
[Sorceress] R4 arcana still retains fire amp effect

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#937]
![20190102211858_1](https://user-images.githubusercontent.com/32621322/50605705-26e66600-0ed4-11e9-9374-dabd2800d86d.jpg)

**Comment by DeckardCainRPC** [comment]
... and doesn't add ice amp at all? wtf

**Comment by redledcat** [comment]
https://www.roshpit.ca/items/item_rpc_sorceress_arcana1
nono, it adds ice amp only after R cast
but it's extra shit rune tbh.
with divinex full int I got 7700% ice amp
R4 arcana gives 10% per rune, 200% for 20 runes, and if you are "lucky" to have R4 arcana, well, 300%+ ice amp.
about 4% dps increase
now look at R3, and it's just twice less shittier:
if you have 80 runes, you get 40% amp per stack. 
Let's say you can effectively stack 20 stacks before tanky target being killed normally in game
hi, it's only 800% amp
Even if you have no divinex and just casual 3000% amp, it's still about 20-25% dps increase
Q4 adds to R3 and to R4, which makes all three runes do exact same job

**Comment by DeckardCainRPC** [comment]
i strongly agree. the body arcana is a relic from a lost time, it is no longer adequate for the modern age

**Comment by GoToNightmare** [comment]
fixed
