### ISSUE TITLE
[Tutorial] People actually being confused after they end the tutorial, and do not understand what to do now.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#949]
Apparently a lof of players waiting from tutorial it will automatically bring them to the game after they finish it.
They keep asking everyone in discord and dota chat what to do now when they complete last part.
That can be fixed by an announcement after 6E, which will tell player to leave and rehost another map.
Probably good way will be to add screenshot in UI to show how to choose the map on mode page.

**Comment by redledcat** [comment]
It's surpisingly stupid, but there was a week when newbies kept asking what they actually should do 1-2 times each day.

**Comment by redledcat** [comment]
So, just to demostrate a small part of this nonsense:
![1](https://user-images.githubusercontent.com/32621322/51281475-8c1d7980-19f3-11e9-9f68-65fa8f0dcd4e.PNG)
![2](https://user-images.githubusercontent.com/32621322/51281478-8d4ea680-19f3-11e9-8e7e-a66af190b4a3.PNG)
![3](https://user-images.githubusercontent.com/32621322/51281480-8e7fd380-19f3-11e9-9cef-b647e72fc506.PNG)
![4](https://user-images.githubusercontent.com/32621322/51281485-917ac400-19f3-11e9-8d7b-3d7d2b42e69d.PNG)
![5](https://user-images.githubusercontent.com/32621322/51281486-92abf100-19f3-11e9-9044-162a083cba4b.PNG)
![6](https://user-images.githubusercontent.com/32621322/51281487-93dd1e00-19f3-11e9-9dd0-d0db224e85f4.PNG)
![7](https://user-images.githubusercontent.com/32621322/51281488-95a6e180-19f3-11e9-83a0-d7efeeb13b35.PNG)

**Comment by redledcat** [comment]
![8](https://user-images.githubusercontent.com/32621322/51281628-1239c000-19f4-11e9-9688-0d8b62fbdd84.PNG)
![9](https://user-images.githubusercontent.com/32621322/51281630-1239c000-19f4-11e9-9d13-11200c5e21ef.PNG)
![10](https://user-images.githubusercontent.com/32621322/51281631-136aed00-19f4-11e9-845c-59da11c18d4a.PNG)
![11](https://user-images.githubusercontent.com/32621322/51281632-149c1a00-19f4-11e9-902a-9c18743d4b81.PNG)

**Comment by redledcat** [comment]
![12](https://user-images.githubusercontent.com/32621322/51281838-9a1fca00-19f4-11e9-8e23-a6ea894c0594.PNG)
![13](https://user-images.githubusercontent.com/32621322/51281839-9ab86080-19f4-11e9-8244-3a92671ea36f.PNG)

**Comment by redledcat** [comment]
Okay I stop now

**Comment by ChalkyBrush** [comment]
didn't need the proof, I had seen it myself lol.
But yes this is a good suggestion

**Comment by redledcat** [comment]
No, I just needed to put my collection of screenshots somewhere

**Comment by redledcat** [comment]
fixed, thanks
