### ISSUE TITLE
Golden coin texture

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#95]
Gold coins which drops from chest puzzle in Crymsith Castle  has pink texture while dropping down and disappears on drop.
Cant catch this with screenshot, because of rarity and fast disappearance.

**Comment by redledcat** [comment]
![20171030123720_1](https://user-images.githubusercontent.com/32621322/32164203-6c52194c-bd67-11e7-9736-7a05bdc924a8.jpg)

**Comment by ChalkyBrush** [comment]
actually they are purple in the dota client, so I will have to go with not a bug

![image](https://user-images.githubusercontent.com/5232984/34592443-03164e3a-f192-11e7-8015-788feeab771d.png)
