### ISSUE TITLE
[Jex] Onibi's tech levels, etc., are NOT saved and do NOT persist between sessions

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#958]
check and make sure that visiting the hero's profile page, even without clicking the "Reset Onibi" button, isn't automatically running the Reset script anyway

**Comment by ChalkyBrush** [comment]
i just tested and it saved and loaded fine?

**Comment by DeckardCainRPC** [comment]
multiple people have complained that they're having the same problem... most of them appear to be veteran players

check my account. i previously had an issue, which redledcat later diagnosed and solved, that caused me to gain a Star achievement LITERALLY EVERY SINGLE TIME any of my heroes had their Immortal weapons level up. this persisted for 2 years, and i just assumed everybody else learned to just deal with it. i was SHOCKED to find out that it was a problem unique to veteran users like myself.

**Comment by DeckardCainRPC** [comment]
i believe this was fixed this morning
