### ISSUE TITLE
Blacksmith eating items issue

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#96]
Dozens of reports tells about disappearing of fresh rerolled items when you trying to equip it.
Approximate steps to reproduce
1)Use Blacksmith to reroll any item, while having same slot of gear equipped (rerolling chest piece while you have one equipped)
2)Reroll an item several times and do it fast. I guess it could be server ping issue, and probably should be tested with ping higher than 0.
3)Click "Close" on Blacksmith window
4)Try to equip an item
5)See briefly blinking window of chose old-or-new window of equip (or even do not see it, because it disappears even while has fade amination)
6)Congrats, item disappeared
7)Also my Blacksmith stopped to work after second time I tested it in a row and did not opened his window.
8)Fixed Blacksmith by trying-to-equip random gear piece and cancelling it

**Comment by FortuneReborn** [comment]
This bug has been around for a long time. It's happened to me multiple weeks ago.

**Comment by redledcat** [comment]
Well, I dont think he is that aggressive now, BUT if you have full inventory while rerolling your item will be eaten.

**Comment by ChalkyBrush** [comment]
I think can close this
