### ISSUE TITLE
[Jex] Electron Shield W4 scaling says 10,000% per rune level, but it means 10k flat

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#963]
to clarify, the tooltip for Electron Shield has green text at the bottom that says each point of W4 additionally grants 10000% bonus attack damage while the shield is active. that would be a hilariously stupid amount of bonus damage. instead, the W4 scaling adds +10,000 *flat* attack damage per point of W4 while the shield is active.

**Comment by redledcat** [comment]
![20190123154028_1](https://user-images.githubusercontent.com/32621322/51607249-3bdb7580-1f25-11e9-9151-25770843d6e5.jpg)
variable in tooltip looks gross. make it work or just write it without underscore
