### ISSUE TITLE
[Jex] Jex weapons do not display properly on the website

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#968]

**Comment by DeckardCainRPC** [comment]
i think this is resolved

**Comment by redledcat** [comment]
NO IT'S NOT

**Comment by redledcat** [comment]
https://www.roshpit.ca/players/91933876/heroes/573280
images for standart weapons are still invisible, as well impossible to check rolls on such weapons

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush you posh frother
