### ISSUE TITLE
[Jex] All weapons' images are broken for Jex (GOD I LOVE THESE SHORT NAMES)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#970]
https://www.roshpit.ca/items/item_rpc_jex_immortal_weapon_1
![jex_immortal_weapon_1](https://user-images.githubusercontent.com/32621322/51601974-d7b1b500-1f16-11e9-8f84-b1756b532553.png)
![jex_immortal_weapon_2](https://user-images.githubusercontent.com/32621322/51601975-d84a4b80-1f16-11e9-9086-38e4762ed6cd.png)
![jex_immortal_weapon_3](https://user-images.githubusercontent.com/32621322/51601976-d84a4b80-1f16-11e9-90e3-5924c659be21.png)
![jex_weapon_00](https://user-images.githubusercontent.com/32621322/51602000-e6986780-1f16-11e9-87f3-ef8da07b19cb.png)
Please add all of these in base, and also fix all other missing icons in #936

**Comment by DeckardCainRPC** [comment]
lol

tomorrow evening, i'll sit down and hammer out some real, non-placeholder weapon art for Jex

**Comment by redledcat** [comment]
Please no DMCA violation

**Comment by redledcat** [comment]
#968 sorry my bad again
