### ISSUE TITLE
[Jex] Something wrong with portals (e_nature_cosmic)

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#976]
First of all, I can create a lot of portals, while having tech lvl at lvl 1.
Second, I have 40000 regen instead of 2000 as it should be (21 portals?)
armor and manaregen are fine.
![image](https://user-images.githubusercontent.com/32621322/51606974-6ed13980-1f24-11e9-801e-c03dd119df51.png)
![image](https://user-images.githubusercontent.com/32621322/51606994-801a4600-1f24-11e9-8c50-4d7e69cdc998.png)

**Comment by ChalkyBrush** [comment]
lvl 20 tech for debug, fixed
