### ISSUE TITLE
Venomort W3 not working

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#98]
I don't know if the description is not correct or if I'm understanding it wrong.
Each stack of Fervor increases armor and base ability damage of necrofusion and plague blister.

I tested my damage with 1 stack and max stacks and I do the same damage. The armor property does work but the ability damage does not.

![20171028110543_1](https://user-images.githubusercontent.com/32886049/32135687-3b786304-bbd1-11e7-9ccd-dbd6afd02395.jpg)
![20171028110554_1](https://user-images.githubusercontent.com/32886049/32135689-3ffeb2ca-bbd1-11e7-82cc-4be962de61fd.jpg)

**Comment by ChalkyBrush** [comment]
surprised nobody noticed sooner.
Stacks weren't being taken into consideration.
Fixed for next patch
