### ISSUE TITLE
Arena transporting titan + Zhonik immo glyph

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#980]
https://media.discordapp.net/attachments/361518564940840971/537728051220316161/unknown.png?width=1191&height=670

**Comment by ChalkyBrush** [comment]
KICK HIS ASS ZHONIK

**Comment by ChalkyBrush** [comment]
its because it can target magic immune now 🤦‍♂️

**Comment by redledcat** [comment]
stun immunity modifier?

**Comment by redledcat** [comment]
Or change his AI to reach the destination first before he can turn back

**Comment by redledcat** [comment]
This glyph idea is op in its core, but piercing magic immunity at least has purpose, dealing with missing models for skullbones

**Comment by redledcat** [comment]
or maybe give them some kind of linken?
