### ISSUE TITLE
Dusbringer's Q1 does not work

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#99]
(And never worked properly??)
Well, I never did read that tooltip apparently and the main rune of Duskbringer just does not work. GG.
ty Chanphal 
![21](https://user-images.githubusercontent.com/32621322/32135709-cc96c196-bc03-11e7-9dba-402b4225fd6b.PNG)
![22](https://user-images.githubusercontent.com/32621322/32135711-cd261378-bc03-11e7-97bc-8fbe5fc5fb04.PNG)

**Comment by ChalkyBrush** [comment]
technically not a bug because his regular attacks weren't intended to apply duskfire (only the actual whirling flail) however this is a fine suggestion and duskbringer needs buffs so I implemented this
