### ISSUE TITLE
Hood of the Sea Oracle isn't reducing enemy attack damage

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#993]

**Comment by Nintai** [comment]
![image](https://user-images.githubusercontent.com/5485559/51788171-468f4800-217b-11e9-9ae6-d1b93670181c.png)

![image](https://user-images.githubusercontent.com/5485559/51788175-4ee78300-217b-11e9-9001-8069d6107ffe.png)

Works just fine

**Comment by Nintai** [comment]
It reduces base attack dmg, thats why u dont see red numbers

**Comment by DeckardCainRPC** [comment]
ah, i see, thank you. i expected it to function like Rubick's Fade Bolt, displaying a negative modifier next to the victim's attack damage readout
