### ISSUE TITLE
When Chernobog touches Power Cogs during E, he is teleported beneath the map at these coordinates

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#994]
https://imgur.com/a/7sWxNt3

**Comment by redledcat** [comment]
When ANY hero touches Power Cogs during mobility spell, he is being disintegrated

**Comment by redledcat** [comment]
https://youtu.be/RviUnto0j7s?t=1819

**Comment by redledcat** [comment]
#904

**Comment by redledcat** [comment]
NO COGS = NO PROBLEMS

**Comment by DeckardCainRPC** [comment]
i got 99 problems but a cog ain't one
